rancher/rke2

Dockerfile, Dockerfile.windows, scripts/validate
* Bump containerd to v1.6.14-k3s1
* Use hardened-containerd build on windows
version bump
* https://github.com/rancher/rke2/issues/3723
=> [release-1.24] Bump containerd to v1.6.14-k3s1

channels.yaml
Stop offering installs of these releases due to the critical containerd regression.
channel server
attempt to install from channel server; note that it will not serve the affected releases as latest for these channels.
* #3723 
```release-note
NONE
```
=> Exclude December r1 releases from channel server

pkg/podexecutor/staticpod.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go
Don't handle kube-proxy in static pod cleanup
This isn't technically a control-plane component, and shouldn't be
handled by the control-plane  static pod cleanup. Instead, handle it
within the static pod executor's agent setup path.
bugfix
* https://github.com/rancher/rke2/issues/3752
=> Don't clean up kube-proxy every time agents start

Dockerfile, Dockerfile.windows
Bump containerd to v1.6.15-k3s1
New build includes fix for containerd version tag on windows.
version bump
bugfix
check containerd version in `kubectl get node -o wide`
* https://github.com/rancher/rke2/issues/3764
=> Bump containerd to v1.6.15-k3s1

Dockerfile, scripts/build-images
Issue: https://github.com/rancher/rke2/issues/3790
=> [Backport 1.25] Update multus to v3.9.3 and whereabouts to v0.6

Dockerfile, scripts/build-images
Waiting on https://github.com/rancher/rke2-charts/pull/317
Linked Issue:
https://github.com/rancher/rke2/issues/3754
=> [Release-1.24] Bump vSphere CPI chart to v1.24.3

Dockerfile, Dockerfile.windows
Bump containerd to v1.6.15-k3s1
New build includes fix for containerd version tag on windows.
version bump
bugfix
check containerd version in `kubectl get node -o wide`
* https://github.com/rancher/rke2/issues/3776
=> [release-1.25] Bump containerd to v1.6.15-k3s1

Dockerfile, Dockerfile.windows
Bump containerd to v1.6.15-k3s1
New build includes fix for containerd version tag on windows.
version bump
bugfix
check containerd version in `kubectl get node -o wide`
* https://github.com/rancher/rke2/issues/3777
=> [release-1.24] Bump containerd to v1.6.15-k3s1

go.mod, go.sum
Bump k3s to fix passthrough of apiserver default tls ciphers
Updates k3s: https://github.com/k3s-io/k3s/compare/7f6e1d1552ab...45c337bb1fa199aa188f083e9e1b2464d55340e9
bugfix, security
check kube-apiserver args
* https://github.com/rancher/rke2/issues/3773
=> [release-1.25] Bump K3s version for tls-cipher-suites fix

go.mod, go.sum
Bump k3s to fix passthrough of apiserver default tls ciphers
Updates k3s: https://github.com/k3s-io/k3s/compare/339d4e36a594...739be58a8b459a0a6a0dd9eeaed7c9e79e79b41f
bugfix, security
check kube-apiserver args
* https://github.com/rancher/rke2/issues/3774
=> [release-1.24] Bump K3s version for tls-cipher-suites fix

go.mod, go.sum
Bump k3s to fix passthrough of apiserver default tls ciphers
Updates k3s: https://github.com/k3s-io/k3s/compare/416d705348cc...27f8fe7d0295d5e36b6d4249129670aa794f3eec
bugfix, security
check kube-apiserver args
* https://github.com/rancher/rke2/issues/3775
=> [release-1.23] Bump K3s version for tls-cipher-suites fix

Dockerfile, scripts/build-images
Pulls in https://github.com/rancher/rke2-charts/pull/317
Linked Issue:
* https://github.com/rancher/rke2/issues/3806
* https://github.com/rancher/rke2/issues/3800
=> [Release-1.23] Bump vSphere CPI chart to v1.23.3

Dockerfile, Dockerfile.windows, go.mod, go.sum, scripts/validate
* Bump containerd to v1.5.16-k3s2
* Use hardened-containerd build on windows
version bump
* https://github.com/rancher/rke2/issues/3828
```release-note
The embedded containerd version has been bumped to v1.5.16-k3s2. This includes a backported fix for [containerd/7843](https://github.com/containerd/containerd/issues/7843) which caused pods to lose their CNI info when containerd was restarted, which in turn caused the kubelet to recreate the pod. 
Windows agents now use the k3s fork of containerd, which includes support for registry rewrites.
```
=> [release-1.23] Bump containerd to v1.5.16-k3s2

pkg/podexecutor/staticpod.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go
Don't handle kube-proxy in static pod cleanup
This isn't technically a control-plane component, and shouldn't be
handled by the control-plane  static pod cleanup. Instead, handle it
within the static pod executor's agent setup path.
bugfix
* https://github.com/rancher/rke2/issues/3832
=> [release-1.25] Don't handle kube-proxy in static pod cleanup

pkg/podexecutor/staticpod.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go
Don't handle kube-proxy in static pod cleanup
This isn't technically a control-plane component, and shouldn't be
handled by the control-plane  static pod cleanup. Instead, handle it
within the static pod executor's agent setup path.
bugfix
* https://github.com/rancher/rke2/issues/3833
=> [release-1.24] Don't handle kube-proxy in static pod cleanup

pkg/podexecutor/staticpod.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go
Don't handle kube-proxy in static pod cleanup
This isn't technically a control-plane component, and shouldn't be
handled by the control-plane  static pod cleanup. Instead, handle it
within the static pod executor's agent setup path.
bugfix
* https://github.com/rancher/rke2/issues/3834
=> [release-1.23] Don't handle kube-proxy in static pod cleanup

bundle/bin/rke2-killall.sh
Remove pod logs as part of killall.
Also, don't double-print the echoed informational message
bugfix
* https://github.com/rancher/rke2/issues/3819
=> Remove pod logs as part of killall

Dockerfile, scripts/build-images
Pulls https://github.com/rancher/rke2/pull/3802 into release-1.25:
- Patch release bumps for Cilium and minor release bump for Cilium Hubble.
=> [release-1.25]: Bump cilium images

Dockerfile, scripts/build-images
Pulls https://github.com/rancher/rke2/pull/3802 into release-1.24:
- Patch release bumps for Cilium and minor release bump for Cilium Hubble.
=> [release-1.24]: Bump cilium images

Dockerfile, scripts/build-images
Pulls https://github.com/rancher/rke2/pull/3802 into release-1.23:
- Patch release bumps for Cilium and minor release bump for Cilium Hubble.
=> [release-1.23]: Bump cilium images

bundle/bin/rke2-killall.sh
Remove pod logs as part of killall.
Also, don't double-print the echoed informational message
bugfix
* #3854
=> [release-1.25] Remove pod logs as part of killall

bundle/bin/rke2-killall.sh
Remove pod logs as part of killall.
Also, don't double-print the echoed informational message
bugfix
* #3855
=> [release-1.24] Remove pod logs as part of killall

bundle/bin/rke2-killall.sh
Remove pod logs as part of killall.
Also, don't double-print the echoed informational message
bugfix
* #3856
=> [release-1.23] Remove pod logs as part of killall

README.md
In PR #3584 the documentation files were moved to their [own separate repo](https://github.com/rancher/rke2-docs). This broke the RKE2 logo on the README.md file. This PR is to change the logo to use the equivalent file in the new repo.
Changes to documentation.
Render the markdown file and you'll see that it appears as it did before the file was deleted.
PR #3584
=> Updated RKE2 README's header image to point to the new rke2-docs repo

pkg/auth/auth.go, pkg/podexecutor/staticpod.go
Add bootstrap token auth handler
Partial revert of 09041c437ed3e3f2f8aa29f2de0d66d543ed051e
This is necessary because RKE2 doesn't inherit the bootstrap token auth that K3s pulls out of the apiserver's request handlers.
bugfix
* https://github.com/rancher/rke2/issues/3893
=> Add bootstrap token auth handler

pkg/auth/auth.go, pkg/podexecutor/staticpod.go
Add bootstrap token auth handler
Partial revert of 09041c437ed3e3f2f8aa29f2de0d66d543ed051e
This is necessary because RKE2 doesn't inherit the bootstrap token auth that K3s pulls out of the apiserver's request handlers.
bugfix
* https://github.com/rancher/rke2/issues/3894
=> [release-1.25] Add bootstrap token auth handler

pkg/auth/auth.go, pkg/podexecutor/staticpod.go
Add bootstrap token auth handler
Partial revert of 09041c437ed3e3f2f8aa29f2de0d66d543ed051e
This is necessary because RKE2 doesn't inherit the bootstrap token auth that K3s pulls out of the apiserver's request handlers.
bugfix
* https://github.com/rancher/rke2/issues/3895
=> [release-1.24] Add bootstrap token auth handler

pkg/auth/auth.go, pkg/podexecutor/staticpod.go
Add bootstrap token auth handler
Partial revert of 09041c437ed3e3f2f8aa29f2de0d66d543ed051e
This is necessary because RKE2 doesn't inherit the bootstrap token auth that K3s pulls out of the apiserver's request handlers.
bugfix
* https://github.com/rancher/rke2/issues/3896
=> [release-1.23] Add bootstrap token auth handler

go.mod, pkg/cli/defaults/defaults.go, pkg/logging/logging.go, pkg/logging/logging_test.go, pkg/pebinaryexecutor/pebinary.go, pkg/podexecutor/staticpod.go
Add support for legacy kubelet logging flags
* Allow use of legacy klog flags to configure lumberjack-based logging
* Partial revert of changes from https://github.com/rancher/rke2/commit/6032a0e553d89506b37990a52f47059119acb62d#diff-9c910b1da0166698d76ca425c39623673dcbc3b078a20174c98cdff2d530cb59
bugfix/enhancement
* Configure logging via --kubelet-arg
* Confirm that settings (logtostderr/alsologtostderr/log-file/log-file-max-size) are honored
* Confirm that v/vmodule are passed through to the kubelet
* Confirm that other flags from https://github.com/kubernetes/klog/blob/v2.60.1/klog.go#L407-L421 are ignored if set and do not cause errors from the kubelet
* https://github.com/rancher/rke2/issues/3909
=> Add support for legacy kubelet logging flags

go.mod, go.sum, scripts/build-images
Bump helm-controller/klipper-helm
Includes update to helm-mapkubeapis plugin to handle removal of psp resources from Kubernetes 1.25
version bump / bugfix
Upgrade from v1.24 to this commit, or v1.24.7+rke2r1 -> v1.25.3+rke2r1 -> this commit
* https://github.com/rancher/rke2/issues/3941
* https://github.com/rancher/rancher/issues/40651
```release-note
The embedded helm-controller job image now correctly handles upgrading charts that contain resource types that no longer exist on the target Kubernetes version. This includes properly handling removal of PodSecurityPolicy resources when upgrading from <= v1.24.
```
=> [release-1.25] Bump helm-controller/klipper-helm

Dockerfile, scripts/build-images
Add sig-storage snapshot controller and validation webhook charts
new feature chart
* Confirm that all three helm charts are installed
* Confirm that rke2-snapshot-validation-webhook and rke2-snapshot-controller pods are running.
* https://github.com/rancher/rke2/issues/3942
=> [release-1.25] Add sig-storage snapshot controller and validation webhook

Dockerfile, scripts/test-helpers, scripts/test-run-basics, tests/e2e/resource_files/csi-driver-host-path.txt
* Add a quick host-path CSI snapshot to the basic CI test
* Bump snapshot chart to serve v1beta1 snapshot CR versions
CI test; version bump
Confirm CI passes
* https://github.com/rancher/rke2/issues/2563
=> Add a quick host-path CSI snapshot to the basic CI test

Dockerfile, scripts/test-helpers, scripts/test-run-basics, tests/e2e/resource_files/csi-driver-host-path.txt
* Add a quick host-path CSI snapshot to the basic CI test
* Bump snapshot chart to serve v1beta1 snapshot CR versions
CI test; version bump
Confirm CI passes
* https://github.com/rancher/rke2/issues/3942
=> [release-1.25] Add a quick host-path CSI snapshot to the basic CI test

pkg/cli/cmds/root.go
Removes the `--debug` flag from the root rke2 command. So `rke2 --debug` is no longer an option. The reason for this is simple: putting the `--debug` flag with the root actually breaks the rest of the flagging structure if using any other flags. So: `rke2 --debug server --token=secret` wont run, because the CLI library will rearrange and  inject all flags where the first flag is found, **before** the `server`, so the command actually comes out as `rke2 --debug --token=secret server` which will fail, because the root rke2 command lacks a `token` flag. 
All commands with the debug flag (server, agent, etcd-snapshot etc.) already copy it over from k3s directly, and invoke the `logrus.SetLevel` in their respective `run` functions. There is no loss of functionality with this PR. 
Fix CLI
Can …
=> Remove root `--debug` flag

bundle/bin/rke2-killall.sh
In the killall script, remove the folders/files that we just unmounted. 
Uninstall cleanup
Verified that `/var/lib/kubelet/pods` and other mounts are deleted after uninstall.
https://github.com/rancher/rke2/issues/855
=> Remove unmounts in killall script

tests/terraform/scripts/Dockerfile.build
Take away the `go get` bits from the Dockerfile that is used for terraform tests. Having `go get` in this file causes failures due to not strictly adhering to the go.mod, so when Go version is bumped, things break.
Bugfix 
Run terraform tests
N/A
N/A
=> Remove unnecessary bits from testing dockerfile

scripts/package-bundle
- Don't include the empty `share/rke2-windows` folder in the linux tarballs.
Install bug
Run `make` for rke2 and verify that the resulting tarball does not contain `share/rke2-windows`
https://github.com/rancher/rke2/issues/3918
=> Don't package empty Windows folder in Linux tar

pkg/podexecutor/staticpod.go
Honor the user's audit-log-path override when determining what log directory to mount.
bugfix, enhancement
* https://github.com/rancher/rke2/issues/4026
=> Automatically add volume mount for audit-log-path dir if set

pkg/podexecutor/staticpod.go
Honor the user's audit-log-path override when determining what log directory to mount.
bugfix, enhancement
* #4087
=> [release-1.25] Automatically add volume mount for audit-log-path dir if set

.gitignore, tests/terraform/modules/main.tf, tests/terraform/modules/master/instances_server.tf, tests/terraform/modules/master/variables.tf, tests/terraform/modules/optional_write_files.sh, tests/terraform/modules/variables.tf, tests/terraform/scripts/Dockerfile.build
1. Allow Terraform tests to pass in files and their locations so we can test things like HelmChartConfigs and custom PSA files easier.
2. Add go.work to gitignore as we have multiple workspaces in the project now (root and ./tests/terraform)
3. Bump default Terraform version in the tests to latest
Tests
Run the terraform tests and pass in a new variable to local.tfvars:
```
optional_files     = "/etc/rancher/rke2/custom-psa.yaml,https://gist.githubusercontent.com/rancher-max/e1c728805b1e5aae8b547b075261bb56/raw/99feb324959d7de9f640d934f098319813202d4a/pod_security_config.yaml"
```
N/A
This especially helps when validating rancher as the local cluster on a hardened rke2 setup.
=> Add ability to have write custom files during TF tests for specialized configurations

.github/dependabot.yml
This adds label "kind/dependabot" to the PRs that dependabot generates.
This contributes to https://github.com/rancher/rke2/issues/4130.
This contributes to https://github.com/rancher/rke2/issues/4165
I tested this by running [the dependabot cli](https://github.com/dependabot/cli) locally:
<details>
<summary>Test Scenario</summary>
```
input:
job:
package-manager: docker
allowed-updates:
- update-type: all
source:
provider: github
repo: matttrach/rke2
directory: /
commit: b4e8a84f2aa2d2361e950dd668569bfcfba26e9a
credentials-metadata:
- host: github.com
type: git_source
credentials:
- host: github.com
password: $LOCAL_GITHUB_ACCESS_TOKEN
type: git_source
username: x-access-token
output:
- type: update_dependency_list
expect:
data:
dependencies:
- name: rancher/hardened-build-base …
```
=> Add label to dependabot PRs

tests/terraform/manual_upgrade/upgradecluster_test.go, tests/terraform/suc_upgrade/upgradecluster.go, tests/terraform/suc_upgrade/upgradecluster_test.go, tests/terraform/testutils.go
- Automated manual upgrade test from patch validations for RKE2
- Change upgradecluster package to /suc_upgrade/...
- Add manual_upgrade package
Note: This PR is the same to  this one: https://github.com/rancher/rke2/pull/4058 . I created this new PR because I was using a wrong fork. Now is in the correct one. 
cc @rancher-max 
Test
https://github.com/rancher/rke2/pull/4058
=> Create 'upgrade traditional with workloads' test automated for RKE2

go.mod, pkg/staticpod/staticpod.go, pkg/windows/calico.go
Currently we are using two YAML packages:
1. `github.com/ghodss/yaml v1.0.1-0.20190212211648-25d852aebe32`
2. `sigs.k8s.io/yaml v1.3.0`
The `github.com/ghodss/yaml` package is no longer being actively maintained. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`, which is actively maintained by Kubernetes SIG and widely used in K8s projects.
The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, while `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. You can see the changes between the two versions here: [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), which mostly consists of bug fixes.
Cleanup
* https://github.com/rancher/rke2/issues/4168
=> chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

Dockerfile
This removes the Trivy install from the local dockerfile 
so that the base image can be the single source of truth.
Thie repo will no longer manage the Trivy version, 
and will assume that Trivy is installed in another repo.
This contributes to https://github.com/rancher/rke2/issues/4182
I was able to test this by building the dapper image locally 
and testing the Trivy version:
<details>
<summary>Test Data</summary>
Before:
```
docker build --build-arg="DAPPER_HOST_ARCH=amd64" . -t local-dapper:before --target dapper -f Dockerfile 
[+] Building 6.8s (19/19) FINISHED                                                                                                                         
=> [internal] load .dockerignore …
```
=> Remove Trivy install from Dockerfile

Dockerfile, scripts/build-images
Update Calico image to v3.25.1 on Canal
#4145
=> Update Calico image on Canal

go.mod, go.sum
This prevents issues like https://github.com/rancher/rke2/issues/4223 in future releases.
This will update the version of the docker/docker package to v20.10.24 in order to resolve [CVE-2023-28840](https://github.com/advisories/GHSA-232p-vwff-86mp).
I was able to verify that Trivy no longer reports a vulnerability by building the binary, packing it into a container image locally, and scanning the image:
<details>
<summary>Test output</summary>
Running trivy against rke2 bin built on changes:
```
Dev: root@dev ~  trivy image --scanners vuln -s HIGH,CRITICAL docker.io/library/rke2-local:after
2023-05-12T22:53:02.368Z        INFO    Vulnerability scanning is enabled
2023-05-12T22:53:03.830Z        INFO    Number of language-specific files: 1
2023-05-12T22:53:03.830Z        INFO    Detecting …
```
=> Upgrade docker/docker package

developer-docs/image_sources.md
This adds to the image list developers documentation, giving the source of the image and the repo that generates it.
=> Add rke2-upgrade to image list

Dockerfile
Bump vsphere csi to remove duplicate CSI deployment.
Removes .orig file in chart left over from failed patch in CI.
bugfix
* https://github.com/rancher/rke2/issues/4275
=> Bump vsphere csi to remove duplicate CSI deployment.

Dockerfile
Bump vsphere csi to remove duplicate CSI deployment.
Removes .orig file in chart left over from failed patch in CI.
bugfix
* https://github.com/rancher/rke2/issues/4276
=> [release-1.26] Bump vsphere csi to remove duplicate CSI deployment.

Dockerfile
Bump vsphere csi to remove duplicate CSI deployment.
Removes .orig file in chart left over from failed patch in CI.
bugfix
* https://github.com/rancher/rke2/issues/4277
=> [release-1.25] Bump vsphere csi to remove duplicate CSI deployment.

Dockerfile
Bump vsphere csi to remove duplicate CSI deployment.
Removes .orig file in chart left over from failed patch in CI.
bugfix
* https://github.com/rancher/rke2/issues/4278
=> [release-1.24] Bump vsphere csi to remove duplicate CSI deployment.

.drone.yml
When CI should trigger based on the `push` event, we should only trigger if the push was to the master or release branches.
This contributes to https://github.com/rancher/rke2/issues/4248.
I was able to validate the drone file by downloading the [drone cli](https://docs.drone.io/cli/install/) and running `drone lint`:
<details>
<summary>Test output</summary>
```
Dev: root@dev rke2 [exclude-external-branches] drone lint --trusted .drone.yml 
2023/05/19 15:27:45 proto: duplicate proto type registered: PluginSpec
2023/05/19 15:27:45 proto: duplicate proto type registered: PluginPrivilege
&{ pipeline docker build-amd64 [] {false 0 0 false false} {0} map[] {linux amd64  } {{[] []} {[] []} {[] []} {[] []} {[] []} {[] []} {[] []} {[] []} {[] []} {[] []}} map[] [] [0xc0003b7500 0xc0003b7880 …
```
=> Ignore untracked branch pushes

go.mod, pkg/bootstrap/bootstrap.go
We need to use our own file copy logic since the helper from continuity replaces ownership and permissions on existing files. The previous approach worked if the manifests directory was created and hardened before RKE2 was first started, but did not do the right thing if the permissions or ownership were changed after the fact.
bugfix
* https://github.com/rancher/rke2/issues/4284
=> Use our own file copy logic instead of continuity

go.mod, pkg/bootstrap/bootstrap.go
We need to use our own file copy logic since the helper from continuity replaces ownership and permissions on existing files. The previous approach worked if the manifests directory was created and hardened before RKE2 was first started, but did not do the right thing if the permissions or ownership were changed after the fact.
bugfix
* https://github.com/rancher/rke2/issues/4304
=> [release-1.26] Use our own file copy logic instead of continuity

go.mod, pkg/bootstrap/bootstrap.go
We need to use our own file copy logic since the helper from continuity replaces ownership and permissions on existing files. The previous approach worked if the manifests directory was created and hardened before RKE2 was first started, but did not do the right thing if the permissions or ownership were changed after the fact.
bugfix
* https://github.com/rancher/rke2/issues/4305
=> [release-1.25] Use our own file copy logic instead of continuity

go.mod, pkg/bootstrap/bootstrap.go
We need to use our own file copy logic since the helper from continuity replaces ownership and permissions on existing files. The previous approach worked if the manifests directory was created and hardened before RKE2 was first started, but did not do the right thing if the permissions or ownership were changed after the fact.
bugfix
* https://github.com/rancher/rke2/issues/4377
=> [release-1.24] Use our own file copy logic instead of continuity

pkg/podexecutor/staticpod.go
If audit-log-path is not set when audit-policy-file is set, use default value.
Fixed regression introduced by https://github.com/rancher/rke2/pull/4139
bugfix
* https://github.com/rancher/rke2/issues/4415
=> Fix failure to set default audit-log-path

pkg/rke2/rke2.go, pkg/rke2/spw.go, pkg/staticpod/staticpod.go
Partial revert of 53d8510c81ff856fd5779e1b7a01f47dca46e233
This reverts static pod UID generation to use the same logic as the kubelet, in favor of manually removing stale static pods for etcd and the apiserver. The fixed pod UID was an attempt to trick the kubelet into syncing static pod containers even when the apiserver was unavailable, but it had the downside of preventing it from ever updating the mirror pods. This was confusing for end users who expect the pods visible via the apiserver to reflect what is actually running on the nodes.
bugfix
* SURE-6674
* https://github.com/rancher/rke2/issues/3725
* https://github.com/rancher/rke2/issues/4323
Note for QA: Please be sure to test this on a multi-server split-role (etcd-only/control-plane-only) cluster. I have …
=> Fix static pod UID generation and cleanup

install.sh
The default channel was changed to `stable` in b7b2e1a503907625a410e1a80e9a81a74a859add, but the corresponding documentation in the `install.sh` script was not updated.
This is a update of the documentation so it matches the code.
N/A
=> Fix incorrect documented default value for INSTALL_RKE2_CHANNEL

bundle/bin/rke2-uninstall.sh
In some cases a machine is configured with `/var/lib/kubelet` as a mount rather than a directory and this causes the `rke2-uninstall.sh` script to fail where it is removing directories so the machine isn't fully cleaned up. If you use the Rancher Federal Ansible RKE2 installer to install/re-instal RKE2, the presence of the files causes a re-install to fail. The change in this PR accomplishes exactly the same thing as the code it replaces because `rm -rf` removes all files under a  directory before trying to remove the directory itself. In the case where `/var/lib/kubelet` is a mount, it just ignores the error and moves on to clean up `/var/lib/rancher`.
In AWS, provision an instance with two drives and configure `/var/lib/kubelet` as a mount:
```
NAME        MAJ:MIN RM SIZE RO TYPE …
```
=> Uninstall handle cases when directories are mounts and cannot be removed

install.sh
hide `grep` No such file or directory error msg in install.sh `install_airgap_tarball`
add `-s` to grep in `install_airgap_tarball`.
verified
=> remove install_airgap_tarball grep error output

pkg/cli/cmds/cert.go
Fix default server address for rotate-ca command
bugfix
* https://github.com/rancher/rke2/issues/4483
```release-note
```
=> Fix default server address for rotate-ca command

pkg/windows/calico.go
Fixes the problem explained in the issue. Now both Felix and Calico-node will use the datastoretype kubernetes, so that the config is correct
Bugfix
Check in the felix logs that all felix daemons running  (linux or windows) use `DatastoreType: kubernetes`
https://github.com/rancher/rke2/issues/4569
```release-note
```
=> Sync Felix and calico-node datastore

pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/4570
Issue: https://github.com/rancher/rke2/issues/4575
=> [Release 1.24] Sync Felix and calico-node datastore

pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/4570
Issue: https://github.com/rancher/rke2/issues/4573
=> [Release 1.26] Sync Felix and calico-node datastore

pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/4570
Issue: https://github.com/rancher/rke2/issues/4574
=> [Release 1.25] Sync Felix and calico-node datastore

Dockerfile, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/4590
Issue: https://github.com/rancher/rke2/issues/4596
=> [Release 1.24] update to whereabouts v0.6.2

go.mod, go.sum
Version bump
Check versions
* https://github.com/rancher/rke2/issues/4629
```release-note
```
This PR is for the etcd snapshnot fixes on the newest commit in k3s
* this PR here -> https://github.com/k3s-io/k3s/pull/8177
=> Bump k3s version to recent 1.27

pkg/windows/calico.go
Add the env variable "VXLAN_VNI" to the calico process. This is required to create the calico hns-network. Without this network, calico fails to start
Bugfix
Deploy and make sure an hns-network with name calico exists 
https://github.com/rancher/rke2/issues/4580
```release-note
```
=> Bug fix: Add VXLAN_VNI env var to Calico-node exec

pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/4670
Issue: https://github.com/rancher/rke2/issues/4655
=> [Release 1.26] Fix bug. Add VXLAN_VNI env var to Calico-node exec

pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/4670
Issue: https://github.com/rancher/rke2/issues/4656
=> [Release 1.25] Fix bug. Add VXLAN_VNI env var to Calico-node exec

go.mod, go.sum, pkg/podexecutor/staticpod.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go, pkg/rke2/spw.go, pkg/staticpod/staticpod.go
=> Add additional static pod cleanup during cluster reset

go.mod, go.sum, pkg/podexecutor/staticpod.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go, pkg/rke2/spw.go, pkg/staticpod/staticpod.go
=> [release-1.27] Add additional static pod cleanup during cluster reset

go.mod, go.sum, pkg/podexecutor/staticpod.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go, pkg/rke2/spw.go, pkg/staticpod/staticpod.go
=> [release-1.26] Add additional static pod cleanup during cluster reset

go.mod, go.sum, pkg/podexecutor/staticpod.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go, pkg/rke2/spw.go, pkg/staticpod/staticpod.go
=> [release-1.25] Add additional static pod cleanup during cluster reset

go.mod, go.sum, pkg/podexecutor/staticpod.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go, pkg/rke2/spw.go, pkg/staticpod/staticpod.go
=> [release-1.24] Add additional static pod cleanup during cluster reset

pkg/cli/cmds/profile_linux.go, pkg/cli/cmds/root.go, pkg/rke2/rke2.go
- Add an new `--profile=cis` option that is equivalant  to`cis-1.23`.
- cis-1.23 is now deprecated, begin waring users that it will be removed in v1.29
Flag change
https://github.com/rancher/rke2/issues/3645
```release-note
```
=> Support new generic "cis" profile

pkg/windows/calico.go
Adds a 5s delay until we try again to start calico. This way, we won't see the same calico message too many times.
Bugfix
Check the rke2 logs in windows without this PR and you'll see Calico trying to start and failing ~20 times. Using this PR, you only see that message 2 or 3 times.
https://github.com/rancher/rke2/issues/4722
```release-note
```
=> Add a time.Sleep in calico-win to avoid polluting the logs

pkg/windows/calico.go
Issue: https://github.com/rancher/rke2/issues/4789
Backport: https://github.com/rancher/rke2/pull/4723
=> [Release 1.26] Add a time.Sleep in calico-win to avoid polluting the logs

pkg/cli/cmds/profile_linux.go, pkg/cli/cmds/root.go, pkg/rke2/rke2.go
Backport #4708  to 1.27
* Support generic "cis" profile
https://github.com/rancher/rke2/issues/4796
```release-note
```
=> [Release-1.27] Support generic "cis" profile

pkg/cli/cmds/profile_linux.go, pkg/cli/cmds/root.go, pkg/rke2/rke2.go
Backport #4708  to 1.25
* Support generic "cis" profile
https://github.com/rancher/rke2/issues/4794
```release-note
```
=> [Release-1.25] Support generic "cis" profile

pkg/rke2/spw.go
Fixes issue where pod restart attempts may obscure currently running pods from being found.
This switches to using upstream functions to determine the current pod sandbox, to ensure that rke2 is in sync with the kubelet.
bugfix
* https://github.com/rancher/rke2/issues/4775
```release-note
Fixed an issue where static pod startup checks may return false positives in the case of pod restarts
```
=> Handle restart attempts in static pod manifest checks

Dockerfile
Bumps chart versions to include the https://github.com/rancher/rke2-charts/pull/372 that makes the option ipFamilyPolicy: PreferDualStack as default
Version bump
Deploy rke2 in dualStack mode and check that now all services, except for kubernetes, have `ipFamilyPolicy: PreferDualStack`:
```
kubectl get svc -A -o yaml | grep Family
ipFamilyPolicy: SingleStack
ipFamilyPolicy: PreferDualStack
ipFamilyPolicy: PreferDualStack
ipFamilyPolicy: PreferDualStack
ipFamilyPolicy: PreferDualStack
```
https://github.com/rancher/rke2/issues/4776
```release-note
Use ipFamilyPolicy: PreferDualStack for system services: coredns, metrics-server, nginx and snapshot-validation-webhook
```
=> Update charts to have ipFamilyPolicy: PreferDualStack as default

scripts/validate-release
A filter in `validate-release` to not accept branchs that contains `dependabot` and `updatecli`
- Improvement
Create a branch with dependabot or update cli in our project
```bash
git checkout -b dependabot/testing
```
Push the branch
```bash
git push origin dependabot/testing
```
See the tag that are in the commit and then use
```bash
git branch --all -q --contains $YOUR_TAG_HERE | grep origin | grep -vE 'dependabot|updatecli|origin$|HEAD' | sed -e 's/^[[:space:]]*//'
```
You will not see any dependabot and updatecli branches
- https://github.com/rancher/rke2/issues/4743
```release-note
```
=> Filter to not accept dependabot and updatecli branchs

scripts/validate-release
Backport https://github.com/rancher/rke2/pull/4841
A filter in `validate-release` to not accept branchs that contains `dependabot` and `updatecli`
- Improvement
- Backport
Create a branch with dependabot or update cli in our project
```bash
git checkout -b dependabot/testing
```
Push the branch
```bash
git push origin dependabot/testing
```
See the tag that are in the commit and then use
```bash
git branch --all -q --contains $YOUR_TAG_HERE | grep origin | grep -vE 'dependabot|updatecli|origin$|HEAD' | sed -e 's/^[[:space:]]*//'
```
You will not see any dependabot and updatecli branches
- https://github.com/rancher/rke2/issues/4855
```release-note
```
=> [Release 1.26] Filter release branchs

Dockerfile, Dockerfile.windows
Bump containerd to v1.7.7+k3s1
version bump
check version
* https://github.com/rancher/rke2/issues/4873
```release-note
```
=> [release-1.27] Bump containerd to v1.7.7+k3s1

Dockerfile, Dockerfile.windows
Bump containerd to v1.7.7+k3s1
version bump
check version
* https://github.com/rancher/rke2/issues/4874
```release-note
```
=> [release-1.26] Bump containerd to v1.7.7+k3s1

go.mod, go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/b8dc95539bfc...5b6b9685e9205c52873398bab537494661330d65
bugfix
* https://github.com/rancher/rke2/issues/4906
```release-note
Re-enable etcd endpoint auto-sync 
Manually requeue configmap reconcile when no nodes have reconciled snapshots
```
=> Bump K3s version for v1.28

go.mod, go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/55e61670c365...0f6e77feaaf16b3019468ba985754adf34fe5614
bugfix
* https://github.com/rancher/rke2/issues/4913
```release-note
Re-enable etcd endpoint auto-sync 
Manually requeue configmap reconcile when no nodes have reconciled snapshots
```
=> [release-1.27] Bump K3s version for v1.27

go.mod, go.sum, pkg/cli/cmds/agent.go, pkg/cli/cmds/server.go
Updates k3s: https://github.com/k3s-io/k3s/compare/c9ee52b4eeab...43d998604f2d816188dacb11e3c46322fb82195f
bugfix
* https://github.com/rancher/rke2/issues/4914
```release-note
Re-enable etcd endpoint auto-sync 
Manually requeue configmap reconcile when no nodes have reconciled snapshots
```
=> [release-1.26] Bump K3s version for v1.26

go.mod, go.sum, pkg/cli/cmds/agent.go, pkg/cli/cmds/server.go
Updates k3s: https://github.com/k3s-io/k3s/compare/ec31704c1ab3...fe637b10b3b1ea03b2d3d095eb128a2ee38cc875
bugfix
* https://github.com/rancher/rke2/issues/4915
```release-note
Re-enable etcd endpoint auto-sync 
Manually requeue configmap reconcile when no nodes have reconciled snapshots
```
=> [release-1.25] Bump K3s version for v1.25

go.mod
This change should prevent some false negatives from static code analysis tools which parse the go version in the go.mod for all of our repositories.
=> Fix: upgrading Go in go.mod to 1.20

bundle/bin/rke2-killall.sh
- https://github.com/rancher/rancher/issues/42895
- #4933 
```release-note
```
=> [release-1.25] Remove pod-manifests dir in killall script

bundle/bin/rke2-killall.sh
Remove Pod manifests dir in the killall script
bugfix
- https://github.com/rancher/rancher/issues/42895
- #4931 
```release-note
```
=> [release-1.27] Remove pod-manifests dir in killall script

Dockerfile, scripts/build-images
Reverts rancher/rke2#4957. Only to turn around and reapply because golangci-lint failed.
=> Revert "[Release-1.26] Bump ingress-nginx to v1.9.3"

Dockerfile, Makefile, charts/build-charts.sh, charts/chart_versions.yaml, scripts/build-images, scripts/validate, scripts/validate-charts
validate-charts runs as part of 'make validate' step and checks that all images used in packaged charts:
- use systemGlobalRegistry
- are present in script/build-images
Tests
https://github.com/rancher/rke2/issues/4485
```release-note
```
At the moment, the new test fails because some charts don't use `systemGlobalRegistry` at all.
I'm not sure what would be the best way to move forward:
- make the test informative only for now
- fix the problematic charts in another PR before merging this one
Also I don;t know if the `busybox` image should be an exception or not.
=> Add chart validation tests

Dockerfile, Makefile, charts/build-charts.sh, charts/chart_versions.yaml, scripts/build-images, scripts/validate, scripts/validate-charts
validate-charts runs as part of 'make validate' step and checks that all images used in packaged charts:
- use systemGlobalRegistry
- are present in script/build-images
Linked issue: https://github.com/rancher/rke2/issues/5000
=> [backport-1.27] Add chart validation tests

Dockerfile, Makefile, charts/build-charts.sh, charts/chart_versions.yaml, scripts/build-images, scripts/validate, scripts/validate-charts
validate-charts runs as part of 'make validate' step and checks that all images used in packaged charts:
- use systemGlobalRegistry
- are present in script/build-images
Linked issue: https://github.com/rancher/rke2/issues/5002
=> [backport 1.26] Add chart validation tests

charts/chart_versions.yaml, scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5055
=> [backport 1.27] bump cilium chart to 1.14.400

charts/chart_versions.yaml, scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5056
=> [backport 1.26] bump cilium chart to 1.14.400

charts/chart_versions.yaml, scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5057
=> [backport 1.25] bump cilium chart to 1.14.400

.drone.yml, manifest-runtime.tmpl
Backport of https://github.com/rancher/rke2/pull/5095
=> [backport 1.25] remove s390x steps temporarily since runners are disabled

Dockerfile, Dockerfile.windows, go.mod, go.sum
Bump containerd to v1.7.11
version bump
check version
* https://github.com/rancher/rke2/issues/5118
```release-note
```
=> [release-1.27] Bump containerd to v1.7.11

bundle/bin/rke2-uninstall.sh, install.sh
Propose adding support for Amazon Linux 2023 (AL2023) for RKE2. Enabling RKE2 to run on Amazon Linux 2023 will ensure compatibility and increase the adoptability for customers to run RKE2 on AWS.
This pull request includes updates to the RKE2 `install.sh` and `rke2-uninstall.sh` scripts to detect "Amazon Linux 2023" in the operating system identification functions and appropriately configure the installation and uninstallation processes for RKE2 on AL2023.
Documentation Update: https://github.com/rancher/rke2-docs/pull/118
* **New Feature:** Support Installing RKE2 on Amazon Linux 2023 (AL2023)
**Verify Operating System:**
```bash
[root@ip-172-31-43-255 ec2-user]# cat /etc/amazon-linux-release
Amazon Linux release 2023 (Amazon Linux)
```
**Install RKE2 with Updated `install.sh`:**
```bash …
```
=> added support for amazon linux 2023

Dockerfile, Dockerfile.windows
Preparing for GCS bucket deprecation at some point (https://github.com/kubernetes/k8s.io/issues/2396)
Code maintenance 
The binary `kubectl` is retrieved successfully and build succeeds.
Already used in testing
https://github.com/rancher/rke2/issues/4951
none
=> Use dl.k8s.io for getting kubectl

Dockerfile.windows
The runtime image created for rke2 windows agents does not include the `charts` directory, causing rke2 to [always execute bootstrapping logic](https://github.com/rancher/rke2/blob/4fd30c26c91dd3f2f623c5af00d1ebcfec8c2709/pkg/bootstrap/bootstrap.go#L98) [whenever the rke2 windows service restarts](https://github.com/rancher/rke2/blob/4fd30c26c91dd3f2f623c5af00d1ebcfec8c2709/pkg/pebinaryexecutor/pebinary.go#L93-L97). When workloads are running on the node, or processes are left behind after the rke2 service is stopped due to https://github.com/rancher/rke2/issues/2204, then the bootstrapping process will fail and the service will enter a crash loop.
This PR adds an additional `mkdir` statement to `Dockerfile.windows` to ensure that newly created runtime images include the `charts` …
=> Address Repetitive Windows Bootstrapping

Dockerfile.windows
Backport #5159 to release-1.28
https://github.com/rancher/rke2/issues/5184
```release-note
```
=> [Release-1.28] ensure charts directory exists in Windows runtime image

charts/chart_versions.yaml, scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/3917
=> update multus chart to add optional dhcp daemonset

charts/chart_versions.yaml, scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5208
=> [release-1.27] update multus chart to add optional dhcp daemonset

tests/e2e/dnscache/Vagrantfile, tests/e2e/dnscache/dnscache_test.go, tests/e2e/resource_files/nodecache.yaml
Backport: https://github.com/rancher/rke2/commit/f8605328d2cb2c7768518900ed04d3170d0b8ddf
Issue: https://github.com/rancher/rke2/issues/5222
=> [Release 1.26] Add e2e test about dnscache

scripts/build-images
arm64 builds fail due to missed version bump
fixup for 08f7595cd0b76acab74d31c9e44ee8401edea79b
Linked issue: https://github.com/rancher/rke2/issues/5236
=> Bump sriov image build verions

charts/chart_versions.yaml, scripts/build-images, scripts/validate-charts
Linked issue: https://github.com/rancher/rke2/issues/5243
=> [release-1.27] update rke2-whereabouts to v0.6.3 and bump rke2-multus parent chart

scripts/build-images
Enables packaging of `arm64` images for calico, multus and harvester.
Also removes the deprecated `cilium-etcd-operator`
Linked issues:
* https://github.com/rancher/rke2/issues/5136
* https://github.com/rancher/rke2/issues/5260
=> Enable arm64 based images for calico, multus and harvester

scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5262
Backport: https://github.com/rancher/rke2/pull/5154
=> [Release-1.26] Enable arm64 based images for calico, multus and harvester

pkg/logging/logging.go, pkg/pebinaryexecutor/pebinary.go, pkg/windows/calico.go
Following on from what we do with Calico processes, use a file to dump the logs of kube-proxy in windows. The current Stdout and Stderr output is supposed to be piped to the Windows Logging System but it does not work. Using a file instead works.
This PR also moves Calico logs to the same place where kubelet logs are. That place is `C:\var\lib\rancher\rke2\agent\logs` which makes much more sense
Bugfix
Check issue
https://github.com/rancher/rke2/issues/5247
```release-note
```
=> [windows] Improve kube-proxy logging and move calico logs to a better path

tests/e2e/dualstack/Vagrantfile, tests/e2e/mixedos/Vagrantfile, tests/e2e/resource_files/secrets.yaml, tests/e2e/secretsencryption/Vagrantfile, tests/e2e/secretsencryption/secretsencryption_test.go, tests/e2e/secretsencryption_old/Vagrantfile, tests/e2e/secretsencryption_old/secretsencryption_test.go, tests/e2e/splitserver/Vagrantfile, tests/e2e/upgradecluster/Vagrantfile, tests/e2e/validatecluster/Vagrantfile
Add Secrets Encryption E2E tests (both new and old versions). The new version is currently broken in 1.29.
`go test -v ./tests/e2e/secretsencryption_old/...` 
https://github.com/rancher/rke2/issues/5092
```release-note
```
=> [E2E] Secrets Encryption test

pkg/controllers/cisnetworkpolicy/controller.go, pkg/rke2/rke2.go
Only run flannel host-network CIS netpol controller when using canal CNI
This will leave the existing policy in place in case anyone was depending on it, but new clusters will not have it. Administrators can delete if if they wish, without risk of the controller putting it back.
After some internal discussion, it appears that this was added when canal was our only CNI, and the policy this controller maintains should not be present when flannel is not in use. We are not going to actively remove it in case users are depending on it, but new clusters will not have it.
bugfix
Check for existence of policy on a new cluster
* https://github.com/rancher/rke2/issues/5315
```release-note
```
=> Only run flannel host-network CIS netpol controller when using canal CNI

charts/chart_versions.yaml, scripts/validate-charts
- clean-up temp yaml file
- fix k8s version check
- fix rke2-coredns templating
```release-note
```
=> fix validate-chart scripts

pkg/pebinaryexecutor/pebinary.go, pkg/rke2/rke2_windows.go, pkg/windows/calico.go, pkg/windows/types.go
Backport: https://github.com/rancher/rke2/pull/5276
Issue: https://github.com/rancher/rke2/issues/5366
=> [Release-1.27] [Windows] Create a common CNI interface and config struct

charts/chart_versions.yaml, scripts/validate-charts
Linked issue: https://github.com/rancher/rke2/issues/5372
Backport of https://github.com/rancher/rke2/pull/5160
=> [release-1.28] Fix validate-charts script

pkg/windows/calico.go, pkg/windows/utils.go
Check that interfaces are back if the HNS network was deleted before moving to HNS Network creation
Bugfix
This is a race condition that really depends on how fast your windows system is able to "recover" the interface after deleting the HNS Network. For me it was impossible to reproduce. However, a basic verification would be:
1 -  Deploy rke2 server with calico
2 - Deploy rke2-agent on windows
3 - Once everything is up, `Stop-Service rke2` and `C:\usr\local\bin\rke2.exe agent service --delete`
4 -  Verify that there is at least one HNS Network: `get-hnsnetwork`
5 - Start the rke2-agent on windows again with `debug: true` (remember to remove the node first or it will complain about password already there)
You should at least see the messages:
```
Deleting network: XXXXXX before starting …
```
=> Avoid race condition when deleting HNS networks

Dockerfile.windows, bundle/bin/rke2-killall.sh, bundle/bin/rke2-uninstall.ps1, charts/chart_versions.yaml, pkg/cli/cmds/server.go, pkg/pebinaryexecutor/pebinary.go, pkg/windows/calico.go, pkg/windows/flannel.go, pkg/windows/types.go, pkg/windows/utils.go, scripts/build-images
This PR adds flannel CNI plugin as an option for rke2. The reasoning is covered in the adr: https://github.com/rancher/rke2/pull/5145
Please only review the commit [Add CNI plugin flannel support for Windows](https://github.com/rancher/rke2/pull/5322/commits/f62faa4da342dddb7bb917a8e80195c0c9c54e5f). The other one is covered in the PR: https://github.com/rancher/rke2/pull/5276, which abstracts the interface so that more CNI plugins can be used
New feature
Use `cni: flannel` when deploying rke2
https://github.com/rancher/rke2/issues/5215
```release-note
Flannel added as CNI plugin option
```
=> Add flannel CNI plugin

bundle/bin/rke2-killall.sh
The network interface 'cilium_wg0' (added when wireguard is enabled in cilium) is not removed by the rke2-killall.sh script.
Bugfix
[5288](https://github.com/rancher/rke2/issues/5288)
```release-note
```
=> fix: missing 'ip link delete cilium_wg0' in rke2-killall.sh

Dockerfile.windows, bundle/bin/rke2-killall.sh, bundle/bin/rke2-uninstall.ps1, charts/chart_versions.yaml, pkg/cli/cmds/server.go, pkg/pebinaryexecutor/pebinary.go, pkg/windows/calico.go, pkg/windows/flannel.go, pkg/windows/types.go, pkg/windows/utils.go, scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5391
Backport: https://github.com/rancher/rke2/pull/5322
=> [Release-1.28] Add CNI plugin flannel support for Windows

bundle/bin/rke2-killall.sh
Backport: https://github.com/rancher/rke2/pull/5274
Issue: https://github.com/rancher/rke2/issues/5403
=> [Release-1.28] fix: missing 'ip link delete cilium_wg0' in rke2-killall.sh

bundle/bin/rke2-killall.sh
Backport: https://github.com/rancher/rke2/pull/5274
Issue: https://github.com/rancher/rke2/issues/5404
=> [Release-1.27] fix: missing 'ip link delete cilium_wg0' in rke2-killall.sh

bundle/bin/rke2-killall.sh
Backport: https://github.com/rancher/rke2/pull/5274
Issue: https://github.com/rancher/rke2/issues/5405
=> [Release-1.26] fix: missing 'ip link delete cilium_wg0' in rke2-killall.sh

docs/adrs/006-add-flannel-support.md
ADR. I am proposing a new feature
New feature proposal
https://github.com/rancher/rke2/issues/5215
```release-note
```
=> Add adr about rke2-flannel

pkg/windows/calico.go, pkg/windows/flannel.go, pkg/windows/utils.go
This PR does a few things:
1 - Fixes a bug in calico which prevented pods from starting (config should have "Calico" instead of "calico")
2 - Increases time out to 30s. I saw twice during my tests that sometimes 20s is not enough for the interfaces to come back in Windows
3 - Similarly to Flannel, before starting Calico, we check if the node is present in kube-api to avoid potential issues
4 - Instead of using an infinite loop to start calico, we use `wait.PollImmediateWithContext` with a time out of 5 minutes
5 - Flannel's `wait.PollImmediateWithContext` now return an error
Bugfix
Just verify that rke2 still works with flannel and calico
https://github.com/rancher/rke2/issues/5415
```release-note
```
=> Improve cni windows code

charts/chart_versions.yaml, scripts/build-images
Also provides an update for:
- cilium-envoy v1.27.2-13f6142b9c02268b10d547c8b093ef16724538e3
- hubble-ui v.12.3
- hardened-cni-plugins v1.4.0-build20240122
Issue: https://github.com/rancher/rke2/issues/5354
=> Update cilium 1.15.0

charts/chart_versions.yaml, scripts/build-images
* *backport of https://github.com/rancher/rke2/pull/5332*
* https://github.com/rancher/rke2/issues/5443
harvester-csi-driver's Helm chart has been bumped to 0.1.7 in rancher/rke-charts[1] (harvester-csi-driver tag v0.1.6)
[1] https://github.com/rancher/rke2-charts/blob/56596f9958f70296dec30f17c6d95bfc1e2690f0/packages/harvester-csi-driver/package.yaml#L1
Signed-off-by: Connor Kuehl <connor.kuehl@suse.com>
(cherry picked from commit 7a81df0886ca523981ba3aceb4301124a08eb24f)
=> [release-1.27] Bump harvester-csi-driver to 0.1.7

charts/chart_versions.yaml, scripts/build-images
Also provides an update for:
- cilium-envoy:v1.27.3-713b673cccf1af661efd75ca20532336517ddcb9
- hubble-ui:v0.13.0
Issue: https://github.com/rancher/rke2/issues/5472
=> Update Cilium to v1.15.1

pkg/rke2/np.go
Add new network policy for ingress controller webhook.
The ingress-nginx chart added a validating webhook a while back, but we did not have a policy that allowed access to it. Access was being allowed by the overly broad network policy that we removed in https://github.com/rancher/rke2/pull/5318.
Unfortunately we can't just add this to the existing netpol, as we document that it is not updated once the namespace annotation has been set.
bugfix
* https://github.com/rancher/rke2/issues/5315#issuecomment-1957853824
```release-note
```
=> Add new network policy for ingress controller webhook

pkg/rke2/np.go
Add new network policy for ingress controller webhook.
The ingress-nginx chart added a validating webhook a while back, but we did not have a policy that allowed access to it. Access was being allowed by the overly broad network policy that we removed in https://github.com/rancher/rke2/pull/5318.
Unfortunately we can't just add this to the existing netpol, as we document that it is not updated once the namespace annotation has been set.
bugfix
* https://github.com/rancher/rke2/issues/5358
```release-note
```
=> [release-1.28] Add new network policy for ingress controller webhook

pkg/rke2/np.go
Add new network policy for ingress controller webhook.
The ingress-nginx chart added a validating webhook a while back, but we did not have a policy that allowed access to it. Access was being allowed by the overly broad network policy that we removed in https://github.com/rancher/rke2/pull/5318.
Unfortunately we can't just add this to the existing netpol, as we document that it is not updated once the namespace annotation has been set.
bugfix
* https://github.com/rancher/rke2/issues/5359
```release-note
```
=> [release-1.27] Add new network policy for ingress controller webhook

pkg/rke2/np.go, pkg/rke2/serviceaccount.go, pkg/rke2/spc.go
Refactor netpol creation and add two new netpols
* Eliminate copy-pasted netpol creation functions in favor of iterating over templates
* Add new netpols for snapshot validation webhook and metrics-server
Continues fixing issues revealed by the removal of the allow-all policy in https://github.com/rancher/rke2/pull/5318
bugfix
* https://github.com/rancher/rke2/issues/5518
* https://github.com/rancher/rke2/issues/5519
```release-note
```
=> Refactor netpol creation and add two new netpols for metrics-server and snapshot-validation-webhook

go.mod, go.sum
Add support for bare hostname as endpoint, fix unnecessary namespace param inclusion
bugfix, enhancement
* https://github.com/rancher/rke2/issues/5516
```release-note
bump wharfie to v0.6.6 to add support for bare hostname as endpoint, fix unnecessary namespace param inclusion
```
=> bump wharfie to v0.6.6

go.mod, go.sum, pkg/rke2/np.go, pkg/rke2/serviceaccount.go, pkg/rke2/spc.go
Backport bugfixes:
* https://github.com/rancher/rke2/pull/5517
* https://github.com/rancher/rke2/pull/5521
bugfix
* https://github.com/rancher/rke2/issues/5522
* https://github.com/rancher/rke2/issues/5525
* https://github.com/rancher/rke2/issues/5528
```release-note
bump wharfie to v0.6.6 to add support for bare hostname as endpoint, fix unnecessary namespace param inclusion
Refactor netpol creation and add two new netpols for metrics-server and snapshot-validation-webhook
```
=> [release-1.28] Backport bugfixes for 2024-02 rc

go.mod, go.sum, pkg/rke2/np.go, pkg/rke2/serviceaccount.go, pkg/rke2/spc.go
Backport bugfixes:
* https://github.com/rancher/rke2/pull/5517
* https://github.com/rancher/rke2/pull/5521
bugfix
* https://github.com/rancher/rke2/issues/5523
* https://github.com/rancher/rke2/issues/5526
* https://github.com/rancher/rke2/issues/5529
```release-note
bump wharfie to v0.6.6 to add support for bare hostname as endpoint, fix unnecessary namespace param inclusion
Refactor netpol creation and add two new netpols for metrics-server and snapshot-validation-webhook
```
=> [release-1.27] Backport bugfixes for 2024-02 rc

go.mod, go.sum, pkg/rke2/np.go, pkg/rke2/serviceaccount.go, pkg/rke2/spc.go
Backport bugfixes:
* https://github.com/rancher/rke2/pull/5517
* https://github.com/rancher/rke2/pull/5521
bugfix
* https://github.com/rancher/rke2/issues/5524
* https://github.com/rancher/rke2/issues/5527
* https://github.com/rancher/rke2/issues/5530
```release-note
bump wharfie to v0.6.6 to add support for bare hostname as endpoint, fix unnecessary namespace param inclusion
Refactor netpol creation and add two new netpols for metrics-server and snapshot-validation-webhook
```
=> [release-1.26] Backport bugfixes for 2024-02 rc

charts/chart_versions.yaml, scripts/build-images
=> [release-1.28] Bump vsphere csi chart to 3.1.2-rancher101 and cpi to 1.7.001

charts/chart_versions.yaml, scripts/build-images
=> [release-1.27] Bump vsphere csi chart to 3.1.2-rancher101 and cpi to 1.7.001

charts/chart_versions.yaml, scripts/build-images
=> [release-1.26] Bump vsphere csi chart to 3.1.2-rancher101 and cpi to 1.7.001

go.mod, go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/c15e17676dea...aa3a18ba9b7a02de75b69412769e14e057661631
bugfix
* Pull through fix for 
https://github.com/k3s-io/k3s/issues/9730
```release-note
```
=> [release-1.28] Bump K3s version for v1.28

pkg/podexecutor/staticpod.go, pkg/staticpod/staticpod.go
- Mount server/cred directory. Allows apiserver to see hot reload for encryption-config.json when secrets-encryption controller updates the file.
- Improved comments
https://github.com/rancher/rke2/issues/5535
```release-note
```
=> Enable apiserver to access updated encryption-config.json

pkg/podexecutor/staticpod.go, pkg/rke2/rke2_linux.go
Clean up kube-proxy during agent bootstrap
If the static pod manifest isn't present during kubelet startup, it won't try to reconcile it until later, after the apiserver is up - which should address whatever weird race condition we've been running into with the volume mounts.
I haven't been able to figure out where exactly in the guts of the kubelet PLEG reconcile loop the volume mounts are getting mangled; all I know is that it appears to be a race condition between the kubelet reading the static pod manifest, and finding the mirror pod from the apiserver. Best we can do is try to avoid triggering it I guess.
bugfix
* https://github.com/rancher/rke2/issues/4864
```release-note
```
=> Remove kube-proxy static pod manifest during agent bootstrap

pkg/staticpod/staticpod.go
Properly handle files and sockets in extra mounts
Also allows manually specifying HostPathType, in case an unhandled type is needed
bugfix
* Test that a socket can be mounted into a pod: 
`/run/systemd/journal/dev-log:/dev/log`
* Test that an already existing file can be mounted into a pod: 
`/usr/share/zoneinfo/Etc/UTC:/etc/localtime`
`/usr/share/zoneinfo/Etc/UTC:/etc/localtime:ro`
* Test that a nonexistent file can be mounted into a pod, and will be created on first use:
`/tmp/example.txt:/tmp/example.txt:rw:FileOrCreate`
`/tmp/example.txt:/tmp/example.txt:ro:FileOrCreate`
* https://github.com/rancher/rke2/issues/1793
* https://github.com/rancher/rke2-docs/pull/173
```release-note
```
=> Properly handle files and sockets in extra mounts

charts/chart_versions.yaml, scripts/build-images
Bump flannel version
Bump version. Fixes a bug, described in issue
Check issue
https://github.com/rancher/rke2/issues/5637
```release-note
Fix flannel bug to work in cluster with taints
```
=> Bump flannel version

pkg/pebinaryexecutor/pebinary.go, pkg/windows/flannel.go
This PR improves two steps:
1 - We move from "cniVersion": "0.2.0", to "cniVersion": "1.0.0" which requires a change in the SourceVipResponse struct
2 - Moved "vxlan0" host-local network to "flannel.4096", so that it is in sync with the flannel network in Windows
3 - Use strings different from "dummy" which confuses support people (understandably)
Kind of bugfix
In the windows node, check /var/lib/network/cni/ and make sure there is no vxlan0 directory but only a flannel.4096. Then, verify that the reserved IP for kube-proxy (you can check it in the windows logs with "Reserved VIP for kube-proxy: $IP" is there and the content is:
```
kube-proxy
source-vip
```
https://github.com/rancher/rke2/issues/5662
```release-note
```
=> Improve how flannel-windows reserves an IP for kube-proxy vip

developer-docs/docker_multiarch.md
This PR adds a developer doc about building multi-arch images using cross-compilation to optimise build times.
Documentation
=> add doc on building multi-arch images

charts/chart_versions.yaml, scripts/build-images
- Hardened nginx bump
TBD
```release-note
```
=> Bump ingress-nginx to 1.9.6

charts/chart_versions.yaml, scripts/build-images
Backport https://github.com/rancher/rke2/pull/5671
```
kubectl get pods -A -o json | jq '.items[] | select(.metadata.labels."app.kubernetes.io/name") | { name: .metadata.labels."app.kubernetes.io/name", version: .metadata.labels."app.kubernetes.io/version" }'
...
{
"name": "rke2-ingress-nginx",
"version": "1.9.6"
}
```
https://github.com/rancher/rke2/issues/5685
```release-note
```
=> [Release-1.28] Bump ingress-nginx to 1.9.6

pkg/pebinaryexecutor/pebinary.go
For some reason it was necessary to configure the PATH for RKE2 to work correctly in Windows, as explained in the docs: https://docs.rke2.io/install/quickstart#3-configure-path. The reason is that we were setting the PATH wrongly and using ":" instead of ";". One is typical for Unix systems and the other one is for Windows
Bugfix
Run rke2-windows without configuring the PATH previously as set in the docs: https://docs.rke2.io/install/quickstart#3-configure-path
https://github.com/rancher/rke2/issues/5697
```release-note
Fix windows path setting
```
=> Fix Windows path setting

pkg/cli/cmds/cert.go
Fix incorrect mapping of subcommands introduced in recent k3s bump: https://github.com/rancher/rke2/pull/5714
bugfix
make sure subcommands to the right thing, not like this:
```console
root@rke2-server-1:/# rke2 certificate rotate
FATA[0000] only https:// URLs are supported, invalid scheme:
root@rke2-server-1:/# rke2 certificate check
INFO[0000] Server detected, rotating agent and server certificates
INFO[0000] Rotating dynamic listener certificate
INFO[0000] Rotating certificates for cloud-controller
INFO[0000] Rotating certificates for etcd
INFO[0000] Rotating certificates for scheduler
INFO[0000] Rotating certificates for supervisor
INFO[0000] Rotating certificates for kubelet
INFO[0000] Rotating certificates for rke2-controller
INFO[0000] Rotating certificates for api-server …
```
=> Fix subcommand mapping for `rke2 certificate`

charts/chart_versions.yaml, scripts/build-images
Update the Harvester cloud provider version
bump newer version
Regular tests for harvester-cloud-provider
```release-note
Bump Harvester-cloud-provider v0.2.3
```
=> Bump harvester-cloud-provider v0.2.3

charts/chart_versions.yaml, scripts/build-images, scripts/test-run-basics
Use a newer verison of metrics-server
Version bump
Regular tests on metrics-server
https://github.com/rancher/rke2/issues/5659
```release-note
Bump metrics server version to v0.7.1 and start using scratch as its base image
```
=> Bump metrics-server version

charts/chart_versions.yaml, scripts/build-images
- https://github.com/rancher/rke2/issues/5765
```release-note
```
=> Bump vsphere csi chart to 3.1.2-rancher300 and add snapshotter image

charts/chart_versions.yaml, scripts/build-images
- https://github.com/rancher/rke2/issues/5767
```release-note
```
=> [release-1.28] Bump vsphere csi chart to 3.1.2-rancher300 and add snapshotter image

charts/chart_versions.yaml, scripts/build-images
- https://github.com/rancher/rke2/issues/5768
```release-note
```
=> [release-1.27] Bump vsphere csi chart to 3.1.2-rancher300 and add snapshotter image

charts/chart_versions.yaml, scripts/build-images, scripts/test-run-basics
Backport: https://github.com/rancher/rke2/pull/5660
Issue: https://github.com/rancher/rke2/issues/5757
=> [Release 1.27] Bump metrics-server version

charts/chart_versions.yaml, scripts/build-images, scripts/test-run-basics
Issue: https://github.com/rancher/rke2/issues/5756
Backport: https://github.com/rancher/rke2/pull/5660
=> [Release 1.28] Bump metrics-server version

go.mod, go.sum
For /db/info fix
Updates k3s: https://github.com/k3s-io/k3s/compare/d3b60543e7df...94e29e2ef5d79904f730e2024c8d1682b901b2d5
bugfix / version bump
* https://github.com/rancher/rke2/issues/5819
```release-note
```
=> Bump K3s version for dbinfo fix

pkg/podexecutor/staticpod.go, pkg/staticpod/staticpod.go
Backport https://github.com/rancher/rke2/pull/5604
* Mount server/cred directory. Allows apiserver to see hot reload for encryption-config.json
* Make double mount a TODO
https://github.com/rancher/rke2/issues/5831
```release-note
```
=> [Release-1.28] Enable apiserver to access updated encryption-config.json 

charts/chart_versions.yaml
This removed the rke2-canal-crd chart.
Issue: https://github.com/rancher/rke2/issues/5833
=> Update rke2-canal to v3.27.3-build2024042301

bundle/bin/rke2-killall.sh
Remove `flannel-v6.4096` interface when running rke2 with `cni: flannel` and then executing `rke2-killall.sh`
Bugfix
After deploying rke2 with cni: flannel in a dual-stack environment, two interfaces get created flannel.4096 and flannel-v6.4096. When we execute rke2-killall.sh, both must be removed
https://github.com/rancher/rke2/issues/5794
```release-note
```
=> Remove flannel-v6.4096 when rke2-killall.sh

tests/e2e/dnscache/Vagrantfile, tests/e2e/dualstack/Vagrantfile, tests/e2e/multus/Vagrantfile
There are three e2e tests that had a useless config parameter: cni in the agent config makes no sense
Bugfix in e2e test
```release-note
```
=> Remove cni parameter from agent config in e2e tests

go.mod, go.sum
- bump k3s to match rc2, since it deprecates pod-infra-container-image
- bump
- check go mod for `1.30.0-rc2` 
```release-note
```
=> Bump k3s to deprecate pod-infra-container-image

tests/e2e/mixedosbgp/mixedosbgp_test.go, tests/e2e/testutils.go
This PR improves the mixedosbgp e2e test. Main changes:
1 - Restarts the Windows RemoteAccess service after RKE2 is set-up. This is a known issue in Calico that appears often. Thanks @rbrtbnfgl 
2 - Waits for Windows node to be ready before continuing executing tests
test e2e fix
```release-note
```
=> Fix mixedosbgp e2e test

scripts/validate
Backport: https://github.com/rancher/rke2/pull/5788
=> [Release 1.29] Add script to validate flannel versions

.github/workflows/test-suite.yaml, tests/e2e/dnscache/Vagrantfile, tests/e2e/dnscache/dnscache_test.go, tests/e2e/testutils.go, tests/e2e/vagrantdefaults.rb
- Enable local builds of RKE2 to run as E2E tests
- Add the dnscache E2E test to PR runs (only test with less than 3 nodes, so it fits inside GHA runner)
- Combine E2E and Integration tests into single "Test Suite" Workflow, helps with the limit number of Rancher runner instances
CI should be green
Its all testing changes
https://github.com/rancher/rke2/issues/5863
```release-note
```
=> Add E2E as a GitHub Action

go.mod, go.sum, pkg/cli/defaults/defaults.go, pkg/cli/defaults/defaults_linux.go, pkg/cli/defaults/defaults_windows.go, pkg/windows/utils.go
=> [1.29] windows changes

bundle/bin/rke2-uninstall.ps1, pkg/pebinaryexecutor/pebinary.go
This PR tries to fix the current implementation of the rke2-uninstall.ps1 script. Often this script fails to remove everything from the node because by the time it tries to remove the containerd namespace, there are still resources in that namespace. As a consequence, we end up with files in /var/lib/rancher/agent/ which are impossible to remove because according to Windows, they are locked. To remove them, a restart normally works but not always.
This PR does two things:
1 - The rke2-uninstall.ps1 would create a lock file in the dataDir. Then it will kill kubelet. In the pebinary code, we won't restart kubelet if that lock file exists
2 - It retries removing the namespace for a few times, in case the previous trial failed. There might be situations where the script can't succeed (e.g. …
=> Improve rke2-uninstall.ps1 script

tests/e2e/ciliumnokp/Vagrantfile, tests/e2e/ciliumnokp/ciliumnokp_test.go, tests/e2e/dnscache/Vagrantfile, tests/e2e/dualstack/Vagrantfile, tests/e2e/mixedos/Vagrantfile, tests/e2e/mixedos/mixedos_test.go, tests/e2e/mixedosbgp/Vagrantfile, tests/e2e/mixedosbgp/mixedosbgp_test.go, tests/e2e/multus/Vagrantfile, tests/e2e/scripts/cilium_nokubeproxy.sh, tests/e2e/secretsencryption/Vagrantfile, tests/e2e/secretsencryption_old/Vagrantfile, tests/e2e/splitserver/Vagrantfile, tests/e2e/testutils.go, tests/e2e/upgradecluster/Vagrantfile, tests/e2e/vagrantdefaults.rb, tests/e2e/validatecluster/Vagrantfile
Adds a e2e test for cilium without kube-proxy and using BPF. It uses ubuntu2310 because we need a kernel version above 5.10.
This PR also moves a couple of functions to testutils and consequently modifies how other tests are calling those functions
New test
go test -v -timeout=25m ./tests/e2e/ciliumnokp/
```release-note
```
=> Add cilium no proxy e2e test

pkg/rke2/np.go
Instead of failing RKE2 startup if the network policies cannot be updated, sync them in the background with retry.
bugfix
* https://github.com/rancher/rke2/issues/5693
```release-note
```
=> Apply netpols async with retry

pkg/controllers/cisnetworkpolicy/cleanup.go, pkg/rke2/rke2.go
Remove cisnetworkpolicy finalizer when controller is disabled
Prevents blocking node deletion after upgrading from a release that previously ran this controller, but no longer does due to the controller not being enabled for the configured CNI.
bugfix
* https://github.com/rancher/rke2/issues/5855
```release-note
```
=> Remove cisnetworkpolicy finalizer when controller is disabled

charts/chart_versions.yaml
Bumps flannel version to fix vni problem
Version bump
Deploy rke2 in linux with `cni: flannel` and then verify that the flannel interface has the name `flannel.4096`.
https://github.com/rancher/rke2/issues/5952
```release-note
Use vni=4096 as default for rke2-flannel
```
=> Update flannel chart to fix vni error

pkg/podexecutor/staticpod.go
- Mount the server directory to when rke2 restarts it doesn't stuck trying to connect to the kine socket
- Bugfix
To verify with sqlite you need to create a db file 
```bash
touch /var/lib/rancher/rke2/server/db/rke2-kine.db
```
now to test rke2 you need to set the `config.yaml` with this setting
```yaml
datastore-endpoint: sqlite:///var/lib/rancher/rke2/server/db/rke2-sqlite.db
```
and then after the server inits, you need to restart and then wait for the apiserver restart
- https://github.com/rancher/rke2/issues/5807
```release-note
Fix apiserver delay to restart when apiserver is using kine
```
=> Add a Kine fix when rke2 restart apiserver

bundle/bin/rke2-uninstall.ps1, pkg/pebinaryexecutor/pebinary.go
Backport: https://github.com/rancher/rke2/pull/5779
Issue: https://github.com/rancher/rke2/issues/5959
=> [Release 1.27] Improve rke2-uninstall.ps1 script

charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/5953
Issue: https://github.com/rancher/rke2/issues/5994
=> [Release 1.29] Update flannel chart to fix vni error (#5953)

tests/e2e/testutils.go
As of today, when running rke2 e2e tests, we can see how the server-0 is created. For example:
```
E2E_NODE_ROLES="server-0 agent-0" E2E_NODE_BOXES="generic/ubuntu2310 generic/ubuntu2310"  vagrant up server-0 &> vagrant.log
```
But we don't see the same log for the rest of VMs which might be confusing. This PR removes that confusion as now the test will print all `vagrant up` commands it runs
Extra logging
Run an e2e test that creates several VMs and you now should see the `vagrant up` command for all nodes, not just server-0
Example:
```
E2E_NODE_ROLES="server-0 agent-0" E2E_NODE_BOXES="generic/ubuntu2310 generic/ubuntu2310"  vagrant up server-0 &> vagrant.log
E2E_NODE_ROLES="server-0 agent-0" E2E_NODE_BOXES="generic/ubuntu2310 generic/ubuntu2310"  vagrant up agent-0 &>> vagrant.log
``` …
=> Add extra log in e2e tests

charts/chart_versions.yaml, scripts/build-images
- Chart bump
```release-note
```
=> Bump nginx to v1.10.1

bundle/bin/rke2-uninstall.sh
This fix will prevent fapolicyd service from inadvertently starting if the previous state was disabled.
- Change 'restart' to 'try-restart' for systemctl option.  Currently, if fapolicyd is disabled and not running, the 'restart'  option will start fapolicyd even if it was disabled.  
- No documentation update necessary.
Bugfix
- set fapolicyd systemd status to 'stopped/inactive' and 'disabled'
- issue command 'systemctl try-restart fapolicyd' . The status of fapolicyd should remain in 'inactive(dead)' and 'disabled' status.
- Pretty simple change.
-  #5809
```
NONE
```
=> Changed systemctl command from 'restart' to 'try-restart' for fapolicyd  in rke2-uninstall.sh

charts/build-chart.sh, pkg/bootstrap/bootstrap.go
Allow disabling injection of cluster config into HelmCharts via annotation, or by default via env var.
At some point we should consider setting it to default by false, so that user charts must opt in to having values injected.
We might also consider future changes to the implementation to do this via a hook to the deploy controller, instead of rewriting files on disk.
enhancements
* https://github.com/rancher/rke2/issues/6009
```release-note
Injection of cluster config variables into HelmChart resources found on disk can now be disabled per-chart by adding a `rke2.cattle.io/inject-cluster-config: "false"` annotation to HelmChart resources, or by setting the RKE2_INJECT_CLUSTER_CONFIG=false environment variable to disable it for all resources that do not set the annotation …
```
=> Allow disabling injection of cluster config into HelmCharts

tests/e2e/testutils.go
Backport: https://github.com/rancher/rke2/pull/5955
=> [Release 1.29] Add extra log in e2e tests

pkg/rke2/rke2_linux.go
- A easy way to set sqlite single node (the same way k3s does)
- New Feature
you will need to `disable etcd` and not send the `server` flag
```bash
rke2 server --disable-etcd
```
- https://github.com/rancher/rke2/issues/5957
```release-note
New behavior when --disable-etcd is used without --server, rke2 will use sqlite as the default database
```
=> Add easy support for single node sqlite with kine

charts/chart_versions.yaml
Backport https://github.com/rancher/rke2/pull/5980
```release-note
Bump Harvester-cloud-provider v0.2.4
```
=> [Release-1.28] Bump harvester-cloud-provider v0.2.4

charts/chart_versions.yaml
Backport https://github.com/rancher/rke2/pull/5980
```release-note
Bump Harvester-cloud-provider v0.2.4
```
=> [Release-1.27] Bump harvester-cloud-provider v0.2.4

go.mod, go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/f9130d537df6...1661f1024a68245bf768925a326ca558f2ea527e
version bump / pull-through
* https://github.com/rancher/rke2/issues/5949
* https://github.com/rancher/rke2/issues/6103
```release-note
```
=> Bump K3s version for v1.30

Dockerfile, Dockerfile.windows
Bump containerd to fixed tag
bugfix version bump
Check version
```release-note
```
=> Bump containerd to correctly built tag

.github/actions/setup-go/action.yaml, .github/workflows/test-suite.yaml, .github/workflows/unittest.yaml
Use a custom caching strategy for GitHub Action `setup-go`, which restricts:
- Only master branch can SAVE caches
- PRs can only RESTORE (ie read) caches
GitHub CI
For now, this PR should not open any new caches
https://github.com/rancher/rke2/issues/6143
```release-note
```
=> Add custom golang setup action for better caching

scripts/build-images
Also adds the `node-feature-discovery` image which is deployed by default as a subchart of the sriov chart
Depends on:
Issue: https://github.com/rancher/rke2/issues/5089
=> Update to the latest SR-IOV image versions

charts/chart_versions.yaml, scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6044
Backport: https://github.com/rancher/rke2/pull/6136
=> [release 1.29] Bump flannel image in rke2-canal

go.mod, go.sum, pkg/cli/defaults/defaults_windows.go, pkg/windows/utils.go
Remove the `acl.Mkdir` implementation and k3s acl dependencies in favor of the `rancher/permissions` repository. This change is associated to https://github.com/k3s-io/k3s/pull/10296, which removes the k3s acl logic rke2 currently relies on. 
Tech Debt 
This change can be verified by creating an RKE2 windows cluster and ensuring that the ACL set on the data directory only permits access to the local system and administrators. 
I have built a custom RKE2 binary using this change and the associated k3s change. I've created a standalone cluster and confirmed that the data directory is properly created with the expected ACL. I've also rebooted the node and service and confirmed that no errors are seen. 
```release-note
NONE
```
We need to merge this PR before we can bump the k3s version.
=> Use `rancher/permissions` dependency

go.mod, go.sum, pkg/cli/defaults/defaults_windows.go, pkg/windows/utils.go
Remove the `acl.Mkdir` implementation and k3s acl dependencies in favor of the `rancher/permissions` repository. This change is associated to https://github.com/k3s-io/k3s/pull/10298, which removes the k3s acl logic rke2 currently relies on. 
Tech Debt 
This change can be verified by creating an RKE2 windows cluster and ensuring that the ACL set on the data directory only permits access to the local system and administrators. 
I have built a custom RKE2 binary using this change and the associated k3s change. I've created a standalone cluster and confirmed that the data directory is properly created with the expected ACL. I've also rebooted the node and service and confirmed that no errors are seen. 
```release-note
NONE
```
=> [1.29] Use `rancher/permissions` dependency

go.mod, go.sum, pkg/cli/defaults/defaults_windows.go, pkg/windows/utils.go
Remove the `acl.Mkdir` implementation and k3s acl dependencies in favor of the `rancher/permissions` repository. This change is associated to https://github.com/k3s-io/k3s/pull/10299, which removes the k3s acl logic rke2 currently relies on. 
Tech Debt 
This change can be verified by creating an RKE2 windows cluster and ensuring that the ACL set on the data directory only permits access to the local system and administrators. 
I have built a custom RKE2 binary using this change and the associated k3s change. I've created a standalone cluster and confirmed that the data directory is properly created with the expected ACL. I've also rebooted the node and service and confirmed that no errors are seen. 
```release-note
NONE
```
=> [1.28] Use `rancher/permissions` dependency

scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5889
Issue: https://github.com/rancher/rke2/issues/6148
=> [Release-1.27] Update to the latest SR-IOV image versions

scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5889
Issue: https://github.com/rancher/rke2/issues/6146
=> [Release-1.29] Update to the latest SR-IOV image versions

scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5889
Issue: https://github.com/rancher/rke2/issues/6147
=> [Release-1.28] Update to the latest SR-IOV image versions

.github/actions/setup-go/action.yaml, .github/workflows/test-suite.yaml, .github/workflows/unittest.yaml, scripts/build-image-runtime, tests/e2e/ciliumnokp/Vagrantfile, tests/e2e/dnscache/Vagrantfile, tests/e2e/dualstack/Vagrantfile, tests/e2e/mixedos/Vagrantfile, tests/e2e/mixedos/mixedos_test.go, tests/e2e/mixedosbgp/Vagrantfile, tests/e2e/mixedosbgp/mixedosbgp_test.go, tests/e2e/multus/Vagrantfile, tests/e2e/splitserver/Vagrantfile, tests/e2e/testutils.go, tests/e2e/upgradecluster/Vagrantfile, tests/e2e/vagrantdefaults.rb, tests/e2e/validatecluster/Vagrantfile
Contains:
- https://github.com/rancher/rke2/pull/6058
- https://github.com/rancher/rke2/pull/6097
- https://github.com/rancher/rke2/pull/6137
- https://github.com/rancher/rke2/pull/6144
Testing and CI
CI still Green
https://github.com/rancher/rke2/issues/6023
https://github.com/rancher/rke2/issues/6119
https://github.com/rancher/rke2/issues/6143
```release-note
Testing CI backports:
- Fix loadManifests function
- Slim down E2E artifacts
- Support MixedOS E2E local testing
- Add custom golang setup action for better caching
```
=> [Release-1.28] June Testing Backports

charts/chart_versions.yaml
Bump rke2-ingress-nginx chart to revert watchIngressWithoutClass default
Will redo this in July for https://github.com/rancher/rke2/pull/5943
bugfix
* https://github.com/rancher/rke2/issues/6214
```release-note
```
=> Bump rke2-ingress-nginx chart to revert watchIngressWithoutClass default

charts/chart_versions.yaml
Bump rke2-ingress-nginx chart to revert watchIngressWithoutClass default
Will redo this in July for https://github.com/rancher/rke2/pull/5943
bugfix
* https://github.com/rancher/rke2/issues/6214
```release-note
```
=> [release-1.29] Bump rke2-ingress-nginx chart to revert watchIngressWithoutClass default

charts/chart_versions.yaml
Bump rke2-ingress-nginx chart to revert watchIngressWithoutClass default
Will redo this in July for https://github.com/rancher/rke2/pull/5943
bugfix
* https://github.com/rancher/rke2/issues/6214
```release-note
```
=> [release-1.28] Bump rke2-ingress-nginx chart to revert watchIngressWithoutClass default

charts/chart_versions.yaml
Bump rke2-ingress-nginx chart to revert watchIngressWithoutClass default
Will redo this in July for https://github.com/rancher/rke2/pull/5943
bugfix
* https://github.com/rancher/rke2/issues/6214
```release-note
```
=> [release-1.27] Bump rke2-ingress-nginx chart to revert watchIngressWithoutClass default

go.mod, go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/b4d4ed8f010a...aa4794b37223156c5f651d94e23670bd7e581607
* https://github.com/rancher/rke2/issues/6226
```release-note
Fix issue that allowed multiple simultaneous snapshots to be allowed
```
=> Bump K3s version for snapshot fix

charts/chart_versions.yaml, scripts/build-images
- Revert back from v1.10.1 to v1.9.6 of ingress-nginx, the arm64 images are not stable.
Bugfix/revert
None of our automated testing covers arm64, nor does upstream have automated arm64 tests
https://github.com/rancher/rke2/issues/6235
```release-note
```
=> Revert rke2-ingress-nginx bump back to v1.9.6

charts/chart_versions.yaml, scripts/build-images
Backport of https://github.com/rancher/rke2/pull/6238
- Revert back from v1.10.1 to v1.9.6 of ingress-nginx, the arm64 images are not stable.
Bugfix/revert
None of our automated testing covers arm64, nor does upstream have automated arm64 tests
https://github.com/rancher/rke2/issues/6239
```release-note
```
=> [Release-1.29] Revert rke2-ingress-nginx bump back to v1.9.6

charts/chart_versions.yaml, scripts/build-images
Backport of https://github.com/rancher/rke2/pull/6238
- Revert back from v1.10.1 to v1.9.6 of ingress-nginx, the arm64 images are not stable.
Bugfix/revert
None of our automated testing covers arm64, nor does upstream have automated arm64 tests
https://github.com/rancher/rke2/issues/6240
```release-note
```
=> [Release-1.28] Revert rke2-ingress-nginx bump back to v1.9.6

charts/chart_versions.yaml, scripts/build-images
Backport of https://github.com/rancher/rke2/pull/6238
- Revert back from v1.10.1 to v1.9.6 of ingress-nginx, the arm64 images are not stable.
Bugfix/revert
None of our automated testing covers arm64, nor does upstream have automated arm64 tests
https://github.com/rancher/rke2/issues/6241
```release-note
```
=> [Release-1.27] Revert rke2-ingress-nginx bump back to v1.9.6

charts/chart_versions.yaml, scripts/build-images
After more QA, ultimate blame came down a binary issue in the canal CNI images, not ingress-nginx. Reinstating the latest v1.10.1 image
https://github.com/rancher/rke2/issues/6235
```release-note
```
=> Reinstate newest rke2-ingress-nginx

charts/chart_versions.yaml, scripts/build-images
After more QA, ultimate blame came down a binary issue in the canal CNI images, not ingress-nginx. Reinstating the latest v1.10.1 image
https://github.com/rancher/rke2/issues/6239
```release-note
```
=> [Release-1.29] Reinstate newest rke2-ingress-nginx

charts/chart_versions.yaml, scripts/build-images
After more QA, ultimate blame came down a binary issue in the canal CNI images, not ingress-nginx. Reinstating the latest v1.10.1 image
https://github.com/rancher/rke2/issues/6241
```release-note
```
=> [Release-1.27] Reinstate newest rke2-ingress-nginx 

charts/chart_versions.yaml, scripts/build-images
After more QA, ultimate blame came down a binary issue in the canal CNI images, not ingress-nginx. Reinstating the latest v1.10.1 image
https://github.com/rancher/rke2/issues/6240
```release-note
```
=> [Release-1.28] Reinstate newest rke2-ingress-nginx 

tests/e2e/mixedos/Vagrantfile, tests/e2e/mixedos/mixedos_test.go, tests/e2e/mixedosbgp/Vagrantfile, tests/e2e/testutils.go
rke2.env is read by the [provisioner.rb](https://github.com/rancher/vagrant-rke2/blob/main/lib/vagrant-rke2/provisioner.rb#L126-L131) and if it is passed as an array, it adds an extra `-`, as a consequence, powershell is executing:
```
./install.ps1 --Commit (Get-Content -TotalCount 1 ./rke2_commits.txt)
```
i.e. the flag Commit has 2 dash symbols and that is wrong. As a consequence, powershell ignores it and passes the value as the first positional flag, which is Method. Then it fails because:
```
Cannot validate argument on parameter 'Method'. The argument "f9aa70bc03be5818efd9016a8d9de2ddadf45703" does not belong to the set "choco,tar" specified by the ValidateSet
```
In the end the e2e test fails because when it tries to check that `rke2.exe --version` is correct, it can't find …
=> [Bug] Pass install_type as a string in the mixedos e2e test

charts/chart_versions.yaml, scripts/build-images
=> Update calico image to v3.28.0-build20240625

tests/e2e/ciliumnokp/Vagrantfile, tests/e2e/dnscache/Vagrantfile, tests/e2e/dualstack/Vagrantfile, tests/e2e/multus/Vagrantfile
Remove the bind-address arg which is not needed and could be problematic if we use `kubectl exec ...` like in the cilium e2e test due to https://github.com/k3s-io/k3s/issues/10444
Besides, `kubelet-arg: "--node-ip=0.0.0.0"` is not needed anymore. That was fixed upstream
Update e2e tests
```release-note
```
=> Update Vagrantfile of a few e2e tests

pkg/rke2/clusterrole.go, pkg/rke2/clusterrole_bootstrap.go
Fixed an issue where failing to include APIGroup on the subject struct caused the reconcile helpers to think the subject needed to be re-added every time RKE2 starts up.
bugfix
1. Install prior RKE2 release
1. Restart RKE2 server service a few times
1. Confirm that the affected ClusterRoles and ClusterRoleBindings have duplicate Subjects
1. Upgrade to a build of RKE2 that includes this fix
1. Confirm that the affected ClusterRoles and ClusterRoleBindings have only a single Subject
* https://github.com/rancher/rke2/issues/6272
```release-note
```
This now includes automated cleanup. Older releases can be manually cleaned with the following commands. Note that these will need to be run periodically until all servers have been upgraded:
`kubectl patch clusterrolebinding …
=> Fix RoleBinding/ClusterRoleBinding subject growth

pkg/cli/defaults/defaults.go
Improve agent logs dir default permissions
This one goes all the way back!
* https://github.com/rancher/rke2/pull/12
enhancement
Check dir permissions
* 
```release-note
```
=> Improve agent logs dir default permissions

tests/e2e/createreport/launchresults.html, tests/e2e/dnscache/Vagrantfile, tests/e2e/dnscache/dnscache_test.go, tests/e2e/dualstack/Vagrantfile, tests/e2e/dualstack/dualstack_test.go, tests/e2e/mixedos/Vagrantfile, tests/e2e/mixedos/mixedos_test.go, tests/e2e/mixedosbgp/Vagrantfile, tests/e2e/mixedosbgp/mixedosbgp_test.go, tests/e2e/multus/Vagrantfile, tests/e2e/multus/multus_test.go, tests/e2e/scripts/latest_commit.sh, tests/e2e/scripts/run_tests.sh, tests/e2e/splitserver/Vagrantfile, tests/e2e/splitserver/splitserver_test.go, tests/e2e/upgradecluster/Vagrantfile, tests/e2e/upgradecluster/upgradecluster_test.go, tests/e2e/validatecluster/Vagrantfile, tests/e2e/validatecluster/validatecluster_test.go
This PR adds some extra logging in the latest_commit.sh script. If there was an error because of the API exceeding the limits, it was impossible to notice
Moreover, it refactors run_tests.sh script trying to make it simpler. Changes:
1 - Removes all the parameters that can be passed except for nodeOS, which is important for the results generation. Some of them depend on the test itself and should not be changed (servercount, agentcount). Some are not read by any test (db or hardened)
2 - Removes `rke2_version` and `rke2_channel` variables and references as the former was always empty and the latter was always `commit`, which is anyway the default: https://github.com/rancher/rke2/blob/master/tests/e2e/vagrantdefaults.rb#L19-L22
3 - Creates a loop that goes over an array with the different …
=> Refactor run_tests.sh script

tests/e2e/mixedos/README.md, tests/e2e/mixedos/Vagrantfile
Adds support for cni: flannel in the mixedos test
New test
E2E_CNI=flannel go test -v -timeout=30m tests/e2e/mixedos/mixedos_test.go
```release-note
```
=> Add e2e test about mixedos+flannel

bundle/bin/rke2-killall.sh, bundle/bin/rke2-uninstall.ps1, bundle/bin/rke2-uninstall.sh
Add `RKE2_DATA_DIR` as an optional environment variable to the `rke2-killall.sh`,`rke2-uninstall.sh`, and `rke2-uninstall.ps1` scripts.
Bugfix
Installing RKE2 with a custom `data-dir` (not `/var/lib/rancher/rke2`), and running the killall and uninstall scripts, verifying assets in `/var/lib/rancher/rke2` are properly removed.
This is not currently covered by testing, though I would be happy to write an integration test if need be.
* https://github.com/rancher/rke2/issues/6292
```release-note
NONE
```
Relates to https://github.com/rancher/rancher/issues/46066.
=> Add `data-dir` to uninstall and killall scripts

charts/chart_versions.yaml, docs/adrs/008-traefik-ingress.md, pkg/bootstrap/bootstrap.go, pkg/cli/cmds/server.go, pkg/pebinaryexecutor/pebinary.go, pkg/podexecutor/staticpod.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go, pkg/rke2/rke2_windows.go
Waiting on:
---
* Add ADR for multiple ingress controller support; initially with traefik as the only additional packaged ingress controller.
* Add CLI flag to select ingress controllers; multiple may be chosen, and `--ingress-controller=none` will disable all of them, same as `--cni=none`.
* Update charts
**Note:** while multiple ingress controllers can be selected via the CLI flag, and the first one will be set as the default ingress class, additional user-provided configuration will be necessary to allow both ingress controllers to run in parallel , due to both charts defaulting to deploying a DaemonSet that binds to ports 80 and 443. **For this reason, while allowed by the CLI flag, we will not be *supporting* parallel installation of multiple ingress controllers.**
If someone did …
=> Add multiple ingress controller support + traefik

main.go, pkg/cli/cmds/cmds_test.go, pkg/cli/cmds/completion.go, pkg/cli/cmds/root.go
- Add a completion for the shell the same way k3s does but with two more cli flags to add the kubectl and crictl to the environment
- Feature
- Install rke2 and run `rke2 completion bash -i --crictl --kubectl` or `rke2 completion zsh -i --crictl --kubectl`
- https://github.com/rancher/rke2/issues/5488
```release-note
RKE2 now support shell completion
```
- I saw the need for the entire Run function to be on RKE2 because the requirement for exposing kubectl and crictl files are only for rke2
=> Rke2 shell completion

install.sh
Remove the append for the fapolicyd rules.
Don't duplicate the fapolicyd rules in the rules file if install.sh script is ran more than once. It should be unlikely that anyone would use this rules file for anything other than RKE2, as the naming of it is specifically for RKE2. This should be a total replacement and not an append. It should be confident enough that it is all inclusive.
Run the install script multiple times on a host with fapolicyd enabled. Note that it no longer continuously appends duplicate rules.
* https://github.com/rancher/rke2/issues/6335
```release-note
```
=> Change fapolicyd rules to full replacement rather than append

charts/chart_versions.yaml, scripts/build-images
vpshere cpi and csi bumps
Chart Bumps
https://github.com/rancher/rke2/issues/6339
```release-note
```
=> [Release-1.27] Bump vsphere csi chart to 3.3.0-rancher100 and cpi to 1.8.000

charts/chart_versions.yaml, scripts/build-images
vpshere cpi and csi bumps
Chart Bumps
https://github.com/rancher/rke2/issues/6338
```release-note
```
=> [Release-1.28] Bump vsphere csi chart to 3.3.0-rancher100 and cpi to 1.8.000

charts/chart_versions.yaml, scripts/build-images
vpshere cpi and csi bumps
Chart Bumps
https://github.com/rancher/rke2/issues/6337
```release-note
```
=> [Release-1.29] Bump vsphere csi chart to 3.3.0-rancher100 and cpi to 1.8.000

charts/chart_versions.yaml, scripts/build-images
vpshere cpi and csi bumps
Chart Bumps
https://github.com/rancher/rke2/issues/6336
```release-note
```
=> [Release-1.30] Bump vsphere csi chart to 3.3.0-rancher100 and cpi to 1.8.000

.github/workflows/pr.yml
=> [release-1.27] Fix secrets for commit id uploads

install.sh
- For the supported CNIs, if images are found in the artifact path, automatically move to the agent images directory, removing a manual step the user would need to perform. 
Create two folder with the following contents:
```
derek@degion:~$ ls ./rke2-artifacts
rke2-images.linux-amd64.tar.zst  rke2.linux-amd64.tar.gz  sha256sum-amd64.txt
derek@degion:~$ ls ./rke2-artifacts-with-extra/
rke2-images-canal.linux-amd64.tar.zst   rke2-images-harvester.linux-amd64.tar.gz  rke2.linux-amd64.tar.gz
rke2-images-flannel.linux-amd64.tar.gz  rke2-images.linux-amd64.tar.zst           sha256sum-amd64.txt
```
Run the installer on both:
```
root@degion:/home/derek/rancher/rke2# INSTALL_RKE2_ARTIFACT_PATH=/home/derek/rke2-artifacts sh install.sh
[INFO]  staging local checksums from …
```
=> Stage CNI (and harvester) images if avaliable for airgap

.github/workflows/release.yml
=> Add missing package windows step in release

scripts/dispatch
=> [release-1.27] Fix dispatch script

charts/chart_versions.yaml
Related issue: https://github.com/rancher/rke2/issues/5832
Jira: SURE-8176
=> Bump rke2-coredns to add option to use nodelocal dns cache with cilium Local Redirect Policy

scripts/build-images
Add traefik airgap image tarball
Note that we are not providing a core image without ingress-nginx; anyone who wants to use traefik instead of ingress-nginx will need to load the core tarball (with the ingress-nginx images) in addition to the traefik tarball. We will continue to ship ingress-nginx in the core tarball until it is no longer the default.
airgap
* https://github.com/rancher/rke2/issues/6438
```release-note
```
=> Add traefik airgap image tarball

scripts/build-images
Add traefik airgap image tarball
Note that we are not providing a core image without ingress-nginx; anyone who wants to use traefik instead of ingress-nginx will need to load the core tarball (with the ingress-nginx images) in addition to the traefik tarball. We will continue to ship ingress-nginx in the core tarball until it is no longer the default.
airgap
* https://github.com/rancher/rke2/issues/6440
```release-note
```
=> [release-1.30] Add traefik airgap image tarball

go.mod, pkg/rke2/rke2_linux.go
- A bugfix for when the user uses datastore endpoint with etcd endpoints
- Bugfix
- Run rke2 with a external etcd instance
- https://github.com/rancher/rke2/issues/6194
```release-note
```
=> Fix external etcd connection

pkg/rke2/np.go
Add netpol template for traefik
bugfix
* https://github.com/rancher/rke2/issues/6449
```release-note
```
=> Add netpol template for traefik

charts/chart_versions.yaml
Issue: https://github.com/rancher/rke2/issues/6431
Backport: https://github.com/rancher/rke2/pull/6372
=> [Release-1.30] - Bump rke2-coredns to add option to use nodelocal dns cache with cilium

charts/chart_versions.yaml, scripts/build-images
https://github.com/rancher/rke2/issues/6476
```release-note
```
=> [Release-1.29] Bump nginx to hardened2

pkg/windows/calico.go, pkg/windows/utils.go
This PR move the delete of all networks on a script that does as Calico that checks if the node is rebooted only.
The fix right now works only if the other version has already the new script check updating from an older version requires a node reboot and the bug is fixed from the next version updates.
1. Run a pod on windows
2. Update RKE2 version on the windows node
3. The pod will have connectivity issue
4. Update RKE2 from a fixed version to a new fixed version
5. No issue should occur
#5551
```release-note
```
=> Added check if the node is rebooted before the networks is deleted on windows

pkg/windows/calico.go, pkg/windows/utils.go
=> [Release 1.30] Fixed hns clean only in case of reboot

bundle/bin/rke2-killall.sh
Modify `rke2-killall.sh` to handle `RKE2_DATA_DIR`
Bugfix
Here is my test script. Place this script and the modified `rke2-killall.sh` into a temp dir on the host and then run the test script with the temp dir as the working directory:
```
#!/usr/bin/env bash
set -e
function wait_cluster() {
while true; do
if ! $1/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml -n kube-system wait job --all --for condition=Complete --timeout=30s; then
sleep 2s
continue
fi
$1/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml -n kube-system get ds,deploy -oname | while read -r unit; do
if ! $1/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml -n kube-system rollout status $unit; then
sleep 2s
continue
fi
done
break
done
$1/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get po -A
}
function …
```
=> Modify rke2-killall.sh to handle RKE2_DATA_DIR

Dockerfile, Dockerfile.windows, bundle/bin/rke2-killall.sh
* Bump containerd/crictl/runc versions
New releases have been built with golang v1.22.6
* Fix killall script with custom data-dir
version bump
Check vuln scan results
* https://github.com/rancherlabs/image-scanning/issues/3727
* https://github.com/rancher/rke2/issues/6542
```release-note
```
=> [release-1.30] Bump containerd/crictl/runc versions

Dockerfile, Dockerfile.windows, bundle/bin/rke2-killall.sh
* Bump containerd/crictl/runc versions
New releases have been built with golang v1.22.6
* Fix killall script with custom data-dir
*
version bump
Check vuln scan results
* https://github.com/rancherlabs/image-scanning/issues/3727
* https://github.com/rancher/rke2/issues/6543
```release-note
```
=> [release-1.29] Bump containerd/crictl/runc versions

Dockerfile, Dockerfile.windows, bundle/bin/rke2-killall.sh
* Bump containerd/crictl/runc versions
New releases have been built with golang v1.22.6
* Fix killall script with custom data-dir
version bump
Check vuln scan results
* https://github.com/rancherlabs/image-scanning/issues/3727
* https://github.com/rancher/rke2/issues/6544
```release-note
```
=> [release-1.28] Bump containerd/crictl/runc versions

Dockerfile, Dockerfile.windows, bundle/bin/rke2-killall.sh
* Bump containerd/crictl/runc versions
New releases have been built with golang v1.22.6
* Fix killall script with custom data-dir
version bump
Check vuln scan results
* https://github.com/rancherlabs/image-scanning/issues/3727
* https://github.com/rancher/rke2/issues/6545
```release-note
```
=> [release-1.27] Bump containerd/crictl/runc versions

Dockerfile, scripts/build-windows-images, scripts/package-windows-images
bugfix
* https://github.com/rancher/rke2/issues/6579
```release-note
```
=> Fix windows airgap image packaging

Dockerfile, scripts/build-windows-images, scripts/package-windows-images
bugfix
* https://github.com/rancher/rke2/issues/6584
```release-note
```
=> [release-1.27] Fix windows airgap image packaging

Dockerfile, scripts/build-windows-images, scripts/package-windows-images
bugfix
* https://github.com/rancher/rke2/issues/6583
```release-note
```
=> [release-1.28] Fix windows airgap image packaging

Dockerfile, scripts/build-windows-images, scripts/package-windows-images
bugfix
* https://github.com/rancher/rke2/issues/6582
```release-note
```
=> [release-1.29] Fix windows airgap image packaging

Dockerfile, scripts/build-windows-images, scripts/package-windows-images
bugfix
* https://github.com/rancher/rke2/issues/6581
```release-note
```
=> [release-1.30] Fix windows airgap image packaging

pkg/rke2/np.go
Fix traefik netpol port names
bugfix
* https://github.com/rancher/rke2/issues/6453
```release-note
```
=> [release-1.30] Fix traefik netpol port names

Dockerfile, go.mod, go.sum
Bump runc to v1.1.13
version bump
Check version
* https://github.com/rancher/rke2/issues/6622
```release-note
```
=> Bump runc to v1.1.13

charts/chart_versions.yaml, scripts/build-images
=> [master] feat: bump harvester-cloud-provider to v0.2.6

charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/6707
Issue: https://github.com/rancher/rke2/issues/6712
=> [Release-1.29] Update cilium chart to `1.16.103`

charts/chart_versions.yaml
Disable cilium envoy by default
Issue: https://github.com/rancher/rke2/issues/6682
Depends on:
=> Update cilium chart to `1.16.103`

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6729
Issue: https://github.com/rancher/rke2/issues/6740
=> [release-1.29] Bump multus chart to v4.1.000

scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6747
Issue: https://github.com/rancher/rke2/issues/6750
=> [release 1.31] Remove sriov images from airgap tarball

scripts/build-images
Backport: [#6747](https://github.com/rancher/rke2/pull/6747)
 Issue: https://github.com/rancher/rke2/issues/6752
=> [release-1.30] Remove sriov images from airgap tarball

scripts/build-images
Backport: [#6747](https://github.com/rancher/rke2/pull/6747)
 Issue: https://github.com/rancher/rke2/issues/6754
=> [release 1.29] Remove sriov images from airgap tarball

scripts/build-images
Backport: [#6747](https://github.com/rancher/rke2/pull/6747) 
Issue: https://github.com/rancher/rke2/issues/6756
=> [release-1.28] Remove sriov images from airgap tarball

charts/chart_versions.yaml, scripts/build-images
Bump the following images and charts:
* canal
* coredns
* flannel
* metrics-server
* multus
* cilium
To fix CVE GO-2024-3106
Version bump
https://github.com/rancher/rke2/issues/6770
```release-note
```
=> Bump charts and images to fix CVE GO-2024-3106

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6771
Issue: https://github.com/rancher/rke2/issues/6781
=> [Release 1.30] Bump charts and images to fix go CVE

charts/chart_versions.yaml, scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6783
Backport: https://github.com/rancher/rke2/pull/6771
=> [Release 1.29] Bump charts and images to fix go CVE

charts/chart_versions.yaml, scripts/build-images
Backport for #6771 #6791
Issue #6792
=> [Release 1.28]  Bump charts and images to fix CVE GO-2024-3106

charts/chart_versions.yaml, scripts/build-images
=> Bump ingress-nginx to v1.10.4-hardened3

.github/workflows/trivy.yaml, scripts/build-image-runtime
Once this is merged, it allows user to comment `/trivy` on a PR to trigger a trivy report on the rke2-runtime and rke2 go.mod
CI
Verified on https://github.com/dereknola/rke2/pull/2 (note that was using the GHA public runners, I can't test if the custom runners work until we merge this PR into master)
N/A
```release-note
```
For now we are only reporting on the linux amd64 build of rke2-runtime. In the future, we can expand this to the windows and other images.
=> Add trivy scanning to PR reports

tests/e2e/ciliumnokp/ciliumnokp_test.go
Backport: https://github.com/rancher/rke2/pull/6808
=> [Release 1.28] Update cilium e2e test

pkg/pebinaryexecutor/pebinary.go
Check if the cni configured is none before doing the setup on windows to fix the panic error. (#6768)
#6819
```release-note
```
=> Fixed windows CNI setup in case cni none is configured

tests/e2e/mixedosbgp/Vagrantfile
This PR fixes a bug in the mixedosbgp e2e test. `-Commit=` is wrong, the equal symbol should be removed. We were getting an error when installing rke2 in windows. 
Bugfix
Run the e2e test
```release-note
```
=> Fix e2e test bug in mixedosbgp

charts/chart_versions.yaml
Bump vsphere charts
Compare: https://github.com/rancher/vsphere-charts/compare/bdbf37809638cd370f6e7327bd012a850b6da077...a5c99d716df960dc50cf417d9ecffad6b55ca0ad
chart fixes
Check chart version
* 
```release-note
```
=> Bump vsphere charts

pkg/pebinaryexecutor/pebinary.go
Backport for #6820
Issue #6826
=> [Release 1.31] Fixed windows CNI setup in case cni none is configured

pkg/pebinaryexecutor/pebinary.go
Backport for #6820
Issue #6828
=> [Release 1.29] Fixed windows CNI setup in case cni none is configured

charts/chart_versions.yaml, scripts/build-images
Bump traefik to chart 27.0.2 / appVersion v2.11.10
version bump
check chart and image version
* https://github.com/rancher/rke2/issues/6859
```release-note
```
=> Bump traefik to chart 27.0.2

tests/e2e/mixedosbgp/Vagrantfile
Backport: https://github.com/rancher/rke2/pull/6840
=> [Release 1.30] Fix e2e test bug in mixedosbgp

.github/workflows/trivy.yaml, scripts/build-image-runtime
Backport https://github.com/rancher/rke2/pull/6806 
```release-note
```
=> [Release-1.28] Add trivy scanning to PR reports

.github/workflows/trivy.yaml
- Breakup trivy scanning into multiple jobs to reduce usage of `write` permissions
- Only allow public members of the Rancher org to trigger /trivy
```release-note
```
=> Breakup trivy scan into isolated jobs

bundle/bin/rke2-uninstall.sh
- Fix uninstall script to correctly identify Amazon Linux 2 OS file (this is basically the same fix as https://github.com/rancher/rke2/pull/6429)
See issue, followed  QA reproduction
https://github.com/rancher/rke2/issues/6521
```release-note
```
=> Fix uninstall for amazon linux 2

.github/workflows/updatecli.yml
The current Updatecli GHA workflow is stuck with Updatecli version `v0.72.0` from January, while the newer version is [v0.84.1](https://github.com/updatecli/updatecli/releases/tag/v0.84.1). Update the workflow to always use the latest available version.
```release-note
```
=> Configure Updatecli GHA to always use the latest version

.github/workflows/trivy.yaml
This PR adds VEX scan in the Trivy check. VEX will remove known false-positive CVEs with Rancher's VEX Hub [standalone report](https://github.com/rancher/vexhub/blob/main/reports/rancher.openvex.json).
Trivy workflow change.
Run the Trivy check in any PR and if there are known false-positives CVEs they will be listed in Trivy's `Suppressed Vulnerabilities` output.
Same as above.
None.
None.
```release-note
```
Once Trivy's version in `rancher/image-build-base` is updated (https://github.com/rancher/image-build-base/pull/69) and then [`rancher/hardened-build-base`](https://github.com/rancher/rke2/blob/master/Dockerfile#L4) version is bumped, we can also add the VEX scan in [scripts/scan-images](https://github.com/rancher/rke2/blob/master/scripts/scan-images).
=> Pass Rancher's VEX report to Trivy to remove known false-positives CVEs

install.sh
I'm working on fixing the RPM install process for ARM64 `aarch64` architecture type.
Does not require a change to docs
Minor bug fixes to enable RPM installs of `aarch64`
Run the following command on an ARM64 version of Rocky 8:
```
curl -sfL https://get.rke2.io/ | INSTALL_RKE2_TYPE="server" INSTALL_RKE2_VERSION="v1.28.14+rke2r1" sh -
```
Not covered by testing
https://github.com/rancher/rke2/issues/6926
```release-note
NONE
```
Quick fix, not a major change
=> Use correct architecture for yum repo instead of hardcoding x86_64 

charts/chart_versions.yaml, scripts/build-images
Bump csi snapshot and nginx charts
version bump
The certgen image is not used in a long-running pod, but you should see it in the node's image list after nginx is installed or upgraded.
* tbd
```release-note
```
=> Bump csi snapshot and nginx charts and images

charts/chart_versions.yaml, scripts/build-images
Bump traefik to chart 27.0.2 / appVersion v2.11.10
version bump
check chart and image version
* https://github.com/rancher/rke2/issues/6868
```release-note
```
=> [Release-1.31] Bump traefik to chart 27.0.2

charts/chart_versions.yaml, scripts/build-images
Bump traefik to chart 27.0.2 / appVersion v2.11.10
version bump
check chart and image version
* https://github.com/rancher/rke2/issues/6869
```release-note
```
=> [Release-1.30] Bump traefik to chart 27.0.2

Dockerfile
Backport for: https://github.com/rancher/rke2/pull/6959
Issue: https://github.com/rancher/rke2/issues/6976
=> [Release-1.31] Bump crictl

charts/chart_versions.yaml, scripts/build-images
Also update the hardened-cni-plugins for cilium, flannel and multus to `v1.5.1-build20241009`
Depends on:
Linked Issue: https://github.com/rancher/rke2/issues/6980
=> Update multus to `v4.1.2`

Dockerfile, Dockerfile.windows
version bump
check version
* #6998
```release-note
```
=> [release-1.28] Bump containerd to v1.7.22

Dockerfile, Dockerfile.windows
version bump
check version
* #6998
```release-note
```
=> [release-1.29] Bump containerd to v1.7.22

charts/chart_versions.yaml, scripts/build-images
Also update the hardened-cni-plugins for cilium, flannel and multus to `v1.5.1-build20241009`
Backport: https://github.com/rancher/rke2/pull/6981
Issue: https://github.com/rancher/rke2/issues/7014
=> [Release-1.31] Update multus to v4.1.2

charts/chart_versions.yaml, scripts/build-images
Also update the hardened-cni-plugins for cilium, flannel and multus to `v1.5.1-build20241009`
Backport: https://github.com/rancher/rke2/pull/6981
Issue: https://github.com/rancher/rke2/issues/7017
=> [Release-1.28] Update multus to v4.1.2

charts/chart_versions.yaml, scripts/build-images
* https://github.com/rancher/rke2/issues/7054
```release-note
```
=> [release-1.28] Bump Harvester CSI driver v0.1.20

Dockerfile, Dockerfile.docs, Dockerfile.windows
This PR adds the image metadata labels to rke2-runtime image
enhancement
check rke2-runtime image labels
* https://github.com/rancher/rke2/issues/4238
```release-note
```
=> add org.opencontainers.image url and source labels to dockerfiles

Dockerfile, Dockerfile.windows
This PR adds the image metadata labels to rke2-runtime image
enhancement
check rke2-runtime image labels
* https://github.com/rancher/rke2/issues/4238
```release-note
```
=> [release-1.28] add org.opencontainers.image url and source labels to dockerfiles

charts/chart_versions.yaml
CRD bump
```
```
* https://github.com/rancher/rke2/issues/6945
```release-note
```
=> Bump CSI snapshot controller chart for CRD updates

charts/chart_versions.yaml
CRD bump
```
```
* https://github.com/rancher/rke2/issues/6950
```release-note
```
=> [release-1.31] Bump CSI snapshot controller chart for CRD updates

charts/chart_versions.yaml
CRD bump
```
```
* https://github.com/rancher/rke2/issues/6951
```release-note
```
=> [release-1.30] Bump CSI snapshot controller chart for CRD updates

charts/chart_versions.yaml
CRD bump
```
```
* https://github.com/rancher/rke2/issues/6952
```release-note
```
=> [release-1.29] Bump CSI snapshot controller chart for CRD updates

charts/chart_versions.yaml
CRD bump
```
```
* https://github.com/rancher/rke2/issues/6953
```release-note
```
=> [release-1.28] Bump CSI snapshot controller chart for CRD updates

charts/chart_versions.yaml, scripts/build-images
* Forward port of https://github.com/rancher/rke2/pull/7098 et al, combined with changes from https://github.com/rancher/rke2/pull/7084, since `update hardened chart images` was PRd directly into the release branches instead of being backported from master.
```release-note
```
=> update hardened chart images

Dockerfile.windows, scripts/package-windows-images, scripts/publish-image-runtime-windows, scripts/publish-manifest-runtime
- Intermediate windows runtime image is tagged with correct platform
- Multiplatform rke2-runtime image is published with docker imagetool to support merging OCI manifests and manifest lists.
```release-note
```
=> Fix publish windows runtime

Dockerfile.windows, scripts/package-windows-images, scripts/publish-image-runtime-windows, scripts/publish-manifest-runtime
Backport of #7143
```release-note
```
=> [release-1.31] Fix publish windows runtime

.github/workflows/release.yml, scripts/scan-images
- Upload trivy report of scanned release images to GH as an action artifact. This enables us to download or share the report elsewhere.
Running locally:
```
docker run --rm -v "$(pwd)/build:/build" -v "$(pwd):/workspace" \
-w /workspace rancher/hardened-build-base:v1.22.8b2 \
make scan-images
```
Afterwards a new file `trivy-scan-report.txt` is available to be uploaded. 
I can't test the release process itself. 
```release-note
```
The current base image used in the `Dockerfile` contains a old version of trivy (0.42). A new version of the base image has been published with trivy (0.56), but I didn't want to complicate this PR by bumping it.
=> Publish release trivy scans as an artifact

bundle/bin/rke2-killall.sh
Only clean up pod filesystems if umount succeeds.
If the unmount fails for some reason we shouldn't `rm -rf` the mountpoint, there might still be stuff under it.
killall script; bugfix
* https://github.com/rancher/rke2/issues/6571#issuecomment-2294339626
```release-note
```
=> Only clean up pod filesystems if umount succeeds

.github/actions/vagrant-setup/action.yaml
Latest version of vagrant suffers from https://github.com/hashicorp/vagrant/issues/13527, this is affecting all our E2E tests. Pin to 2.4.1 for now.
CI
CI Green
```release-note
```
=> Pin vagrant version to prevent E2E suite failure

.github/actions/vagrant-setup/action.yaml, .github/workflows/test-suite.yaml
Backport of https://github.com/rancher/rke2/pull/7175 and https://github.com/rancher/rke2/pull/7168
CI Green
```release-note
```
=> [Release-1.28] Backport E2E GHA fixes

pkg/rke2/rke2_linux.go
Remove special hostname behavior for aws cloud-provider
The in-tree aws cloud provider has been removed and the kubelet will fail to start if the cloud-provider-name is set to aws, so this is dead code.
tech debt
None, this code is unused.
* https://github.com/rancher/rke2/issues/6626
```release-note
```
=> Remove special hostname behavior for aws cloud-provider

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7195
Issue: https://github.com/rancher/rke2/issues/7216
=> [release-1.28] Bump canal chart to v3.29.0

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7195
Issue: https://github.com/rancher/rke2/issues/7218
=> [release-1.29] Bump canal chart to v3.29.0

charts/chart_versions.yaml, scripts/build-images
Bump CSI/CPI charts and images to latest version. Recent UpdateCLI PRs have not actually been updating the images.
https://github.com/rancher/rke2/issues/7246
```release-note
```
=> [Release-1.30] Bump vSphere CSI/CPI charts to 1.9.1 and 3.3.1-rancher700

charts/chart_versions.yaml, scripts/build-images
Bump CSI/CPI charts and images to latest version. Recent UpdateCLI PRs have not actually been updating the images.
https://github.com/rancher/rke2/issues/7248
```release-note
```
=> [Release-1.28] Bump vSphere CSI/CPI charts to 1.9.1 and 3.3.1-rancher700

charts/chart_versions.yaml, scripts/build-images
Bump CSI/CPI charts and images to latest version. Recent UpdateCLI PRs have not actually been updating the images.
https://github.com/rancher/rke2/issues/7247
```release-note
```
=> [Release-1.29] Bump vSphere CSI/CPI charts to 1.9.1 and 3.3.1-rancher700 

tests/e2e/testutils.go
The latest version of vagrant-libvirt current suffers from an error around FOG warnings being constantly produced on any call of `vagrant ssh`. For now we will simply remove these warnings from any output return
CI is once again green
N/A nothing to QA
```release-note
```
=> Fix e2e ci by ignoring FOG warnings

charts/chart_versions.yaml
Bump rke2-coredns chart.
The only change is that we don't set force_tcp in node-local-dns configmap anymore.
This follows the upstream manifest default configuration.
Bugfix
- deploy rke2 with nodelocaldns activated:
```
---
metadata:
name: rke2-coredns
namespace: kube-system
spec:
valuesContent: |-
nodelocal:
enabled: true
```
- check that the configmap `node-local-dns` is created
- check that it has the following block 
```
.:53 { 
errors
cache 30
reload
loop
bind 169.254.20.10 10.43.0.10
forward . __PILLAR__UPSTREAM__SERVERS__
}
```
https://github.com/rancher/rke2/issues/7265
```release-note
When using node-local-dns, the default configuration now has `force_tcp` disabled for port 53.
```
=> Bump coredns chart to 1.33.005:

tests/e2e/testutils.go
Backport https://github.com/rancher/rke2/pull/7267
CI Green Again
N/A Internal CI issue only
```release-note
```
=> [Release-1.28] Fix e2e ci by ignoring FOG warnings 

tests/e2e/testutils.go
Backport https://github.com/rancher/rke2/pull/7267
CI Green Again
N/A Internal CI issue only
```release-note
```
=> [Release-1.30] Fix e2e ci by ignoring FOG warnings 

tests/e2e/testutils.go
Backport https://github.com/rancher/rke2/pull/7267
CI Green Again
N/A Internal CI issue only
```release-note
```
=> [Release-1.31] Fix e2e ci by ignoring FOG warnings 

tests/e2e/testutils.go
Backport https://github.com/rancher/rke2/pull/7267
CI Green Again
N/A Internal CI issue only
```release-note
```
=> [Release-1.29] Fix e2e ci by ignoring FOG warnings 

charts/chart_versions.yaml
Linked issue: #7272
Backport: #7266
=> [release 1.28] Bump rke2-coredns to 1.33.005

charts/chart_versions.yaml
Linked issue: #7274 Backport: #7266
=> [release 1.29] Bump rke2-coredns to 1.33.005

charts/chart_versions.yaml
Linked issue: #7278 Backport: #7266
=> [release 1.31] Bump rke2-coredns to 1.33.005

pkg/cli/cmds/root.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go, pkg/rke2/rke2_windows.go
* Revert https://github.com/rancher/rke2/pull/7212
* Add new `--node-name-from-cloud-provider-metadata` flag to replace the node-name functionality previously enabled by setting `--cloud-provider-name=aws`
* Add Windows support
* Add IMDSv2 token support
Revert / enhancement
* Start node with `--cloud-provider-name=aws` on EC2; note that node name is properly set and kubelet does not crash due to `--cloud-provider=aws` being passed in kubelet args.
* Start node with `--node-name-from-cloud-provider-metadata` on EC2; note that node name is properly set.
* Start node with either of the above on EC2 with IMDSv2 required; note that node name is properly set. 
* https://github.com/rancher/rke2/issues/6626
* https://github.com/rancher/rke2/issues/7336
* Internal: SURE-8892
* Internal: SURE-9292 …
=> Restore AWS node-name support and add IMDSv2 support

pkg/cli/cmds/root.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go, pkg/rke2/rke2_windows.go
* Revert https://github.com/rancher/rke2/pull/7212
* Add new `--node-name-from-cloud-provider-metadata` flag to replace the node-name functionality previously enabled by setting `--cloud-provider-name=aws`
* Add Windows support
* Add IMDSv2 token support
Revert / enhancement
* Start node with `--cloud-provider-name=aws` on EC2; note that node name is properly set and kubelet does not crash due to `--cloud-provider=aws` being passed in kubelet args.
* Start node with `--node-name-from-cloud-provider-metadata` on EC2; note that node name is properly set.
* Start node with either of the above on EC2 with IMDSv2 required; note that node name is properly set. 
* https://github.com/rancher/rke2/issues/6626
* https://github.com/rancher/rke2/issues/7344
* Internal: SURE-8892
* Internal: SURE-9292 …
=> [release-1.31] Restore AWS node-name support and add IMDSv2 support

pkg/cli/cmds/root.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go, pkg/rke2/rke2_windows.go
* Revert https://github.com/rancher/rke2/pull/7212
* Add new `--node-name-from-cloud-provider-metadata` flag to replace the node-name functionality previously enabled by setting `--cloud-provider-name=aws`
* Add Windows support
* Add IMDSv2 token support
Revert / enhancement
* Start node with `--cloud-provider-name=aws` on EC2; note that node name is properly set and kubelet does not crash due to `--cloud-provider=aws` being passed in kubelet args.
* Start node with `--node-name-from-cloud-provider-metadata` on EC2; note that node name is properly set.
* Start node with either of the above on EC2 with IMDSv2 required; note that node name is properly set. 
* https://github.com/rancher/rke2/issues/6626
* https://github.com/rancher/rke2/issues/7346
* Internal: SURE-8892
* Internal: SURE-9292 …
=> [release-1.29] Restore AWS node-name support and add IMDSv2 support

charts/chart_versions.yaml, scripts/build-images
Version bump for coredns and cluster-autoscaler
Version bump
Verify cluster-autoscaler and coredns work
https://github.com/rancher/rke2/issues/7349
```release-note
Bump coredns to v1.12.0 and cluster-autoscaler to v1.9.0
```
=> Bump coredns and cluster-autoscaler

Dockerfile, Dockerfile.windows
* https://github.com/rancher/rke2/issues/7207
```release-note
```
=> Bump containerd for image rewrite fix

Dockerfile, Dockerfile.windows
* https://github.com/rancher/rke2/issues/7301
```release-note
```
=> [release-1.31] Bump containerd for image rewrite fix

Dockerfile, Dockerfile.windows
* https://github.com/rancher/rke2/issues/7302
```release-note
```
=> [release-1.30] Bump containerd for image rewrite fix

Dockerfile, Dockerfile.windows
* https://github.com/rancher/rke2/issues/7303
```release-note
```
=> [release-1.29] Bump containerd for image rewrite fix

Dockerfile, Dockerfile.windows
* https://github.com/rancher/rke2/issues/7304
```release-note
```
=> [release-1.28] Bump containerd for image rewrite fix

charts/chart_versions.yaml, scripts/build-images
Bump rke2-ingress-nginx from v1.10.5-hardened4 to v1.10.5-hardened6. 
- Address CVEs in base SLES image for rke2-ingress-nginx component. 
Dependency Bump
https://github.com/rancher/rke2/issues/7409
```release-note
```
=> Bump ingress-nginx to hardened6

charts/chart_versions.yaml, scripts/build-images
Upstream has released a new dns-node-cache (after 6 months) that fixes about 10 CVEs. 
```release-note
```
=> [Release-1.30] Bump dns-node-cache to 1.24.0

scripts/validate-release
Handles case where tagged commit exists on multiple branches - such as when we branch for a new release and then immediately tag an RC.
https://github.com/rancher/rke2/actions/runs/12470754662/job/34806446905#step:5:1512
bugfix, ci
See CI
```release-note
```
=> Validate single branch for tag

charts/chart_versions.yaml
=> charts: bump Harvester CSI Driver v0.1.22

charts/chart_versions.yaml
Bump cilium chart to v 1.16.501
chart version bump
See linked issue (note: only affects upgrades from 1.29 -> 1.30; will not affect other branches)
* https://github.com/rancher/rke2/issues/7480
* 
```release-note
```
=> Bump cilium chart to v 1.16.501

charts/chart_versions.yaml
Backport for #7530
Issue #7533
=> [Release 1.30] Updated calico chart to fix IP autodetect in case of IPv6 only

charts/chart_versions.yaml
Backport for #7530
Issue #7534
=> [Release 1.29] Updated calico chart to fix IP autodetect in case of IPv6 only

charts/chart_versions.yaml, scripts/build-images
Also bump to the latest images:
- hardened-k8s-metrics-server:v0.7.2-build20250110
- hardened-addon-resizer:1.8.22-build20250110
Linked Issue: https://github.com/rancher/rke2/issues/7539
=> Update metrics-server to `3.2.12`

charts/chart_versions.yaml, scripts/build-images
Bumps hardened-calico image to `v3.29.1-build20250110`
Linked Issue: https://github.com/rancher/rke2/issues/7541
=> Update canal to `v3.29.1-build2025011000`

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7542
Issue: https://github.com/rancher/rke2/issues/7565
=> [release-1.29] Update canal to `v3.29.1-build2025011000`

pkg/staticpod/staticpod.go
reset the `sourceType` variable for each extra mount entry, ensuring it does not retain the value from a previous mount specification.
initialize `sourceType` to `v1.HostPathUnset` at the start of processing each mount
bugfix
Mentioned in linked issue
https://github.com/rancher/rke2/issues/7422
```release-note
```
=> fix-extramount-type 

.github/workflows/release.yml
Add an automatic release trigger for RKE2's downstream components:
- [rke2-upgrade](https://github.com/rancher/rke2-upgrade)
- [system-agent-installer-rke2](https://github.com/rancher/system-agent-installer-rke2)
New feature:
- A new step will be appended to `release.yml` workflow
This was tested in a personal private GitHub Org using the same triggers from `release.yml` workflow.
https://github.com/rancher/rke2/issues/7592
```release-note
```
=> [release-1.31] Fix Release downstream components in release workflow

.github/workflows/test-suite.yaml, go.mod, go.sum, tests/e2e/splitserver/splitserver_test.go, tests/e2e/testutils.go, tests/integration/etcdsnapshot/etcd_int_test.go, tests/integration/integration.go, tests/integration/startup/startup_test.go
Updates k3s: https://github.com/k3s-io/k3s/compare/9515436e80e4...be4b1bcdba3350994c06619726939d6520f7ba04
Add e2e framework enhancements and integration test for bind-address flag
bugfix, tests
tests
yes
```release-note
```
=> [release-1.30] Bump k3s version for master and add/enhance tests

.github/workflows/test-suite.yaml, go.mod, go.sum, tests/e2e/splitserver/splitserver_test.go, tests/e2e/testutils.go, tests/integration/etcdsnapshot/etcd_int_test.go, tests/integration/integration.go, tests/integration/startup/startup_test.go
Updates k3s: https://github.com/k3s-io/k3s/compare/cba30eb6b361...c577569268df6bec32425954527b758de3e7a3b6
Add e2e framework enhancements and integration test for bind-address flag
bugfix, tests
tests
yes
```release-note
```
=> [release-1.29] Bump k3s version for master and add/enhance tests

install.sh
- CENTOS 7 is very EOL, bumping the `default` version number to 8. This should help RHEL adjacent OSes get correct rpms. 
- Fedora 40 installs the correct rpms for RKE2
https://github.com/rancher/rke2/issues/7429
```release-note
```
=> Bump default RPM version number in install script

tests/install/centos-9/Vagrantfile, tests/install/install_util.rb, tests/install/opensuse-leap/Vagrantfile, tests/install/rocky-8/Vagrantfile
- opensuse leap 15.6+ image no longer has `ps` installed by default
- Fixes issue around `rke2-killall.sh` being in different locations depending on OS.
Test Fix
Nightly Install now passes 
https://github.com/dereknola/rke2/actions/runs/12894519908
```release-note
```
=> Fix nightly tests

charts/chart_versions.yaml, scripts/build-images
also update cni-plugins to `v1.6.2-build20250124`
Linked Issue: https://github.com/rancher/rke2/issues/7662
=> Update to cilium `v1.16.6`

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7663
Issue: https://github.com/rancher/rke2/issues/7679
=> [release-1.29] Update to cilium `v1.16.6`

Dockerfile, Dockerfile.windows
Bump containerd for go-cni deadlock fix
Version bump / bugfix
Check version
Not currently reproducible in CI; occurs occasionally in Rancher KDM CI.
* https://github.com/rancher/rke2/issues/7808
* https://github.com/containerd/containerd/pull/11269
* https://github.com/containerd/go-cni/pull/126
```release-note
```
=> Bump containerd for go-cni deadlock fix

Dockerfile, Dockerfile.windows
Bump containerd for go-cni deadlock fix
Version bump / bugfix
Check version
Not currently reproducible in CI; occurs occasionally in Rancher KDM CI.
* https://github.com/rancher/rke2/issues/7808
* https://github.com/containerd/containerd/pull/11269
* https://github.com/containerd/go-cni/pull/126
```release-note
```
=> [release-1.32] Bump containerd for go-cni deadlock fix

Dockerfile, Dockerfile.windows
Bump containerd for go-cni deadlock fix
Version bump / bugfix
Check version
Not currently reproducible in CI; occurs occasionally in Rancher KDM CI.
* https://github.com/rancher/rke2/issues/7808
* https://github.com/containerd/containerd/pull/11269
* https://github.com/containerd/go-cni/pull/126
```release-note
```
=> [release-1.31] Bump containerd for go-cni deadlock fix

updatecli/scripts/retrieve_chart_version.sh, updatecli/updatecli.d/vsphere-cpi.yml, updatecli/updatecli.d/vsphere-csi.yml
Improves Updatecli bumping of CPI and CSI charts. The current method isn't working, see https://github.com/rancher/rke2/pull/7809, because the charts' versioning are fully following the [semantic versioning spec](https://semver.org/#spec-item-2):
> 2. A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and **MUST NOT contain leading zeroes**.
Due to that, Updatecli is correctly ignoring and removing the versions that have `.000`, `.001` etc.
-> https://github.com/updatecli/updatecli/blob/v0.94.1/pkg/plugins/resources/helm/source.go#L43
-> https://github.com/updatecli/updatecli/blob/v0.94.1/pkg/plugins/utils/version/filter.go#L165
-> https://github.com/updatecli/updatecli/blob/v0.94.1/pkg/plugins/utils/version/semver.go#L27-L29
Note: this isn't an …
=> Improves Updatecli bumping of CPI and CSI charts

go.mod, go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/3ce7ca7544a7...781640ecea12e0cd83541c99a066baadf47038ef
bugfix
* https://github.com/rancher/rke2/issues/7899
```release-note
```
=> Bump K3s for apiserver addresses fix

go.mod, go.sum, scripts/build-images
Updates k3s: https://github.com/k3s-io/k3s/compare/7034b96c20a0...f98ebbe1d33dd2ad7d83a0d73c45828254d2d8b5
bugfix
* https://github.com/rancher/rke2/issues/7904
```release-note
```
=> [release-1.32] Bump K3s for apiserver addresses fix

go.mod, go.sum, scripts/build-images
Updates k3s: https://github.com/k3s-io/k3s/compare/02c824e03682...e566886305adc3c7d45c48a8b7874638745c3dec
bugfix
* https://github.com/rancher/rke2/issues/7906
```release-note
```
=> [release-1.31] Bump K3s for apiserver addresses fix

go.mod, go.sum, scripts/build-images
Updates k3s: https://github.com/k3s-io/k3s/compare/f82e387b5ee6...0f0a157e7259347bf2a25b9280eacbcd9daa72dc
bugfix
* https://github.com/rancher/rke2/issues/7906
```release-note
```
=> [release-1.30] Bump K3s for apiserver addresses fix

go.mod, go.sum, scripts/build-images
Updates k3s: https://github.com/k3s-io/k3s/compare/4cbe00913b4b...cd3e17f2f71e3cda740bdcf5bb0689d2b4548f78
bugfix
* https://github.com/rancher/rke2/issues/7907
```release-note
```
=> [release-1.29] Bump K3s for apiserver addresses fix

install.ps1, install.sh
Allow setting `INSTALL_RKE2_ARTIFACT_URL` to override URL prefix for release artifacts, to allow downloading RKE2 from locations other than GitHub.
enhancement
* https://github.com/rancher/rke2/issues/7718
```release-note
```
=> Make artifact URL prefix configurable

charts/chart_versions.yaml, scripts/build-images
Also update to the following image versions:
- rancher/hardened-coredns:v1.12.1-build20250401
- rancher/hardened-cluster-autoscaler:v1.9.0-build20241203
- rancher/hardened-dns-node-cache:1.25.0-build20250127
Issue: https://github.com/rancher/rke2/issues/7985
=> Update to coredns `1.39.201`

charts/chart_versions.yaml, scripts/build-images
Issue: https://github.com/rancher/rke2/issues/8035
Backport: https://github.com/rancher/rke2/pull/7965, https://github.com/rancher/rke2/pull/8002
=> [Release-1.29] Bump multus version to 4.2.0 and whereabouts to v0.9.0

charts/chart_versions.yaml, scripts/build-images
Bump traefik to v3.3.6
* https://github.com/traefik/traefik/security/advisories/GHSA-5423-jcjm-2gpv
version bump
check version
* https://github.com/rancher/rke2/issues/8072
```release-note
```
=> [release-1.32] Bump traefik to v3.3.6

charts/build-charts.sh, charts/chart_versions.yaml, scripts/build-images
Bump traefik to v2.11.24
* https://github.com/traefik/traefik/security/advisories/GHSA-5423-jcjm-2gpv
version bump
check version
```release-note
```
=> [release-1.30] Bump traefik to v2.11.24

updatecli/scripts/retrieve_chart_version.sh
In https://github.com/rancher/rke2/pull/7820 I wrongly assumed that the charts' versions were sorted from newest to oldest automatically in https://rke2-charts.rancher.io/index.yaml. That isn't the case, so we must sort them by natural version sort instead.
Fixes the wrong update PR https://github.com/rancher/rke2/pull/7809.
=> Fix the vSphere chart version check to use version sort for the retrieved versions

pkg/podexecutor/staticpod.go
Remove kube-apiserver flags removed by upstream
bugfix
* https://github.com/rancher/rke2/issues/8134
```release-note
```
=> Remove kube-apiserver flags removed by upstream

pkg/podexecutor/staticpod.go
Remove kube-apiserver flags removed by upstream
bugfix
* https://github.com/rancher/rke2/issues/8134
```release-note
```
=> [release-1.33] Remove kube-apiserver flags removed by upstream

charts/chart_versions.yaml, scripts/build-images
Update to the latest image versions:
- rancher/hardened-k8s-metrics-server:v0.7.2-build20250507
- rancher/hardened-addon-resizer:1.8.23-build20250507
Issue: https://github.com/rancher/rke2/issues/8163
=> Update to Kubernetes Metrics Server 3.12.201

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8164
Issue: https://github.com/rancher/rke2/issues/8207
=> [Release-1.32] Update to Kubernetes Metrics Server 3.12.201

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8164
Issue: https://github.com/rancher/rke2/issues/8208
=> [Release-1.31] Update to Kubernetes Metrics Server 3.12.201

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8164
Issue: https://github.com/rancher/rke2/issues/8209
=> [Release-1.30] Update to Kubernetes Metrics Server 3.12.201

charts/chart_versions.yaml, scripts/build-images
Also updates to the latest image versions:
- rancher/hardened-coredns:v1.12.1-build20250507
- rancher/hardened-cluster-autoscaler:v1.10.2-build20250507
- rancher/hardened-dns-node-cache:1.26.0-build20250515
Issue: https://github.com/rancher/rke2/issues/8161
=> Update to CoreDNS 1.42.000

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8239
Issue: https://github.com/rancher/rke2/issues/8263
=> [Release-1.31] Update to CoreDNS 1.42.000

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8239
Issue: https://github.com/rancher/rke2/issues/8264
=> [Release-1.30] Update to CoreDNS 1.42.000

bundle/bin/rke2-uninstall.ps1, pkg/podexecutor/staticpod.go
We encountered that it is impossible to orchestrate our cmdlines (pipe, settings) to auto-approve the stop-process, stop-service and create file cmds within the uninstall.ps1 for windows nodes.
Thus I tried to improve the script to offer an optional silent param to the script.
If none is given, it still acts & behaves like before.
New feature: Confirm:$falset flag added
supresses confirmation within script while calling stop-process, stop-service and new-item
Using the uninstall script without silent flag still asks for confirmation.
No means from outside are able to overwrite this for us:
examples given: 
$ConfirmationPreference = none/low
pipeing "Y" via `echo Y Y Y [...] | uninstall.ps1`
adding -Confirm:$false
uninstall a windows node with `Confirm:$false` and it should not ask for …
=> Windows: Allow for silent/non confirmation use of uninstall.ps1

install.sh
Use slemicro for 6.x as well, which identifies as sl-micro instead of sle-micro
install script; selinux
Install on SL Micro 6.x; with RPM; note that it installs the slemicro RPM instead of sle.
* https://github.com/rancher/rke2/issues/7458
```release-note
```
=> Use slemicro for 6.x as well, which identifies as sl-micro instead of sle-micro

.github/workflows/test-suite.yaml
- Implement read only vagrant box cache for NON-`master` branches. 
We have too many duplicates of vagrant boxes because all the PRs write duplicates at the end
CI
Should see reduction in duplicate vagrant cache after a few days
```release-note
```
=> Reduce GHA cache thrashing with read only vagrant cache

charts/chart_versions.yaml, scripts/build-images
Update chart and images to the latest versions:
- rancher/hardened-k8s-metrics-server:v0.7.2-build20250612
- rancher/hardened-addon-resizer:1.8.23-build20250612
Depends:
Issue: https://github.com/rancher/rke2/issues/8353
=> Update Kubernetes Metrics Server chart 3.12.2

charts/chart_versions.yaml, scripts/build-images
Update chart and images to the latest versions:
- rancher/hardened-coredns:v1.12.2-build20250611
- rancher/hardened-cluster-autoscaler:v1.10.2-build20250611
- rancher/hardened-dns-node-cache:1.26.0-build20250611
Depends:
Issue: https://github.com/rancher/rke2/issues/8354
=> Update CoreDNS chart 1.42.3

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8377
Issue: https://github.com/rancher/rke2/issues/8412
=> [Release-1.33] Update Kubernetes Metrics Server chart 3.12.2

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8377
Issue: https://github.com/rancher/rke2/issues/8414
=> [Release-1.31] Update Kubernetes Metrics Server chart 3.12.2

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8366
Issue: https://github.com/rancher/rke2/issues/8409
=> [Release-1.32] Update CoreDNS chart 1.42.3

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8366
Issue: https://github.com/rancher/rke2/issues/8410
=> [Release-1.31] Update CoreDNS chart 1.42.3

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8366
Issue: https://github.com/rancher/rke2/issues/8411
=> [Release-1.30] Update CoreDNS chart 1.42.3

pkg/cli/defaults/defaults.go, pkg/cli/defaults/defaults_test.go
- Prepend default values of various ExtraK***Args  CLI flags. This allows correct overriding of the defaults if the user requires. 
CLI fix
Unit test
https://github.com/rancher/rke2/issues/8365
```release-note
```
=> Prepend defaults to extra kube args

.github/workflows/test-suite.yaml, tests/docker/flannel/flannel_test.go, tests/docker/resources/flannel.yaml
This PR introduces integration tests for flannel plugin.
It validates:
- cluster setup with flannel
- inter pod connectivity
- inter node connectivity 
- external access to pods
Integration tests
- https://github.com/rancher/rke2/issues/5387
```release-note
NONE
```
=> Add flannel integration tests

pkg/windows/utils.go
When trying to determine the platform type a time out error was returned in case EC2 or GCE were not able to be contacted.
With this change the platform type "bare-metal" is now returned as a fallback value.
* This fix addresses https://github.com/rancher/rke2/issues/8497
=> Defaults to 'bare-metal' in case the connection to EC2 or GCE times out

pkg/cli/defaults/defaults.go, pkg/cli/defaults/defaults_test.go
Backport of https://github.com/rancher/rke2/pull/8455
See original issue / new Unit test
https://github.com/rancher/rke2/issues/8511
```release-note
```
=> [Release-1.32] Prepend defaults to extra kube args

pkg/cli/defaults/defaults.go, pkg/cli/defaults/defaults_test.go
Backport of https://github.com/rancher/rke2/pull/8455
See original issue / new Unit test
https://github.com/rancher/rke2/issues/8510
```release-note
```
=> [Release-1.33] Prepend defaults to extra kube args

main.go, pkg/cli/cmds/root.go, pkg/cli/cmds/server.go, pkg/cli/types.go, pkg/controllers/types.go, pkg/executor/pebinary/pebinary.go, pkg/executor/staticpod/cleanup.go, pkg/executor/staticpod/command_linux.go, pkg/executor/staticpod/command_other.go, pkg/executor/staticpod/spw.go, pkg/executor/staticpod/staticpod.go, pkg/podtemplate/config.go, pkg/podtemplate/podtemplate.go, pkg/podtemplate/spec.go, pkg/podtemplate/types.go, pkg/podtemplate/utils.go, pkg/rke2/rke2.go, pkg/rke2/rke2_linux.go, pkg/rke2/rke2_linux_test.go, pkg/rke2/rke2_windows.go, pkg/rke2/spc.go
pkg/rke2 contained a bunch of stuff that really belonged in other packages:
* pod template configuration for limits/requests/probes/mounts/envs that should be in a pod template package
* cleanup of static pods that should be in the static pod executor
This PR:
* renames packages for improved consistency:
* `pkg/staticpod -> pkg/executor/staticpod`
* `pkg/bebinaryexecutor -> pkg/executor/pebinary`
* moves all the pod template generation and args parsing into new `pkg/podtemplate`
* moves static pod cleanup out of `pkg/rke2` into `pkg/executor/staticpod`
tech debt
No change to functionality, just cleanup
yes
* https://github.com/rancher/rke2/issues/8655
```release-note
```
=> Separate pod template generation and static pod execution code

tests/e2e/cilium_wireguard/Vagrantfile, tests/e2e/cilium_wireguard/ciliumwireguard_test.go, tests/e2e/scripts/cilium_wireguard.sh
This PR adds the E2E tests for Cilium configured with wireguard encryption.
`go test -timeout=15m ./tests/e2e/cilium_wireguard/ -run E2E`
#8769
```release-note
```
=> Added Cilium with wireguard e2e tests

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8894
Issue: https://github.com/rancher/rke2/issues/8895
=> [Release-1.34] Update CoreDNS chart 1.43.302

charts/chart_versions.yaml, scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8894
Issue: https://github.com/rancher/rke2/issues/8896
=> [Release-1.33] Update CoreDNS chart 1.43.302

charts/chart_versions.yaml, scripts/build-images
Bump vsphere charts
We apparently have not kept up with backporting vsphere chart bumps; we have bumped them as necessary to support new Kubernetes minors but not backported those changes to older branches so we were significantly behind in some places.
version bump for bugfix
Test deployment on vsphere
* https://github.com/rancher/rke2/issues/8934
```release-note
```
=> [release-1.32] Bump vsphere charts
