- pkg/windows/calico.go
This PR dumps felix and calico outputs into different log files. These log files are under `C:/var/log/` which is a directory created by rke2 and removed when uninstalling.
As explained in the issue, there is currently no way to check the logs of calico or felix.
Apart from this, I am changing:
```
if err := cmd.Run(); err != nil {
logrus.Errorf("Felix exited: %v", err)
}
```
because when felix process fails ==>  `err = nil` and we never get that log. This PR will allow us to see the message "Felix exited" in the rke2 service logs and then we could investigate what happened by looking at the felix logs under  `C:/var/log/felix.log`
Bugfix
Deploy rke2 with a windows node and try to find felix logs (e.g. the described default felix.log in the docs) or by checking the rke2 service logs. You …
> Add log files for felix and calico in rke2-windows

- pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/4428
Issue: https://github.com/rancher/rke2/issues/4435
> [Release 1.26] Add log files for felix and calico

- pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/4428
Issue: https://github.com/rancher/rke2/issues/4436
> [Release 1.25] Add log files for felix and calico

- pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/4428
Issue: https://github.com/rancher/rke2/issues/4437
> [Release 1.24] Add log files for felix and calico

- Dockerfile
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/4428
Issue: https://github.com/rancher/rke2/issues/4430
> [Release 1.25] Update multus version

- Dockerfile
- scripts/build-images
ingress-nginx bump
Linked to https://github.com/rancher/rke2-charts/pull/352
> [Release-1.24] Bump ingress-nginx charts to v1.7.1

- Dockerfile
- scripts/build-images
ingress-nginx bump
Linked to https://github.com/rancher/rke2-charts/pull/352
> [Release-1.25] Bump ingress-nginx charts to v1.7.1

- Dockerfile
- scripts/build-images
ingress-nginx bump
Linked to https://github.com/rancher/rke2-charts/pull/352
> [Release-1.26] Bump ingress-nginx charts to v1.7.1

- Dockerfile
Update Calico CRD on Canal chart
#4453
> Updated Calico crd on Canal

- Dockerfile.windows
- pkg/pebinaryexecutor/pebinary.go
- pkg/rke2/rke2_windows.go
- pkg/windows/calico.go
- pkg/windows/utils.go
Backport for  #4164
Issue: #4457
> [Release 1.26] Add support for cni none on windows and initial windows-bgp backend

- Dockerfile.windows
- pkg/pebinaryexecutor/pebinary.go
- pkg/rke2/rke2_windows.go
- pkg/windows/calico.go
- pkg/windows/utils.go
Backport for #4164
Issue:  #4458
> [Release 1.25] Add support for cni none on windows and initial windows-bgp backend

- Dockerfile.windows
- pkg/pebinaryexecutor/pebinary.go
- pkg/rke2/rke2_windows.go
- pkg/windows/calico.go
- pkg/windows/utils.go
Backport for #4164
Issue: #4459
> [Release 1.24] Add support for cni none on windows and initial windows-bgp backend

- Dockerfile
- scripts/build-images
Backport for #4463
Issue #4464
> [Release 1.26] Updated Calico crd on Canal

- Dockerfile
- scripts/build-images
Backport for #4463
Issue #4465
> [Release 1.25] Updated Calico crd on Canal

- Dockerfile
- scripts/build-images
Backport for #4463
Issue #4466
> [Release 1.24] Updated Calico crd on Canal

- Dockerfile
This change updates the `rke2-canal` version to incorporate the changes made in https://github.com/rancher/rke2-charts/pull/359.
This is a non-breaking change to enhance existing functionality with the addition of a standard feature.
The rendered output of the new chart version is byte-for-byte identical to the previous version unless the the additional configuration options it enables are intentionally set.
* https://github.com/rancher/rke2/issues/4525
> Update canal with resource bounds config

- Dockerfile
- scripts/build-images
Backport for https://github.com/rancher/rke2/pull/4535
Issue: https://github.com/rancher/rke2/issues/4563
> [Release 1.24] Update Calico and Flannel on Canal

- Dockerfile
- scripts/build-images
Backport for https://github.com/rancher/rke2/pull/4535
Issue: https://github.com/rancher/rke2/issues/4562
> [Release 1.25] Update Calico and Flannel on Canal

- Dockerfile
- scripts/build-images
Update cilium to the latest version 1.14.0
#4581
```release-note
```
> Update cilium to v1.14.0

- Dockerfile
- scripts/build-images
Backport for #4585
Issue: #4582
> [Release 1.26] Update cilium to v1.14.0

- Dockerfile
- scripts/build-images
Backport for #4585 
Issue: #4583
> [Release 1.25] Update cilium to v1.14.0

- tests/e2e/validatecluster/validatecluster_test.go
Add additional certs in validation test
NA
Run e2e test
> Update certs list for certificates test

- Dockerfile
- scripts/build-images
Update multus chart and image build to include whereabouts v0.6.2
version bump
check versions
* https://github.com/rancher/rke2/issues/4488
```release-note
Updated the embedded whereabouts to v0.6.2
```
> update to whereabouts v0.6.2

- Dockerfile
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/4590
Issue: https://github.com/rancher/rke2/issues/4594
> [Release 1.26] update to whereabouts v0.6.2

- Dockerfile
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/4590
Issue: https://github.com/rancher/rke2/issues/4595
> [Release 1.25] update to whereabouts v0.6.2

- pkg/pebinaryexecutor/pebinary.go
- pkg/windows/calico.go
- pkg/windows/utils.go
Ran `gofmt -s -w .` on pkg/ and got three files which were not well formatted
Bugfix
Ran `gofmt -s -w .` on pkg/  and verify that there is no output
https://github.com/rancher/rke2/issues/4604
```release-note
```
> Fix wrongly formatted files

- .github/ISSUE_TEMPLATE/bug_report.md
The current bug template includes a url which does not work
Bugfix
```release-note
```
> Fix non-working URL in issue template

- pkg/windows/calico.go
This PR:
* Removes the repeating log entry in rke2 windows logs as explained in the issue by creating the calico log path first
* Checks the error of MkdirAll which we were not checking
Bugfix
Check that the rke2 logs in Windows do not include the line:
`error creating calico-node.log: open C:\var\log\calico-node.log: The system cannot find the path specified.`
anymore
https://github.com/rancher/rke2/issues/4608
```release-note
```
> Fix calico-node.log problem

- pkg/pebinaryexecutor/pebinary.go
- pkg/windows/calico.go
- pkg/windows/utils.go
Issue: https://github.com/rancher/rke2/issues/4610
Backport: https://github.com/rancher/rke2/pull/4605
> [Release 1.26] Fix wrongly formatted files

- pkg/pebinaryexecutor/pebinary.go
- pkg/windows/calico.go
- pkg/windows/utils.go
Backport: https://github.com/rancher/rke2/pull/4605
Issue: https://github.com/rancher/rke2/issues/4611
> [Release 1.25] Fix wrongly formatted files

- pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/4609
Issue: https://github.com/rancher/rke2/issues/4616
> [Release 1.26] Fix repeating "cannot find file" error

- pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/4609
Issue: https://github.com/rancher/rke2/issues/4617
> [Release 1.25] Fix repeating "cannot find file" error

- windows/rke2-quickstart.ps1
This change enables users to install RKE2 in standalone Windows server and join the node as agent to an standalone RKE2 cluster using commit Id as well as version
Adding an enhancement to the `rke2-quickstart.ps1` file
- Simple test would be to download and run the script in an Windows server and provide required parameters to the scripts
- Download the script in a Windows node
- Run the script with the arguments
```
.\rke2-quickstart.ps1 -ServerIP 1.2.3.4 -Token token -Version v1.24.12+rke2r1
.\rke2-quickstart.ps1 -ServerIP 1.2.3.4 -Token token -Version v1.24.12+rke2r1 -Mode INSTALL_RKE2_VERSION
```
- Required params:
```
- ServerIP: The private or public IP of the Primary Server
- Token: The token retrieved from Primary Server (/var/lib/rancher/rke2/server/token)
- Version: The version …
```
> Add support for commit installation in Windows quickstart file

- scripts/validate-release
Use 'go list -m' instead of grep to look up versions
bugfix; ci
Normal build checks
this is a test
* 
```release-note
```
> Use 'go list -m' instead of grep to look up versions

- go.mod
- go.sum
* Bump
* Backport
* Check go.mod
* https://github.com/rancher/rke2/issues/4633
```release-note
```
> Bump k3s version to recent 1.26

- go.mod
- go.sum
* Bump
* Backport 
* Check go.mod
* https://github.com/rancher/rke2/issues/4634
```release-note
```
> Bump k3s version to recent 1.25

- tests/e2e/mixedos/Vagrantfile
- tests/e2e/scripts/install-bgp.ps1
In our e2e mixedos testing, add a script to install the required Windows packages that provide BGP support in case we want to change Calico's backend and use bgp instead
Testing new feature
Deploy mixedos test and make sure that it still works (no regression with new packages)
https://github.com/rancher/rke2/issues/4638
```release-note
```
> Install BGP windows packages in Windows image for tests

- pkg/windows/calico.go
This PR does two things:
1 - Cleans up env variables we were passing to all processes (Calico, Felix and confd) which were useles:
* ETCD_*: They are not used because we are using Calico K8s mode (KDD). ETCD variables are covering a different use case
*STARTUP_VALID_IP_TIMEOUT: This variable is used in the upstream powershell script that installs Calico as a service but we are not using it
* DNS_*: These variables are used to build the CNI config file for the calico binary (/etc/cni/10-calico.conf)
* K8S_SERVICE_CIDR: Same as DNS_*
* CNI_*: Same as DNS_*
* VXLAN_VNI: Same as DNS_* and we are already passing it to Felix as FELIX_VXLANVNI which is enough
* FELIX_LOG*: We are always passing none, so they don't make any sense
* FELIX_METADATAADDR: Same as FELIX_LOG*
* CALICO_* are passed as …
> Clean-up env variables and check OS env variables for felix and calico in Windows

- tests/e2e/mixedos/Vagrantfile
- tests/e2e/scripts/install-bgp.ps1
Backport: https://github.com/rancher/rke2/pull/4639
Issue: https://github.com/rancher/rke2/issues/4638
> [Release 1.25] Install BGP windows packages in Windows image for tests

- pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/4640
Issue: https://github.com/rancher/rke2/issues/4655
> [Release 1.26] Allow OS env variables to be consumed

- pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/4640
Issue: https://github.com/rancher/rke2/issues/4656
> [Release 1.25] Allow OS env variables to be consumed

- Dockerfile
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/4662
> [Backport release-1.26] upgrade multus chart to v4.0.2-build2023081100

- Dockerfile
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/4663
> [Backport release-1.25] upgrade multus chart to v4.0.2-build2023081100

- pkg/pebinaryexecutor/pebinary.go
- pkg/windows/calico.go
- pkg/windows/utils.go
- tests/e2e/mixedos/Vagrantfile
- tests/e2e/scripts/install-bgp.ps1
Issues: https://github.com/rancher/rke2/issues/4675, https://github.com/rancher/rke2/issues/4676, https://github.com/rancher/rke2/issues/4677, https://github.com/rancher/rke2/issues/4678
Backports: https://github.com/rancher/rke2/pull/4605, https://github.com/rancher/rke2/pull/4609, https://github.com/rancher/rke2/pull/4639, https://github.com/rancher/rke2/pull/4640, https://github.com/rancher/rke2/pull/4670
How to verify:
* https://github.com/rancher/rke2/pull/4605: Nothing needed, it just formats the files correctly
* https://github.com/rancher/rke2/pull/4609: 
```
Check that the rke2 logs in Windows do not include the line:
error creating calico-node.log: open C:\var\log\calico-node.log: The system cannot find the path specified.
anymore
```
* https://github.com/rancher/rke2/pull/4639: …
> [Release 1.24] Windows fixes

- Dockerfile
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/4681
> [backport 1.24] upgrade multus chart to v4.0.2-build2023081100

- Dockerfile
- scripts/build-images
Update Cilium to 1.14.1 to address #4749
#4750
```release-note
```
> Update cilium to 1.14.1

- Dockerfile
- scripts/build-images
Backport for  #4755
Issue #4751
> [Release 1.27] Update cilium to 1.14.1

- Dockerfile
- scripts/build-images
Backport for #4755
Issue #4752
> [Release 1.26] Update cilium to 1.14.1

- Dockerfile
- scripts/build-images
Backport for #4755
Issue #4753
> [Release 1.25] Update cilium to 1.14.1

- pkg/windows/calico.go
Issue: https://github.com/rancher/rke2/issues/4790
Backport: https://github.com/rancher/rke2/pull/4723
> [Release 1.25] Add a time.Sleep in calico-win to avoid polluting the logs

- .droneignore
skip .github/ changes to make drone drone less
> Fix .github regex to skip drone runs on gh action bumps

- pkg/cli/cmds/profile_linux.go
- pkg/cli/cmds/root.go
- pkg/rke2/rke2.go
Backport #4708  to 1.26
* Support generic "cis" profile
https://github.com/rancher/rke2/issues/4795
```release-note
```
> [Release-1.26] Support generic "cis" profile

- install.sh
Adds an install argument option to not install fapolicy rules
* https://github.com/rancher/rke2/issues/4803
```release-note
```
We need this option to fix an issue we are having with fapolicy rules
> add skip fapolicy option

- Dockerfile
Update Calico chart to accept any Felix config values
#4692
```release-note
```
> Update calico chart to accept felix config values

- Dockerfile
> [Release 1.27] Update calico chart to accept felix config values

- Dockerfile
> [Release 1.26] Update calico chart to accept felix config values

- Dockerfile
> [Release 1.25] Update calico chart to accept felix config values

- .drone.yml
> remove unnecessary docker pull

- pkg/windows/calico.go
> fix function name on comment

- install.sh
Include missing variables in /etc/os-release
Bugfix
Install k3s on official slemicro image
- https://github.com/rancher/rke2/issues/4826
```release-note
```
> Fix slemicro check for selinux

- Dockerfile
- scripts/build-images
- Chart Bump
https://github.com/rancher/rke2/issues/4832
```release-note
```
> Bump cilium to 1.14.2

- scripts/validate-release
Backport https://github.com/rancher/rke2/pull/4841
A filter in `validate-release` to not accept branchs that contains `dependabot` and `updatecli`
- Improvement
- Backport
Create a branch with dependabot or update cli in our project
```bash
git checkout -b dependabot/testing
```
Push the branch
```bash
git push origin dependabot/testing
```
See the tag that are in the commit and then use
```bash
git branch --all -q --contains $YOUR_TAG_HERE | grep origin | grep -vE 'dependabot|updatecli|origin$|HEAD' | sed -e 's/^[[:space:]]*//'
```
You will not see any dependabot and updatecli branches
- https://github.com/rancher/rke2/issues/4856
```release-note
```
> [Release 1.27] Filter release branchs

- scripts/validate-release
Backport https://github.com/rancher/rke2/pull/4841
A filter in `validate-release` to not accept branchs that contains `dependabot` and `updatecli`
- Improvement
- Backport
Create a branch with dependabot or update cli in our project
```bash
git checkout -b dependabot/testing
```
Push the branch
```bash
git push origin dependabot/testing
```
See the tag that are in the commit and then use
```bash
git branch --all -q --contains $YOUR_TAG_HERE | grep origin | grep -vE 'dependabot|updatecli|origin$|HEAD' | sed -e 's/^[[:space:]]*//'
```
You will not see any dependabot and updatecli branches
- https://github.com/rancher/rke2/issues/4854
```release-note
```
> [Release 1.25] Filter release branchs

- Dockerfile
Issue: https://github.com/rancher/rke2/issues/4842
Backport: https://github.com/rancher/rke2/pull/4780
> [Release 1.27] Update charts to have ipFamilyPolicy: PreferDualStack as default

- Dockerfile
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/4843
Backport: https://github.com/rancher/rke2/pull/4780
> [Release 1.26] Update charts to have ipFamilyPolicy: PreferDualStack as default

- Dockerfile
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/4780
Issue: https://github.com/rancher/rke2/issues/4844
> [Release 1.25] Update charts to have ipFamilyPolicy: PreferDualStack as default

- Dockerfile
- Dockerfile.windows
Bump containerd to v1.7.7+k3s1
version bump
check version
* https://github.com/rancher/rke2/issues/4872
```release-note
```
> Bump containerd to v1.7.7+k3s1

- Dockerfile
- Dockerfile.windows
Bump containerd to v1.7.7+k3s1
version bump
check version
* https://github.com/rancher/rke2/issues/4875
```release-note
```
> [release-1.25] Bump containerd to v1.7.7+k3s1

- go.mod
- go.sum
- Bump k3s to commit https://github.com/k3s-io/k3s/commit/ec31704c1ab3d59f2adc40be806d75533fb83abe
https://github.com/rancher/rke2/issues/4891
```release-note
```
> [Release-1.25] Bump k3s

- go.mod
- go.sum
- Bump K3s to commit https://github.com/k3s-io/k3s/commit/c9ee52b4eeab6a4786db7d83c663f458152ae338
https://github.com/rancher/rke2/issues/4892
```release-note
```
> [Release-1.26] K3s Bump

- bundle/bin/rke2-killall.sh
- https://github.com/rancher/rancher/issues/42895
- #4930 
```release-note
```
> Remove pod-manifests dir in killall script

- bundle/bin/rke2-killall.sh
- https://github.com/rancher/rancher/issues/42895
- #4932 
```release-note
```
> [release-1.26] Remove pod-manifests dir in killall script

- developer-docs/updating_rke2_charts.md
- pkg/images/images.go
- scripts/build-windows-binary
- scripts/package-windows-images
> Revert "[release-1.27] - mirrored pause backport"

- developer-docs/updating_rke2_charts.md
- pkg/images/images.go
- scripts/build-binary
- scripts/build-images
- scripts/build-windows-binary
- scripts/build-windows-images
- scripts/package-windows-images
> Revert "[release-1.25] - mirrored pause backport"

- developer-docs/updating_rke2_charts.md
- pkg/images/images.go
- scripts/build-binary
- scripts/build-images
- scripts/build-windows-binary
- scripts/build-windows-images
- scripts/package-windows-images
> Revert "[release-1.26] - mirrored pause backport"

- Dockerfile
- scripts/build-images
- Bump Ingress-nginx to hardened v1.9.3
```release-note
```
> [Release-1.25] Bump ingress-nginx to v1.9.3

- Dockerfile
- scripts/build-images
- Bump Ingress-nginx to hardened v1.9.3
```release-note
```
> [Release-1.26] Bump ingress-nginx to v1.9.3

- Dockerfile
- scripts/build-images
- Bump Ingress-nginx to hardened v1.9.3
```release-note
```
> [Release-1.27] Bump ingress-nginx to v1.9.3

- Dockerfile
- scripts/build-images
- Waiting on https://github.com/rancher/rke2-charts/pull/380
- Bump Ingress-nginx to hardened v1.9.3
```release-note
```
> Bump ingress-nginx to v1.9.3

- go.mod
- go.sum
TBD
```release-note
Fixed an issue with identifying additional container runtimes
```
> [Release-1.25] Bump k3s, include container runtime fix

- go.mod
- go.sum
TBD
```release-note
Fixed an issue with identifying additional container runtimes
```
> [Release-1.26] Bump k3s, include container runtime fix

- go.mod
- go.sum
TBD
```release-note
Fixed an issue with identifying additional container runtimes
```
> [Release-1.27] Bump k3s, include container runtime fix

- go.mod
- go.sum
TBD
```release-note
Fixed an issue with identifying additional container runtimes
```
> Bump k3s, include container runtime fix

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/4996
> Update canal to v3.26.3

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5013
> [backport 1.27] Update canal to v3.26.3

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5014
> [backport 1.26] Update canal to v3.26.3

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5015
> [release 1.25] Update canal to v3.26.3

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5021
> update calico to v3.26.3 and fix nodeAddressAutodetectionV4 issue

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5023
> [backport 1.27] update calico to v3.26.3

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5024
> [backport 1.26] update calico to v3.26.3

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5025
> [backport 1.25] update calico to v3.26.3

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5053
> bump cilium chart to 1.14.400

- .drone.yml
- manifest-runtime.tmpl
Backport of https://github.com/rancher/rke2/pull/5095
> [backport 1.26] remove s390x steps temporarily since runners are disabled

- Dockerfile
- Dockerfile.windows
- go.mod
- go.sum
Bump containerd to v1.7.11
version bump
check version
* https://github.com/rancher/rke2/issues/5116
```release-note
```
> Bump containerd to v1.7.11

- Dockerfile
- Dockerfile.windows
- go.mod
- go.sum
Bump containerd to v1.7.11
version bump
check version
* https://github.com/rancher/rke2/issues/5119
```release-note
```
> [relase-1.26] Bump containerd to v1.7.11

- go.mod
- go.sum
Bump K3s version for v1.29
Updates k3s: https://github.com/k3s-io/k3s/compare/941119640612...3190a5faa28d7a0d428c756d67adcab7eb11e6a5
version bump
* https://github.com/rancher/rke2/issues/5152
```release-note
```
> Bump K3s version for v1.29

- Dockerfile
- Dockerfile.windows
Backport https://github.com/rancher/rke2/pull/4952 to release-1.28
https://github.com/rancher/rke2/issues/5178
```release-note
```
> [Release-1.28] Use dl.k8s.io for getting kubectl

- Dockerfile
- Dockerfile.windows
Backport https://github.com/rancher/rke2/pull/4952 to release-1.27
https://github.com/rancher/rke2/issues/5177
```release-note
```
> [Release-1.27] Use dl.k8s.io for getting kubectl

- Dockerfile
- Dockerfile.windows
Backport https://github.com/rancher/rke2/pull/4952 to release-1.26
https://github.com/rancher/rke2/issues/5176
```release-note
```
> [Release-1.26] Use dl.k8s.io for getting kubectl

- Dockerfile.windows
Backport #5159 to release-1.27
https://github.com/rancher/rke2/issues/5183
```release-note
```
> [Release-1.27] ensure charts directory exists in Windows runtime image

- Dockerfile.windows
Backport #5159 to release-1.26
https://github.com/rancher/rke2/issues/5182
```release-note
```
> [Release-1.26] ensure charts directory exists in Windows runtime image

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5169
Backport: https://github.com/rancher/rke2/pull/5168
> [Release 1.26] Bump versions of different components

- channels.yaml
Add v1.29 to channels list
channel server, release
install from release channel
* https://github.com/rancher/rke2/issues/5192
```release-note
```
> Add v1.29 to channels list

- charts/chart_versions.yaml
Increases version of coredns to fix bug
Version bump
Check issue
https://github.com/rancher/rke2/issues/5156
```release-note
Fix coredns local cache when in dual stack clusters
```
> Version bump of coredns chart to fix bug

- charts/chart_versions.yaml
Issue: https://github.com/rancher/rke2/issues/5197
Backport: https://github.com/rancher/rke2/pull/5189
> [Release-1.28] Update coredns chart to fix bug

- charts/chart_versions.yaml
Issue: https://github.com/rancher/rke2/issues/5198
Backport: https://github.com/rancher/rke2/pull/5189
> [Release-1.27] Update coredns chart to fix bug

- charts/chart_versions.yaml
Issue: https://github.com/rancher/rke2/issues/5199
Backport: https://github.com/rancher/rke2/pull/5189
> [Release-1.26] Update coredns chart to fix bug

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5207
> [release-1.28] update multus chart to add optional dhcp daemonset

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/5209
> [release-1.26] update multus chart to add optional dhcp daemonset

- tests/e2e/dnscache/Vagrantfile
- tests/e2e/dnscache/dnscache_test.go
- tests/e2e/resource_files/nodecache.yaml
Add an e2e test about dnscache to avoid problems like this one https://github.com/rancher/rke2/issues/5156.
Using dnscache is not something common, so we could introduce a regression and not notice it. We should have an e2e test
New e2e test
go test -v -timeout=20m ./tests/e2e/dnscache/
Note that currently it fails because of: https://github.com/rancher/rke2/issues/5156
https://github.com/rancher/rke2/issues/5191
```release-note
```
> Add e2e test for dnscache

- tests/e2e/dnscache/Vagrantfile
- tests/e2e/dnscache/dnscache_test.go
- tests/e2e/resource_files/nodecache.yaml
Backport: https://github.com/rancher/rke2/commit/f8605328d2cb2c7768518900ed04d3170d0b8ddf
Issue: https://github.com/rancher/rke2/issues/5221
> [Release 1.27] Add e2e test about dnscache

- tests/e2e/dnscache/Vagrantfile
- tests/e2e/dnscache/dnscache_test.go
- tests/e2e/resource_files/nodecache.yaml
Backport: https://github.com/rancher/rke2/commit/f8605328d2cb2c7768518900ed04d3170d0b8ddf
Issue: https://github.com/rancher/rke2/issues/5220
> [Release 1.28] Add e2e test about dnscache

- charts/chart_versions.yaml
- scripts/build-images
- scripts/validate-charts
Linked issue: https://github.com/rancher/rke2/issues/5244
> [release-1.26] update rke2-whereabouts to v0.6.3 and bump rke2-multus parent chart

- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5251
Backport: https://github.com/rancher/rke2/pull/5237
> [release-1.28] Bump sriov image build versions

- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5253
Backport: https://github.com/rancher/rke2/pull/5237
> [release-1.26] Bump sriov image build versions

- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5252
Backport: https://github.com/rancher/rke2/pull/5237
> [release-1.27] Bump sriov image build versions

- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5264
Backport: https://github.com/rancher/rke2/pull/5154
> [Release-1.28] Enable arm64 based images for calico, multus and harvester

- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5263
Backport: https://github.com/rancher/rke2/pull/5154
> [Release-1.27] Enable arm64 based images for calico, multus and harvester

- pkg/logging/logging.go
- pkg/pebinaryexecutor/pebinary.go
- pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/5248
Issue: https://github.com/rancher/rke2/issues/5281
> [Release-1.28] Improve kube-proxy and calico logging in Windows

- pkg/logging/logging.go
- pkg/pebinaryexecutor/pebinary.go
- pkg/windows/calico.go
Backport: https://github.com/rancher/rke2/pull/5248
Issue: https://github.com/rancher/rke2/issues/5282
> [Release-1.27] Improve kube-proxy and calico logging in Windows

- .drone.yml
- Dockerfile
> update base image

- channels.yaml
> update channels for January 2024 patch

- pkg/pebinaryexecutor/pebinary.go
- pkg/rke2/rke2_windows.go
- pkg/windows/calico.go
- pkg/windows/types.go
Backport: https://github.com/rancher/rke2/pull/5276
Issue: https://github.com/rancher/rke2/issues/5365
> [Release-1.28] [Windows] Create a common CNI interface and config struct

- pkg/pebinaryexecutor/pebinary.go
- pkg/rke2/rke2_windows.go
- pkg/windows/calico.go
- pkg/windows/types.go
Backport: https://github.com/rancher/rke2/pull/5276
Issue: https://github.com/rancher/rke2/issues/5367
> [Release-1.26] [Windows] Create a common CNI interface and config struct

- charts/chart_versions.yaml
- scripts/validate-charts
Linked issue: https://github.com/rancher/rke2/issues/5373
Backport of https://github.com/rancher/rke2/pull/5160
> [release-1.27] Fix validate-charts script

- charts/chart_versions.yaml
- scripts/validate-charts
Linked issue: https://github.com/rancher/rke2/issues/5374
Backport of https://github.com/rancher/rke2/pull/5160
> [release-1.26] Fix validate-charts script

- charts/chart_versions.yaml
- scripts/build-images
Use the newer multus, whereabouts and coredns images so that they have less CVs (due to scratch or bci-busybox base image and newer code)
Version bump
Just verify that there is no regression with a typical test to check that cluster deploys, dns works and multus deploys and works
https://github.com/rancher/rke2/issues/5378
```release-note
Coredns, multus and whereabouts using minimal base images
```
> Bump coredns and multus/whereabouts versions

- pkg/windows/calico.go
- pkg/windows/utils.go
Issue: https://github.com/rancher/rke2/issues/5380
Backport: https://github.com/rancher/rke2/pull/5336
> [Release-1.28] Avoid race condition when deleting HNS networks

- pkg/windows/calico.go
- pkg/windows/utils.go
Issue: https://github.com/rancher/rke2/issues/5381
Backport: https://github.com/rancher/rke2/pull/5336
> [Release-1.27] Avoid race condition when deleting HNS networks

- pkg/windows/calico.go
- pkg/windows/utils.go
Issue: https://github.com/rancher/rke2/issues/5382
Backport: https://github.com/rancher/rke2/pull/5336
> [Release-1.26] Avoid race condition when deleting HNS networks

- Dockerfile.windows
- bundle/bin/rke2-killall.sh
- bundle/bin/rke2-uninstall.ps1
- charts/chart_versions.yaml
- pkg/cli/cmds/server.go
- pkg/pebinaryexecutor/pebinary.go
- pkg/windows/calico.go
- pkg/windows/flannel.go
- pkg/windows/types.go
- pkg/windows/utils.go
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5392
Backport: https://github.com/rancher/rke2/pull/5322
> [Release-1.27] Add CNI plugin flannel support for Windows

- Dockerfile.windows
- bundle/bin/rke2-killall.sh
- bundle/bin/rke2-uninstall.ps1
- charts/chart_versions.yaml
- pkg/cli/cmds/server.go
- pkg/pebinaryexecutor/pebinary.go
- pkg/windows/calico.go
- pkg/windows/flannel.go
- pkg/windows/types.go
- pkg/windows/utils.go
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5393
Backport: https://github.com/rancher/rke2/pull/5322
> [Release-1.26] Add CNI plugin flannel support for Windows

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5397
Backport: https://github.com/rancher/rke2/pull/5379
> [Release-1.28] Bump coredns and multus/whereabouts versions

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5398
Backport: https://github.com/rancher/rke2/pull/5379
> [Release-1.27] Bump coredns and multus/whereabouts versions

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5399
Backport: https://github.com/rancher/rke2/pull/5379
> [Release-1.26] Bump coredns and multus/whereabouts versions

- charts/chart_versions.yaml
- scripts/build-images
- scripts/validate
Backport for  #5414
Issue #5411
> [Release 1.28] Update canal version

- charts/chart_versions.yaml
- scripts/build-images
- scripts/validate
Backport for #5414
Issue #5412
> [Release 1.27] Update canal version

- charts/chart_versions.yaml
- scripts/build-images
- scripts/validate
Backport for #5414
Issue #5413
> [Release 1.26] Update canal version

- pkg/windows/calico.go
- pkg/windows/flannel.go
- pkg/windows/utils.go
Backport: https://github.com/rancher/rke2/pull/5421
Issue: https://github.com/rancher/rke2/issues/5424
> [Release-1.28] Improve calico in windows

- pkg/windows/calico.go
- pkg/windows/flannel.go
- pkg/windows/utils.go
Backport: https://github.com/rancher/rke2/pull/5421
Issue: https://github.com/rancher/rke2/issues/5426
> [Release-1.27] Improve calico in windows

- charts/chart_versions.yaml
- scripts/build-images
harvester-csi-driver's Helm chart has been bumped to 0.1.17 in rancher/rke-charts[1] (harvester-csi-driver tag v0.1.6)
[1] https://github.com/rancher/rke2-charts/blob/56596f9958f70296dec30f17c6d95bfc1e2690f0/packages/harvester-csi-driver/package.yaml#L1
Update harvester-csi-driver chart to latest version
Helm chart version bump
* https://github.com/rancher/rke2/issues/5430
```release-note
NONE
```
> Bump harvester-csi-driver to 0.1.17

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5420
Issue: https://github.com/rancher/rke2/issues/5450
> [Release-1.26] Update Cilium to 1.15.0

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5420
Issue: https://github.com/rancher/rke2/issues/5449
> [Release-1.27] Update Cilium to 1.15.0

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5420
Issue: https://github.com/rancher/rke2/issues/5448
> [Release-1.28] Update Cilium to 1.15.0

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5473
Issue: https://github.com/rancher/rke2/issues/5474
> [Release-1.28] Update Cilium to 1.15.1

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5473
Issue: https://github.com/rancher/rke2/issues/5475
> [Release-1.27] Update Cilium to 1.15.1

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5473
Issue: https://github.com/rancher/rke2/issues/5476
> [Release-1.26] Update Cilium to 1.15.1

- charts/chart_versions.yaml
bump rke2-coredns chart to revert name generation template
bugfix
* https://github.com/rancher/rke2/issues/5494
* https://github.com/rancher/rke2/discussions/5491
```release-note
```
> [release-1.28] Bump rke2-coredns chart

- charts/chart_versions.yaml
bump rke2-coredns chart to revert name generation template
bugfix
* https://github.com/rancher/rke2/issues/5495
* https://github.com/rancher/rke2/discussions/5491
```release-note
```
> [release-1.27] Bump rke2-coredns chart

- charts/chart_versions.yaml
bump rke2-coredns chart to revert name generation template
bugfix
* https://github.com/rancher/rke2/issues/5496
* https://github.com/rancher/rke2/discussions/5491
```release-note
```
> [release-1.26] Bump rke2-coredns chart

- go.mod
- go.sum
- Bump K3s to pull in: https://github.com/k3s-io/k3s/pull/9539
https://github.com/rancher/rke2/issues/5504
```release-note
```
> Bump K3s for etcd-only fix

- go.mod
- go.sum
Bump K3s to pull in https://github.com/k3s-io/k3s/pull/9545
https://github.com/rancher/rke2/issues/5505
```release-note
```
> [Release-1.28] Bump K3s for etcd-only fix

- go.mod
- go.sum
Bump K3s to pull in https://github.com/k3s-io/k3s/pull/9546
https://github.com/rancher/rke2/issues/5506
```release-note
```
> [Release-1.27] Bump K3s for etcd-only fix

- go.mod
- go.sum
Bump K3s to pull in https://github.com/k3s-io/k3s/pull/9547
https://github.com/rancher/rke2/issues/5507
```release-note
```
> [Release-1.26] Bump k3s for etcd-only fix

- pkg/rke2/np.go
Add new network policy for ingress controller webhook.
The ingress-nginx chart added a validating webhook a while back, but we did not have a policy that allowed access to it. Access was being allowed by the overly broad network policy that we removed in https://github.com/rancher/rke2/pull/5318.
Unfortunately we can't just add this to the existing netpol, as we document that it is not updated once the namespace annotation has been set.
bugfix
* https://github.com/rancher/rke2/issues/5360
```release-note
```
> [release-1.26] Add new network policy for ingress controller webhook

- tests/e2e/multus/Vagrantfile
- tests/e2e/multus/multus_test.go
- tests/e2e/resource_files/multus-pods.yaml
- tests/e2e/scripts/ipv6.sh
Adds a simple test for multus
New test
go test -v -timeout=20m ./tests/e2e/multus/
```release-note
```
> Add a multus e2e test

- tests/e2e/multus/Vagrantfile
- tests/e2e/multus/multus_test.go
- tests/e2e/resource_files/multus-pods.yaml
- tests/e2e/scripts/ipv6.sh
Backport: https://github.com/rancher/rke2/pull/5483
> [Release 1.28] Add a multus e2e test

- tests/e2e/multus/Vagrantfile
- tests/e2e/multus/multus_test.go
- tests/e2e/resource_files/multus-pods.yaml
- tests/e2e/scripts/ipv6.sh
Backport: https://github.com/rancher/rke2/pull/5483
> [Release 1.27] Add a multus e2e test

- tests/e2e/multus/Vagrantfile
- tests/e2e/multus/multus_test.go
- tests/e2e/resource_files/multus-pods.yaml
- tests/e2e/scripts/ipv6.sh
Backport: https://github.com/rancher/rke2/pull/5483
> [Release 1.26] Add a multus e2e test

- charts/chart_versions.yaml
- scripts/build-images
> Bump vsphere csi chart to 3.1.2-rancher101 and cpi to 1.7.001

- charts/chart_versions.yaml
- scripts/build-images
Bumps the coredns image which will use now bci-busybox as base image instead of scratch. That way we have the CA certificates
Bugfix
Explained in the issue
https://github.com/rancher/rke2/issues/5550
```release-note
```
> Fix DNS over TLS bug

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5558
Backport: https://github.com/rancher/rke2/pull/5552
> [Release 1.28] Bump coredns chart

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5559
Backport: https://github.com/rancher/rke2/pull/5552
> [Release 1.27] Bump coredns chart

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5552
Issue: https://github.com/rancher/rke2/issues/5560
> [Release 1.26] Bump coredns chart

- charts/chart_versions.yaml
Linked Issue: rancher/rke2#5538
> Bump multus chart version

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/5575
Issue: https://github.com/rancher/rke2/issues/5591
> [Release-1.28] Bump multus chart version

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/5575
Issue: https://github.com/rancher/rke2/issues/5592
> [Release-1.27] Bump multus chart version

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/5575
Issue: https://github.com/rancher/rke2/issues/5593
> [Release-1.26] Bump multus chart version

- go.mod
- go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/4761befc8301...06ecbe807148d148f94b9c74febc2b950bda6255
bugfix
* Pull through fix for 
https://github.com/k3s-io/k3s/issues/9731
```release-note
```
> [release-1.27] Bump K3s version for v1.27

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5638
Issue: https://github.com/rancher/rke2/issues/5640
> [Release-1.28] Bump flannel version

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5641
Backport: https://github.com/rancher/rke2/pull/5638
> [Release-1.27] Bump flannel version

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5642
Backport: https://github.com/rancher/rke2/pull/5638
> [Release-1.26] Bump flannel version

- pkg/pebinaryexecutor/pebinary.go
- pkg/windows/flannel.go
Backport: https://github.com/rancher/rke2/pull/5661
Issue: https://github.com/rancher/rke2/issues/5664
> [Release 1.28] Add some small fixes in flannel-windows

- pkg/pebinaryexecutor/pebinary.go
- pkg/windows/flannel.go
Backport: https://github.com/rancher/rke2/pull/5661
Issue: https://github.com/rancher/rke2/issues/5665
> [Release 1.27] Add some small fixes in flannel-windows

- pkg/pebinaryexecutor/pebinary.go
- pkg/windows/flannel.go
Backport: https://github.com/rancher/rke2/pull/5661
Issue: https://github.com/rancher/rke2/issues/5668
> [Release 1.26] Add some small fixes in flannel-windows

- charts/chart_versions.yaml
- scripts/build-images
Backport https://github.com/rancher/rke2/pull/5671
```
kubectl get pods -A -o json | jq '.items[] | select(.metadata.labels."app.kubernetes.io/name") | { name: .metadata.labels."app.kubernetes.io/name", version: .metadata.labels."app.kubernetes.io/version" }'
...
{
"name": "rke2-ingress-nginx",
"version": "1.9.6"
}
```
https://github.com/rancher/rke2/issues/5686
```release-note
```
> [Release-1.27] Bump ingress-nginx to 1.9.6

- pkg/pebinaryexecutor/pebinary.go
Backport: https://github.com/rancher/rke2/pull/5698
Issue: https://github.com/rancher/rke2/issues/5725
> [Release 1.28] Fix Windows path setting

- pkg/pebinaryexecutor/pebinary.go
Backport: https://github.com/rancher/rke2/pull/5698
Issue: https://github.com/rancher/rke2/issues/5726
> [Release 1.27] Fix Windows path setting

- go.mod
- go.sum
- pkg/windows/flannel.go
Backport: https://github.com/rancher/rke2/pull/5705
Issue: https://github.com/rancher/rke2/issues/5736
> [Release 1.28] Check if the kube-proxy VIP was already reserved

- charts/chart_versions.yaml
- scripts/build-images
also update to hardened-cni-plugins v1.4.1-build20240325
Issue: rancher/rke2#5709
Waiting on:
> Update to Cilium v1.15.3

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5713
Issue: https://github.com/rancher/rke2/issues/5744
> [Release-1.28] Update to Cilium v1.15.3

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5713
Issue: https://github.com/rancher/rke2/issues/5743
> [Release-1.27] Update to Cilium v1.15.3

- charts/chart_versions.yaml
- scripts/build-images
backport https://github.com/rancher/rke2/pull/5694
```release-note
Bump Harvester-cloud-provider v0.2.3
```
> [Release-1.27] Bump harvester-cloud-provider v0.2.3

- charts/chart_versions.yaml
- scripts/build-images
backport https://github.com/rancher/rke2/pull/5694
```release-note
Bump Harvester-cloud-provider v0.2.3
```
> [Release-1.28] Bump harvester-cloud-provider v0.2.3

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/5760
Waiting on:
> Update to Cilium v1.15.4

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5764
Issue: https://github.com/rancher/rke2/issues/5772
> [Release-1.28] Update to Cilium v1.15.4

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/5764
Issue: https://github.com/rancher/rke2/issues/5771
> [Release-1.27] Update to Cilium v1.15.4

- charts/chart_versions.yaml
> Vsphere csi bump

- charts/chart_versions.yaml
> [release-1.27] Vsphere csi bump

- go.mod
- go.sum
For /db/info fix
Updates k3s: https://github.com/k3s-io/k3s/compare/8eed41d7e0b8...289a1a3edbc0f6ee5a7f91bf96aa1ed1b743bd1f
bugfix / version bump
* https://github.com/rancher/rke2/issues/5820
```release-note
```
> [release-1.28] Bump K3s version for dbinfo fix

- go.mod
- go.sum
For /db/info fix
Updates k3s: https://github.com/k3s-io/k3s/compare/b721a3e05d09...b23f142da8589854cc7ee45da08d96b5ad1ee1ff
bugfix / version bump
* https://github.com/rancher/rke2/issues/5821
```release-note
```
> [release-1.27] Bump K3s version for dbinfo fix

- charts/chart_versions.yaml
- scripts/build-images
Updated Calico and Flannel images for Canal to fix the ARM64 build
#5808
```release-note
```
> Updated Calico and Flannel to fix ARM64 build

- charts/chart_versions.yaml
- scripts/build-images
Backport for #5825
Issue #5826
> [Release 1.28] Updated Calico and Flannel to fix ARM64 build

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/5834
Issue: https://github.com/rancher/rke2/issues/5836
> [release-1.27] Update rke2-canal to v3.27.3-build2024042301

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/5842
Issue: https://github.com/rancher/rke2/issues/5844
> [Release-1.27] Use the newer Flannel chart

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/5842
Issue: https://github.com/rancher/rke2/issues/5845
> [Release-1.28] Use the newer Flannel chart

- charts/chart_versions.yaml
Bump metrics-server chart to restore legacy label
bugfix/version bump
* https://github.com/rancher/rke2/issues/5848
```release-note
```
> Bump metrics-server chart to restore legacy label

- charts/chart_versions.yaml
Bump metrics-server chart to restore legacy label
bugfix/version bump
* https://github.com/rancher/rke2/issues/5850
```release-note
```
> [release-1.28] Bump metrics-server chart to restore legacy label

- charts/chart_versions.yaml
Bump metrics-server chart to restore legacy label
bugfix/version bump
* https://github.com/rancher/rke2/issues/5851
```release-note
```
> [release-1.27] Bump metrics-server chart to restore legacy label

- channels.yaml
> update stable channel to v1.28.9+rke2r1

- tests/e2e/mixedosbgp/Vagrantfile
- tests/e2e/mixedosbgp/mixedosbgp_test.go
- tests/e2e/scripts/calico_manifestbgp.sh
Add a new e2e test that verifies BGP communication works in a mixedos env
https://github.com/rancher/rke2/issues/4486
```release-note
```
> Add mixedos BGP e2e test

- tests/e2e/mixedosbgp/Vagrantfile
- tests/e2e/mixedosbgp/mixedosbgp_test.go
- tests/e2e/scripts/calico_manifestbgp.sh
New e2e test (mixedos-bgp)
New test
https://github.com/rancher/rke2/issues/5871
```release-note
```
> [Release 1.28] Add mixedos BGP e2e test

- tests/e2e/mixedosbgp/Vagrantfile
- tests/e2e/mixedosbgp/mixedosbgp_test.go
- tests/e2e/scripts/calico_manifestbgp.sh
New test (mixedos-bgp)
New test
https://github.com/rancher/rke2/issues/5872
```release-note
```
> [Release 1.27] Add mixedos BGP e2e test

- bundle/bin/rke2-killall.sh
Backport: https://github.com/rancher/rke2/pull/5795
Issue: https://github.com/rancher/rke2/issues/5875
> [Release 1.28] Remove flannel-v6.4096 when rke2-killall.sh

- bundle/bin/rke2-killall.sh
Backport: https://github.com/rancher/rke2/pull/5795
Issue: https://github.com/rancher/rke2/issues/5876
> [Release 1.27] Remove flannel-v6.4096 when rke2-killall.sh

- tests/e2e/dnscache/Vagrantfile
- tests/e2e/dualstack/Vagrantfile
- tests/e2e/multus/Vagrantfile
Backport: https://github.com/rancher/rke2/pull/5881
> [Release 1.29] Remove cni parameter from agent config

- tests/e2e/dnscache/Vagrantfile
- tests/e2e/dualstack/Vagrantfile
- tests/e2e/multus/Vagrantfile
Backport: https://github.com/rancher/rke2/pull/5881
> [Release 1.27] Remove cni parameter from agent config

- scripts/validate
Backport: https://github.com/rancher/rke2/pull/5788
> [Release 1.28] Add script to validate flannel versions

- scripts/validate
Backport: https://github.com/rancher/rke2/pull/5788
> [Release 1.27] Add script to validate flannel versions

- tests/e2e/mixedosbgp/mixedosbgp_test.go
- tests/e2e/testutils.go
Backport: https://github.com/rancher/rke2/pull/5886
> [Release 1.27] Fix mixedosbgp e2e test

- channels.yaml
- Update rke2 channel to 1.30
```release-note
```
> Update channels for 1.30

- go.mod
- go.sum
- pkg/cli/defaults/defaults.go
- pkg/cli/defaults/defaults_linux.go
- pkg/cli/defaults/defaults_windows.go
- pkg/windows/utils.go
> [1.28] windows changes

- go.mod
- go.sum
- pkg/cli/defaults/defaults.go
- pkg/cli/defaults/defaults_linux.go
- pkg/cli/defaults/defaults_windows.go
- pkg/windows/utils.go
> [1.27] windows changes

- charts/chart_versions.yaml
- scripts/build-images
Backport #5935
https://github.com/rancher/rke2/issues/5938
```release-note
```
> [Release-1.28] Cilium version bump to 1.15.5

- charts/chart_versions.yaml
- scripts/build-images
Backport #5935
https://github.com/rancher/rke2/issues/5939
```release-note
```
> [Release-1.27] Cilium version bump to 1.15.5

- charts/chart_versions.yaml
- scripts/build-images
Backport #5935
https://github.com/rancher/rke2/issues/5937
```release-note
```
> [Release-1.29] Cilium version bump to 1.15.5

- developer-docs/updating_rke2_charts.md
- pkg/controllers/cisnetworkpolicy/cleanup.go
Fix incorrect wrangler package import
https://github.com/rancher/rke2/pull/5856 should have been updated after the change to wrangler v3. Tests were green since they were run before the change.
bugfix
RKE2 builds successfully
* https://github.com/rancher/rke2/issues/5855
```release-note
```
> Fix incorrect wrangler package import

- bundle/bin/rke2-uninstall.ps1
- pkg/pebinaryexecutor/pebinary.go
Backport: https://github.com/rancher/rke2/pull/5779
Issue: https://github.com/rancher/rke2/issues/5960
> [Release 1.28] Improve rke2-uninstall.ps1 script

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/5953
Issue: https://github.com/rancher/rke2/issues/5995
> [Release 1.27] Update flannel chart to fix vni error (#5953)

- tests/e2e/ciliumnokp/Vagrantfile
- tests/e2e/ciliumnokp/ciliumnokp_test.go
- tests/e2e/dnscache/Vagrantfile
- tests/e2e/mixedos/Vagrantfile
- tests/e2e/mixedos/mixedos_test.go
- tests/e2e/mixedosbgp/Vagrantfile
- tests/e2e/mixedosbgp/mixedosbgp_test.go
- tests/e2e/multus/Vagrantfile
- tests/e2e/scripts/cilium_nokubeproxy.sh
- tests/e2e/splitserver/Vagrantfile
- tests/e2e/testutils.go
- tests/e2e/upgradecluster/Vagrantfile
- tests/e2e/vagrantdefaults.rb
- tests/e2e/validatecluster/Vagrantfile
Backport: https://github.com/rancher/rke2/pull/5885
Issue: https://github.com/rancher/rke2/issues/5966
> [Release 1.28] Add cilium no proxy e2e test (#5885)

- tests/e2e/ciliumnokp/Vagrantfile
- tests/e2e/ciliumnokp/ciliumnokp_test.go
- tests/e2e/dnscache/Vagrantfile
- tests/e2e/mixedos/Vagrantfile
- tests/e2e/mixedos/mixedos_test.go
- tests/e2e/mixedosbgp/Vagrantfile
- tests/e2e/mixedosbgp/mixedosbgp_test.go
- tests/e2e/multus/Vagrantfile
- tests/e2e/scripts/cilium_nokubeproxy.sh
- tests/e2e/splitserver/Vagrantfile
- tests/e2e/testutils.go
- tests/e2e/upgradecluster/Vagrantfile
- tests/e2e/vagrantdefaults.rb
- tests/e2e/validatecluster/Vagrantfile
Backport: https://github.com/rancher/rke2/pull/5885
Issue: https://github.com/rancher/rke2/issues/5965
> [Release 1.27] Add cilium no proxy e2e test (#5885)

- tests/e2e/ciliumnokp/Vagrantfile
- tests/e2e/ciliumnokp/ciliumnokp_test.go
- tests/e2e/dualstack/Vagrantfile
- tests/e2e/mixedos/Vagrantfile
- tests/e2e/mixedos/mixedos_test.go
- tests/e2e/mixedosbgp/Vagrantfile
- tests/e2e/mixedosbgp/mixedosbgp_test.go
- tests/e2e/multus/Vagrantfile
- tests/e2e/scripts/cilium_nokubeproxy.sh
- tests/e2e/secretsencryption/Vagrantfile
- tests/e2e/secretsencryption_old/Vagrantfile
- tests/e2e/splitserver/Vagrantfile
- tests/e2e/testutils.go
- tests/e2e/upgradecluster/Vagrantfile
- tests/e2e/vagrantdefaults.rb
- tests/e2e/validatecluster/Vagrantfile
Backport: https://github.com/rancher/rke2/pull/5885
Issue: https://github.com/rancher/rke2/issues/5964
> [Release 1.29] Add cilium no proxy e2e test (#5885)

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/5953
Issue: https://github.com/rancher/rke2/issues/5997
> [Release 1.28] Update flannel chart to fix vni error (#5953)

- charts/chart_versions.yaml
- scripts/build-images
Bumps multus and whereabouts version
Version bump
https://github.com/rancher/rke2/issues/6014
```release-note
Bump multus and whereabouts
```
> Bump multus and whereabouts version

- tests/e2e/testutils.go
Backport: https://github.com/rancher/rke2/pull/5955
> [Release 1.28] Add extra log in e2e tests

- tests/e2e/testutils.go
Backport: https://github.com/rancher/rke2/pull/5955
> [Release 1.27] Add extra log in e2e tests

- pkg/podexecutor/staticpod.go
Backport from: https://github.com/rancher/rke2/pull/5931
Issue: https://github.com/rancher/rke2/issues/6001
> [Release-1.27] Add a Kine fix when rke2 restart apiserver

- pkg/podexecutor/staticpod.go
Backport from: https://github.com/rancher/rke2/pull/5931
Issue: https://github.com/rancher/rke2/issues/6002
> [Release-1.28] Add a Kine fix when rke2 restart apiserver

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6015
Issue: https://github.com/rancher/rke2/issues/6034
> [Release 1.29] Bump multus and whereabouts version (#6015)

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6015
Issue: https://github.com/rancher/rke2/issues/6036
> [Release 1.27] Bump multus and whereabouts version (#6015)

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6015
Issue: https://github.com/rancher/rke2/issues/6038
> [Release 1.28] Bump multus and whereabouts version (#6015)

- charts/chart_versions.yaml
Update the Harvester cloud provider version
bump newer version
Regular tests for harvester-cloud-provider
```release-note
Bump Harvester-cloud-provider v0.2.4
```
> Bump harvester-cloud-provider v0.2.4

- charts/chart_versions.yaml
Backport https://github.com/rancher/rke2/pull/5980
```release-note
Bump Harvester-cloud-provider v0.2.4
```
> [Release-1.29] Bump harvester-cloud-provider v0.2.4

- pkg/rke2/rke2_linux.go
- Issue: https://github.com/rancher/rke2/issues/6069
- Backport from: https://github.com/rancher/rke2/pull/5954
> [Release-1.29] Add easy support for single node sqlite with kine

- tests/e2e/vagrantdefaults.rb
- Fix for e2e test util manifest function
All testing fix
https://github.com/rancher/rke2/issues/6023
```release-note
```
> Fix loadManifests function

- charts/chart_versions.yaml
- scripts/build-images
Backport https://github.com/rancher/rke2/pull/6022
https://github.com/rancher/rke2/issues/6053
```release-note
```
> [Release-1.29] Bump nginx to 1.10.1

- charts/chart_versions.yaml
- scripts/build-images
Backport https://github.com/rancher/rke2/pull/6022
https://github.com/rancher/rke2/issues/6054
```release-note
```
> [Release-1.28] Bump nginx to 1.10.1 

- charts/chart_versions.yaml
- scripts/build-images
Backport https://github.com/rancher/rke2/pull/6022
https://github.com/rancher/rke2/issues/6052
```release-note
```
> [Release-1.27] Bump nginx to 1.10.1

- go.mod
- go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/da2625d1a999...485eaf31b4fe6f8502a210eba6103c7d774c923d
version bump / pull-through
* https://github.com/rancher/rke2/issues/6108
* https://github.com/rancher/rke2/issues/6105
```release-note
```
> [release-1.29] Bump K3s version for v1.29

- Dockerfile
- Dockerfile.windows
Bump containerd to fixed tag
bugfix version bump
Check version
```release-note
```
> [release-1.27] Bump containerd to correctly built tag

- Dockerfile
- Dockerfile.windows
Bump containerd to fixed tag
bugfix version bump
Check version
```release-note
```
> [release-1.29] Bump containerd to correctly built tag

- Dockerfile
- Dockerfile.windows
Bump containerd to fixed tag
bugfix version bump
Check version
* https://github.com/rancher/rke2/issues/6079
```release-note
```
> [release-1.28] Bump containerd to correctly built tag

- .github/workflows/test-suite.yaml
- scripts/build-image-runtime
- tests/e2e/ciliumnokp/Vagrantfile
- tests/e2e/dnscache/Vagrantfile
- tests/e2e/dualstack/Vagrantfile
- tests/e2e/mixedos/Vagrantfile
- tests/e2e/mixedos/mixedos_test.go
- tests/e2e/mixedosbgp/Vagrantfile
- tests/e2e/mixedosbgp/mixedosbgp_test.go
- tests/e2e/multus/Vagrantfile
- tests/e2e/secretsencryption/Vagrantfile
- tests/e2e/secretsencryption_old/Vagrantfile
- tests/e2e/splitserver/Vagrantfile
- tests/e2e/testutils.go
- tests/e2e/upgradecluster/Vagrantfile
- tests/e2e/validatecluster/Vagrantfile
- Enable local build testing for MixedOS tests
- Simplify E2E local provisioning steps, utilize parallel provisioning built into vagrant-libvirt
E2E tests
CI is Green
Its all testing changes
https://github.com/rancher/rke2/issues/6119
```release-note
```
> Support MixedOS E2E local testing

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/6042
> Bump flannel image in rke2-canal

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6046
Backport: https://github.com/rancher/rke2/pull/6136
> [release 1.28] Bump flannel image in rke2-canal

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6047
Backport: https://github.com/rancher/rke2/pull/6136
> [release 1.27] Bump flannel image in rke2-canal

- go.mod
- go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/1661f1024a68...f10cb295340133c33de2d2136a697db11de0c05e
version bump
* https://github.com/rancher/rke2/issues/6130
* https://github.com/rancher/rke2/issues/6115
```release-note
```
> Bump K3s version for v1.30

- bundle/bin/rke2-uninstall.ps1
Backport: https://github.com/rancher/rke2/pull/6098
Issue: https://github.com/rancher/rke2/issues/5958
> [Release 1.29] Improve rke2-uninstall.ps1

- bundle/bin/rke2-uninstall.ps1
Backport: https://github.com/rancher/rke2/pull/6098
Issue: https://github.com/rancher/rke2/issues/5960
> [Release 1.28] Improve rke2-uninstall.ps1

- .github/actions/setup-go/action.yaml
- .github/workflows/test-suite.yaml
- .github/workflows/unittest.yaml
- scripts/build-image-runtime
- tests/e2e/ciliumnokp/Vagrantfile
- tests/e2e/dnscache/Vagrantfile
- tests/e2e/dualstack/Vagrantfile
- tests/e2e/mixedos/Vagrantfile
- tests/e2e/mixedos/mixedos_test.go
- tests/e2e/mixedosbgp/Vagrantfile
- tests/e2e/mixedosbgp/mixedosbgp_test.go
- tests/e2e/multus/Vagrantfile
- tests/e2e/splitserver/Vagrantfile
- tests/e2e/testutils.go
- tests/e2e/upgradecluster/Vagrantfile
- tests/e2e/vagrantdefaults.rb
- tests/e2e/validatecluster/Vagrantfile
Contains:
- https://github.com/rancher/rke2/pull/6058
- https://github.com/rancher/rke2/pull/6097
- https://github.com/rancher/rke2/pull/6137
- https://github.com/rancher/rke2/pull/6144
Testing and CI
CI still Green
https://github.com/rancher/rke2/issues/6023
https://github.com/rancher/rke2/issues/6119
https://github.com/rancher/rke2/issues/6143
```release-note
Testing CI backports:
- Fix loadManifests function
- Slim down E2E artifacts
- Support MixedOS E2E local testing
- Add custom golang setup action for better caching
```
> [Release-1.27] June Testing Backports

- .github/actions/setup-go/action.yaml
- .github/workflows/test-suite.yaml
- .github/workflows/unittest.yaml
- scripts/build-image-runtime
- tests/e2e/ciliumnokp/Vagrantfile
- tests/e2e/dnscache/Vagrantfile
- tests/e2e/dualstack/Vagrantfile
- tests/e2e/mixedos/Vagrantfile
- tests/e2e/mixedos/mixedos_test.go
- tests/e2e/mixedosbgp/Vagrantfile
- tests/e2e/mixedosbgp/mixedosbgp_test.go
- tests/e2e/multus/Vagrantfile
- tests/e2e/secretsencryption/Vagrantfile
- tests/e2e/secretsencryption_old/Vagrantfile
- tests/e2e/splitserver/Vagrantfile
- tests/e2e/testutils.go
- tests/e2e/upgradecluster/Vagrantfile
- tests/e2e/vagrantdefaults.rb
- tests/e2e/validatecluster/Vagrantfile
Contains:
- https://github.com/rancher/rke2/pull/6058
- https://github.com/rancher/rke2/pull/6097
- https://github.com/rancher/rke2/pull/6137
- https://github.com/rancher/rke2/pull/6144
Testing and CI
CI still Green
https://github.com/rancher/rke2/issues/6023
https://github.com/rancher/rke2/issues/6119
https://github.com/rancher/rke2/issues/6143
```release-note
Testing CI backports:
- Fix loadManifests function
- Slim down E2E artifacts
- Support MixedOS E2E local testing
- Add custom golang setup action for better caching
```
> [Release-1.29] June Testing Backports

- .drone.yml
Reverts a change that affected the publish-image-runtime step.
> Fix drone pipeline

- .drone.yml
Reverts a change that affected the publish-image-runtime step.
> [release-1.29] Fix drone pipeline

- .drone.yml
Reverts a change that affected the publish-image-runtime step.
> [release-1.28] Fix drone pipeline

- .drone.yml
Reverts a change that affected the publish-image-runtime step.
> [release-1.27] Fix drone pipeline

- go.mod
- go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/dd86a0581f3f...617b0e84f419e37ba995c6dec06ccfbb24bd649c
* https://github.com/rancher/rke2/issues/6228
```release-note
Fix issue that allowed multiple simultaneous snapshots to be allowed
```
> [release-1.28] Bump K3s version for snapshot fix

- go.mod
- go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/cb36c910a6d1...3ced503aa95f9b5831dd6a291c4ddc18287be992
* https://github.com/rancher/rke2/issues/6229
```release-note
Fix issue that allowed multiple simultaneous snapshots to be allowed
```
> [release-1.27] Bump K3s version for snapshot fix

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.27] Update calico image to v3.28.0-build20240625

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.28] Update calico image to v3.28.0-build20240625

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.29] Update calico image to v3.28.0-build20240625

- charts/chart_versions.yaml
- scripts/build-images
Bump multus to v4.0.206 to fix arm64 images
Version bump
Linked issue: https://github.com/rancher/rke2/issues/6181
> Bump multus to v4.0.206

- .github/workflows/pr.yml
> Upload tarball with merges to master and release branches

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6311
Issue: https://github.com/rancher/rke2/issues/6346
> [Release-1.27] Bump multus to v4.0.206

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6311
Issue: https://github.com/rancher/rke2/issues/6350
> [Release-1.29] Bump multus to v4.0.206

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6311
Issue: https://github.com/rancher/rke2/issues/6352
> [Release-1.30] Bump multus to v4.0.206

- .github/workflows/build.yml
> Fix secrets for commit id uploads

- .github/workflows/pr.yml
> [release-1.30] Fix secrets for commit id uploads

- .github/workflows/pr.yml
> [release-1.29] Fix secrets for commit id uploads

- .github/workflows/pr.yml
> [release-1.28] Fix secrets for commit id uploads

- Dockerfile
> Fix decompressing gh tool in Dockerfile

- .github/workflows/release.yml
- Dockerfile
- Makefile
- scripts/publish-binary
> [release-1.27] Publish binaries in dapper

- .github/workflows/release.yml
- Dockerfile
- Makefile
- scripts/publish-binary
> [release-1.28] Publish binaries in dapper

- .github/workflows/release.yml
- Dockerfile
- Makefile
- scripts/publish-binary
> [release-1.29] Publish binaries in dapper

- .github/workflows/release.yml
- Dockerfile
- Makefile
- scripts/publish-binary
> [release-1.30] Publish binaries in dapper

- .github/workflows/release.yml
> fixing pat_username

- .github/workflows/release.yml
> [release-1.30] Add missing package windows step in release

- .github/workflows/release.yml
> [release-1.29] Add missing package windows step in release

- .github/workflows/release.yml
> [release-1.28] Add missing package windows step in release

- .github/workflows/release.yml
> [release-1.27] Add missing package windows step in release

- scripts/dispatch
> Fix dispatch script

- scripts/dispatch
> [release-1.30] Fix dispatch script

- scripts/dispatch
> [release-1.29] Fix dispatch script

- scripts/dispatch
> [release-1.28] Fix dispatch script

- install.sh
- Amazon linux 2023 introduced the `/etc/amazon-linux-release`, but [per the docs](https://docs.aws.amazon.com/linux/al2023/ug/naming-and-versioning.html) this is just a symlink to `/etc/system-release` which exists in older AL2 instances. 
Installer Feature
- Spin up an AL2 instance
- Add the extra selinux packages required (per this [issue](https://github.com/amazonlinux/container-images/issues/101))
```
sudo amazon-linux-extras enable selinux-ng
sudo yum install selinux-policy-targeted
```
- Install rke2 as normal
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION='v1.30.2+rke2r1' INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD=rpm sh -
```
QA and manual testing
https://github.com/rancher/rke2/issues/6354
```release-note
```
> Support Amazon Linux 2 rpm installs

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/6411
```release-note
```
> Bump ingress-nginx to hardened2

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/6475
```release-note
```
> [Release-1.30] Bump nginx to hardened2

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/6477
```release-note
```
> [Release-1.28] Bump nginx to hardened2

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/6478
```release-note
```
> [Release-1.27] Bump nginx to hardened2

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/6495
> Bump rke2-canal to v3.28.1-build2024080600

- charts/chart_versions.yaml
- scripts/build-images
Update Cilium to latest version v1.16.0
#6499
```release-note
```
> Update Cilium to v1.16.0

- go.mod
- pkg/rke2/rke2_linux.go
- Issue https://github.com/rancher/rke2/issues/6454
- Backport from https://github.com/rancher/rke2/pull/6355
> [Release-1.30] Fix external etcd connection

- go.mod
- pkg/rke2/rke2_linux.go
- Issue https://github.com/rancher/rke2/issues/6456
- Backport from https://github.com/rancher/rke2/pull/6355
> [Release-1.28] Fix external etcd connection

- pkg/windows/calico.go
- pkg/windows/utils.go
Backport of #6437
Issue  #6536
> [Release 1.28] Fixed hns clean only in case of reboot

- pkg/windows/calico.go
- pkg/windows/utils.go
> [Release 1.27] Fixed hns clean only in case of reboot

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.28] Bump harvester csi driver v0.1.18

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.29] Bump Harvester CSI driver v0.1.18

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.30] Bump harvester csi driver v0.1.18

- charts/chart_versions.yaml
- scripts/build-images
> Bump Harvester CSI driver v0.1.18

- pkg/windows/calico.go
- pkg/windows/utils.go
Backport of #6437
Issue  #6535
> [Release 1.29] Fixed hns clean only in case of reboot

- pkg/rke2/np.go
* Add netpol template for traefik
* Fix netpol template for traefik
bugfix
* https://github.com/rancher/rke2/issues/6453
```release-note
```
> [release-1.30] Add netpol template for traefik

- pkg/rke2/np.go
Fix netpol template for traefik
bugfix
* https://github.com/rancher/rke2/issues/6449
```release-note
```
> Fix traefik netpol annotation key

- charts/chart_versions.yaml
Update Flannel chart with the fix to rightly disable nft
#6601
```release-note
```
> Fixed Flannel chart to rightly disable nft

- charts/chart_versions.yaml
Backport for #6606
Issue #6602
> [Release 1.30] Fixed Flannel chart to rightly disable nft

- charts/chart_versions.yaml
Backport for #6606
Issue #6603
> [Release 1.29] Fixed Flannel chart to rightly disable nft

- charts/chart_versions.yaml
Backport for #6606
Issue #6604
> [Release 1.28] Fixed Flannel chart to rightly disable nft

- charts/chart_versions.yaml
Backport for #6606
Issue  #6605
> [Release 1.27] Fixed Flannel chart to rightly disable nft

- charts/chart_versions.yaml
- scripts/build-images
Chart Bump
CI
https://github.com/rancher/rke2/issues/6594
```release-note
```
> Bump ingress-nginx to v1.10.4-hardened2

- charts/chart_versions.yaml
- scripts/build-images
Chart Bump
CI
https://github.com/rancher/rke2/issues/6595
```release-note
```
> [Release-1.30] Bump ingress-nginx to v1.10.4-hardened2

- charts/chart_versions.yaml
- scripts/build-images
Chart Bump
CI
https://github.com/rancher/rke2/issues/6596
```release-note
```
> [Release-1.29] Bump ingress-nginx to v1.10.4-hardened2

- charts/chart_versions.yaml
- scripts/build-images
Chart Bump
CI
https://github.com/rancher/rke2/issues/6597
```release-note
```
> [Release-1.28] Bump ingress-nginx to v1.10.4-hardened2

- charts/chart_versions.yaml
- scripts/build-images
Chart Bump
CI
https://github.com/rancher/rke2/issues/6598
```release-note
```
> [Release-1.27] Bump ingress-nginx to v1.10.4-hardened2

- charts/chart_versions.yaml
- scripts/build-images
* https://github.com/rancher/rke2/issues/6550
```release-note
```
> [release-1.27] Bump harvester csi driver v0.1.18

- pkg/rke2/np.go
Fix traefik netpol port names
bugfix
* https://github.com/rancher/rke2/issues/6449
```release-note
```
> Fix traefik netpol port names

- channels.yaml
> Update channel server for August 2024 release

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6658
> Bump canal to v3.28.1-build20240827

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6577
Issue: https://github.com/rancher/rke2/issues/6646
> [Release-1.30] Update to cilium v1.16.1

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6577
Issue: https://github.com/rancher/rke2/issues/6647
> [Release-1.29] Update cilium v1.16.1

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6577
Issue: https://github.com/rancher/rke2/issues/6648
> [Release-1.28] Update cilium v1.16.1

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6577
Issue: https://github.com/rancher/rke2/issues/6649
> [Release-1.27] Update cilium v1.16.1

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6671
Backport: https://github.com/rancher/rke2/pull/6659
> [release-1.29] Bump canal to v3.28.1-build20240827

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6673
Backport: https://github.com/rancher/rke2/pull/6659
> [release-1.28] Bump canal to v3.28.1-build20240827

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6676
> Bump canal to v3.28.1-build20240830

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.28] feat: bump harvester-cloud-provider to v0.2.6

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.29] feat: bump harvester-cloud-provider to v0.2.6

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.30] 1.30 bump harvester cloud provider v0.2.6

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.31] feat: bump harvester-cloud-provider to v0.2.6

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6686
Backport: https://github.com/rancher/rke2/pull/6677
> [release-1.28] Bump canal to v3.28.1-build20240830

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6685
Backport: https://github.com/rancher/rke2/pull/6677
> [release-1.29] Bump canal to v3.28.1-build20240830

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6684
Backport: https://github.com/rancher/rke2/pull/6677
> [release-1.30] Bump canal to v3.28.1-build20240830

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/6707
Issue: https://github.com/rancher/rke2/issues/6711
> [Release-1.30] Update cilium chart to `1.16.103`

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/6707
Issue: https://github.com/rancher/rke2/issues/6713
> [Release-1.28] Update cilium chart to `1.16.103`

- channels.yaml
Add channel for v1.31
channel server
```release-note
```
> Add channel for v1.31

- charts/chart_versions.yaml
- scripts/build-images
Linked issue: https://github.com/rancher/rke2/issues/6728
> Bump multus chart to v4.1.000

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6729
Issue: https://github.com/rancher/rke2/issues/6738
> [release-1.28] Bump multus chart to v4.1.000

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6729
Issue: https://github.com/rancher/rke2/issues/6742
> [release-1.30] Bump multus chart to v4.1.000

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6729
Issue: https://github.com/rancher/rke2/issues/6744
> [release-1.31] Bump multus chart to v4.1.000

- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6746
> Remove sriov images from airgap tarball

- .github/workflows/test-suite.yaml
- .github/workflows/updatecli.yml
- Reduce the use of the vanilla `action/setup-go` in favor of our custom composite action. We are still seeing large cache thrashing due to the use of the default action. 
TOO MANY Go Caches
CI Improvement
Check 1 week after merge, should see reduction in `setup-go-Linux-ubuntu22` under https://github.com/rancher/rke2/actions/caches
N/A
```release-note
```
> Use composite setup-go action in more places, disable GHA go caching

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/6683
Backport: https://github.com/rancher/rke2/pull/6677
> [release-1.31] Bump canal to v3.28.1-build20240830

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/6707
Issue: https://github.com/rancher/rke2/issues/6710
Depends on:
> [Release-1.31] Update cilium chart to `1.16.103`

- charts/chart_versions.yaml
- scripts/build-images
Updated Canal chart with updated Calico image with fixed CNI plugins.
#6770
```release-note
```
> Update Calico image for Canal with updated CNI plugins

- charts/chart_versions.yaml
- scripts/build-images
Backport for #6791
Issue #6779
> [Release 1.31] Update Calico image for Canal with updated CNI plugins

- charts/chart_versions.yaml
- scripts/build-images
Backport for #6791
Issue #6781
> [Release 1.30] Update Calico image for Canal with updated CNI plugins

- charts/chart_versions.yaml
- scripts/build-images
Backport for #6791
Issue  #6783
> [Release 1.29] Update Calico image for Canal with updated CNI plugins

- charts/chart_versions.yaml
- scripts/build-images
> [Release-1.31] Bump ingress-nginx to v1.10.4-hardened3

- charts/chart_versions.yaml
- scripts/build-images
> [Release-1.30] Bump ingress-nginx to v1.10.4-hardened3

- charts/chart_versions.yaml
- scripts/build-images
> [Release-1.29] Bump ingress-nginx to v1.10.4-hardened3

- charts/chart_versions.yaml
- scripts/build-images
> [Release-1.28] Bump ingress-nginx to v1.10.4-hardened3

- tests/e2e/ciliumnokp/ciliumnokp_test.go
The latest Cilium version we are using changed the output of one of the calls we make to verify that BPF is working. That made the e2e test fail.
From :
```
Host Routing:           BPF
```
to
```
Routing:                Network: Tunnel [vxlan]   Host: BPF
```
Bugfix on e2e test
Run the e2e test
```release-note
```
> Update cilium e2e test

- tests/e2e/ciliumnokp/ciliumnokp_test.go
Backport: https://github.com/rancher/rke2/pull/6808
> [Release 1.30] Update cilium e2e test

- tests/e2e/ciliumnokp/ciliumnokp_test.go
Backport: https://github.com/rancher/rke2/pull/6808
> [Release 1.31] Update cilium e2e test

- pkg/pebinaryexecutor/pebinary.go
Backport for #6820
Issue #6827
> [Release 1.30] Fixed windows CNI setup in case cni none is configured

- pkg/pebinaryexecutor/pebinary.go
Backport for #6820
Issue #6829
> [Release 1.28] Fixed windows CNI setup in case cni none is configured

- tests/e2e/mixedosbgp/Vagrantfile
Backport: https://github.com/rancher/rke2/pull/6840
> [Release 1.31] Fix e2e test bug in mixedosbgp

- tests/e2e/mixedosbgp/Vagrantfile
Backport: https://github.com/rancher/rke2/pull/6840
> [Release 1.29] Fix e2e test bug in mixedosbgp

- .github/workflows/trivy.yaml
- scripts/build-image-runtime
Backport https://github.com/rancher/rke2/pull/6806 
```release-note
```
> [Release-1.31] Add trivy scanning to PR reports

- .github/workflows/trivy.yaml
- scripts/build-image-runtime
Backport https://github.com/rancher/rke2/pull/6806 
```release-note
```
> [Release-1.29] Add trivy scanning to PR reports

- .github/workflows/trivy.yaml
- scripts/build-image-runtime
Backport https://github.com/rancher/rke2/pull/6806 
```release-note
```
> [Release-1.30] Add trivy scanning to PR reports

- charts/chart_versions.yaml
Bump coredns chart
Version bump
https://github.com/rancher/rke2/issues/6887
```release-note
```
> Bump coredns chart

- .github/workflows/release.yml
> Fix typo in dispatch workflow

- .github/workflows/release.yml
> [release-1.30] Fix typo in dispatch workflow

- .github/workflows/release.yml
> [release-1.28] Fix typo in dispatch workflow

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/6886
Issue: https://github.com/rancher/rke2/issues/6899
> [Release 1.31] Bump coredns chart

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/6886
Issue: https://github.com/rancher/rke2/issues/6900
> [Release 1.30] Bump coredns chart

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/6886
Issue: https://github.com/rancher/rke2/issues/6901
> [Release 1.29] Bump coredns chart

- bundle/bin/rke2-uninstall.sh
- Backport https://github.com/rancher/rke2/pull/6884
https://github.com/rancher/rke2/issues/6917
```release-note
```
> [Release-1.28] Fix uninstall for amazon linux 2

- bundle/bin/rke2-uninstall.sh
- Backport https://github.com/rancher/rke2/pull/6884
https://github.com/rancher/rke2/issues/6916
```release-note
```
> [Release-1.29] Fix uninstall for amazon linux 2 

- bundle/bin/rke2-uninstall.sh
- Backport https://github.com/rancher/rke2/pull/6884
https://github.com/rancher/rke2/issues/6915
```release-note
```
> [Release-1.30] Fix uninstall for amazon linux 2

- bundle/bin/rke2-uninstall.sh
- Backport https://github.com/rancher/rke2/pull/6884
https://github.com/rancher/rke2/issues/6914
```release-note
```
> [Release-1.31] Fix uninstall for amazon linux 2

- charts/chart_versions.yaml
- scripts/build-images
Update to the latest cilium v1.16.2 release
Linked Issue: https://github.com/rancher/rke2/issues/6882
> Update to Cilium v1.16.2

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6930
Issue: https://github.com/rancher/rke2/issues/6933
> [Release-1.31] Update to Cilium v1.16.2

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6930
Issue: https://github.com/rancher/rke2/issues/6934
> [Release-1.30] Update to Cilium v1.16.2

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6930
Issue: https://github.com/rancher/rke2/issues/6935
> [Release-1.29] Update to Cilium v1.16.2

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/6930
Issue: https://github.com/rancher/rke2/issues/6936
> [Release-1.28] Update to Cilium v1.16.2

- Dockerfile
> Bump crictl

- tests/e2e/scripts/run_tests.sh
Purpose: Failed tests fill up disk space in vagrant setup causing tests to fail. This is to cleanup after each run
> Add cleanup to e2e tests in vagrant env

- Dockerfile
- Dockerfile.windows
version bump
check version
* #6995
```release-note
```
> Bump containerd to v1.7.22

- Dockerfile
- Dockerfile.windows
version bump
check version
* #6996
```release-note
```
> [release-1.31] Bump containerd to v1.7.22

- Dockerfile
- Dockerfile.windows
version bump
check version
* #6997
```release-note
```
> [release-1.30] Bump containerd to v1.7.22

- charts/chart_versions.yaml
- scripts/build-images
- Bump ingress-nginx to v1.10.5-hardened1
Describe ingress-nginx pod and check image version
https://github.com/rancher/rke2/issues/6989
https://github.com/rancher/rke2/issues/6949
```release-note
```
> [Release-1.28] Ingress-nginx bumps

- Dockerfile
Bump crictl to v1.31.1-build20241011
bugfix/bump
check version
https://github.com/rancher/rke2/issues/6976#issuecomment-2406187869
```release-note
```
> Bump crictl to v1.31.1-build20241011

- Dockerfile
Bump crictl to v1.31.1-build20241011
bugfix/bump
check version
https://github.com/rancher/rke2/issues/6976#issuecomment-2406187869
```release-note
```
> [release-1.31] Bump crictl to v1.31.1-build20241011

- charts/chart_versions.yaml
- scripts/build-images
Bump csi snapshot charts
version bump
* https://github.com/rancher/rke2/issues/6950
```release-note
```
> [release-1.31] Bump csi snapshot charts

- charts/chart_versions.yaml
- scripts/build-images
Bump csi snapshot charts
version bump
* https://github.com/rancher/rke2/issues/6951
```release-note
```
> [release-1.30] Bump csi snapshot charts

- charts/chart_versions.yaml
- scripts/build-images
Bump csi snapshot charts
version bump
* https://github.com/rancher/rke2/issues/6952
```release-note
```
> [release-1.29] Bump csi snapshot charts

- charts/chart_versions.yaml
- scripts/build-images
Bump csi snapshot charts
version bump
* https://github.com/rancher/rke2/issues/6953
```release-note
```
> [release-1.28] Bump csi snapshot charts

- charts/chart_versions.yaml
- scripts/build-images
* https://github.com/rancher/rke2/issues/7050
```release-note
```
> Bump Harvester CSI driver v0.1.20

- charts/chart_versions.yaml
- scripts/build-images
* https://github.com/rancher/rke2/issues/7051
```release-note
```
> [release-1.31] Bump Harvester CSI driver v0.1.20

- charts/chart_versions.yaml
- scripts/build-images
* https://github.com/rancher/rke2/issues/7052
```release-note
```
> [release-1.30] Bump Harvester CSI driver v0.1.20

- charts/chart_versions.yaml
- scripts/build-images
* https://github.com/rancher/rke2/issues/7053
```release-note
```
> [release-1.29] Bump Harvester CSI driver v0.1.20

- Dockerfile
- Dockerfile.windows
This PR adds the image metadata labels to rke2-runtime image
enhancement
check rke2-runtime image labels
* https://github.com/rancher/rke2/issues/4238
```release-note
```
> [release-1.31] add org.opencontainers.image url and source labels to dockerfiles

- Dockerfile
- Dockerfile.windows
This PR adds the image metadata labels to rke2-runtime image
enhancement
check rke2-runtime image labels
* https://github.com/rancher/rke2/issues/4238
```release-note
```
> [release-1.30] add org.opencontainers.image url and source labels to dockerfiles

- charts/chart_versions.yaml
- scripts/build-images
Bump coredns to fix a bunch of CVEs, e.g. CVE-2024-22189
Version bump
Deploy rke2 and check the image of coredns is using 1.11.3. Verify DNS queries still work
https://github.com/rancher/rke2/issues/7077
```release-note
Bump coredns version to 1.11.3
```
> Bump coredns chart and image

- .github/workflows/release.yml
- Makefile
- scripts/publish-image-runtime-windows
- scripts/publish-manifest-runtime
> [release-1.28] rke2-runtime signing and manifests (#7089)

- .github/workflows/release.yml
- Makefile
- scripts/publish-image-runtime-windows
- scripts/publish-manifest-runtime
> [release-1.29] rke2-runtime signing and manifests (#7089)

- .github/workflows/release.yml
- Makefile
- scripts/publish-image-runtime-windows
- scripts/publish-manifest-runtime
> [release-1.30] rke2-runtime signing and manifests (#7089)

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.28] update hardened chart images

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.29] update hardened chart images

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.30] update hardened chart images

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.31] update hardened chart images

- Dockerfile
Bump crictl to newer build
bugfix/bump
check version
* https://github.com/rancher/rke2/issues/7109
```release-note
```
> [release-1.30] Update crictl source image for CVE bump

- Dockerfile
Bump crictl to newer build
bugfix/bump
check version
* https://github.com/rancher/rke2/issues/7110
```release-note
```
> [release-1.29] Update crictl source image for CVE bump

- Dockerfile
Bump crictl to newer build
bugfix/bump
check version
* https://github.com/rancher/rke2/issues/7111
```release-note
```
> [release-1.28] Update crictl source image for CVE bump

- charts/chart_versions.yaml
- scripts/build-images
* Backport: https://github.com/rancher/rke2/pull/7076
Issue: https://github.com/rancher/rke2/issues/7112
> [Release 1.28] Bump coredns chart and image

- scripts/build-images
> Fix hardened-flannel airgap image for rke2-flannel

- scripts/build-images
> [release-1.31] Fix hardened-flannel airgap image for rke2-flannel

- scripts/build-images
> [release-1.30] Fix hardened-flannel airgap image for rke2-flannel

- scripts/build-images
> [release-1.29] Fix hardened-flannel airgap image for rke2-flannel

- scripts/build-images
> [release-1.28] Fix hardened-flannel airgap image for rke2-flannel

- .github/workflows/release.yml
- Makefile
- scripts/version.sh
> Fix release workflow

- .github/workflows/release.yml
- Makefile
- scripts/version.sh
> [release-1.31] Fix release workflow

- .github/workflows/release.yml
- Makefile
- scripts/version.sh
> [release-1.30] Fix release workflow

- .github/workflows/release.yml
- Makefile
- scripts/version.sh
> [release-1.29] Fix release workflow

- .github/workflows/release.yml
- Makefile
- scripts/version.sh
> [release-1.28] Fix release workflow

- scripts/publish-image-runtime
- scripts/publish-image-runtime-windows
> Use buildkit

- scripts/publish-image-runtime
- scripts/publish-image-runtime-windows
> [release-1.29] use buildkit

- scripts/publish-image-runtime
- scripts/publish-image-runtime-windows
> [release-1.30] use buildkit

- scripts/publish-image-runtime
- scripts/publish-image-runtime-windows
> [release-1.28] use buildkit

- scripts/publish-image-runtime
- scripts/publish-image-runtime-windows
> [release-1.31] use buildkit

- Dockerfile.windows
- scripts/package-windows-images
- scripts/publish-image-runtime-windows
- scripts/publish-manifest-runtime
Backport of #7143
```release-note
```
> [release-1.30] Fix publish windows runtime

- Dockerfile.windows
- scripts/package-windows-images
- scripts/publish-image-runtime-windows
- scripts/publish-manifest-runtime
Backport of #7143
```release-note
```
> [release-1.28] Fix publish windows runtime

- .github/actions/vagrant-setup/action.yaml
- .github/workflows/test-suite.yaml
Backport of https://github.com/rancher/rke2/pull/7175 and https://github.com/rancher/rke2/pull/7168
CI Green 
```release-note
```
> [Release-1.29] Backport E2E GHA fixes

- .github/actions/vagrant-setup/action.yaml
- .github/workflows/test-suite.yaml
Backport of https://github.com/rancher/rke2/pull/7175 and https://github.com/rancher/rke2/pull/7168
```release-note
```
> [Release-1.30] Backport E2E GHA fixes

- .github/actions/vagrant-setup/action.yaml
- .github/workflows/test-suite.yaml
Backport of https://github.com/rancher/rke2/pull/7175 and https://github.com/rancher/rke2/pull/7168
CI Green 
```release-note
```
> [Release-1.31] Backport E2E GHA fixes

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7166
```release-note
```
> Bump ingress-nginx to v1.10.5-hardened4

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7184
```release-note
```
> [Release-1.29] Bump ingress-nginx to v1.10.5-hardened4

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7185
```release-note
```
> [Release-1.28] Bump ingress-nginx to v1.10.5-hardened4

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7183
```release-note
```
> [Release-1.30] Bump ingress-nginx to v1.10.5-hardened4

- charts/chart_versions.yaml
- scripts/build-images
Update canal chart to track upstream updates
Version bump 
https://github.com/rancher/rke2/issues/7192
```release-note
```
> Bump canal chart to v3.29.0

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7181
```release-note
```
> [Release-1.31] Bump ingress-nginx to v1.10.5-hardened4

- charts/chart_versions.yaml
Bump CSI/CPI charts and images to latest version. 
https://github.com/rancher/rke2/issues/7245
```release-note
```
> [Release-1.31] Bump vSphere CSI/CPI charts to 1.9.1 and 3.3.1-rancher700

- charts/chart_versions.yaml
Linked issue: #7276 Backport: #7266
> [release 1.30] Bump rke2-coredns to 1.33.005

- charts/chart_versions.yaml
- scripts/build-images
Update to the latest cilium `v1.16.4` release
Linked Issue: https://github.com/rancher/rke2/issues/7313
> Update to Cilium v1.16.4

- charts/chart_versions.yaml
- scripts/build-images
Update canal to the latest `v3.29.1` release.
Linked issue: https://github.com/rancher/rke2/issues/7347
> Update canal to `v3.29.1`

- charts/chart_versions.yaml
- scripts/build-images
Bump Harvester CSI driver v0.1.21
Bug fix for backward compatibility and corner cases.
#7333 
```release-note
Bump Harvester-csi-driver v0.1.21
```
> Bump Harvester CSI driver v0.1.21

- charts/chart_versions.yaml
- scripts/build-images
Bump Harvester CSI driver v0.1.21
Bug fix for backward compatibility and corner cases.
https://github.com/rancher/rke2/issues/7357
```release-note
Bump Harvester-csi-driver v0.1.21
```
> [release 1.31] Bump Harvester CSI driver v0.1.21

- charts/chart_versions.yaml
- scripts/build-images
Bump Harvester CSI driver v0.1.21
Bug fix for backward compatibility and corner cases.
https://github.com/rancher/rke2/issues/7358
```release-note
Bump Harvester-csi-driver v0.1.21
```
> [release 1.30] Bump harvester csi driver v0.1.21

- charts/chart_versions.yaml
- scripts/build-images
Bump Harvester CSI driver v0.1.21
Bug fix for backward compatibility and corner cases.
https://github.com/rancher/rke2/issues/7359
```release-note
Bump Harvester-csi-driver v0.1.21
```
> [release 1.29] Bump harvester csi driver v0.1.21

- charts/chart_versions.yaml
- scripts/build-images
Updated Flannel and Canal version with the latest images
#7401
```release-note
```
> Update Flannel and Canal version

- charts/chart_versions.yaml
- scripts/build-images
Backport for #7405
issue #7402
> [Release 1.31] Update Flannel and Canal version

- charts/chart_versions.yaml
- scripts/build-images
Backport for #7405
issue #7403
> [Release 1.30] Update Flannel and Canal version

- charts/chart_versions.yaml
- scripts/build-images
Backport for #7405
issue #7404
> [Release 1.29] Update Flannel and Canal version

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7314
Issue: https://github.com/rancher/rke2/issues/7323
> [release-1.29] Update to Cilium v1.16.4

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7314
Issue: https://github.com/rancher/rke2/issues/7322
> [release-1.30] Update to Cilium v1.16.4

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7314
Issue: https://github.com/rancher/rke2/issues/7321
> [release-1.31] Update to Cilium v1.16.4

- charts/chart_versions.yaml
- scripts/build-images
Backport #7410 
https://github.com/rancher/rke2/issues/7413
```release-note
```
> [Release-1.29] Bump ingress-nginx to hardened6

- charts/chart_versions.yaml
- scripts/build-images
Backport #7410 
https://github.com/rancher/rke2/issues/7412
```release-note
```
> [Release-1.30] Bump ingress-nginx to hardened6

- charts/chart_versions.yaml
- scripts/build-images
Backport #7410 
https://github.com/rancher/rke2/issues/7411
```release-note
```
> [Release-1.31] Bump ingress-nginx to hardened6

- charts/chart_versions.yaml
- scripts/build-images
Upstream has released a new dns-node-cache (after 6 months) that fixes about 10 CVEs. 
```release-note
```
> [Release-1.29] Bump dns-node-cache to 1.24.0

- charts/chart_versions.yaml
- scripts/build-images
Upstream has released a new dns-node-cache (after 6 months) that fixes about 10 CVEs. 
Backport: https://github.com/rancher/rke2/pull/7350
https://github.com/rancher/rke2/issues/7366
```release-note
```
> [Release-1.31] Bump dns-node-cache to 1.24.0

- charts/chart_versions.yaml
- scripts/build-images
Upstream has released a new dns-node-cache (after 6 months) that fixes about 10 CVEs. 
Dependency Bump
TBD
```release-note
```
> Bump dns-node-cache to 1.24.0

- channels.yaml
> Update stable channel - Latest 1.31

- scripts/validate-release
Handles case where tagged commit exists on multiple branches - such as when we branch for a new release and then immediately tag an RC.
https://github.com/rancher/rke2/actions/runs/12470754662/job/34806446905#step:5:1512
bugfix, ci
See CI
```release-note
```
> [release-1.32] Validate single branch for tag

- charts/chart_versions.yaml
- scripts/build-images
Update to the latest cilium `v1.16.5` release
Linked Issue: https://github.com/rancher/rke2/issues/7442
> Update to Cilium `v1.16.5`

- updatecli/updatecli.d/vsphere-cpi.yml
- updatecli/updatecli.d/vsphere-csi.yml
- Fix PRs like https://github.com/rancher/rke2/pull/7459 from trying to downgrade the version.
CI fix
```release-note
```
> Use typefilter not versionfilter for cpi,csi updatecli

- charts/chart_versions.yaml
> [release-1.32] charts: bump Harvester CSI Driver v0.1.2

- charts/chart_versions.yaml
> [release-1.31] charts: bump harvester csi driver v0.1.22 

- charts/chart_versions.yaml
> [release-1.30] charts: bump Harvester CSI Driver v0.1.22

- charts/chart_versions.yaml
> [release-1.29] charts: bump Harvester CSI Driver v0.1.22

- charts/build-chart.sh
- charts/build-charts.sh
- charts/chart_versions.yaml
- scripts/build-images
- scripts/validate-charts
- tests/docker/test-run-basics
* Update volume snapshot controller and CRDs.
* Update chart build scripting to allow generating an empty add-on to trigger removal of the chart by setting version to `0.0.0`
Version bump
* Check chart and image version
* Check for removal of snapshot validation webhook
* https://github.com/rancher/rke2/issues/7489
* https://github.com/rancher/rke2/issues/7467
```release-note
```
> Update snapshot controller and remove snapshot validation webhook

- Dockerfile
Bump runc
version bump
check runc version
* https://github.com/rancher/rke2/issues/7506
```release-note
```
> Bump runc to v1.2.4

- charts/chart_versions.yaml
- scripts/build-images
Backport: 
* https://github.com/rancher/rke2/pull/7443
* https://github.com/rancher/rke2/pull/7508
Issues: 
* https://github.com/rancher/rke2/issues/7521
* https://github.com/rancher/rke2/issues/7517
> [release-1.32] Update to Cilium `v1.16.5`

- charts/chart_versions.yaml
- scripts/build-images
Backport: 
* https://github.com/rancher/rke2/pull/7443
* https://github.com/rancher/rke2/pull/7508
Issues: 
* https://github.com/rancher/rke2/issues/7522
* https://github.com/rancher/rke2/issues/7518
> [release-1.31] Update to Cilium `v1.16.5`

- charts/chart_versions.yaml
- scripts/build-images
Backport: 
* https://github.com/rancher/rke2/pull/7443
* https://github.com/rancher/rke2/pull/7508
Issues: 
* https://github.com/rancher/rke2/issues/7523
* https://github.com/rancher/rke2/issues/7519
> [release-1.30] Update to Cilium `v1.16.5`

- charts/chart_versions.yaml
- scripts/build-images
Backport: 
* https://github.com/rancher/rke2/pull/7443
* https://github.com/rancher/rke2/pull/7508
Issues: 
* https://github.com/rancher/rke2/issues/7524
* https://github.com/rancher/rke2/issues/7520
> [release-1.29] Update to Cilium `v1.16.5`

- charts/chart_versions.yaml
Update the Calico chart with the fix for IP autodetection in case of IPv6 only node.
#7454
```release-note
```
> Updated calico chart to fix IP autodetect in case of IPv6 only

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7483
```release-note
```
> feat: bump harvester-cloud-provider to v0.2.9

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7487
```release-note
```
> [release-1.32] feat: bump harvester-cloud-provider to v0.2.9

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7486
```release-note
```
> [release-1.31] feat: bump harvester-cloud-provider to v0.2.9

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7485
```release-note
```
> [release-1.30] feat: bump harvester-cloud-provider to v0.2.9

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7484
```release-note
```
> [release-1.29] feat: bump harvester-cloud-provider to v0.2.9

- charts/chart_versions.yaml
Backport for #7530
Issue #7531
> [Release 1.32] Updated calico chart to fix IP autodetect in case of IPv6 only

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/issues/7539
Issue: https://github.com/rancher/rke2/issues/7545
> [release-1.32] Update metrics-server to `3.2.12`

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/issues/7539
Issue: https://github.com/rancher/rke2/issues/7546
> [release-1.31] Update metrics-server to `3.2.12`

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/issues/7539
Issue: https://github.com/rancher/rke2/issues/7548
> [release-1.29] Update metrics-server to `3.2.12`

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7542
Issue: https://github.com/rancher/rke2/issues/7562
> [release-1.32] Update canal to `v3.29.1-build2025011000`

- .github/workflows/release.yml
Add an automatic release trigger for RKE2's downstream components:
- [rke2-upgrade](https://github.com/rancher/rke2-upgrade)
- [system-agent-installer-rke2](https://github.com/rancher/system-agent-installer-rke2)
New feature:
- A new step will be appended to `release.yml` workflow
https://github.com/rancher/rke2/issues/7592
```release-note
```
> Add Release downstream components in release workflow

- Dockerfile
- charts/build-chart.sh
- charts/build-charts.sh
- charts/chart_versions.yaml
- go.mod
- go.sum
- pkg/cli/cmds/cert.go
- pkg/staticpod/staticpod.go
- scripts/build-images
- scripts/validate-charts
- tests/docker/test-run-basics
Updates k3s: https://github.com/k3s-io/k3s/compare/68fbd1a6b543...0b414715af20e6173c39ceae6c7676266cf1d7e8
Backports:
* https://github.com/rancher/rke2/pull/7488
* https://github.com/rancher/rke2/pull/7507
* https://github.com/rancher/rke2/pull/7423
backports
see linked issues
* https://github.com/rancher/rke2/issues/7513
* https://github.com/rancher/rke2/issues/7509
* https://github.com/rancher/rke2/issues/7583
```release-note
```
> [release-1.32] Backports for 2025-01

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7555
```release-note
```
> [Release-1.30] Bump ingress-nginx v1.12.0

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7556
```release-note
```
> [Release-1.31] Bump ingress-nginx v1.12.0

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7557
```release-note
```
> [Release-1.32] Bump ingress-nginx v1.12.0

- Dockerfile
- Dockerfile.windows
- charts/chart_versions.yaml
- scripts/build-images
- Bump ingress-nginx to v1.12.0-hardened1
- Bump ingress-nginx-kube-webhook-certgen to v1.5.0
Dependency bump
https://github.com/rancher/rke2/issues/7549
```release-note
```
> Bump ingress-nginx v1.12.0

- .github/workflows/test-suite.yaml
- go.mod
- go.sum
- tests/e2e/splitserver/splitserver_test.go
- tests/e2e/testutils.go
- tests/integration/etcdsnapshot/etcd_int_test.go
- tests/integration/integration.go
- tests/integration/startup/startup_test.go
Updates k3s: https://github.com/k3s-io/k3s/compare/646e3135bc9f...d0ea741b138fbee71aa0fe041b79da1416a7b617
Add e2e framework enhancements and integration test for bind-address flag
bugfix, tests
tests
yes
```release-note
```
> Bump k3s version for master and add/enhance tests

- .github/workflows/test-suite.yaml
- go.mod
- go.sum
- tests/e2e/splitserver/splitserver_test.go
- tests/e2e/testutils.go
- tests/integration/etcdsnapshot/etcd_int_test.go
- tests/integration/integration.go
- tests/integration/startup/startup_test.go
Updates k3s: https://github.com/k3s-io/k3s/compare/0b414715af20...9548f9b6c95290d0b9e5410d41d74d578182c24c
Add e2e framework enhancements and integration test for bind-address flag
bugfix, tests
tests
yes
```release-note
```
> [release-1.32] Bump k3s version for master and add/enhance tests

- charts/chart_versions.yaml
- scripts/build-images
```
rancher/nginx-ingress-controller:v1.12.0-hardened2 (suse linux enterprise server 15.6)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
https://github.com/rancher/rke2/issues/7549
```release-note
```
> Bump ingress-nginx to v1.12.0-hardened2

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7557
```release-note
```
> [Release-1.32] Bump ingress-nginx to v1.12.0-hardened2

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7554
```release-note
```
> [Release-1.29] Bump ingress-nginx to v1.12.0-hardened2

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7555
```release-note
```
> [Release-1.30] Bump ingress-nginx to v1.12.0-hardened2

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7556
```release-note
```
> [Release-1.31] Bump ingress-nginx to v1.12.0-hardened2

- charts/chart_versions.yaml
Bump rke2-ingress-nginx chart for defaultbackend fix
bugfix
* https://github.com/rancher/rke2/issues/7652
```release-note
```
> Bump rke2-ingress-nginx chart for defaultbackend fix

- charts/chart_versions.yaml
https://github.com/rancher/rke2/issues/7672
```release-note
```
> [release-1.29] charts: bump Harvester CSI Driver v0.1.23

- charts/chart_versions.yaml
https://github.com/rancher/rke2/issues/7673
```release-note
```
> [release-1.30] charts: bump Harvester CSI Driver v0.1.23

- charts/chart_versions.yaml
https://github.com/rancher/rke2/issues/7674
```release-note
```
> [release-1.31] charts: bump Harvester CSI Driver v0.1.23

- charts/chart_versions.yaml
https://github.com/rancher/rke2/issues/7675
```release-note
```
> [release-1.32] charts: bump Harvester CSI Driver v0.1.23

- charts/chart_versions.yaml
https://github.com/rancher/rke2/issues/7671
```release-note
```
> charts: bump Harvester CSI Driver v0.1.23

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7663
Issue: https://github.com/rancher/rke2/issues/7678
> [release-1.30] Update to cilium `v1.16.6`

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7663
Issue: https://github.com/rancher/rke2/issues/7677
> [release-1.31] Update to cilium `v1.16.6`

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7663
Issue: https://github.com/rancher/rke2/issues/7676
> [release-1.32] Update to cilium `v1.16.6`

- charts/chart_versions.yaml
- scripts/build-images
Update Cilium to latest `v1.17.0` version
#7697
```release-note
```
> Update cilium to `v1.17.0`

- charts/chart_versions.yaml
- scripts/build-images
Backport for #7698
Issue #7699
> [Release 1.32] Update cilium to v1.17.0

- charts/chart_versions.yaml
- scripts/build-images
> [Release 1.31] Update cilium to v1.17.0

- charts/chart_versions.yaml
- scripts/build-images
> [Release 1.30] Update cilium to v1.17.0

- charts/chart_versions.yaml
- scripts/build-images
> [Release 1.29] Update cilium to v1.17.0

- charts/chart_versions.yaml
- updatecli/updatecli.d/vsphere-cpi.yml
- updatecli/updatecli.d/vsphere-csi.yml
> Bump vsphere CSI to v3.3.1-rancher9

- charts/chart_versions.yaml
> [Release-1.29] Bump vsphere CSI to v3.3.1-rancher9

- charts/chart_versions.yaml
> [Release-1.32] Bump vsphere CSI to v3.3.1-rancher9

- charts/chart_versions.yaml
> [Release-1.30] Bump vsphere CSI to v3.3.1-rancher9

- charts/chart_versions.yaml
> [Release-1.31] Bump vsphere CSI to v3.3.1-rancher9

- charts/chart_versions.yaml
- scripts/build-images
Backport https://github.com/rancher/rke2/pull/7770
https://github.com/rancher/rke2/issues/7780
```release-note
```
> [Release-1.30] Bump ingress-nginx to v1.12.0-hardened6

- charts/chart_versions.yaml
- scripts/build-images
Backport https://github.com/rancher/rke2/pull/7770
https://github.com/rancher/rke2/issues/7779
```release-note
```
> [Release-1.31] Bump ingress-nginx to v1.12.0-hardened6

- charts/chart_versions.yaml
- scripts/build-images
Backport https://github.com/rancher/rke2/pull/7770
Dependency Bump
CI Green
https://github.com/rancher/rke2/issues/7778
```release-note
```
> [Release-1.32] Bump ingress-nginx to v1.12.0-hardened6

- charts/chart_versions.yaml
- scripts/build-images
Bump for the base image only:
- rancher/hardened-calico:v3.29.2-build20250218
- rancher/hardened-flannel:v0.26.4-build20250218
> [chore] Bump canal and flannel images to build20250218

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7772
Issue: https://github.com/rancher/rke2/issues/7783
> [release-1.32] Bump canal and flannel images to build20250218

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7772
Issue: https://github.com/rancher/rke2/issues/7784
> [release-1.31] Bump canal and flannel images to build20250218

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7772
Issue: https://github.com/rancher/rke2/issues/7785
> [release-1.30] Bump canal and flannel images to build20250218

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7772
Issue: https://github.com/rancher/rke2/issues/7786
> [release-1.29] Bump canal and flannel images to build20250218

- charts/chart_versions.yaml
- scripts/build-images
Update to cilium `v1.17.1`
Linked Issue: https://github.com/rancher/rke2/issues/7825
> Update to cilium `v1.17.1`

- Dockerfile
- Dockerfile.windows
Bump to containerd v2.0.3/runc v1.2.5
version bump / bugfix
* https://github.com/rancher/rke2/issues/7827
```release-note
```
> Bump to containerd v2.0.3/runc v1.2.5

- charts/chart_versions.yaml
Issue: https://github.com/rancher/rke2/issues/7840
> Bump coredns to v1.39.100

- charts/chart_versions.yaml
- scripts/build-images
`/opt/cni/bin` should include bond binary.
#7855
```release-note
```
> Update multus with new CNI plugin image with bond included

- charts/chart_versions.yaml
> [Release-1.30] Bump coredns to v1.39.100

- charts/chart_versions.yaml
- scripts/build-images
Backport #7856
Issue [#7863](https://github.com/rancher/rke2/issues/7863)
> [Release 1.30] Update multus with new CNI plugin image with bond included

- charts/chart_versions.yaml
- scripts/build-images
Backport #7856
Issue [#7861](https://github.com/rancher/rke2/issues/7861)
> [Release 1.32] Update multus with new CNI plugin image with bond included

- charts/chart_versions.yaml
- scripts/build-images
Backport #7856
Issue [#7862](https://github.com/rancher/rke2/issues/7862)
> [Release 1.31] Update multus with new CNI plugin image with bond included

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7826
Issue: https://github.com/rancher/rke2/issues/7846
> [Release-1.32] Update to cilium `v1.17.1`

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7826
Issue: https://github.com/rancher/rke2/issues/7847
> [Release-1.31] Update to cilium `v1.17.1`

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/7826
Issue: https://github.com/rancher/rke2/issues/7848
> [Release-1.30] Update to cilium `v1.17.1`

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7884
```release-note
```
> [Release-1.29] Bump ingress-nginx to hardened10

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7882
```release-note
```
> [Release-1.31] Bump ingress-nginx to hardened10

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7881
```release-note
```
> [Release-1.32] Bump ingress-nginx to hardened10

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/7880
```release-note
```
> chore: Bump ingress-nginx to hardened10

- go.mod
- go.sum
- pkg/cli/cmds/server.go
- scripts/build-images
Updates k3s: https://github.com/k3s-io/k3s/compare/f710d4900ce9...3ce7ca7544a78abe82c3ae1b0f975fbbcd5e869e
K3s bump
* https://github.com/rancher/rke2/issues/7894
```release-note
```
> Bump K3s version for master

- charts/chart_versions.yaml
- scripts/build-images
Bump ingress-nginx to latest version v1.12.1-hardened1 to address CVEs
Component bump
https://github.com/rancher/rke2/issues/7953
```release-note
```
> [chore] Bump ingress-nginx to v1.12.1-hardened1, chart to 4.12.1

- charts/chart_versions.yaml
- scripts/build-images
Backport of https://github.com/rancher/rke2/pull/7958
https://github.com/rancher/rke2/issues/7955
```release-note
```
> [Release-1.31] Bump ingress-nginx to v1.12.1-hardened1, chart to 4.12.1

- charts/chart_versions.yaml
- scripts/build-images
Backport of https://github.com/rancher/rke2/pull/7958
https://github.com/rancher/rke2/issues/7954
```release-note
```
> [Release-1.32] Bump ingress-nginx to v1.12.1-hardened1, chart to 4.12.1

- channels.yaml
> Update stable channel

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/7986
Backport: https://github.com/rancher/rke2/pull/7965
> [Release 1.32] Bump multus version

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/7987
Backport: https://github.com/rancher/rke2/pull/7965
> [Release 1.31] Bump multus version

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/7988
Backport: https://github.com/rancher/rke2/pull/7965
> [Release 1.30] Bump multus version

- charts/chart_versions.yaml
- scripts/build-images
Issue: https://github.com/rancher/rke2/issues/7964
Bump whereabouts to v0.9.0 and multus to v4.2.001
Chart version bump
> Bump whereabouts chart to v0.9.0

- charts/chart_versions.yaml
- scripts/build-images
> [Release-1.30] Bump whereabouts to v0.9.0

- charts/chart_versions.yaml
- scripts/build-images
> [Release-1.32] Bump whereabouts to v0.9.0

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8000
Issue: https://github.com/rancher/rke2/issues/8009
> [Release-1.30] Update to coredns `1.39.201`

- charts/chart_versions.yaml
- scripts/build-images
Bump traefik image to v3.3.5
version bump
check version
* https://github.com/rancher/rke2/issues/8015
```release-note
```
> Bump traefik image to v3.3.5

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8000
Issue: https://github.com/rancher/rke2/issues/8031
> [Release-1.29] Update to coredns 1.39.201

- charts/chart_versions.yaml
- scripts/build-images
Update to the latest image:
- rancher/hardened-flannel:v0.26.6-build20250414
Issue: https://github.com/rancher/rke2/issues/8043
Depends:
> Update to flannel `v0.26.601` and canal `v3.29.3-build2025040801`

- charts/chart_versions.yaml
- scripts/build-images
New ingress-nginx image bump
https://github.com/rancher/rke2/issues/8049
```release-note
```
> chore: Bump nginx to v1.12.1-hardened3

- charts/chart_versions.yaml
- scripts/build-images
Backport of https://github.com/rancher/rke2/pull/8055
https://github.com/rancher/rke2/issues/8050
```release-note
```
> [Release-1.32] chore: Bump nginx to v1.12.1-hardened3

- charts/chart_versions.yaml
- scripts/build-images
Backport of https://github.com/rancher/rke2/pull/8055
https://github.com/rancher/rke2/issues/8051
```release-note
```
> [Release-1.31] chore: Bump nginx to v1.12.1-hardened3

- charts/chart_versions.yaml
- scripts/build-images
Backport of https://github.com/rancher/rke2/pull/8055
https://github.com/rancher/rke2/issues/8052
```release-note
```
> [Release-1.30] chore: Bump nginx to v1.12.1-hardened3

- charts/chart_versions.yaml
- scripts/build-images
Backport of https://github.com/rancher/rke2/pull/8055
https://github.com/rancher/rke2/issues/8053
```release-note
```
> [Release-1.29] chore: Bump nginx to v1.12.1-hardened3

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8044
Issue: https://github.com/rancher/rke2/issues/8046
> [Release-1.31] Update to flannel v0.26.601 and canal v3.29.3-build2025040801

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8044
Issue: https://github.com/rancher/rke2/issues/8047
> [Release-1.30] Update to flannel v0.26.601 and canal v3.29.3-build2025040801

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8044
Issue: https://github.com/rancher/rke2/issues/8048
> [Release-1.29] Update to flannel v0.26.601 and canal v3.29.3-build2025040801

- charts/chart_versions.yaml
- scripts/build-images
Update to cilium `v1.17.3`
Linked Issue: https://github.com/rancher/rke2/issues/8074
Depends:
> Update to cilium `v1.17.3`

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8075
Issue: https://github.com/rancher/rke2/issues/8079
> [Release-1.32] Update to cilium `v1.17.3`

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8075
Issue: https://github.com/rancher/rke2/issues/8080
> [Release-1.31] Update to cilium `v1.17.3`

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8075
Issue: https://github.com/rancher/rke2/issues/8081
> [Release-1.30] Update to cilium `v1.17.3`

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8075
Issue: https://github.com/rancher/rke2/issues/8082
> [Release-1.29] Update to cilium `v1.17.3`

- charts/chart_versions.yaml
- scripts/build-images
Bump traefik to v3.3.6
* https://github.com/traefik/traefik/security/advisories/GHSA-5423-jcjm-2gpv
version bump
check version
* https://github.com/rancher/rke2/issues/8015
```release-note
```
> Bump traefik to v3.3.6

- charts/build-charts.sh
- charts/chart_versions.yaml
- scripts/build-images
Bump traefik to v2.11.24
* https://github.com/traefik/traefik/security/advisories/GHSA-5423-jcjm-2gpv
version bump
check version
* https://github.com/rancher/rke2/issues/8111
```release-note
```
> [release-1.31] Bump traefik to v2.11.24

- channels.yaml
> Update stable channel `v1.31.8`

- channels.yaml
Adds `v1.33` as a install channel
Releases
```release-note
```
> Add v1.33 channel

- charts/chart_versions.yaml
Bump harvester-cloud-provider to 0.2.10.
https://github.com/harvester/harvester/issues/8204, https://github.com/rancher/dashboard/issues/14264
* https://github.com/rancher/rke2/issues/8154
```release-note
```
> feat: bump harvester-cloud-provider to v0.2.10

- .github/workflows/pr.yml
- .github/workflows/test-suite.yaml
- tests/docker/basics/basics_test.go
- tests/docker/secretsencryption/secretsencryption_test.go
- tests/docker/splitserver/splitserver_test.go
- tests/docker/test-helpers.go
* Collect logs on docker test failure
* Load br_netfilter module for flannel before running docker tests
CI
Check CI logs
yes
```release-note
```
> Fix docker tests

- charts/chart_versions.yaml
Bump harvester-cloud-provider v0.2.10.
* https://github.com/harvester/harvester/issues/8204
* https://github.com/rancher/dashboard/issues/14264
* https://github.com/rancher/rke2/issues/8155
```release-note
```
> [release-1.33] feat: bump harvester-cloud-provider to v0.2.10

- charts/chart_versions.yaml
Bump harvester-cloud-provider v0.2.10.
* https://github.com/harvester/harvester/issues/8204
* https://github.com/rancher/dashboard/issues/14264
* https://github.com/rancher/rke2/issues/8156
```release-note
```
> [release-1.32] feat: bump harvester-cloud-provider to v0.2.10

- charts/chart_versions.yaml
Bump harvester-cloud-provider v0.2.10.
* https://github.com/harvester/harvester/issues/8204
* https://github.com/rancher/dashboard/issues/14264
* https://github.com/rancher/rke2/issues/8157
```release-note
```
> [release-1.31] feat: bump harvester-cloud-provider to v0.2.10

- charts/chart_versions.yaml
Bump harvester-cloud-provider v0.2.10.
* https://github.com/harvester/harvester/issues/8204
* https://github.com/rancher/dashboard/issues/14264
* https://github.com/rancher/rke2/issues/8158
```release-note
```
> [release-1.30] feat: bump harvester-cloud-provider to v0.2.10

- charts/chart_versions.yaml
- scripts/build-images
> [master] Bump nginx version

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.33] Bump nginx version

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.32] Bump nginx version

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.31] Bump nginx version

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.30] Bump nginx version

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8164
Issue: https://github.com/rancher/rke2/issues/8206
> [Release-1.33] Update to Kubernetes Metrics Server 3.12.201

- charts/chart_versions.yaml
- scripts/build-images
Bump to the latest hardened-cni-plugins:v1.7.1-build20250509
Issue: https://github.com/rancher/rke2/issues/8167
> Update cilium and multus to cni-plugins v1.7.1

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8168
Issue: https://github.com/rancher/rke2/issues/8222
> [Release-1.33] Update cilium and multus to cni-plugins v1.7.1

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8168
Issue: https://github.com/rancher/rke2/issues/8223
> [Release-1.32] Update cilium and multus to cni-plugins v1.7.1

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8168
Issue: https://github.com/rancher/rke2/issues/8224
> [Release-1.31] Update cilium and multus to cni-plugins v1.7.1

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8168
Issue: https://github.com/rancher/rke2/issues/8225
> [Release-1.30] Update cilium and multus to cni-plugins v1.7.1

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.30] Upgrade nginx chart

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.31] Upgrade nginx chart

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.33] Upgrade nginx chart

- charts/chart_versions.yaml
- scripts/build-images
> [release-1.32] Upgrade nginx chart

- charts/chart_versions.yaml
- scripts/build-images
Update to the latest images:
- rancher/hardened-calico:v3.30.0-build20250515
- rancher/hardened-flannel:v0.26.7-build20250515
Issue: https://github.com/rancher/rke2/issues/8237
> Update to flannel v0.26.701 and canal v3.30.0-build2025051500

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8238
Issue: https://github.com/rancher/rke2/issues/8253
> [Release-1.33] Update to flannel v0.26.701 and canal v3.30.0-build2025051500

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8238
Issue: https://github.com/rancher/rke2/issues/8254
> [Release-1.32] Update to flannel v0.26.701 and canal v3.30.0-build2025051500

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8238
Issue: https://github.com/rancher/rke2/issues/8255
> [Release-1.31] Update to flannel v0.26.701 and canal v3.30.0-build2025051500

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8238
Issue: https://github.com/rancher/rke2/issues/8256
> [Release-1.30] Update to flannel v0.26.701 and canal v3.30.0-build2025051500

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8239
Issue: https://github.com/rancher/rke2/issues/8261
> [Release-1.33] Update to CoreDNS 1.42.000

- .github/workflows/release.yml
> Fix secrets syntax

- .github/workflows/release.yml
> [release-1.30] Fix secrets syntax

- .github/workflows/release.yml
> [release-1.31] Fix secrets syntax

- .github/workflows/release.yml
> [release-1.32] Fix secrets syntax

- .github/workflows/release.yml
> [release-1.33] Fix secrets syntax

- bundle/bin/rke2-uninstall.ps1
Issue: https://github.com/rancher/rke2/issues/8338
Backport: https://github.com/rancher/rke2/pull/8147
> [Release 1.32] Windows: Allow for silent/non confirmation use of uninstall.ps1

- bundle/bin/rke2-uninstall.ps1
Issue: https://github.com/rancher/rke2/issues/8339
Backport: https://github.com/rancher/rke2/pull/8147
> [Release 1.31] Windows: Allow for silent/non confirmation use of uninstall.ps1

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8359
Issue: https://github.com/rancher/rke2/issues/8327
> [Release-1.33] Bump canal, flannel and cilium charts (#8359)

- charts/chart_versions.yaml
- scripts/build-images
> [Release-1.31] Bump multus and whereabouts (#8360)

- charts/chart_versions.yaml
- scripts/build-images
> [Release-1.33] Bump multus and whereabouts (#8360)

- .github/workflows/test-suite.yaml
- pkg/cli/cmds/profile_linux.go
- pkg/cli/cmds/root.go
- pkg/podexecutor/spw.go
- pkg/podexecutor/staticpod.go
- pkg/rke2/rke2.go
- pkg/rke2/rke2_linux.go
- tests/docker/profile/profile_test.go
Backport of #8349
New feature
https://github.com/rancher/rke2/issues/8375
```release-note
```
> [Release-1.30] Support profile: etcd

- .github/workflows/test-suite.yaml
- pkg/cli/cmds/profile_linux.go
- pkg/cli/cmds/root.go
- pkg/podexecutor/spw.go
- pkg/podexecutor/staticpod.go
- pkg/rke2/rke2.go
- pkg/rke2/rke2_linux.go
- tests/docker/basics/basics_test.go
- tests/docker/profile/profile_test.go
- tests/docker/secretsencryption/secretsencryption_test.go
- tests/docker/splitserver/splitserver_test.go
- tests/docker/testutils.go
Backport of #8349
New feature
https://github.com/rancher/rke2/issues/8373
```release-note
```
> [Release-1.32] Support profile: etcd

- bundle/bin/rke2-uninstall.sh
- charts/build-chart.sh
- go.mod
- go.sum
- pkg/rke2/clusterrole_bootstrap.go
- scripts/build-binary
- scripts/build-windows-binary
Updates k3s: https://github.com/k3s-io/k3s/compare/c484dbdf421a...c484dbdf421a0b5356b8fc16888859045ed882d2
Backports:
* https://github.com/rancher/rke2/pull/8416
* https://github.com/rancher/rke2/pull/8287
backports
see linked issues
* https://github.com/rancher/rke2/issues/8307
* https://github.com/rancher/rke2/issues/8191
* https://github.com/rancher/rke2/issues/8378
```release-note
```
> [release-1.33] Backports for 2025-06

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/8306
```release-note
```
> Bump ingress-nginx to v1.12.2-hardened2

- go.mod
- go.sum
- scripts/build-images
Updates k3s: https://github.com/k3s-io/k3s/compare/c484dbdf421a...4256d5813c74e1f75ea49c0596e0fdcb181798cc
Bump k3s for helm-controller
version bump
Check helm-controller and klipper-helm
* 
```release-note
```
> [release-1.33] Bump K3s version

- go.mod
- go.sum
- scripts/build-images
Updates k3s: https://github.com/k3s-io/k3s/compare/7ce96aa080b2...7a7331f25f41c51870e284b9ea36c437b80c0987
Bump k3s for helm-controller
version bump
Check helm-controller and klipper-helm
* 
```release-note
```
> [release-1.32] Bump K3s version

- go.mod
- go.sum
- scripts/build-images
Updates k3s: https://github.com/k3s-io/k3s/compare/5f094d699a1c...60862b9d4bc84da0ef2bc336d9fc9adcec23c9e1
Bump k3s for helm-controller
version bump
Check helm-controller and klipper-helm
* 
```release-note
```
> [release-1.31] Bump K3s version

- charts/chart_versions.yaml
- scripts/build-images
> Update Canal chart to latest version

- charts/chart_versions.yaml
- scripts/build-images
> [Release 1.32] Update Canal chart to latest version

- charts/chart_versions.yaml
- scripts/build-images
> [Release 1.31] Update Canal chart to latest version

- go.mod
- go.sum
- pkg/cli/cmds/completion.go
- better structure for shell completion command, this new structure for this command is to avoid unnecessary problems specially related to verify input from the user (this was caused by the urfave cli v2 bump, that the cli cannot get flags after the first argument from the input, so for the rke2 completion works before this update is `rke2 completion --kubectl bash` and not `rke2 completion bash --kubectl`)
```bash
rke2 completion --help
```
```bash
rke2 completion bash --help
```
```bash
rke2 completion zsh --help
```
- Fix
- you can see that the two of them are separated commands by
```bash
rke2 completion --help
```
- the verification to test if it's working as expected is install the completion, tab tab to see the completion working,  run `rke2 server` and see if the exports variables …
> Change structure and set namespace for ctr command

- charts/chart_versions.yaml
- scripts/build-images
> [Release-1.30] Bump multus and whereabouts chart

- charts/chart_versions.yaml
- scripts/build-images
> [Release-1.31] Bump multus and whereabouts chart

- charts/chart_versions.yaml
- scripts/build-images
- Ingress-nginx bump
Dependency bump
https://github.com/rancher/rke2/issues/8549
```release-note
```
> Bump ingress-nginx to v1.12.4-hardened1

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8518
Issue: https://github.com/rancher/rke2/issues/8551
> [Release-1.33] Update Kubernetes Metrics Server chart 3.12.203

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/8567
```release-note
```
> [Release-1.30] Bump ingress-nginx to v1.12.4-hardened1

- charts/chart_versions.yaml
- scripts/build-images
Chart bump for ingress-nginx
Dependency
https://github.com/rancher/rke2/issues/8566
```release-note
```
> [Release-1.31] Bump ingress-nginx to v1.12.4-hardened1

- charts/chart_versions.yaml
- scripts/build-images
Chart bump for ingress-nginx
Dependency
https://github.com/rancher/rke2/issues/8565
```release-note
```
> [Release-1.32] Bump ingress-nginx to v1.12.4-hardened1

- charts/chart_versions.yaml
- scripts/build-images
Bump Harvester CSI driver 0.1.24
New Feature and Bug Fixes
https://github.com/harvester/harvester/issues/8616
```release-note
- Support online resize
- Support external storage
```
> [release-1.30] charts: Bump Harvester CSI driver 0.1.24

- charts/chart_versions.yaml
- scripts/build-images
Bump Harvester CSI driver 0.1.24
New Feature and Bug Fixes
https://github.com/harvester/harvester/issues/8616
```release-note
- Support online resize
- Support external storage
```
> [release-1.31] charts: Bump Harvester CSI driver 0.1.24

- charts/chart_versions.yaml
- scripts/build-images
Bump Harvester CSI driver 0.1.24
New Feature and Bug Fixes
https://github.com/harvester/harvester/issues/8616
```release-note
- Support online resize
- Support external storage
```
> [release-1.33] charts: Bump Harvester CSI driver 0.1.24

- charts/chart_versions.yaml
- scripts/build-images
- image version v0.2.3
Bump Harvester CSI driver 0.1.24
New Feature and Bug Fixes
https://github.com/harvester/harvester/issues/8616
https://github.com/rancher/rke2/issues/8508
```release-note
- Support online resize
- Support external storage
```
> charts: Bump Harvester CSI driver 0.1.24

- bundle/bin/rke2-uninstall.sh
Backport https://github.com/rancher/rke2/pull/8572
https://github.com/rancher/rke2/issues/8583
```release-note
```
> [Release-1.32] Allow for zypper remove 104 code on uninstall

- bundle/bin/rke2-uninstall.sh
Backport https://github.com/rancher/rke2/pull/8572
https://github.com/rancher/rke2/issues/8582
```release-note
```
> [Release-1.33] Allow for zypper remove 104 code on uninstall

- bundle/bin/rke2-uninstall.sh
Backport https://github.com/rancher/rke2/pull/8572
https://github.com/rancher/rke2/issues/8585
```release-note
```
> [Release-1.30] Allow for zypper remove 104 code on uninstall

- bundle/bin/rke2-uninstall.sh
Backport https://github.com/rancher/rke2/pull/8572
https://github.com/rancher/rke2/issues/8584
```release-note
```
> [Release-1.31] Allow for zypper remove 104 code on uninstall

- charts/chart_versions.yaml
Fix an issue that affects RKE2 upgrades.
RKE2 upgrades that involve upgrading _rke2-snapshot-controller_ and _rke2-snapshot-controller-crd_ from version **3.0.601** to **4.0.002** could potentially lead to the deletion of Custom Resources.
Bugfix
I validated this by installing RKE2 1.31.2 and upgrading it to 1.32 (built from source). 
https://github.com/rancher/rke2/issues/8576
```release-note
NONE
```
> Fix snapshot controller backwards compatibility

- charts/chart_versions.yaml
Backport from:
- https://github.com/rancher/rke2/pull/8586
Issue:
- https://github.com/rancher/rke2/issues/8587
> [Release 1.33] - Fix snapshot controller backwards compatibility

- charts/chart_versions.yaml
Backport from: 
- https://github.com/rancher/rke2/pull/8586
Issue: 
- https://github.com/rancher/rke2/issues/8589
> [Release 1.31] - Fix snapshot controller backwards compatibility

- charts/chart_versions.yaml
Backport from: 
- https://github.com/rancher/rke2/pull/8586
Issue: 
- https://github.com/rancher/rke2/issues/8590
> [Release 1.30] - Fix snapshot controller backwards compatibility

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/8566
```release-note
```
> [Release-1.31] Bump ingress-nginx to hardened2

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/8567
```release-note
```
> [Release-1.30] Bump ingress-nginx to hardened2

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/8564
```release-note
```
> [Release-1.33] Bump ingress-nginx to hardened2

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8637
Issue: https://github.com/rancher/rke2/issues/8639
> [Release-1.33] Update to cilium `v1.17.6`

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8637
Issue: https://github.com/rancher/rke2/issues/8642
> [Release-1.30] Update to cilium `v1.17.6`

- .github/workflows/unittest.yaml
- pkg/windows/utils.go
- pkg/windows/utils_test.go
---------
(cherry picked from commit 86d1555815e8c53e8a41222f0fce43d454268621)
```release-note
```
> Add.utils test (#8651) - backport 1.33

- charts/chart_versions.yaml
Bump Rancher CSI chart
https://github.com/rancher/rke2/issues/8614
```release-note
```
> [Release-1.30] Bump rancher vsphere csi to 3.3.1-rancher10

- charts/chart_versions.yaml
- scripts/build-images
Also update cni-plugins to `v1.7.1-build20250725`
Issue: https://github.com/rancher/rke2/issues/8697
> Update to cilium v1.18.000

- charts/chart_versions.yaml
Issue: #8722 ; Backport: #8707
> [Release-1.32] Bump rke2-coredns to 1.43.100

- charts/chart_versions.yaml
> [Release-1.33] Bump rke2-coredns to 1.43.100

- charts/chart_versions.yaml
- scripts/build-images
https://github.com/rancher/rke2/issues/8728
```release-note
```
> [Release-1.32] Bump ingress-nginx to v1.12.4-hardened6

- charts/chart_versions.yaml
Backport: https://github.com/rancher/rke2/pull/8700
Issue: https://github.com/rancher/rke2/issues/8737
> [Release-1.33] Update Kubernetes Metrics Server chart 3.13.000

- main.go
- pkg/cli/cmds/root.go
- pkg/cli/cmds/server.go
- pkg/cli/types.go
- pkg/controllers/types.go
- pkg/executor/pebinary/pebinary.go
- pkg/executor/staticpod/cleanup.go
- pkg/executor/staticpod/command_linux.go
- pkg/executor/staticpod/command_other.go
- pkg/executor/staticpod/spw.go
- pkg/executor/staticpod/staticpod.go
- pkg/podtemplate/config.go
- pkg/podtemplate/podtemplate.go
- pkg/podtemplate/spec.go
- pkg/podtemplate/types.go
- pkg/podtemplate/utils.go
- pkg/rke2/rke2.go
- pkg/rke2/rke2_linux.go
- pkg/rke2/rke2_linux_test.go
- pkg/rke2/rke2_windows.go
- pkg/rke2/spc.go
* Backport: https://github.com/rancher/rke2/pull/8652
* Issue: https://github.com/rancher/rke2/issues/8676
> [release-1.31] Separate pod template generation and static pod execution code

- .github/workflows/release.yml
> [release-1.31] Add prime ribs index upload and cache invalidation

- .github/workflows/release.yml
> [release-1.32] Add prime ribs index upload and cache invalidation

- .github/workflows/release.yml
> [release-1.33] Add prime ribs index upload and cache invalidation

- .github/workflows/release.yml
> [master] Add prime ribs index upload and cache invalidation

- .github/workflows/release.yml
Release artifacts in this branch will be uploaded to the Prime artifacts repository, and not to GitHub release assets or to docker hub.
```release-note
```
> [release-1.30] Publish prime-only assets

- go.mod
- go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/ff6abe8a845f...3d4c2cf2cfd93b4bb4c918d3885272089341d798
* https://github.com/k3s-io/k3s/pull/12744
Version bump
```release-note
```
> Bump K3s version for certificate startup check fix

- go.mod
- go.sum
Updates k3s: https://github.com/k3s-io/k3s/compare/1e51c6dba051...ee389cb9d461f95ddf3548726781d92a0d09c749
* https://github.com/k3s-io/k3s/pull/12748
Version bump
```release-note
```
> [release-1.31] Bump K3s version for certificate startup check fix

- .github/workflows/release.yml
> [release-1.30] Fix missing ECM config

- .github/workflows/release.yml
> [master] Fix missing ECM config

- .github/workflows/release.yml
> [release-1.30] Fix uploader authentication

- .github/workflows/release.yml
> [release-1.31] Fix uploader authentication

- .github/workflows/release.yml
> [release-1.32] Fix uploader authentication

- .github/workflows/release.yml
> [master] Fix uploader authentication

- go.mod
- go.sum
Bump k3s, contains commits for https://github.com/k3s-io/k3s/pull/12760 and https://github.com/k3s-io/k3s/pull/12764
Dependency bump
N/A
```release-note
```
> [Release-1.33] Bump k3s for metric and event fixes

- go.mod
- go.sum
Bump k3s, contains commits for https://github.com/k3s-io/k3s/pull/12762 and https://github.com/k3s-io/k3s/pull/12766
Dependency bump
N/A
```release-note
```
> [Release-1.31] Bump k3s for metric and event fixes

- charts/chart_versions.yaml
- scripts/build-images
Backport of #8788
```release-note
```
> [Release-1.33] Bump ingress-nginx to hardened7 

- charts/chart_versions.yaml
- scripts/build-images
Backport of #8788
```release-note
```
> [Release-1.31] Bump ingress-nginx to hardened7 

- pkg/executor/staticpod/cleanup.go
* Backport https://github.com/rancher/rke2/pull/8805
* https://github.com/rancher/rke2/issues/8804
> [release-1.33] Fix static pod cleanup

- pkg/executor/staticpod/cleanup.go
* Backport https://github.com/rancher/rke2/pull/8805
* https://github.com/rancher/rke2/issues/8804
> [release-1.31] Fix static pod cleanup

- scripts/build-images
Added Calico new mirrored images.
#8304 #8621
```release-note
```
> Added Calico new images

- channels.yaml
> Update stable channel to `v1.32.8+rke2r1`

- scripts/build-images
> [Release 1.33] Added Calico new images

- scripts/build-images
> [Releae 1.32] Added Calico new images

- tests/e2e/cilium_wireguard/Vagrantfile
- tests/e2e/cilium_wireguard/ciliumwireguard_test.go
- tests/e2e/scripts/cilium_wireguard.sh
Just to align the tests with master
Backport #8753
Issue #8810
> [Release 1.33] Added Cilium with wireguard e2e tests

- tests/e2e/cilium_wireguard/Vagrantfile
- tests/e2e/cilium_wireguard/ciliumwireguard_test.go
- tests/e2e/scripts/cilium_wireguard.sh
Just to align the tests with master
Backport #8753
Issue #8811
> [Release 1.32] Added Cilium with wireguard e2e tests

- tests/e2e/cilium_wireguard/Vagrantfile
- tests/e2e/cilium_wireguard/ciliumwireguard_test.go
- tests/e2e/scripts/cilium_wireguard.sh
Just to align the tests with master
Backport #8753
Issue #8812
> [Release 1.31] Added Cilium with wireguard e2e tests

- charts/chart_versions.yaml
- scripts/build-images
- Bump ingress-nginx to new v1.12.6 patch.
```release-note
```
> [Chore] Bump ingress-nginx v1.12.6-hardened1

- charts/chart_versions.yaml
- scripts/build-images
Backport of https://github.com/rancher/rke2/pull/8861
> [Release-1.32] Bump ingress-nginx v1.12.6-hardened1 

- charts/chart_versions.yaml
- scripts/build-images
Bump latest version of the cni charts
#8878
```release-note
```
> Bump CNI chart latest version

- charts/chart_versions.yaml
- scripts/build-images
> [Release 1.31] Bump CNI chart latest version

- charts/chart_versions.yaml
- scripts/build-images
> [Release 1.33] Bump CNI chart latest version

- charts/chart_versions.yaml
- scripts/build-images
> [Release 1.34] Bump CNI chart latest version

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8892
Issue: https://github.com/rancher/rke2/issues/8900
> [Release-1.33] Update metrics-server chart 3.13.001

- charts/chart_versions.yaml
- scripts/build-images
Backport: https://github.com/rancher/rke2/pull/8892
Issue: https://github.com/rancher/rke2/issues/8901
> [Release-1.32] Update metrics-server chart 3.13.001

- charts/chart_versions.yaml
Bump vsphere charts
version bump for bugfix
Test deployment on vsphere
* https://github.com/rancher/rke2/issues/8934
```release-note
```
> Bump vsphere cpi chart

- channels.yaml
> [master] Add v1.34 channel

- charts/chart_versions.yaml
- scripts/build-images
backport PR of https://github.com/rancher/rke2/pull/8923
For rke2: https://github.com/rancher/rke2/issues/8933
Harvester:
https://github.com/harvester/harvester/issues/5670
https://github.com/harvester/harvester/issues/8072
harvester chart: https://github.com/harvester/charts/pull/413
```release-note
```
> [1.33] Bump harvester-cloud-provider chart to v0.2.11 with app image tag v0.2.5

- channels.yaml
> [master] Update stable channel to `v1.33.5+rke2r1`

- .github/workflows/test-suite.yaml
- charts/chart_versions.yaml
- scripts/build-images
- tests/docker/flannel/flannel_test.go
- tests/docker/resources/flannel.yaml
- tests/docker/traefik/traefik_test.go
Backports:
- https://github.com/rancher/rke2/pull/8466
- https://github.com/rancher/rke2/pull/8914
https://github.com/rancher/rke2/issues/8969
```release-note
```
> [Release-1.32] Update traefik to v3.5.1, use new hardened image

- .github/workflows/test-suite.yaml
- charts/chart_versions.yaml
- scripts/build-images
- tests/docker/traefik/traefik_test.go
Backports:
- https://github.com/rancher/rke2/pull/8914
https://github.com/rancher/rke2/issues/8967
```release-note
```
> [Release-1.34] Update traefik to v3.5.1, use new hardened image

- charts/chart_versions.yaml
- scripts/build-images
- ingress-nginx chart bump to new v1.13 minor line
https://github.com/rancher/rke2/issues/8992
```release-note
```
> Bump rke2-ingress-nginx to v1.13.3-hardened1

- charts/chart_versions.yaml
- scripts/build-images
- ingress-nginx chart bump to new v1.13 minor line
https://github.com/rancher/rke2/issues/8994
```release-note
```
> [Release-1.33] Bump rke2-ingress-nginx to v1.13.3-hardened1
