rancher/rke2

README.md
install.sh
pkg/bootstrap/stage.go

Add an installation script based off of the k3s install script and account for installing an rke2 and etcd user, updating permissions, etc. Side note, bash-isms have been removed for the closest I can get the script to posix compatible. I tested in dash and busybox so bash no longer is a requirement.

Add installation script

---

.gitignore
install.sh

Move symlink creation to after the server begins and expands the data directory as well updating .gitignore.

Resolve Symlink Issue in Issue 51

---

install.sh

Update includes setting kernel parameters as well as adjusting how users are created and accounted for in CIS mode and updates the service files for CIS mode.

Update extend install script

---

pkg/rke2/server.go

A situation arose where the code looking at the flag wasn't checking to see if there was actuall a value set and was creating false positives. This remediates issue #64 .

update flag value parse logic

---

README.md

Adds additional information about CIS mode for RKE2 and the installation script.

add additional information about CIS

---

install.sh

Make sure the redirect is done in the scope of sudo

use tee with sudo

---

install.sh

Suppresses the output from tee from being seen during the installation.

suppress tee output

---

install.sh

Remove hard coded file name in favor of the systemd env file variable.

use env var for systemd env file population

---

install.sh

Update quotes from double to single quotes.

update printf quotes

---

Dockerfile

Updates runtime image to use containerd 1.3.3 rather than 1.3.5.

downgrade containerd from 1.3.5 to 1.3.3

---

Dockerfile

Reverts runtime to original state.

revert runtime image build

---

README.md

initial wag at basic documentation around config file support with a basic example/sample

config file docs

---

install.sh

Adds missing kernel config param and resolves #128.

add kernel setting for vm.overcommit_memory=1

---

Dockerfile

Updates the containerd image to use the Rancher fork build.

update containerd in runtime

---

README.md

Contributes to: https://github.com/rancher/rke2/issues/118 and adds simple RPM repo usage instructions.

Update README.md for rpm instructions

---

README.md

Remove erroneous ` from readme
Contributes to https://github.com/rancher/rke2/issues/118

Remove erroneous ` from readme

---

pkg/cli/cmds/root.go
pkg/podexecutor/staticpod.go
pkg/rke2/server.go

https://github.com/rancher/rke2/issues/142

Add cloudprovider support to rke2

---

Makefile
pkg/images/images.go
scripts/airgap/generate-list.sh
scripts/airgap/image-list.txt
scripts/package-airgap

Add airgap support by enabling image preloading and package scripts in the make file
https://github.com/rancher/rke2/issues/140

Add airgap images to rke2 and preload support

---

pkg/podexecutor/staticpod.go
pkg/staticpod/staticpod.go

This PR remediates some additional CIS findings when ran with security-scan.
* Updated audit log limits for section 1.2.2x
* Updated file permissions to 0644 on pod manifests for section 1.1.1, 1.1.3, etc.

CIS Updates

---

.dockerignore

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

add build/images to dockerignore

---

go.mod
go.sum
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go

Depends on rancher/k3s#2111
Addresses rancher/rke2#156

cli: add --selinux flag to agent/server sub-cmds

---

Makefile
pkg/bootstrap/stage.go
scripts/airgap-images.sh
scripts/dev-shell-build
scripts/package-airgap
scripts/validate

Gzip tarballs.
Reduces size down to 852MB.

zip tarballs

---

Dockerfile

runtime: snag socat from the k3s image

---

go.mod
go.sum

Addresses coredns, flannel, and kube-proxy failing to start due to bad
tolerations in the helm install job.

bring in bumped k3s + helm-controller

---

BUILDING.md
Makefile
scripts/clean-cache
scripts/dev-shell-build
scripts/image

Describe how to build and run on arbitrary systems.

building: add BUILDING.md

---

.drone.yml
scripts/k8s-image

ci: fix trivy 'the input device is not a TTY'

---

.gitmodules
Makefile
scripts/package-airgap
scripts/package-bundle

Leverages https://github.com/rancher/rke2-packaging as a git submodule.

package: add tarball bundle to dist/artifacts

---

Vagrantfile

This demonstrates how to install on CentOS 7 via YUM.

vagrantfile: initial support for single vm

---

BUILDING.md

Be specific about which image tarballs to copy when testing air-gapped
vs non-air-gapped.

docs: fix BUILDING.md

---

pkg/images/images.go
scripts/build-images

Also adds comments to warn furture edits.

images: consistent versions for etcd

---

channels.yaml

In preparation for having a rke2 channel server, add channels.yaml
First half of: https://github.com/rancher/rke2/issues/242
Once this is merged, EIO will have to actually stand up the service, point it at this file, and put dns at it.

Add channels.yaml file

---

pkg/bootstrap/stage.go

issue : https://github.com/rancher/rke2/issues/244

fix bootstrap rename manifests error

---

go.mod
go.sum

Update RKE2 with latest k3s.
Verify new commit hash.
```sh
grep k3s go.mod
```

update to latest k3s master

---

pkg/cli/cmds/agent.go
pkg/cli/cmds/root.go
pkg/cli/cmds/server.go
pkg/cli/defaults/defaults.go
pkg/rke2/rke2.go

This PR encompasses the work defined in #206 
No testing necessary.
Rename function arg so not to overlap community convention for context.
#206

Update CLI Context Arg Name

---

pkg/bootstrap/stage.go

Remove arch from bootstrap image airgap tag
Bugfix
Needs airgap test
#248
Credit for fix thanks to @nikkelma

Remove GOARCH from preloaded bootstrap image tag

---

bundle/share/rke2/rke2.service
install.sh
scripts/build-binary

- Compile with selinux
- Remove `Type=notify` from the systemd unit file
- Require root to execute install script
This plus https://github.com/rancher/rke2-selinux/pull/5 should address #156

selinux: specify the build-tag

---

Dockerfile

add crictl

---

pkg/bootstrap/bootstrap.go
pkg/rke2/np.go
scripts/validate

Change processing logic for directory existence and processling logic for network policy processing.
Addresses issues in #244, #259, and #269

Update Directory Manifest Directory Exists Logic and Network Policy Existence Checks

---

pkg/images/images.go

Use RuntimeImageName so that the runtime image can be replaced at build time.

Use RuntimeImageName as placeHolder

---

pkg/rke2/psp.go
pkg/rke2/psp_templates.go

Correct rolebinding links. Code simplification.
See linked issue.
rancher/rke2#159 
N/A

Update PSP Processing Logic, MInor Code Clean Up

---

go.mod
go.sum
pkg/rke2/np.go
pkg/rke2/psp.go

Update setup hook arguments based on underlying k3s code change.
https://github.com/rancher/k3s/issues/2205
N/A

update k3s, adjust setup hook call args

---

Vagrantfile
pkg/podexecutor/staticpod.go
pkg/staticpod/staticpod.go

Set custom selinux context type to containers running in a static pod.
Refactor Vagrantfile to leverage installer and airgap images by default.
Depends on https://github.com/rancher/rke2-selinux/pull/6

selinux: custom context type for static pods

---

go.mod
go.sum

Updates RKE2 with the latest master hash in K3S to allow for proper metrics server function.
https://github.com/rancher/rke2/issues/112

Update K3S for Issue 112

---

pkg/rke2/np.go

* Adds a check to see if running in CIS mode and if so, apply the network policies.
* Adds a new network policy for DNS traffic.
#297

Apply Network Policies Only in CIS Mode and Add Policy For DNS

---

pkg/images/images.go
scripts/build-images

Updates the code to use the rancher pause image rather than getting it from the google container registry.
#196

Use Rancher Pause Image

---

scripts/build-images

Use rancher repo to pull the required images for build images script 
non-breaking change
In ci or local build, check where the nginx-ingress-controller-defaultbackend and nginx-ingress-controller are pulled from
https://github.com/rancher/rke2/issues/196
https://github.com/rancher/rke2-charts/pull/17

use rancher images

---

go.mod
pkg/bootstrap/bootstrap.go
pkg/cli/cmds/root.go
pkg/images/images.go
pkg/podexecutor/staticpod.go
pkg/rke2/rke2.go

* Add support for --system-default-registry flag
* Remove legacy --repo flag
* Clean up, comment, and add logging to bootstrap code paths
- New feature
See limitations for default registry in linked issue.
```
rke2 server --system-default-registry myregistry:443
```
In service of #271

Add support for --system-default-registry CLI flag

---

pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/cli/defaults/defaults.go
pkg/rke2/np.go
pkg/rke2/psp.go
pkg/rke2/rke2.go

Update code to account for moving back to urfave/cli to make cis mode available where needed.
#298

make cis mode known throughout the code

---

Dockerfile
charts/build-chart.sh
pkg/images/images.go
scripts/version.sh

Update references to Kubernetes 1.18.4 to 1.18.8.
rancher/rke2#255

Update Kubernetes from 1.18.4 to 1.18.8

---

docs/upgrading_kubernetes.nd

Adds Kubernetes Upgrade Information.
rancher/rke2#304

Add Kubernetes Upgrade Documentation

---

docs/upgrading_etcd.md

Documentation for the upgrade process of Etcd.
rancher/rke2#311

Documentation for Upgrading Etcd

---

.drone.yml
Dockerfile
docs/upgrading_etcd.md
docs/upgrading_kubernetes.nd
pkg/images/images.go
scripts/build-images

All repositories that are FIPS 140-2 hardened have been move to new
repositories or have been renamed requiring RKE2 to be updated to
reference those. This includes charts built in the CI process.
rancher/rke2#315

Update repositories names.

---

scripts/build-image-kubernetes
scripts/build-images
scripts/publish-image-kubernetes
scripts/publish-manifest-kubernetes
scripts/scan-image-kubernetes

Attempt to complete the rancher/kubernetes to
rancher/hardened-kubernetes rename, unbreaking airgap installations and
dev-shell.
Supplemental to #316
Addresses #315

images: rancher/hardened-kubernetes

---

bundle/bin/rke2-killall.sh
go.sum

Fix the killall script to properly stop rke2 systemd service(s).
Partially addresses #295

bundle: fix killall script

---

install.sh

Add unpack_tarball function, set Install rke2 url
Bugfix
```
root@ip-172-31-21-226:~# curl -fsSL https://raw.githubusercontent.com/MonzElmasry/rke2/fix_installer/install.sh | sudo sh -
[WARN]  unknown installation method, '', assuming you meant 'tar'
[INFO]  finding release for channel testing
[INFO]  using v1.18.8-beta19+rke2 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.18.8-beta19+rke2/sha256sum-amd64.txt
[INFO]  downloading tarball at https://github.com/rancher/rke2/releases/download/v1.18.8-beta19+rke2/rke2.linux-amd64.tar.gz
[INFO]  verifying installer
[INFO]  unpacking tarball file
```
https://github.com/rancher/rke2/issues/326

Add install_rke2_github_url and Unpack tarball

---

Dockerfile

Adds the necessary arguments to have Kubernetes build a static binary.
rancher/rke2#331

adds the flag necessary to create a statically linked binary

---

README.md

Fix port in  README
* README
* Follow instructions in README
* See cluster come up
Related to #336

Fix server port in README

---

go.mod
go.sum

Signed-off-by: MonzElmasry <menna.elmasry@rancher.com>
Updates RKE2 with the latest master hash in K3S to update logging statements stated in https://github.com/rancher/k3s/pull/2246
https://github.com/rancher/rke2/issues/317

Update k3s for issue 317

---

go.mod
go.sum

Update k3s
K3s pull-through
See steps to reproduce in linked issue
For #292

Update k3s for #292

---

docs/airgap.md

Documentation needed to describe the multiple methods of airgap installations available.
https://github.com/rancher/rke2/issues/281

Add documentation for airgap install

---

docs/cis_self_assessment.md

Update section 1.1 formatting, remediations, and audits.
Documentation Updates
N/A
#327

CIS Self Assessment Updates: Section 1.1

---

docs/cis_self_assessment.md

Update 1.2.1 - 1.2.10 controls

---

docs/cis_self_assessment.md

Update 1.2.11 - 1.2.20 controls

---

docs/cis_self_assessment.md

Update Controls 1.2.21 - 1.2.35
#327

Update Controls 1.2.21 - 1.2.35

---

docs/cis_self_assessment.md

Update sections 1.3 and 1.4

---

docs/cis_self_assessment.md

Update section 2

---

docs/cis_self_assessment.md

Update sections 3 and 4

---

scripts/test-helpers

Fix leftover CI containers
Bugfix
Test runs
tbd

Cleanup the test-cleanup function

---

scripts/package-bundle

tarball: strip the binary that is shipped

---

docs/cis_self_assessment.md

update section 5

---

docs/cis_self_assessment.md
docs/hardening_guide.md

Add service account hardening guidance

---

docs/policies.md

Add policy document

---

docs/backup_restore.md

cluster reset documentation
documentation
https://github.com/rancher/rke2/issues/275

Add cluster-reset docs

---

docs/quickstart.md

Update quickstart doc for agent node join.
Docs
N/A

Update url to server for quickstart

---

docs/advanced.md
docs/cis_self_assessment.md
docs/hardening_guide.md
docs/helm.md
docs/networking.md

More docs
* Docs
* Read Docs
* Be Enlightened
N/A
Mostly inspired by K3s docs sections.

Add requested docs sections

---

docs/cis_self_assessment.md

Update audits to conform to upstream doc

---

docs/advanced.md
docs/backup_restore.md
docs/install/quickstart.md
mkdocs.yml

Fix docs headers and remove openrc reference

---

docs/network-options.md

Add network options documentation

Add network options docs

---

docs/advanced.md
docs/index.md
docs/security/fips_support.md

Add docs for disabling/replacing system charts

Add docs for disabling/replacing system charts

---

docs/automated_upgrade.md
docs/basic_upgrade.md
docs/upgrade.md

This pr adds the possible upgrade scenarios for rke2 clusters

Add rke2-upgrade docs

---

docs/containerd_registry_configuration.md

Porting comparable parts of k3s docs of private registry configuration.
Reference: https://rancher.com/docs/k3s/latest/en/installation/private-registry/
docs
N/A
N/A
N/A

Add docs for configuration priv reg for workloads

---

install.sh

install: latest should be the default channel

---

docs/advanced.md

Update `disable` with correct flag for disabling nginx ingress.
Docs

Update disabling server charts with correct disable for nginx

---

docs/install/methods.md

fix links to server and agent config

---

Dockerfile
developer-docs/upgrading_kubernetes.md
pkg/images/images.go
scripts/build-images
scripts/version.sh

Update Kubernetes to v1.18.10
Kubernetes
`rke2 --version`
Related to #484

Update Kubernetes to v1.18.10

---

README.md

fix install methods link, old link was not working.
Fix readme to fix install methods link.
docs fix
Check old link see that it is 404, new link is showing correct docs.
No linked issues.
-

Update README.md to fix install methods link

---

channels.yaml
install.sh

https://github.com/rancher/rke2/issues/404

Add stable channel to rke2-channelserver and set v1.18.12+rke2r1 as stable

---

install.sh

Change the default install to latest channel 
Channelserver
`curl -sfL https://get.rke2.io | sudo sh - ` should install the latest release

make "latest" the default install channel

---

install.sh

install release from stable channel by default 
channelserver
`curl -sfL https://get.rke2.io | sudo sh -`

install release from stable channel by default

---

contrib/custom-image-kubelet/.flake8
contrib/custom-image-kubelet/README.md
contrib/custom-image-kubelet/genconfig.py
contrib/custom-image-kubelet/requirements.txt
pkg/cli/cmds/root.go

Add a Python script that generates config files and extracts binaries from a Release YAML manifest. The resulting configuration will replace core components with those from an alternative Kubernetes distribution.
* contrib
Follow instructions in readme
#543 
cc @cloudnautique

Add custom image / kubelet example script

---

contrib/custom-image-kubelet/README.md
contrib/custom-image-kubelet/genconfig.py

Update custom-image-kubelet for EKS Distro GA changes
* contrib
Run script against release linked in README
https://github.com/aws/eks-distro-build-tooling/pull/26
https://aws.amazon.com/blogs/opensource/introducing-amazon-eks-distro/

Update custom-image-kubelet for EKS Distro GA changes

---

pkg/cli/cmds/root.go

Show go version when executes with --version.
```
rke2 version v1.18.12-dev+229b4b45 (229b4b456c96345fd1e6c565954d381297672d96)
go version go1.13.15b4
```
Enhancement
```
rke2 --version
```
https://github.com/rancher/rke2/issues/555

Include go version in CLI

---

Dockerfile

containerd: v1.3.9-k3s1

---

README.md
docs/index.md

Info about where to report security issues.
Document
`NONE`
https://github.com/rancher/rke2/issues/495
`NONE`

Where to report security issues

---

channels.yaml

Limit `testing` channel to alpha, beta, and rc pre-releases.

channel: tweak testing channel config

---

install.sh

Add `install.sh` script enhancements to allow more customizability for `rke2` RPM installations.
`install.sh` changes
Perform multiple RPM installations, changing/setting the channel and specifying a version of RKE2.
https://github.com/rancher/rke2/issues/528
https://github.com/rancher/rke2/issues/537
https://github.com/rancher/rke2/issues/538

Add install script RPM enhancements

---

docs/known_issues.md

Document the workaround found in testing Istio in Selinux enforcing systems.
docs
N/A
#504 
N/A

Document workaround for istio under selinux

---

docs/security/policies.md
pkg/rke2/psp_templates.go
pkg/rke2/psp_test.go

Removes all annotations from PSP's and updates the documentation reflecting the change.
Run RKE2 on CentOS 7/8 in CIS mode and verify that pods in a deployment are successfully launched.
#483

Remove PSP Annotations and Update Documentation

---

docs/security/cis_self_assessment.md

Typos.
Document
`none`
`none`
`none`

Typo corrections

---

Dockerfile
channels.yaml
contrib/custom-image-kubelet/README.md
developer-docs/upgrading_kubernetes.md
docs/upgrade/automated_upgrade.md
pkg/images/images.go
scripts/version.sh

Update code and docs to use and reference v1.18.13 respectively.

update code and docs to use and reference v1.18.13 respectively

---

channels.yaml

revert update to minor k8s version

revert update to minor k8s version

---

channels.yaml

Change stable version to v1.18.12+rke2r2

update stable to v1.18.12+rke2r2

---

bundle/bin/rke2-uninstall.sh

Update Uninstall Script

---

bundle/bin/rke2-uninstall.sh

Remove unneeded rm and reorder yum call.
https://github.com/rancher/rke2/issues/597

remove unneeded rm and reorder yum call

---

docs/install/uninstall.md
mkdocs.yml

Enhance the uninstall docs
Documentation
Perform the various uninstall instructions provided.
https://github.com/rancher/rke2/issues/597

Enhance the uninstall docs

---

Dockerfile
scripts/build-images

[1.19] coredns: v1.7.1

---

docs/install/install_options/server_config.md
pkg/cli/cmds/server.go

Change rke2-ingress to rke2-ingress-nginx.
Document
`none`
https://github.com/rancher/rke2/issues/611
`none`

Fix ingress service name

---

channels.yaml

mark v1.18.13+rke2r1 as stable

---

docs/install/quickstart.md

Update based on Rey Lejano's Slack comment https://rancher.slack.com/archives/C6U4L2DS9/p1608158730228400

Make requirements harder to miss

---

docs/architecture/architecture.md
docs/helm.md

Update Helm Controller URI from rancher to k3s-io.
Document
`none`
https://github.com/k3s-io/k3s/issues/2189
`none`

Update Helm Controller URL

---

Dockerfile
scripts/build-images

https://github.com/rancher/rke2/issues/345

Revert "[1.19] coredns: v1.7.1 (#607)"

---

docs/upgrade/basic_upgrade.md

Maybe it reads better with these rewords.
Document
`none`
`none`
`none`

Reword note for upgrade sequence

---

docs/networking.md

Remove Klipper service LB from content, and fix the table of contents.
Fix doc.
was
is
N/A
N/A

Fix networking.md anchor and table of contents

---

channels.yaml

https://github.com/rancher/rke2/issues/609

mark v1.19.5+rke2r1 as stable

---

go.mod
go.sum
scripts/build-images

Doing this via replace because there are some fixes to node password in
k3s master that need to be resolved before we can update again.
* update helm-controller
#487
k3s-io/k3s#2777

Update helm-controller to v0.8.3

---

Dockerfile
contrib/custom-image-kubelet/README.md
developer-docs/upgrading_kubernetes.md
docs/install/uninstall.md
docs/upgrade/automated_upgrade.md
pkg/images/images.go
scripts/version.sh

Kubernetes Upgrade to v1.18.15
#657

update release-1.18 with latest patch

---

channels.yaml

Updates channel server config with the 1.18 and 1.19 releases.
Verify that the releases are available here: https://update.rke2.io/

Update channel server config

---

channels.yaml

update stable version

---

Dockerfile
go.mod
go.sum

Update containerd to fix AppArmor on SLES
* Bugfix
k3s-io/k3s#2778 
containerd/containerd#4467

Update containerd to fix AppArmor on SLES

---

Dockerfile
go.mod
go.sum

Update containerd to fix AppArmor on SLES
* Bugfix
k3s-io/k3s#2778 
containerd/containerd#4467

[release-1.19] Update containerd to fix AppArmor on SLES

---

go.mod
go.sum
pkg/cli/cmds/server.go

Add disable flags to rke2
https://github.com/k3s-io/k3s/issues/2635

add disable flags to rke2

---

developer-docs/upgrading_kubernetes.md

Update upgrading_kubernetes.md to explain the KDM process.
Docs change
Not needed, just ensure happy with the spelling/wordage in the PR.

Add KDM process documentation

---

Dockerfile
contrib/custom-image-kubelet/README.md
developer-docs/upgrading_kubernetes.md
docs/upgrade/automated_upgrade.md
pkg/images/images.go
scripts/version.sh

For https://github.com/rancher/rke2/issues/704

Update to k8s v1.18.16

---

Dockerfile
pkg/images/images.go
scripts/build-images

Update dependent images to new base OS versions
https://github.com/rancher/rke2/issues/705

Update hardened images

---

go.mod
go.sum
scripts/build-images

For https://github.com/rancher/rke2/issues/705

Upgrade helm-controller / klipper-helm

---

pkg/podexecutor/staticpod.go

Add args to start of list instead of end 
Fixes issue where user-provided args are overridden by ones we add due to other configuration flags.
Extra args passthrough
For #724

Add args to start of list instead of end

---

Dockerfile
go.mod
go.sum
pkg/images/images.go
scripts/build-images

From https://github.com/rancher/rke2/issues/705

Image build tag forward port

---

channels.yaml

For https://github.com/rancher/rke2/issues/675

Update v1.19.8+rke2r1 to stable

---

docs/security/hardening_guide.md

https://github.com/rancher/rke2/issues/685

update audit docs

---

docs/advanced.md

For https://github.com/rancher/rke2/issues/617

Update docs for node-password

---

scripts/package-images

Fix typo in package-images script
bugfix
Check CI output / artifacts for correct extension
N/A (QA find on RC2)

Fix zstd artifact file extension

---

.github/PULL_REQUEST_TEMPLATE.md

Adds an HTML comment to the Pull Request template asking if the change submitted requires an update to the documentation.

add docs question to PR template

---

docs/install/requirements.md

This change updates documentation so we list SLES 15SP2 as a supported OS.
None needed - ensure PR looks good to update docs.

Add SLES15SP2 to supported OS list

---

docs/index.md

Docs update
Docs change
Not needed; just review the PR for proper language/spelling.

Update why two names documentation

---

docs/install/airgap.md
docs/install/containerd_registry_configuration.md

Update RKE2 docs for airgap / registry mirror configuration
Docs
Read docs
#715

Update airgap / registry mirror docs

---

pkg/cli/cmds/agent.go
pkg/cli/cmds/root.go
pkg/cli/cmds/server.go
pkg/rke2/rke2.go

Add support for the  `--profile` flag to include CIS1.6 profile 
New feature 
Start rke2 with --profile cis1.6
https://github.com/rancher/rke2/issues/350

add support for cis-1.6 profile

---

.drone.yml
install.sh
scripts/build-upload
scripts/package

* Upload the bundle and compressed airgap image tarballs
* Add INSTALL_RKE2_COMMIT support to install.sh
* Update install docs
New feature for install script
Run install.sh with INSTALL_RKE2_COMMIT
#62

Allow install from CI builds

---

.drone.yml
scripts/build-upload
scripts/package

Add CI artifact upload script
CI
Use install script to install from commit on release-1.19 branch
#62

[release-1.19] Allow install from CI builds

---

Dockerfile
pkg/images/images.go
scripts/build-images
scripts/version.sh

Update Kubernetes to v1.19.9
Upstream release
Normal release QA
https://github.com/rancher/rke2/issues/720

update rke2 version to v1.19.9+rke2r1

---

Dockerfile
pkg/images/images.go
scripts/build-images
scripts/version.sh

Update Kubernetes to v1.18.17
Upstream release
Normal release QA
https://github.com/rancher/rke2/issues/719

update rke2 version to v1.18.17+rke2r1

---

install.sh

Add an additional environment variable called `INSTALL_RKE2_ARTIFACT_PATH` to the install script to allow installation from local resources.
Install script changes.
Verification will be done via the RKE2 `system-agent` installer script.
https://github.com/rancher/rke2/issues/795

Add INSTALL_RKE2_ARTIFACT_PATH environment variable to install script

---

Dockerfile

Update containerd to fix AppArmor on SLES
* Bugfix
k3s-io/k3s#2778 
containerd/containerd#4467
k3s-io/containerd#14

[release-1.18] Update containerd to fix AppArmor on SLES

---

docs/install/airgap.md
docs/install/methods.md
docs/install/quickstart.md
docs/install/requirements.md
docs/known_issues.md

https://github.com/rancher/rke2/issues/786
Docs change to add NetworkManager call out.

[docs] Add call out for networkmanager workaround

---

docs/known_issues.md

Gives a better explanation for why there is a problem with networkmanager. 
docs
#786

Update networkmanager docs with problem explanation

---

Dockerfile
scripts/build-images

Update helm charts for ingress-nginx and kube-proxy
Bugfix
* #493
* #645
Waiting on rancher/rke2-charts#63

Update ingress-nginx and kube-proxy chart versions

---

docs/install/network_options.md

Signed-off-by: Jaime Caamaño Ruiz <jcaamano@suse.com>
Add documentation for upcoming support of Cilium as cni.
New feature - docs
Follow the steps of the documentation once images and chart are available.
Feature:
rancher/rancher#15087
rancher/rke2#490
Images:
https://github.com/rancher/image-mirror/pull/72
https://github.com/rancherlabs/eio/issues/361
Charts:
https://github.com/rancher/rke2-charts/pull/46

Add cilium documentation

---

channels.yaml

https://github.com/rancher/rke2/issues/857

Add 1.20 to channel server

---

pkg/podexecutor/staticpod.go
pkg/rke2/rke2.go

check if disable etcd flag is passed and dont use etcd name file if its disabled
bug fix
https://github.com/rancher/rke2/issues/866

Fix disable etcd flag in rke2

---

go.mod
go.sum

Update k3s to bring in cluster reset flag
```sh
rke2 server -h | grep 'cluster-reset'
```
#856

Update k3s to bring in cluster reset flag

---

docs/advanced.md

Add additional advanced documentation for configuring RKE2 on classified AWS regions or regions with custom AWS API endpoints.
docs
see https://github.com/rancher/rke2/issues/814
Open to feedback on location of this information, and of course, the content!
/cc @bgulla

add advanced usage docs for classified aws regions or setups with custom aws api endpoints

---

.drone.yml
Dockerfile
scripts/test-helpers

Port over CI improvements (local registry mirror, etc) from K3s
CI
* Run PR/commit CI; notice lack of image pull backoff errors
???

[release-1.20] Port over CI improvements from K3s

---

.drone.yml
Dockerfile
scripts/test-helpers

Port over CI improvements (local registry mirror, etc) from K3s
CI
* Run PR/commit CI; notice lack of image pull backoff errors
???

Port over CI improvements from K3s

---

.drone.yml
Dockerfile
scripts/test-helpers

Port over CI improvements (local registry mirror, etc) from K3s
CI
* Run PR/commit CI; notice lack of image pull backoff errors
???

[release-1.19] Port over CI improvements from K3s

---

.drone.yml
Dockerfile
scripts/test-helpers

Port over CI improvements (local registry mirror, etc) from K3s
CI
* Run PR/commit CI; notice lack of image pull backoff errors
???

[release-1.18] Port over CI improvements from K3s

---

Dockerfile
charts/build-chart.sh
pkg/cli/cmds/server.go
scripts/build-images

This PR adds the required calico pieces to be able to deploy it through --cni calico
New feature
Use --cni calico
rancher/rke2#860
https://github.com/rancher/image-mirror/pull/99

Add calico as cni

---

Dockerfile

Updates the calico helm charts to use the latest one version
Bugfix

Use the latest helm charts

---

go.mod
go.sum
pkg/cli/cmds/etcd_snapshot.go

Updates the version of k3s in use to the latest in k3s master.

update k3s version

---

Dockerfile

Add ability to configure calico failsafe ports

---

go.mod
go.sum

update k3s with etcd node name bug fix

update k3s with etcd node name bug fix

---

Dockerfile

The calico's chart was updated:
https://github.com/rancher/rke2-charts/pull/77

Update calico's helm chart

---

go.mod
go.sum
scripts/build-images
scripts/package-images

Update klipper-helm and urfave/cli for #948
Changes to helm versions should be called out in next release notes
cli, helm controller
#948

Update klipper-helm and urfave/cli

---

Dockerfile
pkg/cli/cmds/server.go
scripts/build-images

Allow multus to be deployed using the --cni flag
New feature
--cni=$CNI_plugin+multus (e.g. canal+multus)

Integrate Multus in rke2

---

scripts/package-images

Provide .txt file containing list of images used by all components
No docs change necessary
Build artifacts; airgap; vuln scanning
Check artifacts on local build or tagged release
For #966

Add rke2-images-all image list to artifacts

---

docs/install/network_options.md

Align Cilium and Calico docs with Multus'

---

Dockerfile

runc: v1.0.0-rc94

---

.drone.yml
Dockerfile

golang: 1.16.4b7

---

Dockerfile

backport of #976
addresses #980

[backport 1.20] runc: v1.0.0-rc94

---

Dockerfile

backport of #976
addresses #981

[backport 1.19] runc: v1.0.0-rc94

---

Dockerfile

backport of #976
addresses #982

[backport 1.18] runc: v1.0.0-rc94

---

Dockerfile

[backport 1.20] runc: v1.0.0-rc95

---

Dockerfile

[backport 1.19] runc: v1.0.0-rc95

---

Dockerfile

[backport 1.18] runc: v1.0.0-rc95

---

go.mod
go.sum

Bump helm-controller for empty string fix
helm-controller bugfix
#1015

Bump helm-controller for empty string fix

---

Dockerfile

runc: v1.0.0-rc95

---

Dockerfile

Bump containerd to v1.4.4-k3s2

[1.20] containerd: v1.4.4-k3s2

---

Dockerfile

Bump containerd to v1.4.4-k3s2

[1.19] containerd: v1.4.4-k3s2

---

go.mod
go.sum

Bump helm-controller for empty string fix
helm-controller bugfix
#1015

[release-1.20] Bump helm-controller for empty string fix

---

Dockerfile
pkg/images/images.go
scripts/build-images
scripts/version.sh

kubernetes: v1.18.19

---

Dockerfile
scripts/build-images

Also:
- containerd v1.4.4-k3s2 (fix for running in containers on newer kernels)
See #845

kubernetes: v1.21.1

---

channels.yaml

channels: 1.20.7 as stable

---

pkg/rke2/psp.go

Don't write to kube-system namespace if annotations haven't changed.
CIS pod security policy startup sync
* Restart RKE2; note lack of `Updating annotations on kube-system namespace` message.
#1057

[release-1.19] Don't write to kube-system namespace if annotations haven't changed

---

pkg/rke2/rke2.go

Ensure that we are properly setting up the paths and environment for the kubelet and containerd processes that are temporarily started to clean up static pods during reconfiguration (cluster reset, role change, etc).
Because we now defer runtime bootstrap (which has a side effect of modifying the PATH environment variable to include the runtime bin dir), we need to use the bin dir symlink at this stage of the startup. We should also display the kubelet and containerd logs so that we can see what's going on as we wait for static pods to get cleaned up.
This also closes a gap that existed around checking for static pod termination by examining the containerd container names. Container names are not unique; we need to look at the kubernetes labels instead.
Long term we should move this into …

[release-1.20] Ensure kubelet and containerd are in path for temporary startup

---

channels.yaml

Mark v1.20.7+rke2r2 as stable
Signed-off-by: David Nuzik <david.nuzik@rancher.com>

Mark v1.20.7+rke2r2 as stable

---

go.mod
go.sum
pkg/cli/cmds/etcd_snapshot.go

Adds etcd-snapshot subcommands.

Adds etcd-snapshot subcommands

---

pkg/rke2/rke2.go

Ensure that we are properly setting up the paths and environment for the kubelet and containerd processes that are temporarily started to clean up static pods during reconfiguration (cluster reset, role change, etc).
Because we now defer runtime bootstrap (which has a side effect of modifying the PATH environment variable to include the runtime bin dir), we need to use the bin dir symlink at this stage of the startup. We should also display the kubelet and containerd logs so that we can see what's going on as we wait for static pods to get cleaned up.
This also closes a gap that existed around checking for static pod termination by examining the containerd container names. Container names are not unique; we need to look at the kubernetes labels instead.
Long term we should move this into …

Ensure kubelet and containerd are in path for temporary startup

---

developer-docs/upgrading_kubernetes.md

```
* Add callout that once an RC is cut the associated release branch is
frozen. If further PRs need to be merged, then a new RC is required.
Signed-off-by: David Nuzik <david.nuzik@rancher.com>
```
Small dev docs change
Minor dev docs change
Just ensure wording makes sense
Not required, is a small one-line docs change

Update upgrading_kubernetes.md doc

---

docs/security/hardening_guide.md

Add additional info around etcd user creation as well as update command to run.
#1087

update documentation to have getcd group created with user

---

docs/backup_restore.md

Proposed Changes
Update reset-file name and path of the file in docs to reset-flag and db dir
Types of Changes
Docs
Linked Issues
#1088

Update reset-file name and path

---

Dockerfile
scripts/build-images

Updating Calico to 3.19.1 and use mirrored images from rancher docker repo instead of quay.io
New images and new helm version
https://github.com/rancher/rke2/issues/1077

Update calico images and helm

---

Dockerfile
scripts/build-images

Update Cilium from 1.9.6 to 1.9.8. Changelogs of the last two releases:
* https://github.com/cilium/cilium/releases/tag/v1.9.8
* https://github.com/cilium/cilium/releases/tag/v1.9.7
Fixes: #1099
Update of Cilium to 1.9.8
New CNI plugin version
* By deploying rke2 with `--cni=cilium` and ensuring that the cluster is functional
* By performing an upgrade of Cilium on already existing rke2 cluster
#1099

cilium: Update to 1.9.8

---

Dockerfile
scripts/build-images

It updates the canal images to flannel 0.14 and canal 3.19.1
It updates the canal chart which uses the new images
No docs update needed
Updating images
https://github.com/rancher/rke2/issues/1108

Update canal images and chart

---

docs/install/ha.md

Update docs to indicate the config file needs to be created manually.

Update docs to indicate the config file needs to be created manually

---

go.mod
go.sum

https://github.com/k3s-io/k3s/compare/f6cec4e75d0b...b74c499709e6
Brings in:
* Updated iptables version check [#3425](https://github.com/k3s-io/k3s/pull/3425)
* Send systemd notifications for both server and agent [#3430](https://github.com/k3s-io/k3s/pull/3430)
* Add events to deploy controller [#3436](https://github.com/k3s-io/k3s/pull//3436)
* Add nodename to UA string for deploy controller [#3433](https://github.com/k3s-io/k3s/pull/3433)
Pulls through latest master from k3s into the master branch.
#1145

update go mod to latest k3s commit

---

docs/security/cis_self_assessment15.md
docs/security/cis_self_assessment16.md
docs/security/hardening_guide.md

Updates CIS 1.5 and 1.6 docs.
#876

update cis docs

---

go.mod
go.sum

* Update k3s for https://github.com/k3s-io/k3s/issues/3467
Bugfix
https://github.com/rancher/rke2/issues/1153

[Backport 1.21] Update go mod to latest k3s

---

Dockerfile
pkg/images/images.go
scripts/build-images
scripts/version.sh

kubernetes: v1.18.20

---

Dockerfile
pkg/images/images.go
scripts/build-images
scripts/version.sh

kubernetes: v1.19.12

---

go.mod
go.sum

* Update k3s for https://github.com/k3s-io/k3s/issues/3467
Bugfix
https://github.com/rancher/rke2/issues/1152

Update go mod to latest k3s

---

Dockerfile.docs

Updates the version of mkdocs in the Dockerfile to be 7.1.7 which is the version before "latest".
#1164

update link to known issues network manager

---

Dockerfile.docs
mkdocs.yml

Update configuration of mkdocs to account for backwards compatibility. 
#1164

update mkdocs config for backwards compatibility

---

.golangci.json
Dockerfile
pkg/cli/cmds/k3sopts.go
pkg/controllers/cisnetworkpolicy/controller.go
pkg/images/images.go
pkg/rke2/rke2.go
scripts/validate

https://github.com/rancher/rke2/issues/1173

fixing golangci-lint for validate script to start working again

---

channels.yaml

channels: v1.20.8+rke2r1 as stable

---

docs/install/network_options.md

Signed-off-by: rancher-max <max.ross@suse.com>
Document SR-IOV usage as experimental in RKE2 for v1.21.2+rke2r1.
Docs
N/A
https://github.com/rancher/rke2/issues/746

[Docs] Document SR-IOV as experimental

---

.golangci.json
Dockerfile
pkg/cli/cmds/k3sopts.go
pkg/controllers/cisnetworkpolicy/controller.go
pkg/images/images.go
pkg/rke2/rke2.go
scripts/validate

https://github.com/rancher/rke2/issues/1184

[release-1.21] backport: fixing golangci-lint for validate script to start working again

---

.golangci.json
Dockerfile
pkg/cli/cmds/k3sopts.go
pkg/cli/cmds/server.go
pkg/controllers/cisnetworkpolicy/controller.go
pkg/images/images.go
pkg/podexecutor/staticpod.go
pkg/rke2/rke2.go
scripts/validate

https://github.com/rancher/rke2/issues/1186

[release-1.19] backport: fixing golangci-lint for validate script to start working again

---

install.ps1

This provides a PowerShell based installation script for Windows nodes.
Adds an install.ps1 script to support installation on Windows nodes.
A new feature that will not cause any breaking changes.
* Issue #1240
* https://github.com/rancher/windows/issues/55
* https://github.com/rancher/windows/issues/50
* https://github.com/rancher/windows/issues/51

PowerShell based installation script for Windows nodes.

---

channels.yaml

Update channels.yaml to make v1.21.2+rke2r1 stable.

Promote 1.21.2 to stable

---

go.mod
go.sum

Bump wharfie to fix image pull url scheme issue
Bugfix
See steps in linked issue (requires private registry using HTTP with authentication)
* #1264

[release-1.21] Bump wharfie to fix image pull url scheme issue

---

go.mod
go.sum

Bump wharfie to fix image pull url scheme issue
Bugfix
See steps in linked issue (requires private registry using HTTP with authentication)
* #1265

[release-1.20] Bump wharfie to fix image pull url scheme issue

---

go.mod
go.sum

Bump wharfie to fix image pull url scheme issue
Bugfix
See steps in linked issue (requires private registry using HTTP with authentication)
* #1246

Bump wharfie to fix image pull url scheme issue

---

Dockerfile
scripts/build-images

Bump ingress-nginx chart to 3.34.001
Version bump to hardened image
CI, QA (can also test with FIPS mode enabled)
https://github.com/rancher/rke2/issues/659

Bump ingress-nginx chart to 3.34.001

---

Dockerfile
scripts/build-images

Bump ingress-nginx chart to 3.34.001
Version bump to hardened image
CI, QA (can also test with FIPS mode enabled)
https://github.com/rancher/rke2/issues/659

[backport release/1.21] Bump ingress-nginx chart to 3.34.001

---

go.mod
pkg/cli/cmds/agent.go
pkg/cli/cmds/agent_service_linux.go
pkg/cli/cmds/agent_service_windows.go

https://github.com/rancher/rke2/issues/1280

[1.21 backport] adding windows service subcommand

---

.codespellignore
go.mod
go.sum
install.ps1
pkg/bootstrap/bootstrap.go
pkg/pebinaryexecutor/pebinary.go
pkg/podexecutor/staticpod.go
pkg/rke2/clusterrole.go
pkg/rke2/clusterrole_templates.go
pkg/rke2/rke2.go
pkg/rke2/rke2_linux.go
pkg/rke2/rke2_windows.go
pkg/staticpod/staticpod.go
pkg/windows/calico.go
pkg/windows/templates.go
pkg/windows/types.go
scripts/codespell.sh

https://github.com/rancher/rke2/issues/1290

[1.21 backport] Windows + Calico Support

---

Dockerfile
scripts/build-images

This new image fixes the bug described in #1298
Signed-off-by: manuel <mbuil@suse.com>

[release-1.21] Upgrade kube-proxy version

---

Dockerfile
scripts/build-images

This new image fixes the bug described in #1296

[release-1.20] Upgrade kube-proxy version

---

Dockerfile
scripts/build-images

This new image fixes the bug described in #1297 

[release-1.19] Upgrade kube-proxy version

---

go.mod
go.sum

Bump k3s version to commit a939decf0180733cd61de7feaaa1a984845f77d0
update to go.mod
https://github.com/rancher/rke2/issues/1317

[Release-1.21] Bump k3s version

---

go.mod
go.sum

Bumping k3s version to a939decf0180733cd61de7feaaa1a984845f77d0 (latest master)
https://github.com/rancher/rke2/issues/1319

[Release-1.20] Bump k3s version

---

go.mod
go.sum

Upgrade K3s to 0064a39615fc2270371ea6eba297c27a0b22dc3f (latest k3s 1.19 commit)
https://github.com/rancher/rke2/issues/1324

[Release-1.19] Bump k3s version

---

pkg/podexecutor/staticpod.go
pkg/staticpod/staticpod.go

https://github.com/rancher/rke2/issues/1301

added privileged to static pod args

---

scripts/build-images

Fix a problem happening with drone where the build scripts tries to save kubernetes image before actually saving it
bugfix

[Release-1.21] Pull kubernetes image before saving it

---

scripts/package-windows-images

Fix merge conflict in package windows image script

Fix merge conflict

---

.drone.yml

Remove the kubernetes manifest from drone since its already been removed and moved to this:
https://github.com/rancher/image-build-kubernetes/blob/master/.drone.yml#L61-L76

Remove kubernetes manifest

---

.drone.yml

Fixes CI. There was a bug in drone.yml

Fix CI: Bug in .drone.yml

---

scripts/build-images

[Release 1.21] Bug fix airgap multus cniplugins image missing

---

.drone.yml
scripts/build-images

Fixes https://github.com/rancher/rke2/issues/1332

Bug fix airgap multus cniplugins image missing

---

docs/install/install_options/install_options.md
docs/install/install_options/windows_agent_config.md
docs/install/quickstart.md
docs/install/requirements.md

for https://github.com/rancher/rke2/issues/1276

add windows docs for rke2

---

.drone.yml

for https://github.com/rancher/rke2/issues/1362

[release-1.21] package windows images after pushing manifest and runtime images

---

.drone.yml

for https://github.com/rancher/rke2/issues/1364

package windows images after pushing runtime manifest/images

---

.drone.yml
manifest-runtime.tmpl

https://github.com/rancher/rke2/issues/1370

use repo.namespace for manifest-tool template

---

.drone.yml
manifest-runtime.tmpl

for https://github.com/rancher/rke2/issues/1371

[release 1.21] fix bug, use repo.namespace for manifest-tool template

---

manifest-runtime.tmpl

https://github.com/rancher/rke2/issues/1376

[release 1.21] hardcode rancher into manifest-tool template

---

manifest-runtime.tmpl

https://github.com/rancher/rke2/issues/1373

hardcode rancher namespace for rke2-runtime manifest

---

.drone.yml

adding the volume mount for the docker socket

---

.drone.yml

remove manifest kubernetes step

---

go.mod
go.sum
pkg/rke2/clusterrole.go
pkg/rke2/kp.go
pkg/rke2/np.go
pkg/rke2/psp.go
pkg/rke2/serviceaccount.go
scripts/build-images

https://github.com/rancher/rke2/issues/1301

Switching to using StartupHookArgs and adding Disables/Skips

---

Dockerfile

This new image fixes the bug described in https://github.com/rancher/rke2/issues/1229
Signed-off-by: manuel <mbuill@suse.com>

Upgrade kube-proxy version

---

go.mod
go.sum
pkg/rke2/clusterrole.go
pkg/rke2/kp.go
pkg/rke2/np.go
pkg/rke2/psp.go
pkg/rke2/serviceaccount.go
scripts/build-images

https://github.com/rancher/rke2/issues/1301

[Release 1.20] Switch to using StartupHooksArgs using Skips/Disables

---

go.mod
go.sum
pkg/rke2/clusterrole.go
pkg/rke2/kp.go
pkg/rke2/np.go
pkg/rke2/psp.go
pkg/rke2/serviceaccount.go
scripts/build-images

https://github.com/rancher/rke2/issues/1301

[Release 1.21] Add StartupHooks Args and use Disables/Skips

---

Dockerfile

[Release-1.20] Use kubernetes image instead of kube-proxy image

---

Dockerfile

[Release-1.21] Use kubernetes image instead of kube-proxy image

---

docs/upgrade/automated_upgrade.md

* Note the change from master to control-plane starting on 1.20

Improve SUC docs

---

Dockerfile
scripts/build-images

[Release-1.19] Use kubernetes image instead of kube-proxy image

---

.drone.yml

for https://github.com/rancher/rke2/issues/1410

move CI for publishing artifacts to run after windows images

---

go.mod
go.sum
pkg/rke2/clusterrole.go
pkg/rke2/kp.go
pkg/rke2/np.go
pkg/rke2/psp.go
pkg/rke2/rke2.go
pkg/rke2/serviceaccount.go

https://github.com/rancher/rke2/issues/1406

[Release 1.21] Rewrite to pass in waitgroup

---

.drone.yml
Dockerfile
go.mod
go.sum

- https://github.com/rancher/rke2/issues/1417

[Release-1.20] Upgrade k3s bootstrap 120

---

.drone.yml

moving all steps into one pipeline for dist dir to be available

---

.drone.yml
Dockerfile
go.mod
go.sum

- https://github.com/rancher/rke2/issues/1401

Upgrade k3s bootstrap 

---

channels.yaml

Signed-off-by: David Nuzik <david.nuzik@rancher.com>
change stable channel to v1.21.3+k3s1 we will be releasing.
@galal-hussein will need to release rke2-packaging for stable RPMs after release, then:
Post-merge, channel server [endpoint](https://update.rke2.io/v1-release/channels) should automatically update within approximately 15 minutes. When that's done, QA should attempt to install with defaults (uses stable channel) and ensure this works on a rhel environment.
https://github.com/rancher/rke2/issues/1438 
**Stable RPMS must exist first.**

Update RKE2 1.21 stable version

---

install.ps1
windows/rke2-install.ps1

We are adding support for installing the Windows Agent via Rancher with the rke2-installer.ps1. We have also resolved bugs related to the current install.ps1 in the root of the repo.
This will improve the experience for all users and allow better integration with Rancher provisioning.
A new feature which is the RKE2-Installer.ps1 and bug fixes for installer.ps1.
Install via the installer.ps1 produces a Windows node that joins a cluster. The rancher installer will need have a build at the head of the repository, then create a custom cluster with Windows.
https://github.com/rancher/rancher/issues/33625

Add Windows Installation for Rancher, Update existing Installer

---

Dockerfile

Bump ingress-nginx chart to 3.34.002

---

Dockerfile

[backport-1.21] Bump ingress-nginx chart to 3.34.002

---

go.mod
go.sum

Upgrade k3s in 1.20 
bug fix
https://github.com/rancher/rke2/issues/1486

[Release-1.20] Upgrade k3s in 1.20

---

go.mod
go.sum

Upgrade k3s in 1.21 rke2
bug fix
https://github.com/rancher/rke2/issues/1485

[Release-1.21] Upgrade k3s in 1.21

---

go.mod
go.sum
pkg/cli/cmds/agent.go
pkg/cli/cmds/agent_service_windows.go
pkg/windows/service_linux.go
pkg/windows/service_windows.go

Adding windows service manager and eventlog hooks for running as a Windows Service.
Bugfix
Start-Service rke2 should boot, check eventlog for errors
https://github.com/rancher/rke2/issues/1467

Update service watching logic for windows service manager

---

go.mod
go.sum
pkg/cli/cmds/agent.go
pkg/cli/cmds/agent_service_windows.go
pkg/windows/service_linux.go
pkg/windows/service_windows.go

Adding windows service manager and eventlog hooks for running as a Windows Service.
Bugfix backport
Start-Service rke2 should boot, check eventlog for errors
https://github.com/rancher/rke2/issues/1499

[Release 1.21] Update service watching logic for windows service manager

---

docs/install/install_options/install_options.md
docs/install/install_options/windows_agent_config.md
docs/install/linux_uninstall.md
docs/install/quickstart.md
docs/install/requirements.md
docs/install/windows_airgap.md
docs/install/windows_uninstall.md
mkdocs.yml

Update the documentation for Windows
Move `docs/install/uninstall.md` to `docs/install/linux_uninstall.md`
Update mkdocs.yml to reflect new changes
Fixes an issue with bad download links for `install.ps1`
Introduce docs for the new Windows uninstall script, which is currently under review in https://github.com/rancher/rke2/pull/1488
Docs changes only
Tested locally w/ `make mkdocs` and `make serve-docs` with no errors
https://github.com/rancher/rke2/issues/1492

Update the documentation for Windows

---

pkg/rke2/psp_templates.go

Adds labels to the PSP's which are the same as the namespace.
```sh
kubectl get psp -A -o yaml | grep 'labels:' -A 1
```
#1512

add psp labels

---

pkg/rke2/psp_templates.go

[Release 1.21] - Adding annotations to PSPs

---

go.mod
go.sum

update to k3s
bugfix
- https://github.com/rancher/rke2/issues/1485

[Release-1.21] Upgrade k3s

---

go.mod
go.sum

Upgrade k3s
bugfix
https://github.com/rancher/rke2/issues/1486

[Release-1.20] update k3s

---

docs/advanced.md
docs/install/install_options/server_config.md
pkg/cli/cmds/root.go
pkg/podexecutor/staticpod.go
pkg/rke2/rke2.go
pkg/rke2/rke2_linux.go
pkg/staticpod/staticpod.go

Backport of: https://github.com/rancher/rke2/pull/1463
Allow for custom resource requests/limits, extra binds, and extra environment variables for control plane static pod components
CLI, static pod executor
https://github.com/rancher/rke2/issues/1046
https://github.com/rancher/rke2/issues/1525

[release-1.21] Custom resource requests/limits, extra binds, and extra env for control plane static pod components

---

pkg/rke2/psp_templates.go

[Release 1.21] - update labels to be annotations

---

docs/security/fips_support.md

Update fips documentation for the following changes:
- Explain ingress's new fips compliance.
- Link to Rancher's CMVP certificate.
- Call out that only the canal cni is fips compliant
Just a docs change
N/A, just docs
- For ingress bit: https://github.com/rancher/rke2/issues/1511
- For the CMVP bit, I'm submitting without an issue
- For the CNI bit: https://github.com/rancher/rke2/issues/1180

Update FIPS documentation

---

go.mod
go.sum

Upgrade k3s to fix node stuck at removal issue
https://github.com/k3s-io/k3s/compare/2069cdf4eee6...bc96ffb5f3c6
https://github.com/k3s-io/k3s/issues/3773

[Release-1.21] Update k3s to fix node stuck on removal

---

go.mod
go.sum

Upgrade k3s to fix node stuck issue
https://github.com/k3s-io/k3s/issues/3772

[Release-1.20] Update k3s to fix node stuck on removal

---

Dockerfile

Update the coredns chart. The autoscaler requires more memory and it was OOMed when I deployed several times
Bugfix
Deploy rke2 and check that the autoscaler works
Linked issue: https://github.com/rancher/rke2/issues/1556

Update coredns chart

---

install.ps1
windows/rke2-install.ps1

Changes a powershell commandlet to use curl due to self-signed certs and how they are handled.
Bugfix
Installation from Rancher works.
* https://github.com/rancher/rke2/issues/1566
* https://github.com/rancher/rancher/issues/33625

Fixing issues with windows installation scripts.

---

docs/install/network_options.md

The docs are not accurate
Bugfix

Fix bug in docs

---

Dockerfile
scripts/build-images

Moves the patch version of Calico to v3.19.2
Moves charts and images of Calico
Deploy with cni: calico
https://github.com/rancher/rke2/issues/1586

[release-1.21] Update Calico version to v3.19.2

---

go.mod
go.sum

Bumps k3s version to the latest of master to bring in a fix for s3 folder handling. This also brings in a few other changes that can be seen in the link below.
https://github.com/k3s-io/k3s/compare/bc96ffb5f3c6...dcf0657b2083
* #1551

Update k3s to resolve for s3 folder handling when listing snapshots

---

go.mod
go.sum

Bumps k3s version to the latest of master to bring in a fix for s3 folder handling. This also brings in a few other changes that can be seen in the link below.
https://github.com/k3s-io/k3s/compare/bc96ffb5f3c6...dcf0657b2083
* #1551

[Release 1.21] - Update k3s to resolve for s3 folder handling when listing snapshots

---

go.mod
go.sum

Bumps k3s version to the latest of master to bring in a fix for s3 folder handling. This also brings in a few other changes that can be seen in the link below.
https://github.com/k3s-io/k3s/compare/bc96ffb5f3c6...dcf0657b2083
* #1551

[Release 1.20] - Update k3s to resolve for s3 folder handling when listing snapshots

---

windows/rke2-install.ps1

The Rancher installer now gets the version from Rancher and passes it to the regular installer.
Bugfix
That an install from Rancher installs the correct version on Windows.
* https://github.com/rancher/rke2/issues/1577

Allows getting the version from Rancher and passes it to the installer.

---

pkg/rke2/rke2_linux.go

https://github.com/rancher/rke2/issues/1525

Add missing kubeproxy extra env and mounts

---

pkg/rke2/rke2.go

Use FQDN hostname for node name if `--node-name` is not set and `--cloud-provider-name` is set to AWS
Yes we should mention that if the user didn't enter a specific node name and cloud provider is set to aws then node name will default to `hostname -f`
Bug Fix
- Start k3s server with cloud-provider-name=aws
* #1632

[Release-1.20] Use fqdn if cloud provider is set to aws

---

pkg/rke2/rke2.go

Use FQDN hostname for node name if `--node-name` is not set and `--cloud-provider-name` is set to AWS
Yes we should mention that if the user didn't enter a specific node name and cloud provider is set to aws then node name will default to `hostname -f`
Bug Fix
- Start k3s server with cloud-provider-name=aws
* #1633

[Release-1.19] Use fqdn if cloud provider is set to aws

---

docs/architecture/architecture.md

After reading a Jira ticket, I noticed that Calico CNI plugin is not part of the architecture. This PR adds it.
Docs fix

Add Calico to the architecture description

---

go.mod
go.sum

Upgrade k3s to fix issue:
- https://github.com/rancher/rke2/issues/1656
- #1666
- https://github.com/rancher/k3s/compare/ae909c73e51d...e32292478107

Upgrade k3s master

---

go.mod
go.sum

Backport PR for issue:
- https://github.com/rancher/rke2/issues/1659
- #1669
- https://github.com/rancher/k3s/compare/99eadcc10bce...65ec14c96f2b

[Release-1.19] Upgrade k3s 1.19

---

go.mod
go.sum

Backport PR for issue:
- https://github.com/rancher/rke2/issues/1658
- #1668
- https://github.com/rancher/k3s/compare/dcf0657b2083...e32292478107

[Release-1.20] Upgrade k3s 1.20

---

go.mod
go.sum

Backport PR for issue:
- https://github.com/rancher/rke2/issues/1657
- #1667
- https://github.com/rancher/k3s/compare/ae909c73e51d...e32292478107

[Release-1.21] Upgrade k3s 1.21

---

Dockerfile

Bump chart versions to pull in linux nodeSelectors
helm chart
Check nodeSelector on pods deployed by helm charts
* #1664

Bump chart versions to pull in linux nodeSelectors

---

scripts/build-images

need to bump the vsphere images we bundle for airgap

update airgap images

---

channels.yaml

Update channels for v1.21.4+rke2r2

---

MAINTAINERS
scripts/codespell.sh

Update maintainers to reflect team changes
Also use suse email addresses, for consistency with other repos.
housekeeping
n/a
n/a

Update maintainers to reflect team changes

---

go.mod
go.sum

update k3s to fix apiaddresses endpoints issue
https://github.com/k3s-io/k3s/compare/ed5991f13b14...841793de01fd
update k3s
- https://github.com/rancher/rke2/issues/1736

[Release-1.20] Update k3s to latest engine-1.21

---

go.mod
go.sum

Upgrade k3s in release 1.19
k3s Update to fix apiaddresses endpoint issue
https://github.com/k3s-io/k3s/compare/65ec14c96f2b...11813ac82228
- https://github.com/rancher/rke2/issues/1737

[Release-1.19] Update k3s

---

developer-docs/upgrading_kubernetes.md

small release doc update

---

docs/known_issues.md

Update to known_issues.md in docs to provide an easier way to configure istio
Documentation update only
The change can be easily verified by using the sample custom overlay to install Istio on a RKE2 cluster running with selinux in enforcing mode.
None

Sample istio overlay spec to configure and patch the cni

---

developer-docs/upgrading_kubernetes.md

Add drone links to k8s upgrade doc

---

docs/install/windows_airgap.md

docs update to fix bad link and update versions for airgap
documentation update
documentation previewed and links verified
https://github.com/rancher/rke2/issues/1759

patch windows airgap docs

---

channels.yaml

Mark rke2 v1.21.4+rke2r3 as stable version

Mark rke2 v1.21.4+rke2r3 as stable

---

Dockerfile

https://github.com/rancher/rke2/issues/1639

Bump containerd to v1.4.9-k3s1, runc to v1.0.1

---

Dockerfile

https://github.com/rancher/rke2/issues/1641

[release-1.20] Bump containerd to v1.4.9-k3s1, runc to v1.0.1

---

Dockerfile

https://github.com/rancher/rke2/issues/1640

[release-1.21] Bump containerd to v1.4.9-k3s1, runc to v1.0.1

---

Dockerfile
pkg/cli/cmds/root.go
scripts/build-images

Signed-off-by: yaocw2020 <yaocanwu@gmail.com>
To support harvester cloud provider and harvester csi
https://github.com/rancher/rke2/issues/1680
https://github.com/harvester/harvester/issues/1019

Support Harvester CCM and CSI

---

Dockerfile
pkg/cli/cmds/root.go
scripts/build-images

Signed-off-by: yaocw2020 <yaocanwu@gmail.com>
backport: https://github.com/rancher/rke2/pull/1679

[Release 1.21] Support Harvester CCM and CSI

---

go.mod
go.sum

Bump wharfie to v0.4.2
bugfix
* #1784

Bump wharfie to v0.4.2

---

go.mod
go.sum

Bump wharfie to v0.4.2
bugfix
* https://github.com/rancher/rke2/issues/1460

[release-1.21] Bump wharfie to v0.4.2

---

go.mod
go.sum

Bump wharfie to v0.4.2
bugfix
* https://github.com/rancher/rke2/issues/1785

[release-1.20] Bump wharfie to v0.4.2

---

developer-docs/upgrading_kubernetes.md

Add release notes section to release docs

---

go.mod
go.sum

Update K3s for https://github.com/k3s-io/k3s/issues/3988
https://github.com/k3s-io/k3s/compare/11813ac82228...91bb4787979b
* https://github.com/rancher/rke2/issues/1574

[release-1.19] Update embedded k3s to latest 1.19 version

---

go.mod
go.sum

https://github.com/rancher/rke2/issues/1817

[release-1.21] Update K3s to latest engine-1.21

---

developer-docs/upgrading_kubernetes.md

Add release checklist

---

developer-docs/upgrading_kubernetes.md

Add QA Release info to  release docs

---

pkg/podexecutor/staticpod.go

```sh
kubectl describe pod <kube-scheduler-name> | grep permit
```
* #1074

Add Permit Port Sharing Flag to Scheduler and Controller Manager

---

install.ps1

Strict mode has detected a few issues and this PR addresses those issues.
Removing unused variables and code detected by PowerShell strict mode.
Unused variables and code was removed.
RKE2 installs on Windows without any errors.
* https://github.com/rancher/rke2/issues/1866

Cleaning up the PowerShell installation script

---

developer-docs/upgrading_kubernetes.md

Added additional info around v1.19 which has another file that needs to be updated. 
Moved channel update info to after releasing stable (correct order of operations) with a better link.
Reminder about the k3s version.
Documentation

Added more info to release docs, tiny nit

---

developer-docs/updating_rke2_charts.md

Dev-documentation was not accurate. We don't always need to update KDM when updating a rke2-chart
Added more information in our dev-docs

Update the dev-docs with missing information

---

channels.yaml

Promote latest September patch to stable.
https://github.com/rancher/rke2/issues/1861

Promote v1.21.5+rke2r1 to stable

---

Dockerfile

Backport of: https://github.com/rancher/rke2/pull/1878
Linked issue: https://github.com/rancher/rke2/issues/1877

[Backport 1.21] Increment Calico chart version

---

developer-docs/upgrading_kubernetes.md

The KDM release process has changed with Rancher 2.6, more work is required on the part of Rke2 release captain. Additional documentation helps.
Documentation
https://github.com/rancher/rke2/issues/1880

Updated info on KDM releases for rke2

---

docs/install/network_options.md

Several things:
* Add information about dual-stack
* Separate the three different CNI plugins in tabs as done in https://docs.rke2.io/install/linux_uninstall/#rpm-method
* Create a menu to quickly reach the different sections as done in https://docs.rke2.io/install/install_options/install_options/
Docs improvements

Improve network docs

---

Dockerfile
go.mod
go.sum

Bump containerd for CVE CVE-2021-41103
Package Bump
https://github.com/rancher/rke2/issues/1908

[Release-1.19] Bump containerd to v1.4.11 for CVE fix

---

developer-docs/upgrading_kubernetes.md

Documentation
https://github.com/rancher/rke2/issues/1899

Update packaged dev docs

---

Dockerfile
scripts/build-images
scripts/test-run-basics
scripts/test-setup-sonobuoy

Upgrade Nginx ingress to version 4.0.3
chart upgrade
- Install rke2 cluster
- https://github.com/rancher/rke2/issues/1939
-

[Release-1.20] Upgrade nginx chart to version 4.0.305

---

pkg/staticpod/staticpod.go

Don't create static pod manifest tempfiles in the directory that the kubelet is watching.
Bugfix
* #1965

[release-1.21] Don't create static pod tempfiles in static pod dir

---

channels.yaml

Bump stable release to v1.21.6 and add 1.22 channel
channel server
install via install script
* #2043

Bump stable release to v1.21.6 and add 1.22 channel

---

.github/workflows/epic.yaml

Signed-off-by: Chris Wayne <cwayne18@gmail.com>
Adds in an action to automatically update issues listed in an issue marked 'epic'
Github workflow
Land, create an epic issue, close an issue linked from that epic and verify it's automatically checked off

Add in action to automatically update epic issues

---

Dockerfile

Bump containerd to v1.5.7-k3s2
version bump
Run conformance tests
* #2068

Bump containerd to v1.5.7-k3s2

---

.github/workflows/install.yaml
.github/workflows/unitcoverage.yaml
developer-docs/testing.md
tests/vagrant/install/centos7/README.md
tests/vagrant/install/centos7/Vagrantfile
tests/vagrant/install/centos8/README.md
tests/vagrant/install/centos8/Vagrantfile
tests/vagrant/install/microos/README.md
tests/vagrant/install/microos/Vagrantfile

For every change that modifies the installer script, run some quick assertions against:
- CentOS 7
- CentOS 8
- MicroOS
Thanks, Github Actions and Vagrant!

testing: assert that install.sh works correctly

---

developer-docs/image_sources.md

Add image sources doc for @dweomer 
documentation
view the document
* N/A

Add image sources doc

---

Dockerfile
scripts/build-images

Update Calico to its latest version
Updates Calico to latest version
Deploy with `cni: calico`
https://github.com/rancher/rke2/issues/2051

Update Calico chart to v3.20.2

---

.github/workflows/install.yaml
.github/workflows/unitcoverage.yaml
developer-docs/testing.md
tests/vagrant/install/centos8/Vagrantfile
tests/vagrant/install/microos/Vagrantfile
tests/vagrant/install/ubuntu-focal/README.md
tests/vagrant/install/ubuntu-focal/Vagrantfile

- Vagrant fixture for asserting that the installer script works correctly on Ubuntu 20.04, Focal Fossa

tests: vagrant/install/ubuntu-focal

---

go.mod
go.sum
pkg/podexecutor/staticpod.go
pkg/windows/service_windows.go

Updates to using wrangler v0.8.8 which includes fixes to the signal handler to give a exported func to cancel the the context by hand. this is useful in windows services and gives us a way to cancel context to kill all sub-processes and exit gracefully when using windows service manager.
vendor update, small code change to align k3s to use library slight different and pass in context to containerd
this will ultimately be used in rke2 windows services, this will be tested by QA when we work on closing the linked issue.
https://github.com/rancher/rke2/issues/1755
none

[master] updating to new signals package in wrangler

---

docs/advanced.md

Add documentations on configuring http proxy settings.
Docs
Addresses https://github.com/rancher/rke2/issues/2091

[Docs] Configuring http proxy settings

---

Dockerfile

Bump runc version
bugfix
* https://github.com/rancher/rke2/issues/2090

Bump runc on release-1.20 branch

---

scripts/package-windows-images

Fix typo in windows pause image
Bugfix

[release-1.21] Fix typo in windows pause image

---

scripts/package-windows-images

Fix typo in windows pause image

---

go.mod
go.sum
pkg/cli/cmds/server.go
pkg/pebinaryexecutor/pebinary.go
pkg/podexecutor/staticpod.go

Backport: https://github.com/rancher/rke2/pull/2136
Add etcd extra-args support to RKE2
CLI/functionality
https://github.com/k3s-io/k3s/pull/4463#issuecomment-969205988
https://github.com/rancher/rke2/issues/2137
https://github.com/rancher/rke2/issues/2135

[release-1.21] Add etcd extra-args support to RKE2

---

go.mod
go.sum
pkg/cli/cmds/server.go
pkg/pebinaryexecutor/pebinary.go
pkg/podexecutor/staticpod.go

Add etcd extra-args support to RKE2
CLI/functionality
https://github.com/k3s-io/k3s/pull/4463#issuecomment-969205988
https://github.com/rancher/rke2/issues/2135

[master] Add etcd extra-args support to RKE2

---

go.mod
go.sum

Bump k3s to include:
https://github.com/k3s-io/k3s/pull/4494
https://github.com/k3s-io/k3s/pull/4477
https://github.com/rancher/rke2/issues/2129

[Release-1.21] Bump k3s

---

go.mod
go.sum

Bump k3s to include:
https://github.com/k3s-io/k3s/pull/4494
https://github.com/k3s-io/k3s/pull/4477
https://github.com/k3s-io/k3s/pull/4506
https://github.com/rancher/rke2/issues/2130

[Release-1.20] Bump K3s for parser fixes

---

developer-docs/image_sources.md

Update developer docs
docs
n/a
n/a

SR-IOV chart lives in rancher-charts

---

pkg/rke2/rke2_linux.go

The AWS cloud provider expects the node name of a node to have a
specific form. If the user sets the hostname of the of the underlying
machine to a custom name, then the node will fail to bootstrap because
the node will not have the expected name.
With this change, the node name is fetched from the metadata endpoint to
ensure it has the proper value. If this fails, then it will fallback to
the hostname command.

Get node name from metadata if AWS cloud provider is enabled

---

Dockerfile
scripts/build-images

Bump rancher-vsphere charts+images
chart version bump
Launch rke2 cluster with rancher-vsphere cloud provider; confirm that it works and proper images are used.
* https://github.com/rancher/rke2/issues/2168

Bump vsphere charts+images

---

Dockerfile
scripts/build-images

This reverts commit 126a8cba3ca6ed7bb30b9976c24f6c758735093b.
Reverts previously commited Calico update.
#2188

Revert "Update Calico chart to v3.20.2"

---

channels.yaml

Mark v1.22.3+rke2r1 as stable
channel server
Run install.sh
* https://github.com/rancher/rke2/issues/2046

Mark v1.22.3+rke2r1 as stable

---

go.mod
go.sum
pkg/cli/cmds/agent.go
pkg/cli/cmds/etcd_snapshot.go
pkg/cli/cmds/server.go

Pull in K3s change https://github.com/k3s-io/k3s/pull/4613
Modify valid flags for each rke2 command
Bugfix
https://github.com/rancher/rke2/issues/2196

[Release-1.20] Enable Rke2 parser to skip flags

---

go.mod
go.sum
pkg/cli/cmds/agent.go
pkg/cli/cmds/etcd_snapshot.go
pkg/cli/cmds/server.go

Pull in K3s change https://github.com/k3s-io/k3s/pull/4613
Modify valid flags for each rke2 command
Bugfix
https://github.com/rancher/rke2/issues/2195

[Release-1.21] Enable Rke2 parser to skip flags

---

go.mod
go.sum
pkg/cli/cmds/agent.go
pkg/cli/cmds/etcd_snapshot.go
pkg/cli/cmds/server.go

Pull in K3s change https://github.com/k3s-io/k3s/pull/4621
Modify valid flags for each rke2 command
Bugfix
https://github.com/rancher/rke2/issues/2194

Enable Rke2 parser to skip flags

---

docs/security/about_hardened_images.md
mkdocs.yml

Added new section for hardened images

---

docs/install/install_options/server_config.md

Update docs for new server arg
docs
Should be present at https://docs.rke2.io/install/install_options/server_config/
https://github.com/rancher/rke2/issues/2193

Add newly available etcd-arg to the docs

---

Dockerfile

[ Release-1.20 ] - remove socat from dockerfile (#2210)

---

Dockerfile

[ Release-1.21 ] - remove socat from dockerfile (#2210)

---

channels.yaml

mark 1.22.4 stable

---

install.ps1

Updates the install script to account for an issue when doing a local binary install without a local images tarball.
Bugfix
Testing the installation to ensure that it still works.
* https://github.com/rancher/rancher/issues/35740

Fixing bugs with a local binary install without local images.

---

channels.yaml

update channel server

---

docs/install/linux_uninstall.md

Changed url for uninstall & killall scripts so that the latest versions are pulled from master.
(if docs on docs.rancher does not auto-popupate, then yes.
Document update
Both urls can be curled, tested running on local. 
Linked to yesterday's pull-req / issue : https://github.com/rancher/rke2/issues/2216

[ Linux  - DOCS ] Always fetch the latest uninstall and killal scripts

---

docs/install/quickstart.md

Closes https://github.com/rancher/docs/issues/3651
Reference: https://docs.rke2.io/install/quickstart/#prerequisites

Added notes on apparmor_parser install

---

manifest-runtime.tmpl

Signed-off-by: raulcabello <raul.cabello@suse.com>

Remove extra space in s390x manifest runtime template

---

docs/install/requirements.md

Bump minimum requirements to reasonable minimums to be able to actually be able to run something other than RKE2 on the node.
Docs
N/A
https://github.com/rancher/rke2/issues/2262

Bump minimum requirements for RKE2 to reasonable minimums

---

go.mod
go.sum

[ Release-1.21 ] - Update k3s

---

go.mod
go.sum

[ Release-1.20 ] - Update k3s in release-1.20

---

go.mod
go.sum

Update k3s in master

---

Dockerfile

Related issue: https://github.com/harvester/harvester/issues/1659
Dependency: https://github.com/rancher/rke2-charts/pull/200

Bump harvester cloud provider and harvester csi driver

---

go.mod
go.sum

Bump k3s to include https://github.com/k3s-io/k3s/commit/80577a1bd259cbe651485a15b7e79a03b5fffd7b
https://github.com/rancher/rke2/issues/2277

K3s Bump to fix cold restart issue

---

go.mod
go.sum

Bump k3s to include https://github.com/k3s-io/k3s/commit/962113d4a09eac975037c9d0608e32af88730476
https://github.com/rancher/rke2/issues/2277

[Release-1.21] K3s Bump to fix cold restart issue

---

go.mod
go.sum

Pull through fix for config validation issue found by QA
K3s update
* https://github.com/k3s-io/k3s/issues/4773

[release-1.20] Bump RKE2 to v1.20.14-rc2+rke2r1

---

go.mod
go.sum

Pull through fix for config validation issue found by QA
K3s update
* https://github.com/k3s-io/k3s/issues/4773

[release-1.21] Bump RKE2 to v1.21.8-rc2+rke2r1

---

go.mod
go.sum

Pull through fix for config validation issue found by QA
K3s update
* https://github.com/k3s-io/k3s/issues/4779

Bump RKE2 to v1.22.5-rc2+rke2r1

---

pkg/cli/cmds/root.go

Adds check for etcd group when running in CIS mode.
Adds a check for the etcd group and errors if it doesn't exist.
Run rke2 in cis mode with only the etcd user create. Notice the error indicating that the etcd group does not exist.
#2288

add check for etcd group

---

pkg/cli/cmds/root.go

add check for etcd group (#2290)

---

go.mod
go.sum

Updates k3s: https://github.com/k3s-io/k3s/compare/7e79ba7afd1f...bcd63e54dd9f1aa145bc063140ed4573009631ae
bugfix
* https://github.com/rancher/rke2/issues/2287

Bump versions for v1.20.14-rc3+rke2r1

---

go.mod
go.sum

Updates k3s: https://github.com/k3s-io/k3s/compare/7e79ba7afd1f...bcd63e54dd9f1aa145bc063140ed4573009631ae
bugfix
* https://github.com/rancher/rke2/issues/2287

Bump versions for v1.21.8-rc3+rke2r1

---

go.mod
go.sum

Updates k3s: https://github.com/k3s-io/k3s/compare/405bf79da978...05f1bc6e2a62a995564341b48e1191839f9b7e0f
bugfix
* https://github.com/rancher/rke2/issues/2287

Bump versions for v1.22.5-rc3+rke2r1

---

docs/index.md

Fixed typo.

---

install.ps1

Strong push-back from the windows rke2 team has necessitated reverting rancher/rke2#2346.

Revert "Add Adminstrator check to windows install.ps1"

---

Dockerfile
docs/install/network_options.md
scripts/build-images

Backport: https://github.com/rancher/rke2/pull/2353
Issue: https://github.com/rancher/rke2/issues/2351

[Release 1.22] Update canal chart

---

Dockerfile
scripts/build-images

Backport: https://github.com/rancher/rke2/pull/2353
Issue: https://github.com/rancher/rke2/issues/2352

[Release 1.21] Update canal chart

---

Dockerfile
scripts/build-images

Update Cilium from 1.10.4 to 1.11.0.
https://github.com/cilium/cilium/releases/tag/v1.11.0
Ref: rancher/rke2#2242
Depenndency update
No
Dependency update
It can be verified by deploying rke2 with Cilium according to the following instructions:
https://docs.rke2.io/install/network_options/
rancher/rke2#2242

Update Cilium to 1.11.0

---

Dockerfile
scripts/build-images

Use the latest canal, with latest flannel and latest calico
Version bumps
Deploy rke2 (cni: canal is default)
https://github.com/rancher/rke2/issues/2370

Update canal to latest

---

install.sh

This reverts commit 354360876758c32dea1583cd2a1aaa147e9250c9.

Revert "Modify install script to enable SLE Micro installation (#2366)"

---

docs/install/network_options.md

Added information about new option regarding wireguard option with Flannel upgrade in v1.23 (See #2370)

Add information about wireguard

---

docs/install/requirements.md

Closes #1996 
Reference: [Networking docs](https://docs.rke2.io/install/requirements/#networking)

Added additional inbound rules for Calico, Canal, Cilium

---

Dockerfile
scripts/build-images

Also, include the Helm chart fix submitted via rancher/rke2-charts#215
Ref: rancher/rke2#2242
Update Cilium to 1.11.1 and include a Helm chart bugfix.
Dependency update
It can be verified by deploying rke2 with Cilium according to the following instructions:
https://docs.rke2.io/install/network_options/
#2242

Update Cilium to 1.11.1

---

docs/install/requirements.md

Related PR #2381 
Updating port requirements per @manuelbuil from feedback in Slack.

Updated CNI ports per Slack feedback

---

docs/adrs/001-record-architecture-decisions.md
docs/adrs/002-rke2-rpm-support.md

Add ADR template + ADR for RPM publishing decision
Docs/ADR
N/A

Add ADR template + ADR for RPM publishing

---

Dockerfile
scripts/build-images

Update Calico version to 3.21.4
Version update
Configure calico using https://docs.rke2.io/install/network_options/
#2417

Update calico version to 3.21.4

---

Dockerfile

Use the newer canal chart including two CRDs which were missing
No
Version bump
Deploy canal and check that it works. Verify that the new crds are installed:
- ipreservations.crd.projectcalico.org
- kubecontrollersconfigurations.crd.projectcalico.org
https://github.com/rancher/rke2/issues/2425

Update canal to newer chart with bugfix

---

Dockerfile
scripts/build-images

Update Calico version to 3.22.0
Version update
Configure calico using https://docs.rke2.io/install/network_options/
#2438

Update calico to v3.22.0

---

pkg/rke2/psp_templates.go

add apparmor and seccomp annotations

---

pkg/podexecutor/staticpod.go
pkg/rke2/rke2_linux.go
pkg/rke2/rke2_windows.go

Backport of https://github.com/rancher/rke2/pull/1419 to release-1.21
https://github.com/rancher/rke2/issues/2446

[Release-1.21] Made audit-policy-file flag independent of CIS profile flag

---

pkg/rke2/psp_templates.go

add seccomp annotations to unrestricted PSP (#2440)

---

Dockerfile
scripts/build-images

This PR updates calico to v3.21.4 and fixes the calico-kubecontrollers feature
Version bump + bugfix
Enable the feature calicoKubeControllers by setting it to true,
https://github.com/rancher/rke2/issues/2425

Update canal to v3.21.4 and fix calico-kube-controllers

---

Dockerfile
scripts/build-images

Backport: https://github.com/rancher/rke2/pull/2451
Issue: https://github.com/rancher/rke2/issues/2427

[Release 1.22] Update canal to v3.21.4

---

Dockerfile
scripts/build-images

Backport: https://github.com/rancher/rke2/pull/2451
Issue: https://github.com/rancher/rke2/issues/2428

[Release 1.21] Update canal to v3.21.4

---

Dockerfile
charts/build-chart.sh
pkg/bootstrap/bootstrap.go

* #2456
* #2457
Bugfix
See original PRs and linked issues
* https://github.com/k3s-io/helm-controller/issues/110
* https://github.com/rancher/dashboard/issues/4442

[release-1.21] Helm Chart improvements

---

Dockerfile
charts/build-chart.sh
pkg/bootstrap/bootstrap.go

* #2456
* #2457
Bugfix
See original PRs and linked issues
* https://github.com/k3s-io/helm-controller/issues/110
* https://github.com/rancher/dashboard/issues/4442

[release-1.20] Helm Chart improvements

---

Dockerfile

Update kube proxy for February Release

update kube-proxy for February release

---

docs/advanced.md

Closes [#3878](https://github.com/rancher/docs/issues/3878).

Added section to rotate secrets encryption keys

---

developer-docs/upgrading_kubernetes.md

Add missing step to RC release.

Update docs: changes to creating a release

---

channels.yaml

Update channel server latest for February release

---

tests/e2e/resource_files/loadbalancer.yaml
tests/e2e/scripts/latest_commit.sh
tests/e2e/testutils.go
tests/e2e/upgradecluster/Vagrantfile
tests/e2e/upgradecluster/upgradecluster_test.go
tests/e2e/vagrantdefaults.rb
tests/e2e/validatecluster/Vagrantfile
tests/e2e/validatecluster/validatecluster_test.go

Added new upgradeCluster test
Consolidate common vagrant code
Update validateCluster test with loadbalancer check
New Test
`go test -timeout=15m -v ./tests/e2e/upgradecluster/... -run E2E`
N/A internal testing change only

E2E Upgradecluster test 

---

pkg/cli/cmds/k3sopts.go
pkg/cli/cmds/secrets_encrypt.go

Backport of https://github.com/rancher/rke2/pull/2540
https://github.com/rancher/rke2/issues/2546

[Release-1.22] Process secrets-encrypt subcommands and added ignore option

---

pkg/cli/cmds/k3sopts.go
pkg/cli/cmds/secrets_encrypt.go

Backport of https://github.com/rancher/rke2/pull/2540
https://github.com/rancher/rke2/issues/2545

[Release-1.21] Process secrets-encrypt subcommands and added ignore option

---

Dockerfile
scripts/build-images

Bump calico version to v3.22.1 and especially calico-operator:v1.25.3, which fixes the windows problem
https://github.com/rancher/rke2/issues/2556

Update calico to v3.22.1

---

Dockerfile.windows

https://github.com/rancher/rke2/issues/2575

bump containerd to 1.5.10, remove wins and flannel

---

Dockerfile.windows

https://github.com/rancher/rke2/issues/2573

[release-1.22] Bump windows containerd to v1.5.10

---

Dockerfile
scripts/build-images

Backport: https://github.com/rancher/rke2/pull/2564
Issue: https://github.com/rancher/rke2/issues/2565

[Release 1.22] Update calico chart

---

Dockerfile

remove line breaks

---

Dockerfile

Related issue:
https://github.com/rancher/rancher/issues/36716
https://github.com/harvester/harvester/issues/1999
Dependency: https://github.com/rancher/rke2-charts/pull/227
Signed-off-by: yaocw2020 <yaocanwu@gmail.com>

Bump harvester-cloud-provider 0.1.10

---

Dockerfile

Bump harvester-cloud-provider 0.1.10 
Backport of https://github.com/rancher/rke2/pull/2590
version bump
TBD

[release-1.21] Bump harvester-cloud-provider 0.1.10

---

.drone.yml

Use EIO fossa plugin (#2582)

---

Dockerfile
scripts/build-images

Issue: https://github.com/rancher/rke2/issues/2608
Cherry-pick: https://github.com/rancher/rke2/pull/2607

[Release 1.22] Update Cilium to 1.11.2

---

Dockerfile
scripts/build-images

Version bump of Cilium. Yes, it requires an update in the documentation
Version bump
Deploy with `cni: cilium`
https://github.com/rancher/rke2/issues/2604

Update Cilium to 1.11.2

---

Dockerfile.windows

PR number two :) 
https://github.com/rancher/rke2/issues/2573

[release-1.22] bump containerd to 1.5.10 for windows, rm wins/flannel

---

.gitignore
scripts/build-image-runtime
scripts/package-windows-images

Backport of https://github.com/rancher/rke2/pull/2601
Ignore vagrant build files
https://github.com/rancher/rke2/issues/2616

[Release-1.22] Explicitly retag runtime for linux and windows

---

.drone.yml
Dockerfile
Makefile
go.mod
go.sum
install.sh
manifest-runtime.tmpl
scripts/build-binary
scripts/build-image-runtime
scripts/build-image-test
scripts/build-images
scripts/build-windows-binary
scripts/build-windows-images
scripts/dev-runtime-image
scripts/package-windows-binary
scripts/package-windows-bundle
scripts/publish-image-runtime

This PR adds support for the s390x architecture in rke2.
New feature
See https://confluence.suse.com/pages/viewpage.action?spaceKey=PM&title=Rancher+on+Z+Test+Plan for reference

[release-1.22] - Add s390x support

---

.drone.yml
Dockerfile
Makefile
go.mod
go.sum
manifest-runtime.tmpl
scripts/build-binary
scripts/build-image-runtime
scripts/build-image-test
scripts/build-images
scripts/build-windows-binary
scripts/build-windows-images
scripts/dev-runtime-image
scripts/package-windows-binary
scripts/package-windows-bundle
scripts/publish-image-runtime

This PR adds support for the s390x architecture in rke2.
New feature
See https://confluence.suse.com/pages/viewpage.action?spaceKey=PM&title=Rancher+on+Z+Test+Plan for reference

Add support for s390x arch

---

docs/install/network_options.md

Docs update
Doc updates
https://github.com/rancher/rke2/issues/2604

[docs] Update cilium docs

---

docs/adrs/003-rke2-rpm-sle-support.md

Add ADR for SUSE OS distribution RPMs
DOCS/ADR
N/A

ADR for SLE RPM support

---

scripts/build-image-runtime
scripts/package-windows-images

Backport of https://github.com/rancher/rke2/pull/2601
https://github.com/rancher/rke2/issues/2629

[Release-1.21] Explicitly retag runtime for linux and windows

---

Dockerfile
bundle/bin/rke2-killall.sh
scripts/build-images

Updates canal chart with a new flannel image that fixes a couple of bugs
https://github.com/rancher/rke2/issues/2599
https://github.com/rancher/rke2/issues/2605

Fix canal bugs

---

bundle/bin/rke2-uninstall.sh
install.sh

- Adding ability to install rke2 on SLE systems using rpms
- Fixing uninstall script to detect both rpm and tarball installations on SLE
- Fix method conflict to to detect tarball installation
This change applies design decision in https://github.com/rancher/rke2/pull/2409
Enhancement
https://github.com/rancher/rke2/issues/2628

Add rpm installation support for SLE systems

---

.github/workflows/install.yaml
developer-docs/testing.md
tests/vagrant/install/rocky-8/README.md
tests/vagrant/install/rocky-8/Vagrantfile

Drop in replacement of CentOS 8 with rocky 8 in the install vagrant testing.
Testing 
Smoke test for Rocky 8
`vagrant up` and following the provision calls [here](https://github.com/rancher/rke2/blob/master/.github/workflows/install.yaml#L58)
https://github.com/rancher/rke2/issues/2550

Replace CentOS 8 with Rocky Linux 8 for install testing

---

Dockerfile
bundle/bin/rke2-killall.sh
scripts/build-images

[release 1.21] Fix canal bug

---

docs/advanced.md

Fix docs problem:
* rke2-kube-proxy cannot be disabled via the disable flag
* rke2-canal was missing in the list of valid values
Docs fix
https://github.com/rancher/rke2/pull/2036

Fix doc inconsistency with --disable flag

---

pkg/rke2/rke2.go

Adding force-restart file to the rke2 data dir after restoration, this will force rke2 to restart the etcd static pod on the next run
bufix
- start rke2 server
- take snapshot
- restore snapshot on fresh/existing node
- run rke2 server 
https://github.com/rancher/rke2/issues/2301

Add force-restart file when cluster-reset-restore-path is passed

---

Dockerfile
scripts/build-images

Bump coredns to 1.9.1
Waiting on merge of https://github.com/rancher/rke2-charts/pull/233
version bump
`cricl image ls`
* https://github.com/rancher/rke2/issues/2649

Bump coredns to 1.9.1

---

pkg/rke2/rke2.go

Backport fix for restoring snapshot without running killall script
#2652

[release-1.22] Add force-restart file when cluster-reset-restore-path is passed

---

Dockerfile
scripts/build-images

Bump coredns to 1.9.1
Waiting on merge of https://github.com/rancher/rke2-charts/pull/233
version bump
`cricl image ls`
* https://github.com/rancher/rke2/issues/2650

[release-1.22] Bump coredns to 1.9.1

---

pkg/rke2/rke2.go

Backport fix for restoring snapshot without running killall script
#2653

[release-1.21] Add force-restart file when cluster-reset-restore-path is passed

---

Dockerfile
scripts/build-images

Bump coredns to 1.9.1
Waiting on merge of https://github.com/rancher/rke2-charts/pull/233
version bump
`cricl image ls`
* https://github.com/rancher/rke2/issues/2651

[release-1.21] Bump coredns to 1.9.1

---

bundle/bin/rke2-uninstall.sh

Fix uninstall script in tarball method to check if the /usr/local is read only fs in SLE systems, if so then we use /opt/rke2 as the default installation prefix
bug fix
In SLES (with transactional updates disabled):
- install rke2 using curl and tarball method (default)
- uninstall using rke2-uninstall.sh
- make sure that /var/lib/rancher/rke2 is removed
- https://github.com/rancher/rke2/issues/2691

Fix uninstall script on SLES

---

bundle/bin/rke2-uninstall.sh

backport for 
- https://github.com/rancher/rke2/pull/2692

[Release-1.22] Fix uninstall script in SLES systems

---

bundle/bin/rke2-uninstall.sh

backport for:
- https://github.com/rancher/rke2/pull/2692

[Release-1.21] Fix uninstall script in SLES systems

---

go.mod
go.sum

Updates k3s: https://github.com/k3s-io/k3s/compare/542771151c4e...1339626a5b40dd9464f3a9e8d8e12d065ef5bf22
bugfix
* https://github.com/rancher/rke2/issues/2682

Bump K3s version for v1.23

---

go.mod
go.sum

Updates k3s: https://github.com/k3s-io/k3s/compare/9f7530c5b3fc...4cc9a48c1bf27369ccdde140c56a540116e595b8
bugfix
* https://github.com/rancher/rke2/issues/2682

[release-1.22] Bump K3s version for v1.22

---

go.mod
go.sum

Updates k3s: https://github.com/k3s-io/k3s/compare/3a8910f0b4c9...90ce62ceaacd612a3d06d4c3556be371e5b2cd72
bugfix
* https://github.com/rancher/rke2/issues/2682

[release-1.21] Bump K3s version for v1.21

---

channels.yaml

Mark v1.22.8 as stable.
Updates channel server.

mark v1.22.8 stable

---

developer-docs/upgrading_kubernetes.md

Update Kubernetes upgrade documentation.

Update Kubernetes upgrade documentation

---

docs/install/containerd_registry_configuration.md

See also https://github.com/rancher/rke2/issues/915
Addresses https://github.com/rancher/rke2/issues/2707

[Docs] Document registry mirror rewrite configuration

---

bundle/bin/rke2-killall.sh

Backport: https://github.com/rancher/rke2/pull/2727
Issue: https://github.com/rancher/rke2/issues/2625

[Release 1.22] Add message in the killall script

---

bundle/bin/rke2-killall.sh

Issue: https://github.com/rancher/rke2/issues/2626
Backport: https://github.com/rancher/rke2/pull/2727

[Release 1.21] Add message in the killall script

---

developer-docs/upgrading_kubernetes.md

Update documentation regarding the components outside of RKE2 built downstream upon release
Documentation update
Proofreading 
N/A
None

List downstream release projects

---

Dockerfile

Issue: https://github.com/rancher/rke2/issues/2746
Backport: https://github.com/rancher/rke2/pull/2744

[Release 1.22] Update cilium to support automatic dual-stack config

---

Dockerfile

Issue: https://github.com/rancher/rke2/issues/2747
Backport: https://github.com/rancher/rke2/pull/2744

[Release 1.21] Update cilium to support automatic dual-stack config

---

Dockerfile
scripts/build-images

Bump harvester cloud provider 0.1.11

---

Dockerfile
scripts/build-images

version bump
backport of https://github.com/rancher/rke2/pull/2754
TBD

[release-1.21] Bump harvester cloud provider 0.1.11

---

Dockerfile
scripts/build-images

Bump Harvester CSI Driver chart
see more details on https://github.com/harvester/harvester/issues/2151#issuecomment-1100002624
https://github.com/rancher/rke2/issues/2776

Bump Harvester csi to v0.1.11

---

.drone.yml

This is done since s390x support is being planned for GA

[Release-1.22] Remove failure:ignore tag for s390x pipeline

---

.drone.yml

This is done since s390x support is being planned for GA

[Release-1.21] Remove failure:ignore tag for s390x pipeline

---

.drone.yml

Revert "[Release-1.22] Remove failure:ignore tag for s390x pipeline"

---

.drone.yml

Revert "[Release-1.21] Remove failure:ignore tag for s390x pipeline"

---

go.mod
go.sum

Brings in 
https://github.com/k3s-io/k3s/pull/5496
https://github.com/k3s-io/k3s/pull/5480
Bump K3s

[Release-1.21] Bump k3s for April Fixes

---

go.mod
go.sum

Brings in 
https://github.com/k3s-io/k3s/pull/5498
https://github.com/k3s-io/k3s/pull/5479
Bump K3s

[Release-1.22] Bump k3s for April Fixes

---

go.mod
go.sum

Brings in 
https://github.com/k3s-io/k3s/pull/5495
https://github.com/k3s-io/k3s/pull/5478
Bump K3s

Bump k3s for April Fixes

---

Dockerfile
go.mod
go.sum

Bump containerd for selinux fix:
* https://github.com/opencontainers/selinux/issues/172
bugfix
* https://github.com/rancher/rke2/issues/2808

Bump containerd for selinux fix

---

Dockerfile
go.mod
go.sum

Bump containerd for selinux fix:
* https://github.com/opencontainers/selinux/issues/172
bugfix
* https://github.com/rancher/rke2/issues/2809

[release-1.22] Bump containerd for selinux fix

---

Dockerfile
scripts/build-images

Upgrade ingress nginx chart and images

---

Dockerfile
scripts/build-images

[Release-1.22] Upgrade ingress nginx chart and images

---

Dockerfile
scripts/build-images

[Release-1.21] Upgrade ingress nginx chart and images

---

bundle/bin/rke2-killall.sh

Added `flannel-v6.1` delete on killall script
#2810

Added flannel-v6.1 delete on killall script

---

channels.yaml

Mark 1.22.9 as stable

---

Dockerfile

Bump rke2-ingress-nginx to remove accidentally committed .orig files
bugfix
* https://github.com/rancher/rke2/issues/2835

Bump rke2-ingress-nginx to remove accidentally committed .orig files

---

Dockerfile

Bump rke2-ingress-nginx to remove accidentally committed .orig files
bugfix
* https://github.com/rancher/rke2/issues/2835

[release-1.22] Bump rke2-ingress-nginx to remove accidentally committed .orig files

---

Dockerfile

Bump rke2-ingress-nginx to remove accidentally committed .orig files
bugfix
* https://github.com/rancher/rke2/issues/2835

[release-1.21] Bump rke2-ingress-nginx to remove accidentally committed .orig files

---

docs/upgrade/automated_upgrade.md

Improve docs readability and increase upgrade controller version
Docs

Bump upgrade controller version and improve readability

---

Dockerfile
scripts/build-images

Bumps Cilium to the latest version
Version bump
Typical CNI verification
https://github.com/rancher/rke2/issues/2859

Update Cilium version

---

Dockerfile
scripts/build-images

Updates calico version
Version bump
Regular cni verification
https://github.com/rancher/rke2/issues/2860

Update calico version

---

Dockerfile
scripts/build-images

Version bump
Deploy multus and check that the versions are the newer ones
https://github.com/rancher/rke2/issues/2853

Update Multus chart and sriov/multus images

---

Dockerfile
scripts/build-images

Issue: https://github.com/rancher/rke2/issues/2875
Backport: https://github.com/rancher/rke2/issues/2859

[Release 1.22] Update Cilium version

---

Dockerfile
scripts/build-images

Backport: https://github.com/rancher/rke2/issues/2859
Issue: https://github.com/rancher/rke2/issues/2874

[Release 1.21] Update Cilium version

---

channels.yaml

Signed-off-by: Jonnatan Jossemar Cordero <jonnatan.cordero@suse.com>

Update rke2 channel

---

docs/advanced.md
docs/backup_restore.md
docs/install/requirements.md
docs/security/secrets_encryption.md
docs/subcommands.md
docs/upgrade/automated_upgrade.md
docs/upgrade/basic_upgrade.md

Update docs
Documentation
N/A
Resolves: https://github.com/rancher/rke2/issues/2862
Resolves: https://github.com/rancher/rke2/issues/2839
Resolves: https://github.com/rancher/rke2/issues/2726
No testing needed on linked issues so gave them the resolves keyword so that it will automatically close for us.

multiple docs updates

---

mkdocs.yml

Related to https://github.com/rancher/rke2/pull/2894 -- didn't realize I needed to add the new page to the sidebar via this file.

Include subcommands in docs sidebar

---

.drone.yml
Dockerfile

Bump containerd to fix missing s390x arch
Also bump a base image reference that I missed.
version bump / CI
See CI build status
* TBD

Bump containerd for S390x

---

Dockerfile
scripts/build-images

Update Canal to 3.22.2
CNI version update
#2881

Update canal to 3.22.2

---

Dockerfile
scripts/build-images

Update Canal to version 3.22.2
#2905

[Release 1.23] Update canal to 3.22.2

---

Dockerfile
scripts/build-images

[Release 1.22] Updated canal to 3.22.2

---

Dockerfile

Update calico to newest version
Version bump
https://github.com/rancher/rke2/issues/2887

Update calico to newest version to fix bug

---

Dockerfile

Update the multus chart
Version bump
Deploy rke2 + multus and verify that things are still working
https://github.com/rancher/rke2/issues/2918

Update multus to the latest chart version

---

Dockerfile

Backport: https://github.com/rancher/rke2/pull/2921
Issue:https://github.com/rancher/rke2/issues/2919

[Release 1.23] Update multus to the latest chart version

---

Dockerfile
scripts/build-images

Backport: https://github.com/rancher/rke2/pull/2921
Issue: https://github.com/rancher/rke2/issues/2920

[Release 1.22] Update multus to the latest chart version

---

scripts/validate
scripts/validate-release

Move window binaries check to CI validation
Backport PR of #2880
#2912

[Release 1.21] Move windows dependencies check to CI  (#2880)

---

bundle/bin/rke2-killall.sh
pkg/staticpod/staticpod.go

Fixed URL to support IPv6 only setup. Updated killall script for new Calico version.
It supports IPv6 only setup when the CNI is Canal or Calico. (Cilium is not fully supported yet)
#2861

Ipv6 support

---

Dockerfile
install.sh
scripts/build
scripts/dev-rpm
scripts/package-dev-rpm
scripts/publish-dev-rpm

Backport of #2542
* Package commit as dev rpm's
* Add RKE2 dev rpm installation support
* Delegate RKE2 commit rpm fetch process to zypper
Development workflow enhancement
#2933

[Release 1.23] Support dev rpm creation and installation

---

Dockerfile
install.sh
scripts/build
scripts/dev-rpm
scripts/package-dev-rpm
scripts/publish-dev-rpm

Backport of #2542
* Package commit as dev rpm's
* Add RKE2 dev rpm installation support
* Delegate RKE2 commit rpm fetch process to zypper
Development workflow enhancement
#2934

[Release 1.22] Support dev rpm creation and installation

---

Dockerfile
install.sh
scripts/build
scripts/dev-rpm
scripts/package-dev-rpm
scripts/publish-dev-rpm

Backport of #2542
* Package commit as dev rpm's
* Add RKE2 dev rpm installation support
* Delegate RKE2 commit rpm fetch process to zypper
Development workflow enhancement
#2935

[Release 1.21] Support dev rpm creation and installation

---

scripts/package-bundle

Backport of #2928
* Ignore windows binaries when creating linux bundle
#2943

[Release 1.22]  ignore windows binaries when creating linux bundle

---

scripts/package-bundle

Backport of #2928
* Ignore windows binaries when creating linux bundle
#2944

[Release 1.21]  ignore windows binaries when creating linux bundle

---

Dockerfile

Update calico chart to set tigera-operatot pod on the right namespace to update calico.
#2932

Updated Calico chart to fix update

---

Dockerfile
scripts/build-images

Updated Calico to v3.23.1
#2949

Updated Calico to v3.23.1

---

bundle/bin/rke2-killall.sh
pkg/staticpod/staticpod.go

Backport for IPv6 only support
#2951

[Release 1.23] ipv6 support

---

Dockerfile
scripts/build-images

Update Calico to v3.23.1
#2953

[Release 1.23] Updated Calico to v3.23.1

---

pkg/staticpod/staticpod.go

Backport for IPv6 support
#2955

[release 1.22] Fixed IPv6 only support

---

bundle/bin/rke2-killall.sh

Updated `rke2-killall.sh` to remove `flannel-wg` and `flannel-wg-v6` interfaces
#2960

Added flannel wireguard interface deletion

---

docs/install/network_options.md

Update network installation doc
#2861

Update network_options.md 

---

bundle/bin/rke2-killall.sh

Backport for `flannel-wg` and `flannel-wg-v6` interfaces deletion.
#2962

[Release 1.23] Added flannel wireguard interface deletion

---

go.mod
go.sum
pkg/cli/cmds/server.go

* Bump K3s for calico egress-selector fix: 
https://github.com/k3s-io/k3s/pull/5577
* Auto-configure the egress selector mode based on CNI choice
bugfix
* https://github.com/rancher/rke2/issues/2930
Will require a docs update for the new flag

Bump K3s for calico egress-selector fix

---

Dockerfile

Signed-off-by: Roberto Bonafiglia <roberto.bonafiglia@suse.com>
Backport for canal ipv6 only fix
#2951

[Release 1.23] Fixed canal chart for IPv6 only setup

---

Dockerfile

Fixed Canal chart for IP6 only setup
#2861

Fixed canal chart for IPv6 only setup

---

Dockerfile
scripts/build-images

Update Cilium to 1.11.5 to fix a couple of CVEs
Version bump
https://github.com/rancher/rke2/issues/2970

Update Cilium to 1.11.5

---

Dockerfile
scripts/build-images

Backport: https://github.com/rancher/rke2/pull/2971
Issue: https://github.com/rancher/rke2/issues/2985

[Release 1.21] Update Cilium to 1.11.5

---

go.mod
go.sum

Updates k3s: https://github.com/k3s-io/k3s/compare/1ef34728c99b...29397b4e68cacc651659c7c3b4acc27e33f75e9f
bugfix
See linked issu
* #3000

Bump K3s version to fix issue with kubelet addresses

---

docs/install/network_options.md

Update dual-stack docs

---

pkg/podexecutor/staticpod.go
pkg/rke2/rke2_linux.go

Update default resource requests for control-plane and etcd components
enhancement
* https://github.com/rancher/rke2/issues/2885

Update default component requests

---

MAINTAINERS

removed dweomer from maintainers

---

Dockerfile
go.mod
go.sum
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/rke2/rke2.go
pkg/rke2/spw.go
pkg/staticpod/staticpod.go
scripts/build-images

Backport of https://github.com/rancher/rke2/pull/3054
https://github.com/rancher/rke2/issues/3056
https://github.com/rancher/rke2/issues/3059

[Release-1.23] Add Static Pod Startup Hook + K3s Bump + CoreDNS bump

---

Dockerfile
go.mod
go.sum
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/rke2/rke2.go
pkg/rke2/spw.go
pkg/staticpod/staticpod.go
scripts/build-images

Backport of https://github.com/rancher/rke2/pull/3054
https://github.com/rancher/rke2/issues/3057
https://github.com/rancher/rke2/issues/3060

[Release-1.22] Add Static Pod Startup Hook + K3s Bump + CoreDNS bump

---

Dockerfile

Update Cilium Chart to support IPv6 only config
#3065

Updated cilium chart to support IPv6 only config

---

Dockerfile

[Release 1.23] Updated cilium chart to support IPv6 only config

---

Dockerfile

[Release 1.22] Updated cilium chart to support IPv6 only config

---

Dockerfile
go.mod
go.sum
pkg/cli/cmds/server.go
pkg/rke2/rke2.go
pkg/rke2/spw.go
pkg/staticpod/staticpod.go
scripts/build-images

Backport of https://github.com/rancher/rke2/pull/3054
https://github.com/rancher/rke2/issues/3061

[Release-1.21] Add Static Pod Startup Hook + K3s Bump + CoreDNS bump

---

go.mod
go.sum
scripts/build-images

Bump K3s and helm-controller versions for v1.24
Updates k3s: https://github.com/k3s-io/k3s/compare/a9b5a1933fbd...a5414bb1fc904e3d44a6a66ccffa819340e712a8
bugfix
Check version of klipper-helm image used by cluster
* https://github.com/rancher/rke2/issues/3082

Bump K3s and helm-controller versions

---

channels.yaml

Updates stable channel to v1.22.10+rke2r2, and adds release channel for v1.24 in channel server #3048

Update channel server for May patch release

---

developer-docs/upgrading_kubernetes.md

adding additional line to update rke2

---

pkg/rke2/spw.go

Backport of https://github.com/rancher/rke2/pull/3117
https://github.com/rancher/rke2/issues/3114

[Release-1.23] Double numer of steps for criBackoff

---

pkg/rke2/spw.go

Backport of https://github.com/rancher/rke2/pull/3117
https://github.com/rancher/rke2/issues/3116

[Release-1.21] Double numer of steps for criBackoff

---

Dockerfile
scripts/build-images

version bump
https://github.com/rancher/rke2/issues/3142

Bump harvester cloud provider 0.1.13

---

Dockerfile
scripts/build-images

version bump
backport of https://github.com/rancher/rke2/pull/3138
https://github.com/rancher/rke2/issues/3142

[release-1.23] Bump harvester cloud provider 0.1.13

---

Dockerfile
scripts/build-images

version bump
backport of https://github.com/rancher/rke2/pull/3138
https://github.com/rancher/rke2/issues/3142

[release-1.22]Bump harvester cloud provider 0.1.13

---

docs/migration.md

Update migration docs to reflect that the procedure is experiment / unsupported.

update migration doc to reflect unsupported / experimental

---

pkg/rke2/spw.go

Backport of https://github.com/rancher/rke2/pull/3166

[Release-1.22] Consolidate staticPod timeout to static 30 minutes

---

pkg/rke2/spw.go

Backport of https://github.com/rancher/rke2/pull/3166

[Release-1.23] Consolidate staticPod timeout to static 30 minutes

---

channels.yaml

Signed-off-by: matttrach <matt.trachier@suse.com>

Updating stable to 1.23.9

---

README.md
docs/index.md

* Links to landscape.cncf.io have been broken in docs.
* Bugfix
* The new link works. (https://landscape.cncf.io/?selected=rke-government)
* Only fix broken links in docs, no code-level verification needed.
* No

Fix broken links to landscape.cncf.io in docs

---

Dockerfile
scripts/build-images

Updated Cilium to version 1.12.0
Version Update
#3181

Updated cilium to v1.12.0

---

Dockerfile
scripts/build-images

[Backport release-1.22] Updated cilium to v1.12.0

---

Dockerfile
scripts/build-images

[Backport release-1.23] Updated cilium to v1.12.0

---

pkg/rke2/np.go

Backport for https://github.com/rancher/rke2/pull/3220
- https://github.com/rancher/rke2/issues/3225

[Release-1.22] Add ingress network policy

---

pkg/rke2/np.go

Backport for https://github.com/rancher/rke2/pull/3220
- https://github.com/rancher/rke2/issues/3224

[Release-1.23] Add ingress network policy

---

docs/adrs/README.md
docs/adrs/adr-template.md

Signed-off-by: matttrach <matt.trachier@suse.com>
This establishes a format for ADRs, a process for updating them, and a process for revisiting them.
- This gives a 1 week proposal period where the group can deliberate before a decision is made.
- This gives a 1 week "cooling" period before revisiting a decision (unless additional context is added).
- This acknowledges a "stale by" date where decisions should be reconfirmed or revisited.

Adding format for adrs, adding process for updating and revisiting

---

docs/known_issues.md

Signed-off-by: rancher-max <max.ross@suse.com>
Documentation for network policies for cis mode and ingress.
Docs
N/A
https://github.com/rancher/rke2/issues/3195
N/A

Document ingress in CIS mode issue

---

Dockerfile
scripts/build-images

Backport: https://github.com/rancher/rke2/pull/3274
Issue: https://github.com/rancher/rke2/issues/3278

[Release 1.23] Update Cilium version

---

Dockerfile
scripts/build-images

Update flannel version to v0.19.1 and Calico to v3.23.3 on Canal
Version update
#3271

Update canal version

---

Dockerfile

Increase the Cilium chart version to incorporate preflight chart fixes.
Bugfix
The fixes were verified before submitting the fix to `rke2-charts` repo.
https://github.com/rancher/rke2/issues/3288
n/a

Bump the cilium chart version

---

Dockerfile

Issue: https://github.com/rancher/rke2/issues/3291
Backport: https://github.com/rancher/rke2/pull/3289

[Release 1.23] Bump the cilium chart version

---

Dockerfile

Backport: https://github.com/rancher/rke2/pull/3289
Issue: https://github.com/rancher/rke2/issues/3292

[Release 1.22] Bump the cilium chart version

---

Dockerfile
scripts/build-images

Update flannel version to v0.19.1 and Calico to v3.23.3 on Canal
Version update.
#3284

[Release 1.22] Update canal version

---

Dockerfile
scripts/build-images

Update flannel version to v0.19.1 and Calico to v3.23.3 on Canal
Version update
#3283

[Release 1.23] Update canal version

---

Dockerfile
scripts/build-images

Update Calico to v3.23.3
#3285

Update calico to v3.23.3

---

Dockerfile
scripts/build-images

Signed-off-by: Roberto Bonafiglia <roberto.bonafiglia@suse.com>
Update Calico to v3.23.3
#3285

[Release 1.24] Update calico to v3.23.3

---

Dockerfile
scripts/build-images

Update calico to v3.23.3
#3310

[Release 1.23] Update calico to v3.23.3

---

pkg/rke2/psa.go

Add exception for cis-operator-system namespace

---

pkg/rke2/rke2.go

Fix static pod cleanup when `--container-runtime-endpoint` (external CRI) is used.
Right now the code always tries to start and configure the kubelet to use the embedded containerd, which will fail if container-runtime-endpoint is set.
bugfix
* https://github.com/rancher/rke2/issues/3331
Note that when doing a cluster-reset using an external runtime (such as standalone containerd) the user will need to manually delete running containers using `crictl` after running rke2-killall.sh, as the killall script will not find and kill containers managed by the external runtime.
For example, if using standalone containerd, the user should run:
1. `rke2-killall.sh`
2. `export CONTAINER_RUNTIME_ENDPOINT=unix:///run/containerd/containerd.sock; /var/lib/rancher/rke2/bin/crictl ps -aq | …

[release-1.23] Fix static pod cleanup when using container-runtime-endpoint

---

pkg/podexecutor/staticpod.go
pkg/rke2/psa.go

Fix permissions of /etc/rancher/rke2 when created during startup.
bugfix
* https://github.com/rancher/rke2/issues/3339
Will need additional refactoring later to consolidate PSA and Audit Policy file creation logic.

Fix config directory permissions

---

Dockerfile
scripts/build-images
scripts/validate

Issue: https://github.com/rancher/rke2/issues/3342
Backport: https://github.com/rancher/rke2/pull/3340

[Release 1.24] Update calico to v3.24.1

---

Dockerfile
scripts/build-images
scripts/validate

Backport: https://github.com/rancher/rke2/pull/3340
Issue: https://github.com/rancher/rke2/issues/3341

[Release 1.23] Update calico to v3.24.1

---

install.sh

Fix distro version detection on EL9 variants
installer bugfix
* https://github.com/rancher/rke2/issues/3320

Fix distro version detection on EL9 variants

---

pkg/rke2/psa.go

https://github.com/rancher/rke2/issues/3365

Add exception for tigera-operator namespace (#3365)

---

docs/known_issues.md

Add another way to fix the problem
Yes, that's what this PR is about
Docs update

Update docs with extra option

---

docs/install/network_options.md
docs/known_issues.md

Docs update
Docs update
https://github.com/rancher/rke2/issues/3361

Update docs with iptables requirement on canal and calico

---

channels.yaml

Signed-off-by: Nikolai Shields <nikolai@nikolaishields.com>
Bump latest for September release.

Update latest in channels.yaml to v1.24.6+rke2r1

---

channels.yaml

Add v1.25 channel to the channel server

---

pkg/rke2/rke2.go

Pass through kubelet-args to temporary kubelet.
We also need to set `eviction-hard` to the same value as it is set to when
running the full kubelet, otherwise the Node Allocatable math comes out
different for the temporary kubelet, which will also cause failures.
bugfix
* https://github.com/rancher/rke2/issues/3417

Pass through kubelet-args to temporary kubelet

---

go.mod
go.sum
tests/terraform/.gitignore
tests/terraform/README.md
tests/terraform/cluster.go
tests/terraform/createcluster_test.go
tests/terraform/modules/define_node_role.sh
tests/terraform/modules/install_rke2_master.sh
tests/terraform/modules/join_rke2_agent.sh
tests/terraform/modules/join_rke2_master.sh
tests/terraform/modules/main.tf
tests/terraform/modules/master/instances_server.tf
tests/terraform/modules/master/outputs.tf
tests/terraform/modules/master/variables.tf
tests/terraform/modules/outputs.tf
tests/terraform/modules/providers.tf
tests/terraform/modules/variables.tf
tests/terraform/modules/worker/instances_worker.tf
tests/terraform/modules/worker/outputs.tf
tests/terraform/modules/worker/variables.tf
tests/terraform/resource_files/clusterip.yaml
tests/terraform/resource_files/daemonset.yaml
tests/terraform/resource_files/dnsutils.yaml
tests/terraform/resource_files/ingress.yaml
tests/terraform/resource_files/nodeport.yaml
tests/terraform/scripts/Dockerfile.build
tests/terraform/scripts/Jenkinsfile
tests/terraform/scripts/build.sh
tests/terraform/scripts/configure.sh
tests/terraform/testutils.go

Add terraform automation to rke2. This should allow users to create rke2 clusters in AWS easily, and in a repeatable fashion, using the terraform here. It also moves our terraform automation from the rancher/rancher Python framework directly here in the repo it belongs.
New feature primarily for testing
See README included in this PR for how to run tests.
N/A
I'm not a Go expert, so the Go code is likely really bad. Please feel free to let me know what to do better here and I can update as needed.
I've confirmed that the Jenkinsfile and build scripts provided succeed when running this in Jenkins. The output initially has a lot of terraform details for what it is doing, then gives the KUBECONFIG, followed by a detailed view of the cluster's nodes and pods (`kubectl get nodes,pods -A -o …

Initial terraform automation

---

Dockerfile
scripts/build-images

Bump vsphere CSI to v2.6.1
version bump; bugfix
* https://github.com/rancher/rke2/issues/3377#issuecomment-1267201423
* Waiting on https://github.com/rancher/rke2-charts/pull/290

Bump vsphere CSI to v2.6.1

---

Dockerfile

Update Canal chart to fix token renewal
Bugfix
#3425

Updated Canal chart to fix token renewal from calico-node

---

Dockerfile

[Release 1.24] Updated Canal chart to fix token renewal from calico-node

---

Dockerfile

[Release 1.23] Updated Canal chart to fix token renewal from calico-node

---

go.mod
go.sum

Updates k3s: https://github.com/k3s-io/k3s/compare/027039530d43...934d013614022a8310d45b39b22d9bc52c85fc94
bugfix
* https://github.com/rancher/rke2/issues/3437

Bump K3s version for v1.25

---

Dockerfile
scripts/build-images

Update canal to v3.24.1
Version bump which fixes a bug in canal
two things:
1 - Run the command: `kubectl get clusterinformations.crd.projectcalico.org -o yaml` and you should see `calicoVersion: v3.24.1`
2 - Verify calico images in the canal pod are using tag: `v3.24.1-build20221011`
https://github.com/rancher/rke2/issues/3424

Update canal to v3.24.1

---

Dockerfile
scripts/build-images

Backport: https://github.com/rancher/rke2/pull/3444
Issue: https://github.com/rancher/rke2/issues/3445

[Release 1.24] Update canal to v3.24.1

---

developer-docs/upgrading_kubernetes.md

Signed-off-by: Nikolai Shields <nikolai@nikolaishields.com>
Improve release documentation.

Update release docs to include content discussed during release retro

---

channels.yaml

Update channel server latest version

---

Dockerfile

Update Cilium chart to fix system-default-registry for some images
Bugfix
#3479

Updated cilium chart for private registry

---

tests/e2e/dualstack/Vagrantfile
tests/e2e/dualstack/dualstack_test.go
tests/e2e/scripts/ipv6.sh

Fix dualstack tests for IPv6
Bugfix
`go test -v -timeout=15m ./tests/e2e/dualstack/ -run E2E`
#3471

Fixed dualstack e2e tests

---

pkg/bootstrap/bootstrap.go

Use wrangler's YAML helpers to read/write the manifest with proper support for multiple documents (objects).
Also uses Unstructured helpers instead of the native type to rewrite HelmChart resources without the potential for dropping unknown fields.
bugfix
* https://github.com/rancher/rke2/issues/3469
* https://github.com/rancher/rke2/issues/527

Fix handling of manifests with multiple resources

---

docs/install/network_options.md

This PR syncs between rke2-docs and rke2. This is the PR that was created in rke2-docs: https://github.com/rancher/rke2-docs/pull/6
Documentations

Sync docs with rke2-docs

---

docs/install/install_options/windows_agent_config.md
pkg/windows/calico.go

Issue: https://github.com/rancher/rke2/issues/3523
Backport: https://github.com/rancher/rke2/pull/3517/commits/3b6e2cf4c10617f95df3bd9f9f930669b428da40

[Release 1.24] Read VXLAN_ADAPTER env and use it to create the external network

---

docs/install/install_options/windows_agent_config.md
pkg/windows/calico.go

Issue: https://github.com/rancher/rke2/issues/3525
Backport: https://github.com/rancher/rke2/pull/3517

[Release 1.23] Read VXLAN_ADAPTER env and use it to create the external network

---

Dockerfile

Update Calico chart to use PSP for tigera-operator for CIS-1.6
Run RKE2 with the following config
```
cni: calico
profile: "cis-1.6"
```
#3532

[Release 1.23] Update Calico chart to support PSP for CIS 1.6

---

Dockerfile

Update Calico chart to use PSP for tigera-operator for CIS-1.6
Run RKE2 with the following config
```
cni: calico
profile: "cis-1.6"
```
#3535

[Release 1.24] Update Calico chart to support PSP for CIS 1.6

---

Dockerfile

Backport: https://github.com/rancher/rke2/pull/3553
Issue: https://github.com/rancher/rke2/issues/3487

[Release 1.23] Fix cilium system default registry123

---

.drone.yml
Dockerfile

update crictl image tag, remove silent failure ignores

---

channels.yaml

update channels.yaml for November

---

tests/terraform/scripts/Jenkinsfile

Use environment variables for the few required vars to make the cluster creation Jenkins job easier to use.
Testing - Jenkins CI
Run tests in Jenkins
N/A
N/A

Utilize Jenkins env vars for required cluster creation variables

---

.drone.yml
Dockerfile
install.ps1
install.sh
scripts/build-upload
scripts/log-upload
scripts/publish-dev-rpm
tests/e2e/scripts/latest_commit.ps1
tests/e2e/scripts/latest_commit.sh

The GCS buckets have been migrated to S3, so the code has to be updated to push artifacts to the new S3 buckets.

switching from GCP gcs to AWS s3 buckets

---

tests/terraform/README.md
tests/terraform/cluster.go
tests/terraform/createcluster/createcluster_test.go
tests/terraform/resource_files/suc.yaml
tests/terraform/resource_files/upgrade-plan.yaml
tests/terraform/scripts/Jenkinsfile
tests/terraform/testutils.go
tests/terraform/upgradecluster/upgrade.go
tests/terraform/upgradecluster/upgradecluster_test.go

Added tests to perform cluster upgrades via our Terraform framework, using system-upgrade-controller upgrade path. This required a slight refactor to place separately scoped tests into different packages in order to run them separately.
Documentation updates to the README in tests/terraform were made as part of this.
Tests
Run the tests
https://github.com/rancher/rke2/issues/3582

Create upgrade test in TF and refactor to allow running packages separately

---

tests/e2e/mixedos/mixedos_test.go
tests/e2e/resource_files/pod_client.yaml
tests/e2e/resource_files/windows_app_deployment.yaml
tests/e2e/testutils.go

This PR tests the connectivity linux-windows which was broken in the previous releases (now fixed)
New test
https://github.com/rancher/rke2/issues/3593

Add more tests to the windows env

---

tests/terraform/modules/main.tf
tests/terraform/modules/master/instances_server.tf
tests/terraform/modules/master/variables.tf
tests/terraform/modules/variables.tf

Update var name in Terraform tests to be more clear.
```sh
$ docker build . -f ./tests/terraform/scripts/Dockerfile.build -t rke2-tf
$ docker run --name rke2-tf-creation-test -t -e AWS_ACCESS_KEY_ID=<redacted> -e AWS_SECRET_ACCESS_KEY=<redacted> -v /path/to/aws_key.pem:/go/src/github.com/rancher/rke2/tests/terraform/modules/config/.ssh/aws_key.pem rke2-tf sh -c "go test -timeout=30m -v ./tests/terraform/createcluster/..."
...
Ran 7 of 7 Specs in 561.341 seconds
SUCCESS! -- 7 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: Test_TFClusterCreateValidation (561.34s)
PASS
ok  	github.com/rancher/rke2/tests/terraform/createcluster	561.366s
```

Update tf variable for AWS to be more clear

---

tests/e2e/mixedos/mixedos_test.go
tests/e2e/resource_files/pod_client.yaml
tests/e2e/resource_files/windows_app_deployment.yaml
tests/e2e/testutils.go

Backport: https://github.com/rancher/rke2/pull/3594
Issue: https://github.com/rancher/rke2/issues/3604

[Release 1.24] add more tests to the windows env

---

tests/e2e/mixedos/mixedos_test.go
tests/e2e/resource_files/pod_client.yaml
tests/e2e/resource_files/windows_app_deployment.yaml
tests/e2e/testutils.go

Backport: https://github.com/rancher/rke2/pull/3594
Issue: https://github.com/rancher/rke2/issues/3605

[release 1.23] add more tests to the windows env

---

windows/rke2-quickstart.ps1

This PR includes a script that automates installing RKE2 in Windows instances to reduce the manual effort needed for setup and installation. 
That can be decided based on feedback from the team
No changes to the RKE2 codebase 
For testing,
- Setup a server node and install rke2
- Setup an Windows instance
- Download the script
- Run the script by providing serverIP, token and rke2 version
https://github.com/rancher/qa-tasks/issues/151

Add rke2 standalone install script for Windows

---

Dockerfile
scripts/build-images

Backport for #3625
Issue: #3623

[Release 1.24] Update Canal version

---

Dockerfile
scripts/build-images

Signed-off-by: thomasferrandiz <thomas.ferrandiz@suse.com>
update rke2-multus chart to v3.9-build2022102805
- BCI update: https://github.com/rancher/rke2/issues/3260
- whereabouts cronjob issue: https://github.com/rancher/rke2/issues/3603

update rke2-multus chart to v3.9-build2022102805

---

Dockerfile
scripts/build-images

Backport of https://github.com/rancher/rke2/pull/3622
Issue: https://github.com/rancher/rke2/issues/3632

[Backport 1.24] update multus chart to v3.9-build2022102805

---

Dockerfile
scripts/build-images

Backport of https://github.com/rancher/rke2/pull/3622
Issue: https://github.com/rancher/rke2/issues/3633

[Backport 1.23] update multus chart to v3.9-build2022102805

---

tests/terraform/modules/install_rke2_master.sh
tests/terraform/modules/join_rke2_agent.sh
tests/terraform/modules/join_rke2_master.sh
tests/terraform/scripts/Jenkinsfile

There was a typo in the Jenkinsfile where a letter is missing, so I fixed that. Also included `oracle` as a working node_os option so that we don't have to put `rhel8` every time we use this TF automation for an Oracle machine.

Fix Jenkinsfile typo and clarify support for oracle in TF automation

---

Dockerfile
scripts/build-images

Update cilium to v1.12.4 and added all the other cilium images
#3638 #3556

Updated cilium version and added new cilium images

---

Dockerfile
scripts/build-images

Bump metrics-server tag.
Should have bumped the date tag on the chart too, but oh well.
version bump
Check metrics-server image tag in running cluster
* TBD

Bump metrics-server tag

---

Dockerfile
scripts/build-images

[Release 1.24] Updated cilium version and added new cilium images

---

Dockerfile
scripts/build-images

[Release 1.23] Updated cilium version and added new cilium images

---

pkg/windows/calico.go
pkg/windows/types.go
pkg/windows/utils.go

Backport: https://github.com/rancher/rke2/pull/3615
Issue: https://github.com/rancher/rke2/issues/3634

[Release 1.24] Support autodetection interface methods in windows

---

Dockerfile

Fixed cilium chart when hubble is enabled
#3683

Fixed cilium chart when enabled hubble images

---

Dockerfile

backport for #3687
issue #3684

[Backport v1.25] Fixed cilium chart when enabled hubble images

---

Dockerfile

Backport for #3687 
issue #3685

[Backport v1.24] Fixed cilium chart when enabled hubble images

---

Dockerfile

Backport for #3687 
Issue #3686

[Backport v1.23] Fixed cilium chart when enabled hubble images

---

Dockerfile

Backport https://github.com/rancher/rke2/pull/3703 to release-1.25
https://github.com/rancher/rke2/issues/3708

[Release-1.25] Bump ingress-nginx

---

Dockerfile

Backport https://github.com/rancher/rke2/pull/3703 to release-1.24
https://github.com/rancher/rke2/issues/3706

[Release-1.24] Bump ingress-nginx

---

Dockerfile

Backport https://github.com/rancher/rke2/pull/3703 to release-1.23
https://github.com/rancher/rke2/issues/3707

[Release-1.23] Bump ingress-nginx

---

Dockerfile

Bump ingress-nginx to version 8
Chart Bump
- Make rke2 cluster
- Deploy yaml provided in https://github.com/rancher/rke2/issues/3702
- `kubectl get ingress -n auto-ingress` should have IPs
- ` curl -H 'Host: foo1.bar.com' http://NODE_IP/name.html` should work
https://github.com/rancher/rke2/issues/3702

Bump ingress-nginx

---

channels.yaml

Add v1.26 to channels.yaml
version bump; release
install using v1.26 channel
* n/a

Add v1.26 to channels.yaml

---

channels.yaml

December 2022 channels.yaml update

---

developer-docs/upgrading_kubernetes.md

[WIP] - update rke2 release docs

---

Dockerfile
scripts/build-images

Issue: https://github.com/rancher/rke2/issues/3791

[Backport 1.24] Update multus to v3.9.3 and whereabouts to v0.6

---

Dockerfile
scripts/build-images

**Types of Changes**
version bump
**Verification**
**Linked Issues**
https://github.com/rancher/rke2/issues/3765
**Further Comments**

[release-1.25] Bump harvester cloud provider and harvester csi driver

---

Dockerfile
scripts/build-images

**Types of Changes**
version bump
**Verification**
**Linked Issues**
https://github.com/rancher/rke2/issues/3765
**Further Comments**

[release-1.24] Bump harvester cloud provider and harvester csi driver

---

Dockerfile
scripts/build-images

**Types of Changes**
version bump
**Verification**
**Linked Issues**
https://github.com/rancher/rke2/issues/3765
**Further Comments**

[release-1.23] Bump harvester cloud provider and harvester csi driver

---

Dockerfile
scripts/build-images

Patch release bumps for Cilium and minor release bump for Cilium Hubble.
Depends on:
- https://github.com/rancher/rke2-charts/pull/320

Bump cilium images

---

Dockerfile
scripts/build-images

Issue: https://github.com/rancher/rke2/issues/3878

Update canal chart to v3.25.0-build2023020901

---

go.mod
go.sum

Bump wharfie and go-containerregistry
version bump
* #3838

Bump wharfie and go-containerregistry

---

Dockerfile
scripts/build-images

Issue: https://github.com/rancher/rke2/issues/3881

[Backport 1.24] Update canal chart to v3.25.0-build2023020901

---

Dockerfile
scripts/build-images

Issue: https://github.com/rancher/rke2/issues/3880

[Backport 1.25] Update canal chart to v3.25.0-build2023020901

---

go.mod
go.sum

Updates k3s: https://github.com/k3s-io/k3s/compare/3d146d2f1b43...21560155217bdfc12c5105d7cb79fad61b2985aa
bugfix
* #3842

Bump K3s commit

---

go.mod
go.sum

Updates k3s: https://github.com/k3s-io/k3s/compare/14f2226b674c...97100de8d06117ecff5f94eeb7a38e8cbd073fec
bugfix
* #3843

[release-1.25] Bump K3s commit

---

go.mod
go.sum

Updates k3s: https://github.com/k3s-io/k3s/compare/77dbe648ad78...74ed4bef6191f74b9f9d178c03c3d5da729c7003
bugfix
* #3844

[release-1.24] Bump K3s commit

---

go.mod
go.sum

Updates k3s: https://github.com/k3s-io/k3s/compare/0f7514e08f5e...52e7a47e1afff65047a66faf13e66b20b793b64e
bugfix
* #3845

[release-1.23] Bump K3s commit

---

Dockerfile
scripts/build-images

Add sig-storage snapshot controller and validation webhook charts
new feature chart
* Confirm that all three helm charts are installed
* Confirm that rke2-snapshot-validation-webhook and rke2-snapshot-controller pods are running.
* See https://github.com/rancher/rke2/issues/2563#issuecomment-1444850862 for E2E test
* https://github.com/rancher/rke2/issues/2563

Add sig-storage snapshot controller and validation webhook

---

Dockerfile
scripts/build-images

Update Flannel version to `v0.21.3` on Canal
Version update
#3979

Update Flannel version to v0.21.3 on Canal

---

Dockerfile
scripts/build-images

[Release 1.25] Update Flannel version to v0.21.3 on Canal

---

Dockerfile
scripts/build-images

[Release 1.24] Update Flannel version to v0.21.3 on Canal

---

tests/terraform/upgradecluster/upgradecluster_test.go

expand test case to add checks for pod health
no 
test coverage improvement
running SUC upgrades should now check pods are in a completed (for helm install) or a running state. 
https://github.com/rancher/rancher/issues/40651
Please critique and give feedback especially QA I need to grow here.

Expand SUC upgrade check to check pods as well as nodes 

---

bundle/bin/rke2-killall.sh
pkg/cli/cmds/root.go

Backports:
- https://github.com/rancher/rke2/pull/3955
- https://github.com/rancher/rke2/pull/3954
https://github.com/rancher/rke2/issues/3964
https://github.com/rancher/rke2/issues/3966

[Release-1.25] Remove Root debug + Remove unmounts

---

scripts/package-bundle

-Backport https://github.com/rancher/rke2/pull/3970
https://github.com/rancher/rke2/issues/3972

[Release-1.25] Don't package empty windows folder 

---

scripts/package-bundle

- Backport #3970 
https://github.com/rancher/rke2/issues/3973

[Release-1.24] Don't package empty windows folder

---

Dockerfile
scripts/build-images

Backport of  #4000
Version update
#4001

[Release 1.25] Update cilim to v1.13.0

---

Dockerfile
scripts/build-images

Backport of #4000 
Version update
#4002

[Release 1.24] Update cilim to v1.13.0

---

Dockerfile
scripts/build-images

Bump harvester csi driver version
Version bump
https://github.com/harvester/harvester/issues/3571

Bump harvester csi driver to v0.1.16

---

Dockerfile
scripts/build-images

Bump harvester csi driver version
Version bump
https://github.com/harvester/harvester/issues/3571

[release-1.24] Bump harvester csi driver to v0.1.16

---

channels.yaml

update stable channel to v1.24.11+rke2r1

---

tests/e2e/testutils.go
tests/e2e/validatecluster/validatecluster_test.go

Automation to test restart server and agents from rke2
Test
Run the test
https://github.com/rancher/rke2/issues/3641

Add automation for Restart command for Rke2

---

bundle/bin/rke2-uninstall.sh

This PR solves some leftover when uninstalling RKE2 on RedHat based system with TAR method.
This change does not require an update to documentation
Bugfix without breaking change. It deletes files that was not deleted when RKE2 is uninstalled. (Only when RKE2 is installed with TAR method on RedHat based system.)
* https://github.com/rancher/rke2/issues/4017

[release-1.25] Improve uninstallation on RHEL based OS

---

bundle/bin/rke2-uninstall.sh

This PR solves some leftover when uninstalling RKE2 on RedHat based system with TAR method.
This change does not require an update to documentation
Bugfix without breaking change. It deletes files that was not deleted when RKE2 is uninstalled. (Only when RKE2 is installed with TAR method on RedHat based system.)
* https://github.com/rancher/rke2/issues/4018

[release-1.24] Improve uninstallation on RHEL based OS

---

docs/adrs/004-rke2-rc-versioning.md

Signed-off-by: matttrach <matt.trachier@suse.com>

Adding decision against rc version removal

---

.drone.yml
.droneignore

Add skipfiles step to skip drone runs based on files in PR matching items in .droneignore.
This addresses https://github.com/rancher/rke2/issues/3976

Add skipfiles step to skip drone runs based on files in PR

---

Dockerfile
scripts/build-images

Issue: https://github.com/rancher/rke2/issues/4079

update whereabouts to v0.6.1

---

Dockerfile
scripts/build-images

Issue: https://github.com/rancher/rke2/issues/4082

[backport 1.24] update whereabouts to v0.6.1

---

Dockerfile
scripts/build-images

Issue: https://github.com/rancher/rke2/issues/4081

[backport 1.25] update whereabouts to v0.6.1

---

Dockerfile

[Release 1.25] Updated Calico chart to add crd missing values

---

Dockerfile

[Release 1.24] Updated Calico chart to add crd missing values

---

pkg/rke2/spc.go

Clean up static pods on etcd member removal
The bit of logic that terminates the static pods when the node is deleted was not firing when RKE2 is managed by Rancher, as Rancher uses the etcd member removal annotation to remove the node from the etcd cluster before it is actually deleted. This meant that the node was never able to actually see the deletion event when pre-removal was used.
bugfix
Use the `etcd.rke2.cattle.io/remove=true` annotation to pre-delete a member from the cluster; note that the static pods are terminated.
* For #4060
*

Clean up static pods on etcd member removal

---

docs/adrs/005-security-updates-automation.md

This PR adds an ADR to propose the automation of versions and security bump of dependencies.
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

Add ADR for security bumps automation

---

Dockerfile
scripts/build-images

- Bump hardened ingress-nginx to 1.6.4-hardened4 (1-3 are nonfunctional RCs)
https://jira.suse.com/browse/SURE-5933

Bump ingress-nginx to 1.6.4

---

tests/terraform/upgradecluster/upgradecluster_test.go

-fix: wrong dependency name
- n/a 
- n/a

fix: wrong dependency name

---

Dockerfile
scripts/build-images

* Bump ingress-nginx
* Bump webhook-certgen

[Release-1.24] Bump ingress-nginx to 1.6.4

---

Dockerfile
scripts/build-images

* Bump ingress-nginx
* Bump webhook-certgen

[Release-1.25] Bump ingress-nginx to 1.6.4

---

pkg/podexecutor/staticpod.go

Honor the user's audit-log-path override when determining what log directory to mount.
bugfix, enhancement
* #4088

[release-1.24] Automatically add volume mount for audit-log-path dir if set

---

.drone.yml

[Release 1.24] Fix drone dispatch step

---

.drone.yml

[Release 1.25] Fix drone dispatch step

---

.drone.yml

[Release 1.26] Fix drone dispatch step

---

pkg/podexecutor/staticpod.go
pkg/staticpod/staticpod.go

Fix hardcoded file mount handling for default audit log filename. Also handle audit log file name of `-` which is a supported value for writing to stdout.
The RKE2 apiserver currently fails to start if `--kube-apiserver-arg=audit-log-path` is set to:
* an existing file that **does not contain the string `audit.log`**, in which case a read-only mount for the file is generated
* `-` for writing to stdout, in which case a bad directory mount for `/` is generated. 
The first case will cause the apiserver to fail to restart properly, after the initial startup (which worked) created the file.
bugfix
* https://github.com/rancher/rke2/issues/4136

Fix hardcoded file mount handling for default audit log filename

---

.drone.yml

Fix drone dispatch step

---

Dockerfile
scripts/build-images

[Release 1.24] Update Cilium to v1.13.2

---

Dockerfile
scripts/build-images

[Release 1.25] Update Cilium to v1.13.2

---

Dockerfile
scripts/build-images

[Release 1.26] Update Cilium to v1.13.2

---

pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go

Enable --with-node-id flag

---

Dockerfile
scripts/build-images

[Release 1.25] Update Calico image on Canal

---

.drone.yml

Moves the dispatch pipeline below the build pipelines, and above the manifest pipeline.

[Release-1.24] Move Drone dispatch pipeline

---

.drone.yml

Moves the dispatch pipeline below the build pipelines, and above the manifest pipeline.

[Release-1.25] Move Drone dispatch pipeline

---

.drone.yml

Moves the dispatch pipeline below the build pipelines, and above the manifest pipeline.

[Release-1.26] Move Drone dispatch pipeline

---

go.mod
go.sum

Backport for #4225 resolving issue #4223

[release-1.26] Upgrade docker/docker package (#4225)

---

Dockerfile
scripts/build-images

Bump metrics-server
version bump
check version
* https://github.com/rancher/rke2/issues/4240
* SURE-6174

Bump metrics-server to v0.6.3

---

Dockerfile
scripts/build-images

Bump metrics-server
version bump
check version
* https://github.com/rancher/rke2/issues/4241
* SURE-6174

[release-1.26] Bump metrics-server to v0.6.3

---

.drone.yml
Dockerfile
scripts/build-images

Bump metrics-server
version bump
check version
* https://github.com/rancher/rke2/issues/4242
* SURE-6174

[release-1.25] Bump metrics-server to v0.6.3

---

.drone.yml
Dockerfile
scripts/build-images

Bump metrics-server
version bump
check version
* https://github.com/rancher/rke2/issues/4243
* SURE-6174

[release-1.24] Bump metrics-server to v0.6.3

---

install.sh

- Check for fagenrules command before adding rules
- Check if fapolicyd service actually started or not
Bug fix
- https://github.com/rancher/rke2/issues/4195

Fix fapolicyd checks in install script

---

Dockerfile
scripts/build-images

Bump vsphere csi/cpi and csi snapshot charts
version bump
Check deployed image versions
* https://github.com/rancher/rke2/issues/4275
* https://github.com/rancher/rke2/issues/4264

Bump vsphere csi/cpi and csi snapshot charts

---

Dockerfile
scripts/build-images

Bump vsphere csi/cpi and csi snapshot charts
version bump
Check deployed image versions
* https://github.com/rancher/rke2/issues/4276
* https://github.com/rancher/rke2/issues/4279

[release-1.26] Bump vsphere csi/cpi and csi snapshot charts

---

Dockerfile
scripts/build-images

Bump vsphere csi/cpi and csi snapshot charts
version bump
Check deployed image versions
* https://github.com/rancher/rke2/issues/4277
* https://github.com/rancher/rke2/issues/4280

[release-1.25] Bump vsphere csi/cpi and csi snapshot charts

---

Dockerfile
scripts/build-images

Bump vsphere csi/cpi charts
version bump
Check deployed image versions
* https://github.com/rancher/rke2/issues/4278

[release-1.24] Bump vsphere csi/cpi charts

---

install.sh

Add el9 to the install script
- https://github.com/rancher/rke2-selinux/issues/36
- https://github.com/rancher/rke2/issues/4285

Add el9 to install script

---

install.sh

This reverts commit 7e42927767437b68a1fa8818b48dd60272c9316d.
This PR should revert adding new distros to the install script until the stable/latest rpms are out for rke2-packaging and rke2-selinux

Revert "Add el9 to install script (#4256)"

---

pkg/bootstrap/bootstrap.go

Preserve mode when extracting runtime data
bugfix
* https://github.com/rancher/rke2/issues/4284

Preserve mode when extracting runtime data

---

go.mod
go.sum

Module dynamiclistener 0.3.3 doesn't support changing the certificate duration via environment variable `CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS`. 
-  (https://github.com/rancher/dynamiclistener/blob/v0.3.3/cert/cert.go)
Bump the dynamiclistener version to latest (0.3.5) to support the functionality.
-  (https://github.com/rancher/dynamiclistener/blob/7001abfa1f75dca934334b0c0d86186ec432f14b/cert/cert.go#L118)
Documentation can be updated to indicate the support for the functionality.
Bumps the dynamiclistener version.
- Build rke2 for Ubuntu 20.04
- Provide `CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS` with a value other than 365. I achieved this by adding it to `/etc/default/rke2-server`
- Verify the enddate for the certificates generated under `/var/lib/rancher/rke2/server/tls` is consistent …

DynamicListener version bump (v0.3.3 -> v0.3.5)

---

Dockerfile
scripts/build-images

Update the canal chart
Version update
https://github.com/rancher/rke2/issues/4338

Update canal chart

---

Dockerfile
scripts/build-images

Issue: https://github.com/rancher/rke2/issues/4340
Backport: https://github.com/rancher/rke2/pull/4339

[Release 1.26] Update canal chart

---

.github/ISSUE_TEMPLATE/os_validation.md

New GH Issue template for OS Validations
GH Issue template
It should show up in the templates
N/A
This will make ours/Caroline's/PM's lives easier

Add issue template for OS validation

---

tests/e2e/testutils.go
tests/e2e/validatecluster/validatecluster_test.go

Add rotation certificate check and refactor the restart check
Same as the PR https://github.com/k3s-io/k3s/pull/7097
Test
Run the test

Refactoring of Restart Cluster Server and Add the Certificate Rotation

---

Dockerfile
scripts/build-images

version bump
https://github.com/rancher/rke2/issues/4184
Dependency PR: https://github.com/rancher/rke2-charts/pull/345

Bump harvester cloud provider 0.2.1

---

Dockerfile

bump the rke2-coredns chart version (not the images, just the chart)
Waiting on:
version bump
Check chart version
* https://github.com/rancher/rke2/issues/4321

Bump rke2-coredns chart version

---

Dockerfile
scripts/build-images

version bump
https://github.com/rancher/rke2/issues/4184

[release-1.24] Bump harvester cloud provider 0.2.2

---

Dockerfile
scripts/build-images

version bump
https://github.com/rancher/rke2/issues/4184

[release-1.25] Bump harvester cloud provider 0.2.2

---

Dockerfile
scripts/build-images

version bump
https://github.com/rancher/rke2/issues/4184

[release-1.26] Bump harvester cloud provider 0.2.2

---

pkg/bootstrap/bootstrap.go

Preserve mode when extracting runtime data
bugfix
* https://github.com/rancher/rke2/issues/4304

[release-1.26] Preserve mode when extracting runtime data

---

pkg/bootstrap/bootstrap.go

Preserve mode when extracting runtime data
bugfix
* https://github.com/rancher/rke2/issues/4377

[release-1.24] Preserve mode when extracting runtime data

---

Dockerfile
scripts/build-images

ingress-nginx bump
Waiting for https://github.com/rancher/rke2-charts/pull/352

Bump ingress-nginx charts to v1.7.1

---

.github/workflows/nightly-install.yaml
tests/install/opensuse-leap/Vagrantfile

[CodeFreeze] Add opensuse leap testing to install tests

---

Dockerfile
Dockerfile.windows
scripts/build-images

Update Calico to v3.26.1 and Cilium to v1.13.4
CNI update
#4417

Update Calico to v3.26.1

---

Dockerfile
Dockerfile.windows
scripts/build-images

[Release 1.26] Update Calico to v3.26.1

---

Dockerfile
scripts/build-images

This PR moves Multus to version v4.0.2
Increase version
Deploy rke2 with multus and verify that things work correctly
https://github.com/rancher/rke2/issues/4427

Update multus to version v4.0.2
